website/content/docs/api-clients/commands/auth-methods/change-state.mdx
website/content/docs/api-clients/commands/auth-methods/create.mdx
website/content/docs/api-clients/commands/auth-methods/delete.mdx
website/content/docs/api-clients/commands/auth-methods/index.mdx
website/content/docs/api-clients/commands/auth-methods/list.mdx
website/content/docs/api-clients/commands/auth-methods/read.mdx
website/content/docs/api-clients/commands/auth-methods/update.mdx
website/data/docs-nav-data.json

This PR adds the `boundary auth-methods` command docs to https://github.com/hashicorp/boundary/pull/3411
🔍 [Deploy preview](https://boundary-77knuc0c8-hashicorp.vercel.app/boundary/docs/api-clients/commands/auth-methods)

Add 'auth-methods' command doc

---

internal/bsr/bsr.go
internal/bsr/bsr_open_test.go
internal/bsr/container.go
internal/bsr/convert/convert.go
internal/bsr/internal/fstest/fs.go
internal/bsr/internal/fstest/options.go

- Add checks to close opened files in a container if not nil
- Close files opened during reads for `OpenSession`, `OpenConnection` & `OpenChannel`
- Close opened scanner readers
Update `fs.MemFS` to support returning the original files instead of copies when the `withOriginalOption` is passed. Had to do this to get the current `Closed` state of each file. Because all changes were just editing a copy, `fs.MemFS` was not getting updated with the true closed state of the fil

fix: Close opened BSR files

---

website/content/docs/api-clients/commands/dev.mdx
website/content/docs/api-clients/commands/logout.mdx
website/content/docs/api-clients/commands/server.mdx
website/data/docs-nav-data.json

🔍 [Deploy preview](https://boundary-git-cli-commands-basics-hashicorp.vercel.app/boundary/docs/api-clients/commands/dev)
This PR adds the CLI command page for:
- `dev`
- `logout`
- `server`

Add the docs for 'logout', 'server', and 'dev' commands

---

internal/bsr/bsr.go

Add check to make sure container isn't nil before `container.close()` is called

chore: BSR container close check

---

internal/gen/controller.swagger.json
internal/gen/controller/api/services/account_service.pb.go
internal/proto/controller/api/resources/accounts/v1/account.proto
internal/proto/controller/api/services/v1/account_service.proto
scripts/remove-gotags-comments/main.go
sdk/pbs/controller/api/resources/accounts/account.pb.go

This PR adds observation gotags to proper fields for telemetry purposes and modifies remove-gotags-comment to remove observation gotags from comments 

telemetry: accounts proto

---

internal/daemon/controller/handlers/sessions/session_service.go

This fixes a dropped `err` variable in `internal/daemon/controller/handlers/sessions`.

internal/daemon/controller/handlers/sessions: fix dropped error

---

enos/enos-modules.hcl
enos/modules/docker_openssh_server_ca_key/custom-cont-init.d/00-trust-user-ca
enos/modules/docker_openssh_server_ca_key/main.tf
enos/modules/test_e2e/main.tf
enos/modules/test_e2e_docker/main.tf
enos/modules/test_e2e_docker/test_runner.sh
testing/internal/e2e/tests/base_with_vault/env_test.go

This PR adds the pieces necessary to add tests for SSH certificate injection.
- A new terraform module to create an openssh server target with a CA key
- Added other supporting files per https://developer.hashicorp.com/boundary/tutorials/credential-management/hcp-certificate-injection
Here is a branch with a working version of the test: https://github.com/hashicorp/boundary-enterprise/compare/moduli-e2e-cert-injection-ICU-9766?expand=1

test(e2e): Add infra for ssh certificate injection test

---

internal/gen/controller/api/services/group_service.pb.go
internal/proto/controller/api/resources/groups/v1/group.proto
internal/proto/controller/api/services/v1/group_service.proto
sdk/pbs/controller/api/resources/groups/group.pb.go

This PR adds observation tags to group proto for telemetry purposes.

Telemetry: groups proto

---

internal/gen/controller/api/services/host_catalog_service.pb.go
internal/proto/controller/api/resources/hostcatalogs/v1/host_catalog.proto
internal/proto/controller/api/services/v1/host_catalog_service.proto
sdk/pbs/controller/api/resources/hostcatalogs/host_catalog.pb.go

This PR adds observation gotags in `host_catalog.proto` and `host_catalog_service.proto` for telemetry purposes

Telemetry: host_catalog proto

---

internal/bsr/bsr.go
internal/bsr/bsr_validate_test.go

Add support for validating all files in a Boundary Session Recording (BSR). All files and sub container files will be verified by comparing it against checksums for each file in `SHA256SUM` file
- Validation will continue even if there's an error encountered during validation. The validation error will be added to the Validation struct `Error` field

feat: Validate BSR files

---

internal/gen/controller/api/services/auth_method_service.pb.go
internal/proto/controller/api/resources/authmethods/v1/auth_method.proto
internal/proto/controller/api/services/v1/auth_method_service.proto
sdk/pbs/controller/api/resources/authmethods/auth_method.pb.go

This PR adds observation gotags to auth_methods for telemetry purposes

Telemetry: auth_methods proto

---

.github/workflows/test.yml

This PR modifies the `go test` workflow in CI. Actual values can still be up for debate (figured we can have that discussion in the PR).
- The `go test` timeout was reduced to 40m to differentiate it from the `nick-fields/retry` action timeout. 
- We currently have a test that is hanging and causing jobs to run the whole 2 hours. Since the two timeout values have the same value, it seems like the `nick-fields/retry` action took precedence and prevented `go test` from printing any output for why it's hanging. Here is an example that shows output for why it has been hanging: https://github.com/hashicorp/boundary-enterprise/actions/runs/5743578382/attempts/1
- In `boundary`, `go test` takes about ~10 minutes (there are a number of jobs that are more in the 15 minute range - this is due to …

chore: Modify go test retry settings

---

internal/gen/controller/api/services/host_set_service.pb.go
internal/proto/controller/api/resources/hostsets/v1/host_set.proto
internal/proto/controller/api/services/v1/host_set_service.proto
sdk/pbs/controller/api/resources/hostsets/host_set.pb.go

This PR adds observation gotags into `hostset.proto` and `host_set_service.proto` for telemetry purposes

Telemetry: hostset proto

---

internal/gen/controller/api/services/host_service.pb.go
internal/proto/controller/api/resources/hosts/v1/host.proto
internal/proto/controller/api/services/v1/host_service.proto
sdk/pbs/controller/api/resources/hosts/host.pb.go

This PR adds observation gotags into `host.proto` and `host_service.proto` for telemetry purposes

Telemetry: Add observation tag to host proto

---

website/content/docs/configuration/kms/awskms.mdx
website/content/docs/configuration/session-recording/create-storage-bucket.mdx
website/content/docs/configuration/session-recording/enable-session-recording.mdx

Per [SPE-249](https://hashicorp.atlassian.net/browse/SPE-249), there is some information missing from the session recording configuration docs. The example policy in the topic [Create a storage bucket](https://developer.hashicorp.com/boundary/docs/configuration/session-recording/create-storage-bucket) does not include KMS encryption, which most customers would use. This PR adds an additional example policy that includes KMS encryption settings.
Additionally, in the AWSKMS configuration topic, it is not apparent that `bsr` is a required parameter to enable session recording. I added an additional note to help clarify.
Finally, the metadata for one of the topic titles was incorrect. I corrected the error.
- [Create a storage …

docs: Update session recording configuration

---

.github/workflows/enos-run.yml

This PR mitigates a common flaky failure in e2e tests and prevents the job from failing as this is not a test error.
The e2e test framework is organized by “scenarios”, which define a series of steps to set up infrastructure and execute tests.
```
scenario "scenario name" {
step "build_boundary_executable" { ... }
step "create_aws_boundary_cluster" { ... }
step "create_aws_target" { ... }
step "run_tests" { ... }
}
```
You can then use the enos cli to control execution. Operations include…
```
enos scenario launch <scenario name> 
enos scenario destroy <scenario name>
enos scenario run <scenario name>
```
The [GitHub Actions workflow](https://github.com/hashicorp/boundary/blob/main/.github/workflows/enos-run.yml) currently uses the following logic
```
...
enos scenario run
if: run == …
```

test(e2e): Mitigate aws dependencies error

---

enos/enos-scenario-e2e-database.hcl
enos/modules/test_e2e/main.tf
testing/internal/e2e/infra/env.go
testing/internal/e2e/tests/database/migration_test.go

This PR adds updates to the e2e test suite to support a `boundary-enterprise` version of the migration test. Specifically, we need to pass in the BoundaryLicense value from the enos scenario to the test suite.
There will be a follow-up PR in `boundary-enterprise` to add in the test.

test(e2e): Add pieces necessary for enterprise migration test

---

.git-blame-ignore-revs
Makefile
internal/proto/controller/api/.copywrite.hcl
internal/proto/controller/custom_options/.copywrite.hcl
internal/proto/plugin/.copywrite.hcl

Adds a hack that removes existing copyright headers
from files before rerunning copywrite with directory
specific configuration.
Also remove the massive copyright change commit from blame

Re-enable copywrite with hack

---

internal/gen/controller/api/services/scope_service.pb.go
internal/proto/controller/api/resources/scopes/v1/scope.proto
internal/proto/controller/api/services/v1/scope_service.proto
sdk/pbs/controller/api/resources/scopes/scope.pb.go

This PR adds observation gotags into `scope.proto` and `scope_service.proto` for telemetry purposes

Telemetry: scope.proto

---

internal/gen/controller/api/services/worker_service.pb.go
internal/proto/controller/api/resources/workers/v1/worker.proto
internal/proto/controller/api/services/v1/worker_service.proto
sdk/pbs/controller/api/resources/workers/worker.pb.go

This PR adds observation gotags into `worker.proto` and `worker_service.proto` for telemetry purposes.

Telemetry: worker.proto

---

website/content/docs/api-clients/commands/config/autocomplete.mdx
website/content/docs/api-clients/commands/config/decrypt.mdx
website/content/docs/api-clients/commands/config/encrypt.mdx
website/content/docs/api-clients/commands/config/get-token.mdx
website/content/docs/api-clients/commands/config/index.mdx
website/data/docs-nav-data.json

This adds `boundary config` command doc on top of https://github.com/hashicorp/boundary/pull/3411
🔍 [Deploy preview](https://boundary-git-config-command-doc-hashicorp.vercel.app/boundary/docs/api-clients/commands/config)

Add config command docs

---

testing/internal/e2e/infra/docker.go
testing/internal/e2e/tests/database/migration_test.go

This PR updates the e2e migration test based on a comment here: https://github.com/hashicorp/boundary-enterprise/pull/670#discussion_r1291668121
It refactors where `docker pull` is executed in order to reduce the number of places where a docker repo needs to be specified (In the comment above, I had modified the image that `docker run` would use, but did not modify the corresponding `docker pull`). Additionally, this makes it simpler to modify which version of Boundary to use in the event we want to run the migration test on a different starting version.

test(e2e): Refactor migration test docker repo definition

---

internal/gen/controller/api/services/role_service.pb.go
internal/proto/controller/api/resources/roles/v1/role.proto
internal/proto/controller/api/services/v1/role_service.proto
sdk/pbs/controller/api/resources/roles/role.pb.go

This PR adds observation gotags into `role.proto` and `role_service.proto` for telemetry purposes
cc: @jimlambrt  @ajayreshc

Telemetry: role.proto

---

internal/gen/controller/api/services/managed_group_service.pb.go
internal/proto/controller/api/resources/managedgroups/v1/managed_group.proto
internal/proto/controller/api/services/v1/managed_group_service.proto
sdk/pbs/controller/api/resources/managedgroups/managed_group.pb.go

This PR adds observation gotags into `managed_group.proto` and `managed_group_service.proto` for telemetry purposes

Telemetry: managed_group.proto

---

testing/internal/e2e/infra/docker.go

This PR is a follow-up to https://github.com/hashicorp/boundary/pull/3578.
The enterprise version of the test needs one more place where the BOUNDARY_LICENSE env needs to be set.

test(e2e): Add license env to migration test

---

enos/modules/build_boundary_docker_local/build.sh

This PR addresses an issue with a script that builds a docker image locally prior to running e2e tests. 
I ran into this issue after restarting my VS Code instance. Now, the script will set an environment variable based on the host's architecture (the `Makefile` defaults to `amd64`). I'm assuming I just always had that environment variable set whenever I was testing.

test(e2e): Build docker image based on host architecture

---

internal/gen/controller/api/services/session_service.pb.go
internal/proto/controller/api/resources/sessions/v1/session.proto
internal/proto/controller/api/services/v1/session_service.proto
sdk/pbs/controller/api/resources/sessions/session.pb.go

This PR adds observation gotags into `session.proto` and `session_service.proto` for telemetry purposes
** please review all the fields as this proto has more fields

Telemetry: session proto

---

website/content/docs/install-boundary/install.mdx

This PR updates the Install Boundary topic by adding installation tabs to distinguish between the Enterprise and Community binaries.

adds tabs for Enterprise vs Community

---

website/content/docs/install-boundary/configure-workers.mdx

The default listener ports were listed incorrectly in the configure workers topic. This PR fixes them.
From a Slack conversation: https://hashicorp.slack.com/archives/C01AQDJF3SA/p1690860684124889
These changes were already applied to the Boundary ENT deployment guide tutorial: [#1579](https://github.com/hashicorp/tutorials/pull/1579).

docs: Update listener ports in worker config

---

internal/gen/controller/api/services/target_service.pb.go
internal/proto/controller/api/resources/targets/v1/target.proto
internal/proto/controller/api/services/v1/target_service.proto
sdk/pbs/controller/api/resources/targets/target.pb.go

This PR adds observation gotags into `target.proto` and `target_service.proto` for telemetry purposes

Telemetry: target.proto

---

internal/gen/controller/servers/servers.pb.go
internal/gen/controller/servers/services/server_coordination_service.pb.go
internal/gen/controller/servers/services/session_service.pb.go
internal/proto/controller/servers/services/v1/server_coordination_service.proto
internal/proto/controller/servers/services/v1/session_service.proto
internal/proto/controller/servers/v1/servers.proto

This PR adds observation gotags into `servers.proto` and `session_service.proto` in the servers package for telemetry purposes.

Telemetry: servers proto

---

website/content/docs/enterprise/automated-license-reporting.mdx

The language on the automated license utilization reporting topic is carefully controlled. The PM has asked that we make a minor update to bring the Boundary topic in line with the changes that were applied in [Vault PR #22026](https://github.com/hashicorp/vault/pull/22026).
The Vault PR has minor wording updates on lines #58 and #195, but these were already applied to the existing Boundary topic in [PR #3491](https://github.com/hashicorp/boundary/pull/3491):
Line [#58](https://github.com/hashicorp/vault/pull/22026/files#diff-13490f1ee5e6b5cbb1370b297aeba8eb2c97815681b4479853631d2326b7b606R58):
Line [#195](https://github.com/hashicorp/vault/pull/22026/files#diff-13490f1ee5e6b5cbb1370b297aeba8eb2c97815681b4479853631d2326b7b606R195):
Therefore, this PR contains only the remaining minor text …

docs: Update automated license reporting topic

---

internal/server/testing.go

This fixes a dropped error in `internal/server`. No changelog update is required.

internal/server: fix dropped testing error

---

internal/cmd/commands/connect/connect.go

The message `"Session is already in use"` can appear if an authz token is reused after tearing down a session.
Updated the messaging to be a bit clearer.

chore(connect): improve messaging if tofu token already used

---

website/content/docs/configuration/worker/index.mdx

The `recording_storage_path` parameter was missing from the worker stanza topic. This PR adds it to the configuration examples and adds a definition to the list of parameters.
[View the preview deployment.](https://boundary-ojxwl8d5l-hashicorp.vercel.app/boundary/docs/configuration/worker)

docs: Add recording storage path to worker config

---

website/content/docs/api-clients/commands/users/add-accounts.mdx
website/content/docs/api-clients/commands/users/create.mdx
website/content/docs/api-clients/commands/users/delete.mdx
website/content/docs/api-clients/commands/users/index.mdx
website/content/docs/api-clients/commands/users/list.mdx
website/content/docs/api-clients/commands/users/read.mdx
website/content/docs/api-clients/commands/users/remove-accounts.mdx
website/content/docs/api-clients/commands/users/set-accounts.mdx
website/content/docs/api-clients/commands/users/update.mdx
website/data/docs-nav-data.json

Adds the `users` commands on top of the existing assembly branch for CLI commands #3411.

docs: Add `users` commands

---

website/content/docs/api-clients/commands/targets/add-credential-sources.mdx
website/content/docs/api-clients/commands/targets/add-host-sources.mdx
website/content/docs/api-clients/commands/targets/authorize-session.mdx
website/content/docs/api-clients/commands/targets/create.mdx
website/content/docs/api-clients/commands/targets/delete.mdx
website/content/docs/api-clients/commands/targets/index.mdx
website/content/docs/api-clients/commands/targets/list.mdx
website/content/docs/api-clients/commands/targets/read.mdx
website/content/docs/api-clients/commands/targets/remove-credential-sources.mdx
website/content/docs/api-clients/commands/targets/remove-host-sources.mdx
website/content/docs/api-clients/commands/targets/set-credential-sources.mdx
website/content/docs/api-clients/commands/targets/set-host-sources.mdx
website/content/docs/api-clients/commands/targets/update.mdx
website/content/docs/api-clients/commands/users/add-accounts.mdx
website/content/docs/api-clients/commands/users/index.mdx
website/content/docs/api-clients/commands/users/list.mdx
website/content/docs/api-clients/commands/users/remove-accounts.mdx
website/content/docs/api-clients/commands/users/set-accounts.mdx
website/content/docs/api-clients/commands/users/update.mdx
website/content/docs/api-clients/commands/workers/add-worker-tags.mdx
website/content/docs/api-clients/commands/workers/remove-worker-tags.mdx
website/content/docs/api-clients/commands/workers/set-worker-tags.mdx
website/content/docs/api-clients/commands/workers/update.mdx
website/data/docs-nav-data.json

Adds the `targets` commands on top of the existing assembly branch for CLI commands #3411.

docs: Add `targets` commands

---

website/content/docs/api-clients/commands/accounts/update.mdx
website/content/docs/api-clients/commands/credential-libraries/create.mdx
website/content/docs/api-clients/commands/credential-libraries/delete.mdx
website/content/docs/api-clients/commands/credential-libraries/index.mdx
website/content/docs/api-clients/commands/credential-libraries/list.mdx
website/content/docs/api-clients/commands/credential-libraries/read.mdx
website/content/docs/api-clients/commands/credential-libraries/update.mdx
website/data/docs-nav-data.json

This PR adds docs for `credential-libraries` command on top of https://github.com/hashicorp/boundary/pull/3411

Add 'credential-libraries' command docs

---

website/content/docs/api-clients/commands/credential-libraries/update.mdx
website/content/docs/api-clients/commands/credential-stores/create.mdx
website/content/docs/api-clients/commands/credential-stores/delete.mdx
website/content/docs/api-clients/commands/credential-stores/index.mdx
website/content/docs/api-clients/commands/credential-stores/list.mdx
website/content/docs/api-clients/commands/credential-stores/read.mdx
website/content/docs/api-clients/commands/credential-stores/update.mdx
website/data/docs-nav-data.json

Add the `credential-stores` command docs on top of https://github.com/hashicorp/boundary/pull/3411
🔍 [Deploy preview](https://boundary-git-cred-stores-docs-hashicorp.vercel.app/boundary/docs/api-clients/commands/credential-stores)

Add 'credential-stores' command docs

---

website/content/docs/api-clients/commands/storage-buckets/create.mdx
website/content/docs/api-clients/commands/storage-buckets/delete.mdx
website/content/docs/api-clients/commands/storage-buckets/index.mdx
website/content/docs/api-clients/commands/storage-buckets/list.mdx
website/content/docs/api-clients/commands/storage-buckets/read.mdx
website/content/docs/api-clients/commands/storage-buckets/update.mdx
website/data/docs-nav-data.json

Adds the storage-buckets commands on top of the existing assembly branch for CLI commands #3411.
Use this PR in favor of #3613.

docs: Add `storage-bucket` commands - update

---

website/content/docs/api-clients/commands/session-recordings/download.mdx
website/content/docs/api-clients/commands/session-recordings/index.mdx
website/content/docs/api-clients/commands/session-recordings/list.mdx
website/content/docs/api-clients/commands/session-recordings/read.mdx
website/data/docs-nav-data.json

Adds the `session-recordings` commands on top of the existing assembly branch for CLI commands #3411.

docs: Add `session-recordings` commands

---

website/content/docs/api-clients/commands/credential-stores/create.mdx
website/content/docs/api-clients/commands/credentials/create.mdx
website/content/docs/api-clients/commands/credentials/delete.mdx
website/content/docs/api-clients/commands/credentials/index.mdx
website/content/docs/api-clients/commands/credentials/list.mdx
website/content/docs/api-clients/commands/credentials/read.mdx
website/content/docs/api-clients/commands/credentials/update.mdx
website/data/docs-nav-data.json

This PR adds the `boundary credentials` command docs on top of https://github.com/hashicorp/boundary/pull/3411
🔍 [Deploy preview](https://boundary-git-credentials-docs-hashicorp.vercel.app/boundary/docs/api-clients/commands/credentials)

Add 'credentials' command docs

---

internal/proto/controller/api/resources/plugins/v1/plugin.proto
sdk/pbs/controller/api/resources/plugins/plugin.pb.go

Add eventstream:"observation" tags to plugin.proto field.
Closed a previous PR (3591) and created it fresh, as there was an issue with a rebase in the my branch.

Add telemetry observation tags to plugin.proto

---

website/content/docs/api-clients/commands/roles/add-grants.mdx
website/content/docs/api-clients/commands/roles/add-principals.mdx
website/content/docs/api-clients/commands/roles/create.mdx
website/content/docs/api-clients/commands/roles/delete.mdx
website/content/docs/api-clients/commands/roles/index.mdx
website/content/docs/api-clients/commands/roles/list.mdx
website/content/docs/api-clients/commands/roles/read.mdx
website/content/docs/api-clients/commands/roles/remove-grants.mdx
website/content/docs/api-clients/commands/roles/remove-principals.mdx
website/content/docs/api-clients/commands/roles/set-grants.mdx
website/content/docs/api-clients/commands/roles/set-principals.mdx
website/content/docs/api-clients/commands/roles/update.mdx
website/data/docs-nav-data.json

Adds the `roles` commands on top of the existing assembly branch for CLI commands #3411.

docs: Add `roles` commands

---

website/content/docs/api-clients/commands/auth-methods/change-state.mdx
website/content/docs/api-clients/commands/auth-methods/create.mdx
website/content/docs/api-clients/commands/auth-methods/list.mdx
website/content/docs/api-clients/commands/auth-methods/update.mdx
website/content/docs/api-clients/commands/auth-tokens/list.mdx
website/content/docs/api-clients/commands/config/decrypt.mdx
website/content/docs/api-clients/commands/config/encrypt.mdx
website/content/docs/api-clients/commands/config/get-token.mdx
website/content/docs/api-clients/commands/connect/http.mdx
website/content/docs/api-clients/commands/credential-libraries/create.mdx
website/content/docs/api-clients/commands/credential-libraries/update.mdx
website/content/docs/api-clients/commands/credential-stores/create.mdx
website/content/docs/api-clients/commands/credential-stores/list.mdx
website/content/docs/api-clients/commands/credential-stores/update.mdx
website/content/docs/api-clients/commands/database/index.mdx
website/content/docs/api-clients/commands/database/init.mdx
website/content/docs/api-clients/commands/database/migrate.mdx
website/content/docs/api-clients/commands/dev.mdx
website/content/docs/api-clients/commands/index.mdx
website/data/docs-nav-data.json

This PR adds the docs for `boundary database` command on top of https://github.com/hashicorp/boundary/pull/3411
🔍 [Deploy preview](https://boundary-git-database-docs-hashicorp.vercel.app/boundary/docs/api-clients/commands/database)

Add 'database' command docs

---

website/content/docs/api-clients/commands/host-sets/add-hosts.mdx
website/content/docs/api-clients/commands/host-sets/create.mdx
website/content/docs/api-clients/commands/host-sets/delete.mdx
website/content/docs/api-clients/commands/host-sets/index.mdx
website/content/docs/api-clients/commands/host-sets/list.mdx
website/content/docs/api-clients/commands/host-sets/read.mdx
website/content/docs/api-clients/commands/host-sets/remove-hosts.mdx
website/content/docs/api-clients/commands/host-sets/set-hosts.mdx
website/content/docs/api-clients/commands/host-sets/update.mdx
website/data/docs-nav-data.json

Adds the `host-sets` commands on top of the existing assembly branch for CLI commands #3411.

docs: Add `host-sets` commands

---

website/content/docs/api-clients/commands/host-catalogs/create.mdx
website/content/docs/api-clients/commands/host-catalogs/delete.mdx
website/content/docs/api-clients/commands/host-catalogs/index.mdx
website/content/docs/api-clients/commands/host-catalogs/list.mdx
website/content/docs/api-clients/commands/host-catalogs/read.mdx
website/content/docs/api-clients/commands/host-catalogs/update.mdx
website/content/docs/api-clients/commands/host-sets/read.mdx
website/data/docs-nav-data.json

Adds the `host-catalogs` commands on top of the existing assembly branch for CLI commands #3411.

docs: Add `host-catalogs` commands

---

website/content/docs/api-clients/commands/accounts/read.mdx
website/content/docs/api-clients/commands/groups/add-members.mdx
website/content/docs/api-clients/commands/groups/create.mdx
website/content/docs/api-clients/commands/groups/delete.mdx
website/content/docs/api-clients/commands/groups/index.mdx
website/content/docs/api-clients/commands/groups/list.mdx
website/content/docs/api-clients/commands/groups/read.mdx
website/content/docs/api-clients/commands/groups/remove-members.mdx
website/content/docs/api-clients/commands/groups/set-members.mdx
website/content/docs/api-clients/commands/groups/update.mdx
website/data/docs-nav-data.json

This PR adds the docs for `boundary groups` commands on top of https://github.com/hashicorp/boundary/pull/3411

Add 'boundary groups' command docs

---

internal/daemon/controller/handlers/targets/tcp/target_service_test.go

This reduces the runtime from 79s to 24s on my machine

handlers/targets/tcp: run tests in parallel

---

testing/internal/e2e/tests/base/target_tcp_connect_localhost_test.go
testing/internal/e2e/tests/base/target_tcp_connect_ssh_remote_command_test.go
testing/internal/e2e/tests/base/target_tcp_connect_ssh_test.go

This PR adds a test for the new `connect ssh -remote-command` option: https://github.com/hashicorp/boundary/pull/3633.
The test runs `connect ssh -remote-command "hostname -i"` and confirms that the output of `hostname` matches the expeced value.

test(e2e): Add test for `connect ssh -remote-command`

---

CHANGELOG.md
internal/target/repository.go
internal/target/tcp/repository_test.go

Fix address not returning on 10001+ list value

---

.github/workflows/fuzz.yml

The lint warnings are bogus but they keep failing so lets try to work around the suggested issues.

ci: attempt to silence action linter

---

website/content/docs/api-clients/commands/auth-methods/change-state.mdx
website/content/docs/api-clients/commands/auth-methods/create.mdx
website/content/docs/api-clients/commands/auth-methods/delete.mdx
website/content/docs/api-clients/commands/auth-methods/index.mdx
website/content/docs/api-clients/commands/auth-methods/list.mdx
website/content/docs/api-clients/commands/auth-methods/read.mdx
website/content/docs/api-clients/commands/auth-methods/update.mdx

Edit the `auth-methods` options in the CLI draft doc #3411.

docs: Edit `auth-methods` options

---

website/content/docs/api-clients/commands/auth-tokens/delete.mdx
website/content/docs/api-clients/commands/auth-tokens/index.mdx
website/content/docs/api-clients/commands/auth-tokens/list.mdx
website/content/docs/api-clients/commands/auth-tokens/read.mdx
website/content/docs/api-clients/commands/authenticate/index.mdx
website/content/docs/api-clients/commands/authenticate/ldap.mdx
website/content/docs/api-clients/commands/authenticate/oidc.mdx
website/content/docs/api-clients/commands/authenticate/password.mdx

Edits the `auth-tokens` and `authenticate` options in the CLI draft doc #3411.

docs: Edit `auth-tokens` & `authenticate` options

---

website/content/docs/api-clients/commands/config/autocomplete.mdx
website/content/docs/api-clients/commands/config/decrypt.mdx
website/content/docs/api-clients/commands/config/encrypt.mdx
website/content/docs/api-clients/commands/config/get-token.mdx
website/content/docs/api-clients/commands/config/index.mdx

Edits the `config` options in the CLI draft doc #3411.

docs: Edit `config` options

---

internal/perms/grants.go
internal/perms/grants_test.go
internal/perms/testdata/fuzz/FuzzParse/3187a710d9bc1612
internal/perms/testdata/fuzz/FuzzParse/4572b81e0281070d
internal/perms/testdata/fuzz/FuzzParse/536fbfc4db40b83d
internal/perms/testdata/fuzz/FuzzParse/5d676d09fce49675
internal/perms/testdata/fuzz/FuzzParse/6bfe75c429073a6a
internal/perms/testdata/fuzz/FuzzParse/9b33c3b84320755d
internal/perms/testdata/fuzz/FuzzParse/c9a7351b4994e353

This fixes two bugs in the grant parser:
1. The parser would accept "," as an output field when parsing from JSON. This would then make it into the canonical string, which would make it look like we had a trailing comma. Disallow the use of a comma as an output field.
2. The parser would accept empty IDs when parsing from JSON. Make this behavior consistent with the text behavior.

internal/perms: Fix grant parser bugs

---

internal/gen/controller/api/services/host_service.pb.go
internal/proto/controller/api/resources/hosts/v1/host.proto
internal/proto/controller/api/services/v1/host_service.proto
sdk/pbs/controller/api/resources/hosts/host.pb.go

This PR adds observation gotags into `host.proto` and `host_service.proto` for telemetry purposes.

Telemetry: host proto

---

website/content/docs/api-clients/commands/groups/add-members.mdx
website/content/docs/api-clients/commands/groups/create.mdx
website/content/docs/api-clients/commands/groups/delete.mdx
website/content/docs/api-clients/commands/groups/index.mdx
website/content/docs/api-clients/commands/groups/list.mdx
website/content/docs/api-clients/commands/groups/read.mdx
website/content/docs/api-clients/commands/groups/remove-members.mdx
website/content/docs/api-clients/commands/groups/set-members.mdx
website/content/docs/api-clients/commands/groups/update.mdx
website/content/docs/api-clients/commands/managed-groups/create.mdx
website/content/docs/api-clients/commands/managed-groups/delete.mdx
website/content/docs/api-clients/commands/managed-groups/index.mdx
website/content/docs/api-clients/commands/managed-groups/list.mdx
website/content/docs/api-clients/commands/managed-groups/read.mdx
website/content/docs/api-clients/commands/managed-groups/update.mdx
website/content/docs/api-clients/commands/storage-buckets/list.mdx

Edits the `groups` and `managed-groups` options in the CLI draft doc #3411.

docs: Edit multiple groups options

---

website/content/docs/api-clients/commands/host-catalogs/create.mdx
website/content/docs/api-clients/commands/host-catalogs/delete.mdx
website/content/docs/api-clients/commands/host-catalogs/index.mdx
website/content/docs/api-clients/commands/host-catalogs/list.mdx
website/content/docs/api-clients/commands/host-catalogs/read.mdx
website/content/docs/api-clients/commands/host-catalogs/update.mdx
website/content/docs/api-clients/commands/host-sets/add-hosts.mdx
website/content/docs/api-clients/commands/host-sets/create.mdx
website/content/docs/api-clients/commands/host-sets/delete.mdx
website/content/docs/api-clients/commands/host-sets/index.mdx
website/content/docs/api-clients/commands/host-sets/list.mdx
website/content/docs/api-clients/commands/host-sets/read.mdx
website/content/docs/api-clients/commands/host-sets/remove-hosts.mdx
website/content/docs/api-clients/commands/host-sets/set-hosts.mdx
website/content/docs/api-clients/commands/host-sets/update.mdx
website/content/docs/api-clients/commands/hosts/create.mdx
website/content/docs/api-clients/commands/hosts/delete.mdx
website/content/docs/api-clients/commands/hosts/index.mdx
website/content/docs/api-clients/commands/hosts/list.mdx
website/content/docs/api-clients/commands/hosts/read.mdx
website/content/docs/api-clients/commands/hosts/update.mdx

Edits the `host-catalogs`, `host-sets`, and `hosts` options in the CLI draft doc #3411.

docs: Edit multiple hosts options

---

website/content/docs/api-clients/commands/accounts/update.mdx
website/content/docs/api-clients/commands/auth-methods/create.mdx
website/content/docs/api-clients/commands/credential-libraries/create.mdx
website/content/docs/api-clients/commands/credential-libraries/delete.mdx
website/content/docs/api-clients/commands/credential-libraries/index.mdx
website/content/docs/api-clients/commands/credential-libraries/list.mdx
website/content/docs/api-clients/commands/credential-libraries/read.mdx
website/content/docs/api-clients/commands/credential-libraries/update.mdx
website/content/docs/api-clients/commands/credential-stores/create.mdx
website/content/docs/api-clients/commands/credential-stores/delete.mdx
website/content/docs/api-clients/commands/credential-stores/index.mdx
website/content/docs/api-clients/commands/credential-stores/list.mdx
website/content/docs/api-clients/commands/credential-stores/read.mdx
website/content/docs/api-clients/commands/credential-stores/update.mdx
website/content/docs/api-clients/commands/credentials/create.mdx
website/content/docs/api-clients/commands/credentials/delete.mdx
website/content/docs/api-clients/commands/credentials/index.mdx
website/content/docs/api-clients/commands/credentials/list.mdx
website/content/docs/api-clients/commands/credentials/read.mdx
website/content/docs/api-clients/commands/credentials/update.mdx

Edits the `credential-libraries`, `credential-stores`, and `credentials` options in the CLI draft doc #3411.

docs: Edit multiple credentials options

---

website/content/docs/api-clients/commands/roles/add-grants.mdx
website/content/docs/api-clients/commands/roles/add-principals.mdx
website/content/docs/api-clients/commands/roles/create.mdx
website/content/docs/api-clients/commands/roles/delete.mdx
website/content/docs/api-clients/commands/roles/index.mdx
website/content/docs/api-clients/commands/roles/list.mdx
website/content/docs/api-clients/commands/roles/read.mdx
website/content/docs/api-clients/commands/roles/remove-grants.mdx
website/content/docs/api-clients/commands/roles/remove-principals.mdx
website/content/docs/api-clients/commands/roles/set-grants.mdx
website/content/docs/api-clients/commands/roles/set-principals.mdx
website/content/docs/api-clients/commands/roles/update.mdx
website/content/docs/api-clients/commands/scopes/create.mdx
website/content/docs/api-clients/commands/scopes/delete.mdx
website/content/docs/api-clients/commands/scopes/destroy-key-version.mdx
website/content/docs/api-clients/commands/scopes/index.mdx
website/content/docs/api-clients/commands/scopes/list-key-version-destruction-jobs.mdx
website/content/docs/api-clients/commands/scopes/list-keys.mdx
website/content/docs/api-clients/commands/scopes/list.mdx
website/content/docs/api-clients/commands/scopes/read.mdx
website/content/docs/api-clients/commands/scopes/rotate-keys.mdx
website/content/docs/api-clients/commands/scopes/update.mdx

Edits the `roles` and `scopes` options in the CLI draft doc #3411.

docs: Edit `roles` and `scopes` options

---

internal/ui/VERSION

The old commit artifact has expired. This bumps the commit to https://github.com/hashicorp/boundary-ui/commit/f4c153a1321281017cc22a3eea46e01ea5f876a9.

ui: bump UI commit

---

internal/cmd/commands/server/worker_shutdown_reload_test.go
internal/daemon/controller/handlers/targets/target_service_test.go
internal/daemon/controller/handlers/targets/tcp/target_service_test.go
internal/daemon/controller/handlers/targets/testing.go
internal/tests/api/credentials/credentials_test.go
internal/tests/cluster/multi_controller_worker_test.go
internal/tests/cluster/session_cleanup_test.go
internal/tests/cluster/worker_bytesupdown_test.go
internal/tests/cluster/worker_proxy_test.go
internal/tests/cluster/x509_verification_test.go

The SetupSuiteTargetFilters globally mutates the function used for logic inside the target handler service. This means that we could get inconsistent logical behavior in certain tests that were run in parallel, since the logic can change at runtime. Ensure tests that make use of this function are never run in parallel with other tests.

all: avoid mutating global state in parallel tests

---

internal/cmd/ops/server_test.go

The connectivity state changes for `upstream_connection_state` health field is causing the test to be flaky. Commenting out the field during assertions. `upstream_connection_state` health field is tested in other tests

fix: Flaky upstream connection test

---

CHANGELOG.md

Add missing changelog entry for https://github.com/hashicorp/boundary/pull/3650

chore: update changelog with new worker upstream connection status

---

go.mod
go.sum

This latest version includes:
PR #98 -> feat (ldap): add worker pool for LDAP token group lookups

chore: update cap/ldap dependency

---

.github/workflows/enos-run.yml
enos/enos-scenario-e2e-aws.hcl
enos/enos-scenario-e2e-docker-base-with-worker.hcl
enos/modules/docker_boundary/boundary-config-bsr.hcl
enos/modules/docker_boundary/boundary-config.hcl
enos/modules/docker_boundary/main.tf
enos/modules/docker_worker/worker-config-bsr-downstream.hcl
enos/modules/docker_worker/worker-config-bsr.hcl
enos/modules/docker_worker/worker-config-downstream.hcl
enos/modules/docker_worker/worker-config.hcl
enos/modules/test_e2e/main.tf
enos/modules/test_e2e_docker/main.tf
enos/modules/test_e2e_docker/test_runner.sh
enos/modules/test_e2e_ui/main.tf
testing/internal/e2e/boundary/target.go
testing/internal/e2e/tests/aws/env_test.go
testing/internal/e2e/tests/aws/worker_test.go
testing/internal/e2e/tests/base_with_worker/env_test.go
testing/internal/e2e/tests/base_with_worker/target_tcp_worker_connect_ssh_test.go
testing/internal/e2e/tests/base_with_worker/target_tcp_worker_connect_test.go
testing/internal/e2e/tests/base_with_worker/testdata/boundary-controller-policy.hcl

This PR adds a new e2e test that does the following...
- create a target with an egress worker filter and confirm that you can connect to it
- update the target to use a worker filter that can't reach the host and confirm that you cannot connect to it
- attempt to create a target with an ingress worker filter and confirm that the operation fails
A new enos scenario was also added to CI to support this test. This scenario creates the following...
```
docker network: e2e_db
- postgres database
- boundary controller
docker network: e2e_cluster
- boundary controller
- worker
- vault
docker network: e2e_host
- worker
- host
```
There were some differences when running this directly from your machine vs using the docker test runner. 
Without any changes to the worker config, tests were passing …

test(e2e): Add a test for a single-hop worker

---

internal/authtoken/repository.go
internal/authtoken/repository_test.go
internal/pagination/pagination.go
internal/pagination/pagination_test.go
internal/session/repository_session.go
internal/session/repository_session_test.go
internal/target/repository.go
internal/target/tcp/repository_test.go

If an item was deleted between us listing items and us listing deleted Ids, it could appear in both. This change changes the order of operations to make this impossible.
Also always include a refresh token in the response when one is provided in the request.

pagination: list deleted Ids before items

---

enos/modules/docker_boundary/boundary-config-bsr.hcl

While working on a multihop test, I discovered that I made an error in a boundary config file when I added a collocated worker back to the file. This PR adds the necessary proxy listener to the config file so that the worker can properly load.

test(e2e): Add missing proxy listener to config file

---

enos/modules/docker_postgres/main.tf
enos/modules/docker_worker/main.tf
enos/modules/docker_worker/worker-config-bsr-downstream.hcl
enos/modules/docker_worker/worker-config-bsr.hcl
enos/modules/docker_worker/worker-config-downstream.hcl
enos/modules/docker_worker/worker-config.hcl

This PR updates the e2e test suite to add a worker health check when setting up a docker worker container. This adds testing coverage on the `health` endpoint as well as ensures that the container is ready to use before running tests.

test(e2e): Add worker health check when setting up infra

---

website/content/docs/concepts/domain-model/targets.mdx

The backport of #3513 to the `stable-website` branch failed in PR #3725. I closed that PR and recreated the update in this pull request.
* Added detail to targets.mdx around target type in relation to whether using injected credentials, i.e. setting type to ssh or tcp
* Update website/content/docs/concepts/domain-model/targets.mdx
* Update website/content/docs/concepts/domain-model/targets.mdx
* docs: Update target type info, add requirements
* docs: Revise SSH credential text
* docs: Clarify reference to SSH
---------

Cherry pick #3513 to `stable-website`

---

testing/internal/e2e/tests/base_with_vault/credential_store_test.go
testing/internal/e2e/tests/base_with_vault/target_tcp_vault_connect_test.go
testing/internal/e2e/tests/base_with_vault/target_tcp_vault_generic_connect_authz_token_test.go
testing/internal/e2e/tests/base_with_vault/target_tcp_vault_generic_connect_ssh_test.go
testing/internal/e2e/tests/base_with_vault/target_tcp_vault_generic_connect_test.go
testing/internal/e2e/tests/base_with_worker/target_tcp_worker_connect_ssh_test.go
testing/internal/e2e/tests/database/migration_test.go
testing/internal/e2e/vault/vault.go

This PR makes an adjustment to the test suite to support tests for multihop.
The primary change is to the `vault.Setup` method, allowing it to pass in the desired `boundary-controller-policy` file. This enables test packages in `boundary-enterprise` to pass in their own file.

test(e2e): Refactor vault setup method

---

internal/daemon/controller/handlers/accounts/account_service_test.go
internal/daemon/controller/handlers/authtokens/authtoken_service_test.go
internal/daemon/controller/handlers/sessions/session_service_test.go
internal/pagination/pagination.go
internal/pagination/pagination_test.go

When we have a request without a request token and all results fit within the page size, we can set the estimated item count directly from the size of the items, since it contains all visible items.

pagination: use size of items when possible

---

internal/pagination/pagination.go
internal/pagination/pagination_test.go

The previous code had a bug whereby it assumed that as soon as there is at least one more element available from the list items function, we're not at the end. This is incorrect, as that element may be subject to the filter.
The new code asserts that we have at least one more element available after the filtering has been applied. This allows us to correctly determine when a listing is complete and not.
This also allowed us to significantly simplify the fillPage function.

pagination: assert we have enough after filtering

---

internal/authtoken/query.go
internal/authtoken/repository.go
internal/authtoken/repository_test.go
internal/daemon/controller/auth/auth.go
internal/daemon/controller/handlers/accounts/account_service_test.go
internal/daemon/controller/handlers/authtokens/authtoken_service_test.go
internal/daemon/controller/handlers/credentiallibraries/credentiallibrary_service_test.go
internal/daemon/controller/handlers/sessions/session_service_test.go
internal/daemon/controller/handlers/targets/tcp/target_service_test.go
internal/session/query.go
internal/session/repository_session.go
internal/session/repository_session_test.go
internal/target/query.go
internal/target/repository.go
internal/target/tcp/repository_test.go

Replace the use of the expensive count(*) function with an estimate maintained by the Postgres query planner.

Replace count(*) with meta estimate

---

internal/cmd/base/event_flags.go
internal/cmd/base/event_flags_test.go
internal/cmd/base/server_test.go
internal/cmd/base/servers.go
internal/cmd/commands/dev/dev.go
internal/cmd/commands/dev/flags_test.go
internal/observability/event/event_type.go
internal/observability/event/eventer.go
internal/observability/event/eventer_config.go
internal/observability/event/eventer_config_test.go
internal/observability/event/sink_config.go
internal/observability/event/sink_config_test.go

In this PR, we are adding a new event type called telemetry to both flag and sink types.
Telemetry event is associated with observation events and the following logic must be applied 
- Case 1: `Observation` flag is true, `Telemetry` flag is false -> This is a current and default behavior and we should just get the observation events without telemetry events
- Case 2: `Observation` flag is false, `Telemetry` flag is true -> In this situation, we throw an error saying that the Observation flag should be set to true if you want to receive telemetry events
- From CLI if the flag is set with `--observation-events false --telemetry-events true` user will receive the following error message: ` event.(EventerConfig).Validate: telemetry events require observation event to be enabled: invalid …

Telemetry: Adding telemetry flag and and telemetry sink event type

---

testing/controller/controller.go

This PR adds an option to the test controller to enable logging (Related: https://github.com/hashicorp/boundary/pull/3163)
Example:
```
testController := controller.NewTestController(
t,
controller.WithWorkerAuthKms(workerAuthWrapper),
controller.WithRootKms(rootWrapper),
controller.WithRecoveryKms(recoveryWrapper),
controller.WithEnableEventing(),
)
```

test: Add option for logging in test controller

---

go.mod
internal/auth/oidc/auth_method.go
internal/auth/oidc/repository_auth_method_update.go
internal/bsr/internal/checksum/checksum.go
internal/bsr/internal/checksum/checksum_test.go
internal/bsr/internal/sign/sign.go
internal/bsr/internal/sign/sign_test.go
internal/cmd/base/base.go
internal/cmd/base/dev.go
internal/cmd/base/format.go
internal/cmd/base/keyring.go
internal/cmd/base/servers.go
internal/cmd/commands/server/server.go
internal/cmd/ops/server.go
internal/daemon/controller/handlers/targets/target_service.go
internal/daemon/controller/listeners.go
internal/daemon/worker/listeners.go
internal/db/read_writer.go
internal/db/schema/internal/postgres/postgres.go
internal/errors/match_test.go
internal/event/cloudevents_formatter_node_test.go
internal/event/context.go
internal/event/event_error.go
internal/event/event_error_test.go
internal/event/eventer.go
internal/event/eventer_retry.go
internal/event/eventer_retry_test.go
internal/session/service_worker_status_report.go

multierror errors will be converted to a stdlib error (because multierror doesn't support json marshaling).
This PR also includes:
- [refact (errors): convert from multierror to stdlib errors.Join(...)](https://github.com/hashicorp/boundary/commit/53743de99d087fcbbbed33d608c811010b8b7007)
- [refact: convert from pkg/errors to stdlib error wrapping](https://github.com/hashicorp/boundary/commit/0ac4f65b40cd38bdf6f716322f2ecefca5350edb)

fix (events): convert multierror to stdlib error

---

internal/auth/ldap/repository_account.go
internal/auth/oidc/repository_account.go
internal/auth/password/repository_account.go
internal/authtoken/repository.go
internal/credential/vault/repository_credential_library.go
internal/credential/vault/repository_ssh_certificate_credential_library.go
internal/session/repository_session.go
internal/target/repository.go

The old clause would be read as
```
(original_where_clause AND update_time > last_item_update_time) OR (foo)
```
Add explicit parantheses to avoid this. It would have been extremely unlikely to be hit, as it requires two elements to have identical update times, but this is correct now.

all: fix pagination where clause

---

website/content/docs/concepts/domain-model/credential-libraries.mdx

Adding/updating pieces of the Credential Library domain docs that are missing currently:
Added Attributes:
* credential-type
* credential-mapping-override 
Modified Attributes
* path -> vault-path 
* http_method -> vault-http-method
* http_request_body -> vault-http-request-body

Update Vault Credential Library Docs with additional options

---

internal/credential/credential.go
internal/credential/redact_test.go
internal/credential/static/repository_credentials_test.go
internal/credential/static/testing.go
internal/daemon/controller/handlers/credentials/credential_service.go
internal/daemon/controller/handlers/credentials/credential_service_test.go

The existing pattern was subject to a bug whereby a lock value was copied every time the value was passed around. This was happening because of the use of an embedded protobuf type. To avoid copying a mutex, use a pointer type in the embedding.
Also fixes a few linter warnings complaining about the use of unkeyed literals.

credential: fix lint errors

---

internal/observability/event/event_observation.go
internal/observability/event/event_observation_test.go
internal/observability/event/eventer.go
internal/observability/event/options.go
internal/observability/event/options_test.go
internal/observability/event/telemetry_filter.go
internal/observability/event/telemetry_filter_test.go
internal/observability/event/testing.go

Changes:
* Define option: `WithTelemetry()` (to specify if telemetry events are enabled)
* Create new `filterProtoMessage` function to sanitise proto messages based on a filter.
* Add `Request` and `Response` to `observation` type.
* Add `Request` / `Response` handling to `ComposeFrom` to included filtered telemetry data.
* Unit tests for `filterProtoMessage` and `ComposeFrom`.

event(observation): Add request / response observation and add telemetry filter

---

enos/ci/service-user-iam/main.tf
enos/enos-modules.hcl
enos/enos-scenario-e2e-aws-base-with-vault.hcl
enos/enos-scenario-e2e-aws-base.hcl
enos/enos-scenario-e2e-aws.hcl
enos/enos-scenario-e2e-database.hcl
enos/enos-scenario-e2e-ui.hcl
enos/modules/aws_vpc/main.tf
enos/modules/worker/main.tf
enos/modules/worker/variables.tf

The terraform-enos-aws-infra repo was a terraform module to set up the base aws infrastructure. Vault made some local updates that might mitigate flakiness we've been seeing ("can't delete due to dependencies" error). We are replacing our usage of that module with Vault's local copy.

chore(enos): Move `terraform-enos-aws-infra` to `boundary`

---

internal/daemon/controller/gateway.go
internal/daemon/controller/interceptor.go
internal/daemon/controller/listeners.go
internal/observability/event/cloudevents_formatter_node.go
internal/observability/event/cloudevents_formatter_node_test.go
internal/observability/event/context.go
internal/observability/event/context_test.go
internal/observability/event/event_observation.go

This PR will add 
- request and response events into WriteObservation 
- gRPC `request_info` into the observation pipeline
- default `deny` filter for when `observation_events` is enabled and `worker_status` events emitting from worker to controller 
`"/type" contains "observation" and "/data/request_info/method" contains "ServerCoordinationService/Status"`
- if the user specifies the `deny` filter, it will overwrite the default `deny` will be available

Telemetry: Add request and response interceptors with deny filter update

---

internal/cmd/commands/server/worker_initial_upstreams_reload_test.go
internal/daemon/controller/listeners.go
internal/daemon/controller/testing.go

With the KMS changes this should never have worked at all (because the different databases means the credentials conveyed after the KMS-based authentication would never be valid). However, it was sometimes passing because of a race condition: the worker could be found in the database before the new credentials were returned to the worker, causing the worker to start at the KMS step with the second controller.
This changes the test to use the same database for two controllers, but to only ever have one running at a time, and uses a sequence of two changed (or unchanged, depending) status updates from the worker to ensure that the reload was successful.

Fix flaky TestServer_ReloadInitialUpstreams

---

website/content/docs/configuration/events/common.mdx
website/content/docs/configuration/events/index.mdx

This pull request updates the `events` documentation to add the new telemetry attributes per [ICU-11049](https://hashicorp.atlassian.net/browse/ICU-11049).
View the updates in the preview deployment here:
- [events stanza](https://boundary-mzyri3g2f-hashicorp.vercel.app/boundary/docs/configuration/events)
- [Common sink parameters](https://boundary-mzyri3g2f-hashicorp.vercel.app/boundary/docs/configuration/events/common)
[ICU-11049]: https://hashicorp.atlassian.net/browse/ICU-11049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Update `events` stanza for telemetry

---

internal/event/cloudevents_formatter_node.go

This PR fixes the default behavior of the deny filter, if the user specifies any filter (allow/deny), that will override the default deny filter but if the user does not specify any filter, the default deny filter will apply for observation events.

Filtering events: fix default deny filter behavior

---

internal/daemon/worker/worker.go

give the storage struct an empty context so that it can close cleanly during a forced shutdown. fixes an issue where if a worker is forced to shut down via double ctrl-c, the session recording is missing all recording data. (bsr file only contained keys on aws)
tested via command line worker and killed with double ctrl-c

Finish Uploading BSR During Forced Worker Shutdown

---

internal/event/telemetry_filter.go
internal/event/telemetry_filter_test.go

Changes: 
* `telemetryFilter()` requires both `eventstream:"observation"` and `class:"public"` explicitly specified on fields.
* Added test case. 
* Updated existing telemetry tests.

Ignore non-public tagged struct fields from telemetry

---

enos/enos-scenario-e2e-aws-base-with-vault.hcl
enos/enos-scenario-e2e-aws-base.hcl
enos/enos-scenario-e2e-aws.hcl
enos/enos-scenario-e2e-docker-base-with-postgres.hcl
enos/enos-scenario-e2e-docker-base-with-vault.hcl
enos/enos-scenario-e2e-docker-base-with-worker.hcl
enos/enos-scenario-e2e-docker-base.hcl
enos/enos-scenario-e2e-ui.hcl
enos/modules/build_boundary_docker_crt/main.tf
enos/modules/build_boundary_docker_local/main.tf
enos/modules/build_crt/main.tf

This PR updates the e2e test suite to ensure that the appropriate version of the UI is built into the boundary binary. This addresses an issue where elements like the Session Recording UI were not being visible when spinning up boundary through enos.

chore(enos): Provide boundary edition when building UI

---

.github/workflows/enos-run.yml

This PR updates the GitHub Action workflow that runs the e2e tests to grab logs from the postgres container. Hopefully, this will shed some light on a flaky deadlock error we've been seeing.
```
Messages:   	Error from controller when performing delete on scope
Error information:
Kind:                Internal
Message:             scope.(Service).deleteFromRepo: unable to delete scope:
iam.(Repository).DeleteScope: failed for o_TG0TF3JWcq:
iam.(Repository).delete: db.DoTx: iam.(Repository).delete: db.Delete: unknown,
unknown: error #0: dbw.Delete: ERROR: deadlock detected (SQLSTATE 40P01)
Status:              500
context:             Error from controller when performing delete on scope
```

chore(e2e): Get logs from postgres container to debug deadlock errors

---

.github/workflows/enos-fmt.yml
.github/workflows/enos-run.yml

Terraform 1.6 was just released, and it may have caused some issues with `enos`. This PR will modify `enos` to pin it to use Terraform 1.5 until there's a fix.
```
Error: json: cannot unmarshal array into Go struct field rawState.checks of type tfjson.CheckResultStatic
```
Equivalent PR in vault: https://github.com/hashicorp/vault/pull/23508

chore(e2e): Set terraform version to 1.5 until issue is addressed

---

plugins/boundary/mains/aws/go.mod
plugins/boundary/mains/aws/go.sum

This new version fixes a problem with static credentials set as environment variables.

chore(plugins/aws): Bump to v0.2.1

---

CHANGELOG.md
internal/daemon/worker/controller_connection.go

With a suitably slow system -- say, if you're waiting on a Windows Terminal to output text inside a virtual machine -- the expected order of things can be thrown off. One specific way this can happen is that the worker can attempt to dial and have its dial fail because of the slowness causing the dial context to time out. If, because of the slowness, we also haven't released the log gate yet, then the event with the failure information will be queued, along with the context that was used.
Unfortunately, in some of these error cases, the context that was used was the dial context instead of the system base context. In many other places in the function it was the system base context so this is just a mismatch, probably from code written at different times.
Normally this wouldn't be a …

Fix intermittent startup issues on slow systems

---

CHANGELOG.md
go.mod
go.sum

When the boundary client establishes a connection to the websocket used
to communicate with a worker, it was configured with a max websocket
message size of 32KiB. This was the default behavior for v1.8.7 of
nhooyr/websocket. However, there are cases where the worker can send
messages to the client that are larger than 32KiB. When this happens the
client returns an error and terminates the connection.
Notably this seems to only currently impact sessions made to SSH
Targets, although it could theoretically impact any target type
depending on the details of how the worker performs the writing of the
messages. The issue can be reproduced by attempting to scp a large
enough file from an SSH Target to the client. In this case the
connection gets terminated and results in a partial transfer of …

fix(cli): Remove websocket message size limit

---

.github/workflows/enos-run.yml

This PR updates the GitHub Action workflow that runs the e2e tests to grab logs from the enos/terraform in order to shed some light on a flaky cleanup error we've been seeing.
```
Error: deleting EC2 Internet Gateway (igw-06f8eaf99d9358a07): DependencyViolation: The internetGateway 'igw-06f8eaf99d9358a07' has dependencies and cannot be deleted.
status code: 400, request id: 5dcfda59-d43d-4ed6-a7ed-ccf0bed47b42
```

chore(e2e): Get logs to debug aws dependencies error 

---

.github/workflows/enos-fmt.yml
.github/workflows/enos-run.yml

This reverts commit 031e143dfb8313683a4e8a2343f030a30ed07475.
The newly released `Enos 0.0.23` contains a fix to be compatible with `Terraform 1.6`. We can remove the pin to `Terraform 1.5`.

Revert "chore(e2e): Set terraform version to 1.5"

---

enos/modules/aws_target/main.tf
testing/internal/e2e/tests/base/target_tcp_connect_scp_test.go

This PR adds an e2e test that validates `scp` operations over a boundary connection. The test does the following
- creates a `tcp` target
- connects to the target
- generates a text file of ~300K
- `scp` the file from the client to the target. validates the checksum
- `cat` the file on the target
- `scp` the file from the target to the client. validates the checksum
There will be a follow-up PR to do the same for an `ssh` target.

test(e2e): Add test with scp operations

---

website/content/docs/configuration/worker/pki-worker.mdx
website/content/docs/install-boundary/configure-workers.mdx

From a Slack conversation: https://hashicorp.slack.com/archives/C01AQDJF3SA/p1694709178068199
The example we use for the `auth_storage_path` is `/boundary/demo-worker-1`. However, this assumes the Boundary user has access to create a directory in the root file system. This seems unlikely.
A better example would be to use `/var/lib/boundary`. 
This PR updates the `auth_storage_path` to reflect the best practice.
- [PKI worker configuration](https://boundary-8cdbn42ol-hashicorp.vercel.app/boundary/docs/configuration/worker/pki-worker)
- [Configure workers](https://boundary-8cdbn42ol-hashicorp.vercel.app/boundary/docs/install-boundary/configure-workers)
Jira: https://hashicorp.atlassian.net/browse/SPE-432

docs: Update worker auth storage path

---

website/content/docs/operations/session-recordings/index.mdx
website/content/docs/operations/session-recordings/manage-recorded-sessions.mdx

This PR seeks to clarify the way session recording handles some SSH connection options per issue number 344 and slack conversation (https://hashicorp.slack.com/archives/C014AHXUL3G/p1695043488542069).
- [Recorded sessions operations](https://boundary-ekdxl1ko7-hashicorp.vercel.app/boundary/docs/operations/session-recordings)
- [Manage recorded sessions](https://boundary-ekdxl1ko7-hashicorp.vercel.app/boundary/docs/operations/session-recordings/manage-recorded-sessions)
Jira: https://hashicorp.atlassian.net/browse/SPE-433

docs: Clarify SSH options and session recording

---

internal/cmd/config/config.go
internal/cmd/config/config_load_test.go
internal/cmd/config/config_test.go
internal/cmd/config/testdata/TestLoad/MultiFileDuplicateStanza/00-controller.hcl
internal/cmd/config/testdata/TestLoad/MultiFileDuplicateStanza/01-controller-duplicated.hcl
internal/ratelimit/config.go
internal/ratelimit/doc.go

This PR adds the configuration structure for API rate limiting

Rate Limit Configuration

---

internal/target/service_list_test.go

The new location is right next to the logic it is testing. The reason the file wasn't created here originally was because the author didn't know about the `targettest` package.

internal/target: move service list test

---

testing/internal/e2e/tests/base/auth_method_password_test.go

This PR adds a test to the e2e test suite that does the following
- creates a new org
- creates a new password auth method in that org
- sets the new auth method as the primary auth method for the new org
- creates an account in the new auth method
- logs in to the new org using the new auth method (a user will be auto-created)
- create another account in the new auth method
- create another user and attach account
- log in as the new user

test(e2e): Add test for creating an auth method

---

internal/tests/cli/boundary/roles.bats

After updating the Boundary version to `0.15.0`, bats tests started to fail for the following reason
```
boundary/role/add-grants: can associate test role with id=*;type... 99/212 ✗ boundary/role/add-grants: can associate test role with id=*;type=*;actions=create,read,update,delete,list grant
(in test file boundary/roles.bats, line 77)
`[ "$status" -eq 0 ]' failed
Grant "id=*;type=*;actions=create,read,update,delete,list" uses the "id" field which is no longer supported. Please use "ids" instead.
boundary/role/add-grantss: test role contains id=*;type=*;action...100/212 ✗ boundary/role/add-grantss: test role contains id=*;type=*;actions=create,read,update,delete,list grant
(in test file boundary/roles.bats, line 84)
`[ "$status" -eq 0 ]' failed
boundary/role/remove-grants: can remove …
```

test(bats): Fix grant due to deprecation

---

website/content/docs/commands/connect/ssh.mdx
website/content/docs/concepts/domain-model/accounts.mdx
website/content/docs/concepts/domain-model/auth-methods.mdx
website/content/docs/concepts/domain-model/managed-groups.mdx
website/content/docs/concepts/domain-model/storage-buckets.mdx
website/content/docs/configuration/session-recording/create-storage-bucket.mdx
website/content/docs/configuration/worker/pki-worker.mdx
website/content/docs/install-boundary/configure-workers.mdx
website/content/docs/operations/health.mdx
website/content/docs/operations/session-recordings/index.mdx
website/content/docs/operations/session-recordings/manage-recorded-sessions.mdx
website/content/docs/release-notes/v0_14_0.mdx
website/content/docs/troubleshoot/troubleshoot-recorded-sessions.mdx
website/content/partials/release-notes/intro.mdx
website/data/docs-nav-data.json

Several docs changes didn't make it from `main` to the `release/0.14.1` branch when it was created:
https://github.com/hashicorp/boundary/compare/release/0.14.1...main
These commits include all of the docs published for the 0.14.0 release:
- https://github.com/hashicorp/boundary/pull/3818
- https://github.com/hashicorp/boundary/pull/3759
- https://github.com/hashicorp/boundary/pull/3749
- https://github.com/hashicorp/boundary/pull/3852
This PR cherry-picks the missing docs changes above from `main` to `release/0.14.1`.

docs: Cherry pick 0.14.0 docs changes to 0.14.1 branch

---

testing/internal/e2e/tests/base_with_worker/target_tcp_worker_connect_ssh_test.go

This PR updates an e2e test to check that vault worker filters are not available in Boundary CE. There will be a follow-up PR in `boundary-enterprise` to add a test that uses vault worker filters.

test(e2e): Add check for vault worker filters

---

internal/daemon/controller/handlers/targets/target_service.go
internal/pagination/doc.go
internal/pagination/example_test.go
internal/pagination/pagination2.go
internal/pagination/pagination2_test.go
internal/target/service_list.go
internal/target/service_list_ext_test.go
internal/target/service_list_refresh.go

This unifies the core of the pagination logic in
the new pattern, significantly simplifying the
domain logic and removing repetition. This also
makes it easier to test the generic logic in
isolation.
I've established that this pattern can be applied
both to the simpler pagination in the target
domain and the more complicated logic in
the auth domain.
Jim, I hope this doesn't add too much indirection to the domain logic. I'm open to suggestion to improve it in any way, but I found that implementing the pagination logic through copy-paste-edit was error prone and this significantly reduces the burden when implementing a new resource.

New generic pagination

---

enos/modules/docker_postgres/postgresql.conf

This PR updates the postgres docker container in the e2e test suite to use the default deadlock timeout. The current setting was occasionally causing some flaky tests, like the following...
```
Error from controller when performing delete on scope
Error information:
Kind:                Internal
Message:             scope.(Service).deleteFromRepo: unable to delete scope:
iam.(Repository).DeleteScope: failed for o_TG0TF3JWcq:
iam.(Repository).delete: db.DoTx: iam.(Repository).delete: db.Delete: unknown,
unknown: error #0: dbw.Delete: ERROR: deadlock detected (SQLSTATE 40P01)
Status:              500
context:             Error from controller when performing delete on scope
```
This PR removes the current override so it uses the default value instead. The override was carried over from some …

test(e2e): Change postgres deadlock timeout to default

---

internal/db/schema/migrations/oss/postgres/77/03_kms_oplog.up.sql

We inadvertently used
kms.GetWrapper(ctx, am.ScopeId, kms.KeyPurposeDatabase) which resulted in the use of a database key for an oplog entry. See:
https://github.com/hashicorp/boundary/pull/3665/files#diff-bcf83b5283886c98fc45b6435fdc94d87d545b2768c6beac8acd14eb9d6b13f1
This fixes the issue with the missing "Database" purpose key when we converted the oplog keys into their own tables.
We've chosen to truncate the existing oplog entries to eliminate any references to a Database kms key in existing oplog entries.

fix (oplog keys): fix issue with migration of oplog keys to new tables

---

CHANGELOG.md
internal/daemon/worker/controller_connection.go

Bug found in https://github.com/hashicorp/boundary/issues/3881
`monitorUpstreamConnectionState()` is a goroutine that listens for GRPC client connection changes using GRPC's `WaitForStateChange` method. 
`monitorUpstreamConnectionState()` is currently consuming the a lot of CPU. It seems to be continuously running and not actually waiting for state changes.
Reference for GRPC Connection State Transitions: https://grpc.github.io/grpc/core/md_doc_connectivity-semantics-and-api.html
`state` was never getting updated so the default state was never getting updated which was causing the loop not to wait for new state chanegs
**Before Fix**
**After Fix**

fix: monitorUpstreamConnectionState CPU consumption

---

CHANGELOG.md

Update the changelog details for High CPU Utilization bug fix: https://github.com/hashicorp/boundary/pull/3884

chore: Update changelog for bug fix

---

.github/workflows/schema-diff.yml

When generating the JSON for submitting the github comment, if the
message was too large, the workflow would fail with the following error:
/usr/bin/jq: Argument list too long
This fix switches to using the `--rawfile`, which allows jq to process
the large comment.

ci(schema-diff): Fix error with large diffs

---

enos/modules/aws_target/main.tf

This PR updates the e2e test suite to address some new flakiness we started seeing.
Tests would sometimes fail due to the following
```
worker_test.go:96: 
│         	Error Trace:	/home/runner/work/boundary/boundary/testing/internal/e2e/tests/aws/worker_test.go:96
│         	Error:      	Received unexpected error:
│         	            	exit status 255
│         	Test:       	TestCliWorker
│         	Messages:   	Warning: Permanently added '[127.0.0.1]:37479' (ED25519) to the list of known hosts.
│         	            	"System is booting up. Unprivileged users are not permitted to log in yet. Please come back later. For technical details, see pam_nologin(8)."
│         	            	Connection closed by 127.0.0.1 port 37479
```
Based on the error message, it seems like we're trying to …

test(e2e): Wait until target ec2 instance is ready to be used

---

internal/db/schema/migrations/oss/postgres/78/01_deleted_tables_and_triggers.up.sql
internal/db/sqltest/Makefile
internal/db/sqltest/tests/purge/deleted_table_tests.sql
internal/db/sqltest/tests/purge/trigger_insert_on_delete.sql

Creates a new foo_deleted table for each subtype of each resource that needs to support pagination. The deleted
tables are used to track deletions of resources and return them to users of the new pagination API. We track only the ID and delete_time of the resource, so there's no way to filter out resources that the user could not see before it was deleted. This is intentional to keep the design simple and is not considered a security issue.

List pagination schema changes

---

internal/host/plugin/immutable_fields_test.go

This is a lint error but wasn't caught because it was a historic problem. It's appearing again now because we're adding another method to this type as part of the pagination work.

internal/host: fix inconsistent receiver

---

website/content/docs/commands/credential-libraries/create.mdx
website/content/docs/commands/credential-libraries/update.mdx

Adds documentation for command to add additional valid principals when creating a Vault SSH signed certificate credential library.
This PR adds the CLI docs. Domain model and API docs were added in #3791.
View the preview deployment here:
- [Create](https://boundary-fhkt3ehs5-hashicorp.vercel.app/boundary/docs/commands/credential-libraries/create#usages-by-type)
- [Update](https://boundary-fhkt3ehs5-hashicorp.vercel.app/boundary/docs/commands/credential-libraries/update#usages-by-type)

docs: Document additional valid principals

---

.github/workflows/enos-run.yml
enos/enos-scenario-e2e-docker-worker-registration-controller-led.hcl
enos/modules/docker_boundary/get_auth_token.sh
enos/modules/docker_boundary/get_worker_token.sh
enos/modules/docker_boundary/main.tf
enos/modules/docker_boundary/script_runner.sh
enos/modules/docker_worker/main.tf
enos/modules/docker_worker/worker-config-controller-led.hcl

This PR adds an e2e test that verifies that a worker can be registered using the [controller-led registration flow](https://developer.hashicorp.com/boundary/docs/configuration/worker/pki-worker#controller-led-authorization-flow).
When standing up the controller docker instance, some additional options were added to retrieve a boundary auth token (to run subsequent boundary commands) and to retrieve a worker token from boundary. When standing up the worker docker instance, we update the worker config file with the worker token and confirm that the worker is registered successfully.
Because this new "controller-led registration" scenario runs the same test package as the "kms registration" scenario, we needed to update the names of the log files to be unique (they are currently named by …

test(e2e): Add test for controller-led worker registration

---

internal/auth/ldap/service_authenticate.go
internal/auth/ldap/service_authenticate_test.go
internal/auth/oidc/service_callback.go
internal/auth/oidc/service_callback_test.go
internal/daemon/controller/handlers/authmethods/ldap_test.go

This PR adds an observation event for OIDC and LDAP authentication methods. This observation event will include the user ID and auth token start and end time. This will be used for telemetry purposes
cc: @jimlambrt

Telemetry(observations): add oidc and ldap observation events

---

internal/credential/static/json_credential_test.go
internal/credential/static/repository_credential_test.go
internal/credential/static/repository_credentials_test.go
internal/credential/static/rewrapping_test.go
internal/credential/static/testing.go
internal/credential/static/testing_test.go
internal/daemon/controller/handlers/credentials/credential_service_test.go

The TestObject test helper previously returned an error, but it's easier to have it perform the error check itself, as it conventionally done with test helpers.

internal/credential: simplify TestObject test helper

---

internal/cmd/config/config.go
internal/cmd/config/config_test.go

In #2076 the refactor changed the position of a parenthesis, causing the dev key to truncate the base64 representation instead of specifying which bytes to base64 encode.
We don't need this slicing anymore anyways since we now do individual key generation calls so just remove it.

Fix dev key generation

---

internal/auth/ldap/service_authenticate_test.go
internal/auth/oidc/service_callback_test.go
internal/daemon/controller/handlers/authmethods/ldap_test.go
internal/daemon/controller/handlers/authmethods/password_test.go
internal/event/context.go
internal/event/context_test.go

This PR fix the telemetry checks, with this PR we only emit authenticate events if and only if the telemetry flag is turned on

telemetry(observations): fix the details flag check

---

internal/daemon/controller/testing.go

The Vault Credential Store only accepts Vault tokens that have a TTL greater than the internal job scheduler's run frequency. This prevents a Vault Credential Store from being created with a Vault token that will expire before Boundary can renew it.
The Vault test server, by default, creates Vault tokens with a TTL equal to the duration of time remaining until `t.Deadline()` is reached.
This change sets the test controller's default job scheduler duration to be half of time remaining until `t.Deadline()`. The default job scheduler duration can still be overridden by setting a duration on `TestConrollerOpts.SchedulerRunJobInterval`.
This change fixes the error received when running:
go test -timeout 30s \
-tags devlicense \
-run '^TestList$' \ …

tests: Set a default job run interval based on the test deadline

---

enos/modules/test_e2e_docker/test.sh
enos/modules/test_e2e_docker/test_runner.sh
testing/internal/e2e/tests/aws/dynamichostcatalog_host_set_test.go

This PR updates the e2e test suite in order to support a test for using the new `-additional-valid-principals` option in `vault-ssh-certificate credential libraries`. 
The primary change is to install the `docker` cli on the test runner so that it's able to restart a container during a test. This is needed because the test needs to modify the SSH config on the target host and reload the container to get those changes. 
There will be a follow-up PR in `boundary-enterprise` to add the test.

test(e2e): Add support for `-additional-valid-principals` test

---

internal/cmd/commands/server/server.go

Add `dev-` prefix support to cluster ID for hcp boundary

[HCP Boundary] add support for remote-dev

---

.github/workflows/build.yml

This updates the linux package license to BUSL-1.1.
This PR should be merged to main so that the change is included in the next major release (#.X.#) that is cut from main.
License changes are not required on release branches (ongoing patch releases of current minor releases).

Update linux package license to BUSL-1.1

---

internal/credential/vault/supported.go
internal/credential/vault/testing.go
internal/credential/vault/testing_test.go
internal/credential/vault/vault.go

Two Vault client settings were not being properly used when constructing a Vault client.
The `TLS Skip Verify` setting was only being set if a `CA Cert` was also configured. This fix sets the `TLS Skip Verify` when configured regardless of other settings. Closes #3961.
The `TLS Server Name` setting was never being set. Bad programmers. This fix now sets it on the Vault client if the Vault Credential Store has been configured to use a value for this setting. Closes #3962.

fix(vault): Set the Vault TLS client options if specified

---

website/content/docs/commands/session-recordings/download.mdx
website/content/docs/commands/session-recordings/index.mdx
website/content/docs/commands/session-recordings/list.mdx
website/content/docs/commands/session-recordings/read.mdx
website/content/docs/commands/storage-buckets/create.mdx
website/content/docs/commands/storage-buckets/delete.mdx
website/content/docs/commands/storage-buckets/index.mdx
website/content/docs/commands/storage-buckets/list.mdx
website/content/docs/commands/storage-buckets/read.mdx
website/content/docs/commands/storage-buckets/update.mdx
website/content/docs/concepts/auditing.mdx
website/content/docs/concepts/credential-management.mdx
website/content/docs/concepts/domain-model/credential-libraries.mdx
website/content/docs/concepts/domain-model/session-recordings.mdx
website/content/docs/concepts/domain-model/storage-buckets.mdx
website/content/docs/concepts/domain-model/targets.mdx
website/content/docs/concepts/filtering/worker-tags.mdx
website/content/docs/concepts/security/data-encryption.mdx
website/content/docs/concepts/workers.mdx
website/content/docs/configuration/session-recording/create-storage-bucket.mdx
website/content/docs/configuration/session-recording/enable-session-recording.mdx
website/content/docs/configuration/session-recording/index.mdx
website/content/docs/configuration/worker/index.mdx
website/content/docs/configuration/worker/pki-worker.mdx
website/content/docs/operations/session-recordings/index.mdx
website/content/docs/operations/session-recordings/manage-recorded-sessions.mdx
website/content/docs/operations/session-recordings/validate-data-store.mdx
website/content/docs/operations/session-recordings/validate-session-recordings.mdx
website/content/docs/troubleshoot/troubleshoot-recorded-sessions.mdx
website/data/docs-nav-data.json

This pull request adds enterprise badges/alerts to Boundary docs pages where it is appropriate to call out that a feature is supported only in Enterprise or HCP Boundary. The enterprise badge and enterprise alert are existing devdot web components.
I added an **HCP/ENT** badge to the table of contents for any topics that only apply to one of the Enterprise versions. If there are nested topics, I only applied the badge to the top level:
For other examples in the TOC, view:
- Concepts > Domain model > Session recordings & Storage buckets
- Configuration > Session recordings
- Operations > Session recordings
- Commands (CLI) > session-recordings & storage-buckets
At the topic level, I added an alert to any topics or sections that only applied to one of the Enterprise versions. I added the …

docs: Add enterprise badge

---

.github/workflows/enos-run.yml

This PR makes a small fix to the e2e test GitHub Actions workflow.
https://github.com/hashicorp/boundary/pull/3882/files introduced a modification that renamed log files to be based on scenario name rather than the test package name (some scenarios use the same test package, which would cause some overwrites).
A simplified form of the workflow goes like...
- run scenario
- rename log
- retry scenario if first run failed
If the first run failed, however, the `rename log` step would also fail due to not finding any `*.log` files (Example: https://github.com/hashicorp/boundary/actions/runs/6773821118/job/18410808033#step:28:32). This PR updates the step to ignore the error so that it can attempt the retry.

chore(e2e): Continue if log renaming fails

---

internal/daemon/worker/auth_rotation_test.go
internal/tests/api/credentials/credentials_test.go

The auth rotation test fix allows us to keep checking if we did not yet see the expected bytes in case the call to lookup succeeds but we are late in rotating due to parallelism.
The api credentials test fix allows us to check if at _least_ one rotation has happened. That way if two rotations happen before we check again due to parallelism, this is deemed a successful result.

Minor test fixes

---

.github/workflows/enos-run.yml

Observed another instance where the step to get debug logs for the "Delete AWS dependencies" issue isn't triggering: https://github.com/hashicorp/boundary/actions/runs/6778925990/job/18425552648
This PR attempts to modify the `if` condition again to get it to trigger. This update makes it match the condition in the step below (`Destroy Enos scenario (Retry)`), so it SHOULD work.

chore(e2e): Fix trigger to get debug logs

---

internal/plugin/loopback/testing_grpc_stream_test.go

The following flaky tests were found in the plugin loopback package:
```
go test github.com/hashicorp/boundary/internal/plugin/loopback -count=100
--- FAIL: Test_GetObjectStream_Server (0.00s)
testing_grpc_stream_test.go:208: 
Error Trace:    /Users/mycow/Developer/boundary/internal/plugin/loopback/testing_grpc_stream_test.go:208
Error:          Should be true
Test:           Test_GetObjectStream_Server
--- FAIL: Test_GetObjectStream_Server (0.00s)
testing_grpc_stream_test.go:171: 
Error Trace:    /home/johan/src/hashicorp/boundary/internal/plugin/loopback/testing_grpc_stream_test.go:171
Error:          An error is expected but got nil.
Test:           Test_GetObjectStream_Server
go test github.com/hashicorp/boundary/internal/plugin/loopback -count=100 -run Test_GetObjectStream_Server
--- …
```

fix(plugin): remove unit test race condition

---

website/content/docs/commands/session-recordings/download.mdx
website/content/docs/commands/session-recordings/index.mdx
website/content/docs/commands/session-recordings/list.mdx
website/content/docs/commands/session-recordings/read.mdx
website/content/docs/commands/storage-buckets/create.mdx
website/content/docs/commands/storage-buckets/delete.mdx
website/content/docs/commands/storage-buckets/index.mdx
website/content/docs/commands/storage-buckets/list.mdx
website/content/docs/commands/storage-buckets/read.mdx
website/content/docs/commands/storage-buckets/update.mdx
website/content/docs/concepts/credential-management.mdx
website/content/docs/concepts/domain-model/credential-libraries.mdx
website/content/docs/concepts/domain-model/session-recordings.mdx
website/content/docs/concepts/domain-model/storage-buckets.mdx
website/content/docs/concepts/domain-model/targets.mdx
website/content/docs/concepts/filtering/worker-tags.mdx
website/content/docs/concepts/security/data-encryption.mdx
website/content/docs/concepts/workers.mdx
website/content/docs/configuration/session-recording/create-storage-bucket.mdx
website/content/docs/configuration/session-recording/enable-session-recording.mdx
website/content/docs/configuration/session-recording/index.mdx
website/content/docs/configuration/worker/index.mdx
website/content/docs/configuration/worker/pki-worker.mdx
website/content/docs/operations/session-recordings/index.mdx
website/content/docs/operations/session-recordings/manage-recorded-sessions.mdx
website/content/docs/operations/session-recordings/validate-data-store.mdx
website/content/docs/operations/session-recordings/validate-session-recordings.mdx

Some of the changes from #3981 did not get properly backported to the `stable-website` branch during a GitHub outage. This PR backports those changes.
* docs: Add enterprise badge
* docs: Add heading-level enterprise alert
* docs: Add some missing tags

[docs] Cherry pick #3981 to website

---

testing/internal/e2e/tests/base/target_tcp_connect_localhost_test.go

This PR updates an existing e2e test to run some additional commands over a session and confirm that the appropriate exit code is returned. This was inspired by the issue outlined in this ticket: https://hashicorp.atlassian.net/browse/ICU-11267.
There will be a follow-up PR in `boundary-enterprise` to add the same commands to a test for SSH targets.

test(e2e): Run additional commands over localhost and validate exit codes

---

internal/cmd/commands/connect/connect.go
internal/cmd/commands/credentialscmd/ssh-private-key_funcs.go

* If passing a private key without specifying it in URL syntax, give a proper error message (previously we were only making sure it was a scheme we knew how to handle, but we need to also be more informative if it's not a URL at all)
* If the handshake from the proxy fails, don't hang, just exit
* Update some error messages to use capitalization in line with our standard CLI error format

Fix three minor issues:

---

website/content/docs/concepts/domain-model/targets.mdx
website/content/docs/concepts/workers.mdx
website/content/docs/configuration/session-recording/create-storage-bucket.mdx
website/content/docs/configuration/session-recording/enable-session-recording.mdx
website/content/docs/install-boundary/configure-workers.mdx

We renamed some subheadings to simplify how we call out enterprise features and inadvertently broke some anchor links. This PR fixes the links.

docs: Fix broken subheading links

---

internal/tests/cli/boundary/credential_libraries.bats

This PR fixes a bats test to check for the correct attribute. This particular test is validating `vault-ssh-certificate library critical-options`, but there were a few checks using the wrong attribute.

test(bats): Use correct attribute for the `vault-ssh-certificate critical-options` test

---

website/content/docs/concepts/host-discovery/index.mdx
website/content/docs/operations/session-recordings/validate-session-recordings.mdx

There is a broken link in the [Host discovery index page](https://developer.hashicorp.com/boundary/docs/concepts/host-discovery). It should go to the AWS host catalogs tutorial:
This PR updates the link. I also fixed a recently introduced typo on the [Validate the integrity of session recordings](https://developer.hashicorp.com/boundary/docs/operations/session-recordings/validate-session-recordings) page.
View the preview deployment:
- [Host discovery](https://boundary-pisnem33d-hashicorp.vercel.app/boundary/docs/concepts/host-discovery)
- [Validate the integrity of session recordings](https://boundary-pisnem33d-hashicorp.vercel.app/boundary/docs/operations/session-recordings/validate-session-recordings)
UPDATE: I found and fixed 2 more broken links in the same topic here:

docs: Fix broken link

---

testing/internal/e2e/tests/base/target_tcp_connect_go_ssh_test.go
testing/internal/e2e/tests/base/target_tcp_connect_golang_ssh_test.go

This PR adds an e2e test that uses the [go ssh library](https://pkg.go.dev/golang.org/x/crypto/ssh) to connect to a `tcp` target.
There will be a follow-up PR in `boundary-enterprise` to add a similar test for `ssh` targets.

test(e2e): Add test that connects to target using go ssh library

---

testing/internal/e2e/infra/docker.go

This PR makes a minor fix to the e2e migration test. There were a few spots where we're not pulling the docker image from the docker mirror even though we're specifying the mirror when calling `RunWithOptions`.

test(e2e): Use docker mirror when pulling image

---

internal/event/event_observation.go
internal/event/event_observation_test.go

This PR adds an `op` string instead of a `type` inside details payload in the observation event.
cc: @jimlambrt

Observation(event): adding op instead of type details paylaod

---

internal/auth/oidc/auth_method.go
internal/auth/oidc/auth_method_test.go
internal/auth/oidc/repository_auth_method_create.go
internal/auth/oidc/repository_auth_method_create_test.go
internal/auth/oidc/repository_auth_method_delete_test.go
internal/auth/oidc/repository_auth_method_read.go
internal/auth/oidc/repository_auth_method_read_test.go
internal/auth/oidc/repository_auth_method_update.go
internal/auth/oidc/repository_auth_method_update_test.go
internal/auth/oidc/testing.go

Boundary OIDC method does not currently support passing in prompts during authentication. This change adds the capability of passing OIDC prompts. Prompts are optional OIDC parameters that determine the behaviour of the authentication server: https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest
- Update create, read, write and delete  repository changes to support new `Prompt` option for OIDC auth method
- Update test helper functions to support creating a test auth method with prompts

feat(oidc-prompt): repository changes for OIDC Prompt

---

internal/auth/oidc/immutable_fields_test.go
internal/auth/oidc/prompt.go
internal/auth/oidc/prompt_test.go
internal/auth/oidc/service_start_auth.go
internal/auth/oidc/service_start_auth_test.go
internal/cmd/commands/authmethodscmd/oidc_funcs.go
internal/daemon/controller/handlers/authmethods/authmethod_service.go
internal/daemon/controller/handlers/authmethods/authmethod_service_test.go
internal/daemon/controller/handlers/authmethods/oidc.go
internal/daemon/controller/handlers/authmethods/oidc_test.go

Boundary OIDC method does not currently support passing in prompts during authentication. This change adds the capability of passing OIDC prompts. Prompts are optional OIDC parameters that determine the behaviour of the authentication server: https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest
- Add `prompt` option for OIDC auth method CLI create and update
- Pass configured prompt during OIDC authentication
- Add `prompt` API validation for create and update
- Add missed tests for prompt, immutable fields test, handler test
1. Create OIDC auth method with `select_account` prompt
```
curl --location 'http://127.0.0.1:9200/v1/auth-methods' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer $TOKEN' \
--data '{
"type": "oidc",
"name": "OIDC Name", …
```

feat(oidc-prompt): OIDC Prompt API & CLI

---

internal/daemon/controller/handlers/accounts/account_service.go
internal/daemon/controller/handlers/authmethods/authmethod_service.go
internal/daemon/controller/handlers/authmethods/authmethod_test.go
internal/daemon/controller/handlers/credentiallibraries/credentiallibrary_service.go
internal/daemon/controller/handlers/credentials/credential_service.go
internal/daemon/controller/handlers/credentialstores/credentialstore_service.go
internal/daemon/controller/handlers/host_catalogs/host_catalog_service.go
internal/daemon/controller/handlers/host_sets/host_set_service.go
internal/daemon/controller/handlers/hosts/host_service.go
internal/daemon/controller/handlers/managed_groups/managed_group_service.go
internal/daemon/controller/handlers/outgoing_response_filter_test.go
internal/daemon/controller/handlers/subtypes.go
internal/daemon/controller/handlers/subtypes_test.go
internal/daemon/controller/handlers/targets/credentials.go
internal/daemon/controller/handlers/targets/target_service.go
internal/types/subtypes/attribute_transform.go
internal/types/subtypes/attribute_transform_test.go
internal/types/subtypes/interceptor.go
internal/types/subtypes/interceptor_test.go
internal/types/subtypes/transformations.go
testing/TRACING.md

The subtype.Filterable and handlers.ProtoToStruct functions are costly and worth measuring whenever runtime tracing is in use. This has almost no cost when tracing is not in use, so there's little harm in having them in place. Runtime tracing like this allows us to create user regions viewable in the pprof trace format, like this:

subtypes,handlers: add runtime trace regions

---

api/accounts/account.gen.go
api/authmethods/authmethods.gen.go
api/authtokens/authtokens.gen.go
api/credentiallibraries/credential_library.gen.go
api/credentials/credential.gen.go
api/credentialstores/credential_store.gen.go
api/groups/group.gen.go
api/hostcatalogs/host_catalog.gen.go
api/hosts/host.gen.go
api/hostsets/host_set.gen.go
api/managedgroups/managedgroups.gen.go
api/roles/role.gen.go
api/scopes/scope.gen.go
api/sessionrecordings/session_recording.gen.go
api/sessions/session.gen.go
api/storagebuckets/storage_bucket.gen.go
api/targets/session_secret.gen.go
api/targets/target.gen.go
api/users/user.gen.go
api/workers/worker.gen.go
internal/api/genapi/templates.go
internal/listtoken/list_token.go
internal/listtoken/list_token_test.go

When using the new auto-pagination logic, we would previously return the Body and Map of the last response, instead of one corresponding to the returned result. Correct this by overwriting the Body and Map after pagination has finished.

internal/genapi: correct list response body and map

---

enos/enos-scenario-e2e-docker-base-plus.hcl
enos/enos-scenario-e2e-docker-base-with-vault.hcl
enos/enos-scenario-e2e-docker-base-with-worker.hcl
enos/enos-scenario-e2e-docker-base.hcl
enos/enos-scenario-e2e-docker-worker-registration-controller-led.hcl
enos/enos-scenario-e2e-docker-worker-registration-worker-led.hcl
enos/modules/docker_boundary/boundary-config-bsr.hcl
enos/modules/docker_boundary/boundary-config-init.hcl
enos/modules/docker_boundary/boundary-config.hcl
enos/modules/docker_boundary/main.tf
enos/modules/test_e2e_docker/main.tf
enos/modules/test_e2e_docker/test_runner.sh
testing/internal/e2e/README.md
testing/internal/e2e/tests/base/env_test.go
testing/internal/e2e/tests/base/paginate_target_test.go

Exercises target pagination both over the CLI and the API. The max page size of the controller is configured to make the tests run quicker while still exercising the desired behavior.

Target pagination e2e test

---

internal/daemon/controller/controller.go
internal/ratelimit/limiter.go
internal/ratelimit/metrics.go

This provides two prometheus metrics to monitor the rate limiter:
boundary_controller_api_ratelimiter_quota_storage_capacity:
This is a gague that shows the total number of quotas that can be stored
at a given moment by the rate limiter.
boundary_controller_api_ratelimiter_quota_storage_usage:
This is a gague that shows the number of quotas currently being stored
by the limiter. If this becomes equal to the capacity, requests that
would result in a new quota being created will get limited and receive a
429 status code.

feat(ratelimit): Expose metrics on quota usage

---

website/content/docs/install-boundary/index.mdx

On our website, the link to the HCP get started section is broken on this page:
https://developer.hashicorp.com/boundary/docs/install-boundary
This pull request fixes the broken link. View the update in the preview deployment:
https://boundary-dhfgdhbu4-hashicorp.vercel.app/boundary/docs/install-boundary

docs: Fix broken link for HCP deployment

---

website/content/docs/install-boundary/index.mdx

This pull request backports the fix from #4081 to the `stable-website` branch.

docs: Backport fix for broken link

---

website/content/docs/install-boundary/index.mdx

This pull request backports the fix from #4081 to the `release/0.14.x` branch.

docs: Backport fix for broken link to release branch

---

website/content/docs/commands/accounts/update.mdx
website/content/docs/commands/auth-methods/create.mdx
website/content/docs/commands/auth-methods/update.mdx
website/content/docs/concepts/domain-model/auth-methods.mdx

Per ICU-11466, we are adding the OIDC `prompts` attribute to support authentication prompts including account picker functionality. This PR updates the domain model and CLI documentation with the new options (https://hashicorp.atlassian.net/browse/ICU-11903).
- [OIDC domain model auth method attributes](https://boundary-h766xzy27-hashicorp.vercel.app/boundary/docs/concepts/domain-model/auth-methods#oidc-auth-method-attributes)
- CLI
- [auth method create](https://boundary-h766xzy27-hashicorp.vercel.app/boundary/docs/commands/auth-methods/create#usages-by-type) on the OIDC tab
- [auth method update](https://boundary-h766xzy27-hashicorp.vercel.app/boundary/docs/commands/auth-methods/update#usages-by-type) on the OIDC tab

docs: Add OIDC prompt attribute

---

go.mod
go.sum
internal/cmd/commands/server/controller_ratelimit_reload_test.go
internal/daemon/controller/handlers/host_catalogs/host_catalog_service_test.go
internal/ratelimit/handler.go
internal/ratelimit/handler_test.go

Previously this would truncate to the nearest integer, which could
result in clients retrying before the quota has reset, and getting rate
limited again.
Note that in the case of a 503, the Retry-After header was already being
set correctly.

fix(ratelimit): Round up when setting Retry-After header

---

testing/TRACING.md

I missed that you need to explicitly create a server using http.DefaultServeMux.

testing: clarify tracing requirements

---

internal/credential/static/credential.go
internal/credential/static/repository_credential.go

Using a struct for the list parsing simplifies the logic and makes the mapping between the result and the Go type safer.

internal/credential/static: simplify list parsing

---

.github/workflows/schema-diff.yml

This commit disables `schema-diff` on PRs in the draft state. This is another layer of control to prevent `schema-diff` GitHub comments from polluting PRs that might not necessarily need `schema-diff` run against them

feat(github): Disable schema-diff for PRs in draft state

---

website/content/docs/configuration/session-recording/create-storage-bucket.mdx

The worker requirements in the **Create a storage bucket** topic do not mention the need for a self-managed worker in HCP environments. I added a new topic to the HCP docs that discusses the self-managed worker configuration in PR [#798](https://github.com/hashicorp/hcp-docs/pull/798). This pull request clarifies the difference between Enterprise and HCP configurations and links out to the new HCP topic.
[View the update in the preview deployment](https://boundary-7i46v0l7b-hashicorp.vercel.app/boundary/docs/configuration/session-recording/create-storage-bucket#boundary-workers-requirements).
** Note that the link in the preview environment will not work until PR [#798](https://github.com/hashicorp/hcp-docs/pull/798) is merged.

docs: Update session recording reqs for HCP

---

internal/auth/oidc/service_start_auth.go
internal/auth/oidc/service_start_auth_test.go
internal/daemon/controller/handlers/authmethods/authmethod_service.go
internal/daemon/controller/handlers/authmethods/authmethod_service_test.go

Add validation to prevent "none" from being combined with multiple prompts.
- Valid: `["none"]`
- Invalid: `["none", "select_account"]`
- Valid: `["consent", "select_account"]`

feat(oidc-prompts): Add Validation for Prompts

---

internal/cmd/commands/server/controller_ratelimit_reload_test.go
internal/daemon/controller/testdata/Test_rateLimiterConfig_writeSysEvent/defaults.json
internal/daemon/controller/testdata/Test_rateLimiterConfig_writeSysEvent/max_size.json
internal/ratelimit/config.go

This increases the default rate limits to:
- 1,500 reqs / 30 seconds for list actions in total
- 1,500 reqs / 30 seconds for list actions per IP address
- 150 reqs / 30 seconds for list actions per auth token
And for all other actions:
- 30,000 reqs / 30 seconds for list actions in total
- 30,000 reqs / 30 seconds for list actions per IP address
- 3,000 reqs / 30 seconds for list actions per auth token
This seems to be a reasonable default for a small to medium size cluster
based on some scale testing.

feat(ratelimit): Increase default values

---

internal/auth/oidc/service_start_auth.go
internal/auth/oidc/service_start_auth_test.go
internal/daemon/controller/handlers/authmethods/authmethod_service.go
internal/daemon/controller/handlers/authmethods/authmethod_service_test.go

Cherry-pick https://github.com/hashicorp/boundary/pull/4130 commit to release/0.14.x
Add validation to prevent "none" from being combined with multiple prompts.
- Valid `["none"]`
- Invalid `["none", "select_account"]`
- Valid `["consent", "select_account"]`

feat(oidc-prompts): Add Validation for Prompts (#4130)

---

website/content/docs/api-clients/api.mdx
website/content/docs/api-clients/go-sdk.mdx
website/content/docs/configuration/controller.mdx
website/content/docs/operations/metrics.mdx

Per [ICU-11978](https://hashicorp.atlassian.net/browse/ICU-11978), this PR adds documentation for API rate limiting.
- API > [Rate limiting](https://boundary-kczg7opdd-hashicorp.vercel.app/boundary/docs/api-clients/api#rate-limiting)
- Controller stanza > [api_rate_limiting](https://boundary-kczg7opdd-hashicorp.vercel.app/boundary/docs/configuration/controller#api_rate_limit)
- Metrics > [Controller](https://boundary-kczg7opdd-hashicorp.vercel.app/boundary/docs/operations/metrics#controller)
- [GoSDK](https://boundary-kczg7opdd-hashicorp.vercel.app/boundary/docs/api-clients/go-sdk) 
[ICU-11978]: https://hashicorp.atlassian.net/browse/ICU-11978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Document API rate limiting

---

website/content/docs/api-clients/api.mdx
website/content/docs/api-clients/go-sdk.mdx
website/content/docs/configuration/controller.mdx
website/content/docs/operations/metrics.mdx

This pull request backports the API rate limiting update from https://github.com/hashicorp/boundary/pull/4111 to the release/0.14.x branch:
* docs: Document API rate limiting
* docs: Fix default setting
* addss rate limiting examples to complete configuration example
* use # for comments for consistency
* Update website/content/docs/api-clients/api.mdx
Co-authored-by: Michael Li <michael.li@hashicorp.com>
* docs: Updates from review feedback
* docs: Updates from review feedback
* docs: Add new defaults and sub-headings
* Update website/content/docs/api-clients/go-sdk.mdx
Co-authored-by: Timothy Messier <tim.messier@gmail.com>
* docs: Remove remaining comments from code blocks
* …

docs: Backport API rate limiting update to release branch

---

enos/enos-scenario-e2e-docker-base-plus.hcl
enos/modules/docker_boundary/boundary-config-rate-limit.hcl
testing/internal/e2e/boundary/boundary.go
testing/internal/e2e/boundary/http.go
testing/internal/e2e/helpers.go
testing/internal/e2e/tests/base_plus/rate_limit_test.go

This PR adds some e2e tests for rate limiting. 
One test validates rate limiting when making HTTP requests. Another test validates rate limiting when making CLI requests.
```
❯ go test -v -count=1  github.com/hashicorp/boundary/testing/internal/e2e/tests/base_plus -run RateLimit
=== RUN   TestHttpRateLimit
scope.go:60: Created Org Id: o_B1HSi1dnli
scope.go:93: Created Project Id: p_WAMv0hSIJt
target.go:101: Created Target: ttcp_SB0GJRUHIu
rate_limit_test.go:61: Sending API requests until quota is hit...
rate_limit_test.go:81: 5;w=5;comment="auth-token"
rate_limit_test.go:85: limit=5, remaining=4, reset=5
rate_limit_test.go:105: limit=5, remaining=3, reset=5
rate_limit_test.go:105: limit=5, remaining=2, reset=5
rate_limit_test.go:105: limit=5, remaining=1, reset=5
rate_limit_test.go:105: …
```

test(e2e): Add rate limit test

---

testing/internal/e2e/tests/base/paginate_session_test.go

Attempting to cancel sessions is flaky so these tests avoid the cancellation part of the process

Session pagination e2e tests

---

website/content/docs/release-notes/v0_14_0.mdx

This pull request backports the release notes update from #4146 to the `release/0.14.x` branch.

docs: Backport 0.14.0 release notes to release branch

---

internal/pagination/pagination.go
internal/pagination/pagination_plugin.go
internal/pagination/pagination_plugin_test.go
internal/pagination/pagination_plugins.go
internal/pagination/pagination_plugins_test.go

Some resources return a plugin or slice of plugins alongside its list repository methods (hosts, host sets, host catalogs, storage buckets). These are used for filtering and other things that are done at the handler level, so the service level functions need to return these alongside the items. These new pagination helpers performs the generic pagination logic while returning a plugin or map of plugin id to plugin to the caller, all the while exposing the plugins to the filtering.

Add plugin/plugins pagination helpers

---

internal/credential/service_list_credentials_ext_test.go
internal/credential/service_list_libraries_ext_test.go
internal/session/service_list_ext_test.go
internal/target/service_list_ext_test.go

It might be surprising that these were passing, but I think functionally this doesn't change anything since our pagination logic actually mutates the incoming list token directly. Better still to have this look correct to avoid confusion.

Some pagination test fixes

---

.github/workflows/enos-run.yml

This PR makes a small update to the e2e test GitHub Actions workflow. This updates avoids an error showing up in the action summary if no log files were found (i.e. the test failed on the first run).

chore(e2e): Avoid error in action if no log files are found

---

internal/clientcache/internal/cache/repository_targets_test.go
internal/daemon/controller/handlers/authtokens/authtoken_service_test.go
internal/daemon/controller/handlers/credentiallibraries/credentiallibrary_service_test.go
internal/daemon/controller/handlers/credentials/credential_service_test.go
internal/daemon/controller/handlers/credentialstores/credentialstore_service_test.go
internal/daemon/controller/handlers/sessions/session_service_test.go
internal/daemon/controller/handlers/targets/tcp/target_service_test.go

The stability of the authorized_actions have been removed in main, so we need to add these sorts to all our new tests.

all: fix test failures after rebase

---

enos/modules/test_e2e/main.tf
testing/internal/e2e/tests/aws/env_test.go

[ICU-11880](https://hashicorp.atlassian.net/browse/ICU-11880)
This PR updates the e2e test suite to pass in the IP address of a worker to the aws test package. This allows for a test to execute a system command on the worker instance. The desired use case here is to test a scenario where we temporarily fill up the disk space on a worker during session recording.
We will need to update boundary-enterprise's `enos-scenario-e2e-aws_ent` to pass in the worker address to the test.
```
worker_address                = step.create_isolated_worker.worker_address
```
I tested this with the following test...
```
func TestFalloc(t *testing.T) {
e2e.MaybeSkipTest(t)
c, err := loadTestConfig()
require.NoError(t, err)
ctx := context.Background()
boundary.AuthenticateAdminCli(t, ctx)
output := …
```

test(e2e): Add worker ip to aws tests

---

enos/modules/docker_boundary/boundary-config-rate-limit.hcl
testing/internal/e2e/tests/base_plus/rate_limit_test.go

In `llb-list-pagination2`, TestCliRateLimit was failing for the following reason
```
rate_limit_test.go:326: Getting rate limit info...
rate_limit_test.go:343: Sending multiple CLI requests to hit rate limit...
rate_limit_test.go:347: 1.356015783s
rate_limit_test.go:347: 1.354126404s
rate_limit_test.go:347: 1.355090349s
rate_limit_test.go:347: 1.352092617s
rate_limit_test.go:347: 1.352088211s
rate_limit_test.go:347: 1.353169131s
rate_limit_test.go:354: 
Error Trace:	/src/boundary/testing/internal/e2e/tests/base_plus/rate_limit_test.go:354
Error:      	An error is expected but got nil.
Test:       	TestCliRateLimit
```
`llb-list-pagination` increased CLI request times, which caused `TestCliRateLimit` to send commands after the first quota expires, preventing the test from being …

test(e2e): Decrease rate limit in boundary config to resolve failures

---

internal/authtoken/query.go
internal/credential/query.go
internal/credential/static/query.go
internal/credential/vault/query.go
internal/db/schema/migrations/oss/postgres/80/02_target_base_table_updates.up.sql
internal/db/schema/migrations/oss/postgres/80/03_credential_static_base_table_updates.up.sql
internal/db/schema/migrations/oss/postgres/80/04_credential_library_base_table_updates.up.sql
internal/db/schema/migrations/oss/postgres/80/05_session_base_table_updates.up.sql
internal/db/schema/migrations/oss/postgres/80/06_auth_token_base_table_updates.up.sql
internal/db/schema/migrations/oss/postgres/80/07_credential_store_base_table_updates.up.sql
internal/db/schema/migrations/oss/postgres/80/08_iam_updates.up.sql
internal/db/schema/migrations/oss/postgres/80/09_host_table_updates.up.sql
internal/host/plugin/query.go
internal/host/static/query.go
internal/iam/repository_role.go
internal/session/query.go
internal/target/query.go

As @talanknight found, ordering the public_id by ascending while using the compound `(create_time, public_id) <` comparison risks missing items with identical update or create times. Order public_id by descending to keep ordering consistent.

Order public_id descending

---

.github/workflows/enos-run.yml
enos/enos-scenario-e2e-ui-aws.hcl
enos/enos-scenario-e2e-ui-docker.hcl
enos/modules/docker_worker/main.tf
enos/modules/test_e2e_ui/main.tf
enos/scripts/test_e2e_env.sh

This PR adds an enos scenario to set up docker-based infrastructure for use in Admin UI e2e tests. Note that this isn't adding anything to CI, just a scenario that can be used to run things locally.
```
enos scenario launch e2e_ui_docker builder:local
bash scripts/test_e2e_env.sh
yarn run e2e:ce:docker
```

test(e2e): Add docker-based infra scenario for Admin UI tests

---

internal/clientcache/testing.go
testing/internal/e2e/tests/base/search_test.go

This PR adds an e2e test for search.
```
❯ go test -v -count=1  github.com/hashicorp/boundary/testing/internal/e2e/tests/base -run Search
=== RUN   TestCliSearch
search_test.go:74: {"error":"The daemon process is not running."}. Retrying...
scope.go:61: Created Org Id: o_F2BOrKzDzq
scope.go:95: Created Project Id: p_y0EnVCy7Rf
search_test.go:110: Creating targets...
search_test.go:130: Listing targets...
search_test.go:143: Waiting for client cache to populate data...
search_test.go:186: Did not see expected number of targets in status, EXPECTED: 14, ACTUAL: 3. Retrying...
search_test.go:186: Did not see expected number of targets in status, EXPECTED: 14, ACTUAL: 3. Retrying...
search_test.go:181: Found 14 target(s)
search_test.go:193: Searching targets...
--- PASS: TestCliSearch (10.15s) …
```

test(e2e): Add test for search

---

internal/db/schema/migrations/oss/postgres/80/12_recording_session_updates.up.sql
internal/db/sqltest/tests/pagination/session_recording.sql

Session recordings will not require any new columns but will join storage buckets in the query to access the scope id.

internal/db: db migrations for session recordings

---

internal/authtoken/query.go
internal/authtoken/repository.go

Instead of doing the scope_id filtering in the second CTE, join the auth_account table to the auth_token table in the query directly.

internal/authtoken: join to auth_account to filter

---

internal/db/schema/migrations/oss/postgres/80/01_storage_bucket.up.sql

The storage domain does not allow the storage bucket prefix value to be mutated during an update action because it is not supported in the mask. However the column is mutable when directly interacting with the database table. This PR updates the `immutable_columns` trigger on the `storage_plugin_storage_bucket` table to include `bucket_prefix`.

fix(db): make bucket_prefix column immutable for storage buckets

---

.copywrite.hcl
LICENSE
internal/proto/controller/api/.copywrite.hcl
internal/proto/controller/custom_options/.copywrite.hcl
internal/proto/plugin/.copywrite.hcl
internal/proto/worker/proxy/v1/.copywrite.hcl

DO NOT MERGE UNTIL EOY 2023
Updates text in license and copywrite bot files for 2024.
Do not backport; release branches will be addressed individually.

EOY license updates

---

website/content/docs/release-notes/v0_13_0.mdx
website/content/docs/release-notes/v0_14_0.mdx

The Boundary 0.14.1 and 0.13.5 releases contained a CVE fix for Go that was not documented. It should be added to the release notes.
- [v 0.14.0 Release notes - known issues](https://boundary-bt4e2hohx-hashicorp.vercel.app/boundary/docs/release-notes/v0_14_0#known-issues-and-breaking-changes)
- [v 0.13.0 Release notes - new features (Enterprise)](https://boundary-bt4e2hohx-hashicorp.vercel.app/boundary/docs/release-notes/v0_13_0#new-features)

docs: Update release notes with fixes

---

website/content/docs/release-notes/v0_13_0.mdx
website/content/docs/release-notes/v0_14_0.mdx

This pull request backports the updates from #4192 to the `stable-website` branch:
* docs: Update release notes with fixes
* docs: Add note re fix in HCP/ENT
* docs: Update version numbers
* Update website/content/docs/release-notes/v0_14_0.mdx
---------

docs: Backport #4192 to stable website

---

website/content/docs/release-notes/v0_13_0.mdx
website/content/docs/release-notes/v0_14_0.mdx

This pull request backports the updates from #4192 to the `release/0.14.x` branch:
* docs: Update release notes with fixes
* docs: Add note re fix in HCP/ENT
* docs: Update version numbers
* Update website/content/docs/release-notes/v0_14_0.mdx
---------

docs: Backport #4192 to release 0.14.x

---

testing/dbtest/template.go

Normally the tests are run on a host machine with a docker container for
the database. The docker container should be accessible via 127.0.0.1.
However there might be cases where the test execution is run in a docker
container, or the postgres server is configured to use a different
docker network, in which case the container would be accessible via some
other dns name or ip. In these cases, users can now set the TEST_DB_HOST
environment variable so the tests can connect to the postgres server.

feat(dbtest): Allow host to be configurable

---

internal/daemon/controller/cors_test.go
internal/daemon/controller/handler.go

This adds a Access-Control-Expose-Headers response header to an Options
request to allow the rate limiting related headers to be accessible via
requests that are subject to CORS.

feat(controller): Expose rate limiting headers via CORS

---

internal/daemon/common/client_ip.go

Some platforms use `@` for a Unix socket address, and some leave it empty. In the empty case this causes the rate limiting code to throw a 500 error. This commit standardizes on using `@` for incoming connections over a Unix socket.

Fix Unix listener causing 500s on Mac

---

internal/cmd/base/internal/docker/supported.go
testing/dbtest/docker/Dockerfile.14-alpine
testing/dbtest/docker/Dockerfile.15-alpine
testing/dbtest/docker/Dockerfile.16-alpine
testing/dbtest/docker/postgresql.conf

After updating `boundary dev` to use postgres:12 by default, it was noticed
that the responsiveness of boundary was noticeably slower. This is due to
the introduction of JIT being enabled by default in postgres:12. JIT seems
to incur noticeable overhead without providing benefits, at least for the
instance used for `boundary dev`.
It is also worth noting that for postgres:14 and newer, JIT does not get
triggered for the same queries since they seem to result in a cheaper query
plan that does not exceed the default threshold for JIT.
This also updates the docker image used by tests to also disable JIT,
and adds additional docker images for tests for other postgres versions.

Disable postgres JIT for boudary dev

---

enos/ci/service-user-iam/main.tf
enos/modules/aws_bucket/main.tf
enos/modules/aws_iam_setup/main.tf

migrates from deprecated aws permission boundary user `BoundaryDemoPermissionsBoundary` to `DemoUser` and adds `s3:ListBucket` permissions where necessary

update enos permissions to include s3:ListBucket

---

internal/db/schema/migrations/oss/postgres/81/09_host_table_updates.up.sql
internal/db/sqltest/tests/pagination/host.sql

In tests, the index including the `catalog_id` performs significantly better.
I'm adding this to the host_plugin_host table too without actually having tested it (I will test it next), because it also looks up by catalog_id so it seems a reasonable starting point.

internal/db: use more efficient index for host listing

---

internal/session/repository_connection.go
internal/session/service_worker_status_report.go

This commit modifies a log line produced in the WorkerStatusReport function when closing orphaned connections that appears to incorrectly label a worker identifier as a controller identifier.

Use correct argument name in log line

---

website/content/docs/install-boundary/no-gen-resources.mdx

Message from terraform init : 
Single quotes are not valid. Use double quotes (") to enclose strings.

simple quote not accepted

---

website/redirects.js

In testing links for the new release, we realized some old pages that were moved never got added as redirects. This PR adds them.
These links should redirect:
(Old) https://boundary-38zwua70r-hashicorp.vercel.app//boundary/docs/api-clients/cli > (New) https://boundary-38zwua70r-hashicorp.vercel.app/boundary/docs/commands
(Old) https://boundary-38zwua70r-hashicorp.vercel.app//boundary/docs/concepts/service-discovery > (New) https://boundary-38zwua70r-hashicorp.vercel.app/boundary/docs/concepts/host-discovery

docs: Updating redirects for old pages

---

enos/modules/aws_iam_setup/main.tf

This PR addresses an issue in the e2e test suite after switching to use the [DemoUser](https://github.com/hashicorp/boundary/pull/4255) permissions boundary. I was getting the following error when running locally
```
Error: creating IAM User (demo-boundary-e2e-DXqX0): AccessDenied: User: arn:aws:sts::807078899029:assumed-role/boundary_team_acctest_dev-developer/michael.li@hashicorp.com is not authorized to perform: iam:CreateUser on resource: arn:aws:iam::807078899029:user/demo-boundary-e2e-DXqX0 because no identity-based policy allows the iam:CreateUser action
status code: 403, request id: 6c553fb1-a23e-45e9-86ad-e7d4db55188d
with module.iam_setup.aws_iam_user.boundary,
on ../../modules/aws_iam_setup/main.tf line 14, in resource "aws_iam_user" "boundary":
14: resource "aws_iam_user" …
```

chore(e2e): Fix iam user creation

---

internal/db/schema/migrations/oss/postgres/82/02_recording_session.up.sql
internal/db/sqltest/tests/pagination/session_recording.sql

The new index includes the new delete_time and delete_after columns, which are used in the list query.

internal/db/schema: update recording indexes

---

internal/cmd/commands/scopescmd/funcs.go

fixes indentation of `StoragePolicyId` during `boundary scopes list`
before:
```
% boundary scopes list
Scope information:
ID:                    o_64nJo0tYB1
Version:             2
Name:                session-recording-org
StoragePolicyId:      pst_MurBL06C6I
read
update
delete
attach-storage-policy
detach-storage-policy
no-op
ID:                    o_v46NxFsOQz
Version:             1
Name:                Generated org scope
Description:         Provides an initial org scope in Boundary
no-op
read
update
delete
attach-storage-policy
detach-storage-policy
```
after:
```
% boundary scopes list
Scope information:
ID:                    o_64nJo0tYB1
Version:             2
Name:                session-recording-org
StoragePolicyId:     pst_MurBL06C6I …
```

fix(cli): StoragePolicyId indent on list scopes

---

internal/cmd/commands/policiescmd/funcs.go
internal/cmd/commands/policiescmd/storage_funcs.go
internal/cmd/commands/sessionrecordingscmd/funcs.go
internal/cmd/commands/sessionrecordingscmd/reapply_storage_policy.go
internal/recording/time.go

This mainly fixes a typo in the reapply error string and changes `Retain Until: Keep Forever` to `Retain Until: Forever` to align the text with what the UI will display. Plus a couple of minor things my IDE was complaining about

chore: Fix typos

---

website/redirects.js

Added `permanent: true` to the recently added redirects as this is causing a build error in Dev Portal.
Error message:
```
`permanent` is not set to `true` or `false` for route {"source":"/boundary/docs/api-clients/cli","destination":"/boundary/docs/commands/","has":[{"type":"host","value":"developer.hashicorp.com"}]}
`permanent` is not set to `true` or `false` for route {"source":"/boundary/docs/concepts/service-discovery","destination":"/boundary/docs/concepts/host-discovery","has":[{"type":"host","value":"developer.hashicorp.com"}]}
Error: Invalid redirects found
Error: Command "npm run build" exited with 1
```

[website] Added permanent: true to redirects to fix build error

---

website/redirects.js

Heat fixed an error with our redirects in #4301. This PR backports the fix to stable website.

docs: Backport redirects fix to stable web

---

website/redirects.js

Heat fixed an error with our redirects in #4301. This PR backports the fix to release 0.14.x.

docs: Backport redirects fix to release 0.14.x

---

internal/credential/vault/supported.go

In `boundary-enterprise`, we were seeing the following test failure in CI
```
--- FAIL: TestAuthorizeSession_Errors (0.38s)
{"@level":"error","@message":"event.WriteError: no eventer available to write error: kms.(Kms).GetWrapper: unable to get wrapper: unknown: error #0: kms.(Kms).GetWrapper: error loading root key for scope \"global\": kms.(Kms).loadRoot: missing root key for scope \"global\": key not found","@timestamp":"2024-01-25T22:01:47.165680Z"}
supported.go:173: 
Error Trace:    /home/runner/actions-runner/_work/boundary-enterprise/boundary-enterprise/internal/credential/vault/supported.go:173
/home/runner/actions-runner/_work/boundary-enterprise/boundary-enterprise/internal/credential/vault/testing.go:1052
/home/runner/actions-runner/_work/boundary-enterprise/boundary-enterprise/ …
```

test: Randomize docker network name

---

website/content/docs/api-clients/client-cache.mdx
website/content/docs/commands/daemon/add-token.mdx
website/content/docs/commands/daemon/index.mdx
website/content/docs/commands/daemon/start.mdx
website/content/docs/commands/daemon/status.mdx
website/content/docs/commands/daemon/stop.mdx
website/content/docs/commands/search/index.mdx
website/data/docs-nav-data.json

This PR adds information about the new `boundary search` command and the client cache. The following topics were added or updated:
- [Client cache](https://boundary-gzhgt8rgo-hashicorp.vercel.app/boundary/docs/api-clients/client-cache) - new overview topic about how the local cache works with `search`
- New command documentation:
- [`search`](https://boundary-gzhgt8rgo-hashicorp.vercel.app/boundary/docs/commands/search)
- `daemon`:
- [Overview](https://boundary-gzhgt8rgo-hashicorp.vercel.app/boundary/docs/commands/daemon)
- [`add-token`](https://boundary-gzhgt8rgo-hashicorp.vercel.app/boundary/docs/commands/daemon/add-token)
- [`start`](https://boundary-gzhgt8rgo-hashicorp.vercel.app/boundary/docs/commands/daemon/start)
- [`status`](https://boundary-gzhgt8rgo-hashicorp.vercel.app/boundary/ …

docs: Add client cache documentation

---

website/content/docs/commands/policies/create.mdx
website/content/docs/commands/policies/delete.mdx
website/content/docs/commands/policies/index.mdx
website/content/docs/commands/policies/list.mdx
website/content/docs/commands/policies/read.mdx
website/content/docs/commands/policies/update.mdx
website/content/docs/concepts/domain-model/scopes.mdx
website/content/docs/concepts/domain-model/session-recordings.mdx
website/content/docs/concepts/domain-model/storage-policy.mdx
website/content/docs/configuration/session-recording/configure-storage-policy.mdx
website/content/docs/configuration/session-recording/create-storage-bucket.mdx
website/content/docs/configuration/session-recording/update-storage-policy.mdx
website/data/docs-nav-data.json

This PR updates the create storage bucket documentation to include new aws s3 actions that are required permissions for the recent changes in the aws storage plugin. The following new permissions are required: `DeleteObjects` `ListBucket`

chore: add storage policy documentation

---

website/content/docs/commands/roles/add-grants.mdx
website/content/docs/commands/roles/remove-grants.mdx
website/content/docs/commands/roles/set-grants.mdx

The `id` field was deprecated for grants in 0.13.1 in favor of an `ids` field. This PR updates the following command docs:
- [add-grants](https://boundary-oyrmli4jn-hashicorp.vercel.app/boundary/docs/commands/roles/add-grants)
- [remove-grants](https://boundary-oyrmli4jn-hashicorp.vercel.app/boundary/docs/commands/roles/remove-grants)
- [set-grants](https://boundary-oyrmli4jn-hashicorp.vercel.app/boundary/docs/commands/roles/set-grants)
Additional docs updates were made in #4274 and are already merged to `main`.

docs: Update `id` field for grants

---

website/content/docs/release-notes/v0_15_0.mdx
website/data/docs-nav-data.json

Adds the 0.15.0 release notes to the docs.
[View the update in the preview deployment](https://boundary-chah7vfi0-hashicorp.vercel.app/boundary/docs/release-notes/v0_15_0).

docs: Update release notes

---

website/content/docs/commands/roles/add-grant-scopes.mdx
website/content/docs/commands/roles/index.mdx
website/content/docs/commands/roles/remove-grant-scopes.mdx
website/content/docs/commands/roles/set-grant-scopes.mdx
website/content/docs/concepts/iam.mdx
website/data/docs-nav-data.json

This PR adds documentation for the new multiple grant scope commands.
It updates the existing index page for the `role` command to reflect the new subcommands: [Overview](https://boundary-1ewqwx586-hashicorp.vercel.app/boundary/docs/commands/roles)
And adds the following new pages for the subcommands:
- [add-grant-scopes](https://boundary-1ewqwx586-hashicorp.vercel.app/boundary/docs/commands/roles/add-grant-scopes)
- [remove-grant-scopes](https://boundary-1ewqwx586-hashicorp.vercel.app/boundary/docs/commands/roles/remove-grant-scopes)
- [set-grant-scopes](https://boundary-1ewqwx586-hashicorp.vercel.app/boundary/docs/commands/roles/set-grant-scopes)

docs: Add multiple grant scopes commands

---

.github/workflows/enos-run.yml

In GitHub Action `upload-artifact v4.0`, there was a breaking change for uploading multiple files to the same name (https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes). Previously, when you did that, it was bundled into a single zip file. Now, that is no longer allowed and files now need to have unique artifact names.
We will need this change when the action is updated to the new version.
Before:
After:

chore(e2e): Name output based on scenario

---

website/redirects.js

Added `permanent: true` to the [recently added](https://github.com/hashicorp/boundary/pull/4325) redirects as this is causing a build error in Dev Portal.
Error message:
```
`permanent` is not set to `true` or `false` for route {"source":"/boundary/docs/configuration/worker/kms-worker","destination":"/boundary/docs/configuration/worker/worker-configuration","has":[{"type":"host","value":"developer.hashicorp.com"}]}
`permanent` is not set to `true` or `false` for route {"source":"/boundary/docs/configuration/worker/pki-worker","destination":"/boundary/docs/configuration/worker/worker-configuration","has":[{"type":"host","value":"developer.hashicorp.com"}]}
Error: Invalid redirects found
Error: Command "npm run build" exited with 1
```
- [Asana …

[website] Added permanent: true to redirects to fix dev portal build error 

---

.github/labeler.yml

The github [labeler](https://github.com/actions/labeler) broke when upgrading to v5 from the [automated](https://github.com/hashicorp/boundary-ui/pull/2065) workflow pin upgrade.
The check for labeler in this PR will still fail as it's using the workflow and config file from `main`
(similar change to https://github.com/hashicorp/boundary-ui/pull/2078)

chore: Fix breaking change in labeler when upgrading to v5

---

enos/enos-scenario-e2e-aws-base.hcl
enos/enos-scenario-e2e-aws.hcl
enos/enos-scenario-e2e-database.hcl
enos/modules/aws_boundary/boundary-instances.tf
enos/modules/aws_boundary/outputs.tf
enos/modules/aws_boundary/templates/controller.hcl
enos/modules/aws_boundary/templates/controller_bsr.hcl
enos/modules/aws_boundary/variables.tf
enos/modules/test_e2e/main.tf
testing/internal/e2e/tests/aws/env_test.go

This is needed to add e2e tests for paginating storage buckets and session recordings.

enos: support max_page_size in AWS scenarios

---

enos/enos-scenario-e2e-aws.hcl

This PR modifies the enos aws scenario to reduce the number of ec2 instances created by 1 in order to help reduce costs. 
Previously, we were creating...
- 2 hosts with tag A
- 1 hosts with tag B
- 1 host in a different subnet
Now...
- 2 hosts with tag A
- 1 host in a different subnet with tag B
Will need to modify the enterprise variant of the scenario once this is merged.

chore(e2e): Reduce number of instances created

---

website/redirects.js

In PR #4338, Heat fixed a syntax error with Boundary redirects that were causing build errors. The fix was merged to `main` and `stable-website`, but it should also be backported to the `release/0.15.x` branch. This PR is that backport.

docs: Backport fix for redirects to 0.15.x branch

---

internal/cmd/commands/rolescmd/funcs.go
website/content/docs/commands/roles/add-grant-scopes.mdx

PR #4348 fixed an example in the CLI help and docs. It was merged to `main`, but must be merged to the stable website branch to make the change appear in the Boundary docs. This PR backports the change.

docs: Backport scope ID fix to website

---

.github/workflows/enos-run.yml
enos/modules/test_e2e/main.tf
enos/modules/test_e2e_docker/test_runner.sh

This PR removes the use of `tparse` in the e2e test suite (it was only being used in AWS-based enos scenarios). Doing so also removes the need to use the go cache, saving some time in CI (~20 seconds)
Note on the below times:
- `setup` has the most time-savings
- There's some time variability in the scenarios, but it saves ~10 seconds now that it does not have to restore the go cache.
Before:
https://github.com/hashicorp/boundary/actions/runs/7786366940/job/21231734235
After:
https://github.com/hashicorp/boundary/actions/runs/7763621684/job/21176203742

chore(e2e): Remove tparse

---

internal/cmd/commands/rolescmd/funcs.go
website/content/docs/commands/roles/add-grant-scopes.mdx

PR #4348 fixed an example in the CLI help and docs. It was merged to `main`, but must be merged to the release 0.15.x branch to be included in future versions. This PR backports the change.

docs: Backport scope ID fix to 0.15.x

---

.github/workflows/enos-run.yml
enos/modules/test_e2e/main.tf
enos/modules/test_e2e_docker/test_runner.sh

Reverts hashicorp/boundary#4326
I didn't realize that when running `go test`, it needed to download other go modules in order to execute. I assumed that the test suite only needed the go mod cache specifically for `tparse`.

Revert "chore(e2e): Remove tparse"

---

website/content/docs/enterprise/supported-versions.mdx

This PR backports the changes from #4334 and #4339 to the release 0.15.x branch.

docs: Backport support policy updates to 0.15.x

---

testing/internal/e2e/infra/docker.go
testing/internal/e2e/tests/database/migration_test.go

This is a fix to get the migration test passing due to changes in boundary (specifically the client cache daemon). This PR is an extension of this closed PR: https://github.com/hashicorp/boundary/pull/4344
If I understand the issue correctly...
The test is currently failing for the following reason
```
migration_test.go:389: 
│         	Error Trace:	/home/runner/work/boundary/boundary/testing/internal/e2e/tests/database/migration_test.go:389
│         	            				/home/runner/work/boundary/boundary/testing/internal/e2e/tests/database/migration_test.go:54
│         	Error:      	Should be empty, but was Error opening keyring: Specified keyring backend not available
│         	            	Token must be provided via BOUNDARY_TOKEN env var or -token flag. Reading the token can also be …
```

test(e2e): Fix error in migration test

---

internal/cmd/commands/authmethodscmd/authmethods.gen.go
internal/cmd/commands/authmethodscmd/ldap_authmethods.gen.go
internal/cmd/commands/authmethodscmd/oidc_authmethods.gen.go
internal/cmd/commands/authmethodscmd/password_authmethods.gen.go
internal/cmd/commands/authtokenscmd/authtokens.gen.go
internal/cmd/commands/credentiallibrariescmd/credentiallibraries.gen.go
internal/cmd/commands/credentiallibrariescmd/vault-generic_credentiallibraries.gen.go
internal/cmd/commands/credentiallibrariescmd/vault-ssh-certificate_credentiallibraries.gen.go
internal/cmd/commands/credentiallibrariescmd/vault_credentiallibraries.gen.go
internal/cmd/commands/credentialstorescmd/credentialstores.gen.go
internal/cmd/commands/credentialstorescmd/static_credentialstores.gen.go
internal/cmd/commands/credentialstorescmd/vault_credentialstores.gen.go
internal/cmd/commands/hostcatalogscmd/hostcatalogs.gen.go
internal/cmd/commands/hostcatalogscmd/plugin_hostcatalogs.gen.go
internal/cmd/commands/hostcatalogscmd/static_hostcatalogs.gen.go
internal/cmd/commands/hostsetscmd/hostsets.gen.go
internal/cmd/commands/hostsetscmd/plugin_hostsets.gen.go
internal/cmd/commands/hostsetscmd/static_hostsets.gen.go
internal/cmd/commands/managedgroupscmd/ldap_managedgroups.gen.go
internal/cmd/commands/managedgroupscmd/managedgroups.gen.go
internal/cmd/commands/managedgroupscmd/oidc_managedgroups.gen.go
internal/cmd/commands/policiescmd/policies.gen.go
internal/cmd/commands/sessionrecordingscmd/sessionrecordings.gen.go
internal/cmd/commands/storagebucketscmd/storagebuckets.gen.go
internal/cmd/common/help.go
internal/cmd/gencli/input.go
internal/cmd/gencli/templates.go

Fixes plural resource help displayed when using `boundary -h`
```
credential-libraries      Manage Boundary credential librarys
...
policies                  Manage Boundary policys
```
is now
```
credential-libraries      Manage Boundary credential libraries
...
policies                  Manage Boundary policies
```
This will also come in handy for aliases (right now, they would be displayed as `Manage Boundary aliass`)

commands: fix plurals

---

website/content/docs/commands/roles/create.mdx
website/content/docs/commands/roles/update.mdx
website/content/docs/release-notes/v0_15_0.mdx

This PR creates links from the 0.15.0 release notes to the command documentation for multi-grant scope support. It also adds a deprecation notice for the `grant-scope-id` field in the relevant command docs.
- [Version 0.15.0 release notes](https://boundary-qwetn9q2a-hashicorp.vercel.app/boundary/docs/release-notes/v0_15_0)
- [`roles create`](https://boundary-qwetn9q2a-hashicorp.vercel.app/boundary/docs/commands/roles/create)
- [`roles update`](https://boundary-qwetn9q2a-hashicorp.vercel.app/boundary/docs/commands/roles/update)

docs: Add links for multi grant scopes

---

website/content/docs/commands/roles/create.mdx
website/content/docs/commands/roles/update.mdx
website/content/docs/release-notes/v0_15_0.mdx

This PR backports the changes from #4368 to `stable-website`.
* docs: Add links for multi grant scopes
* Update website/content/docs/commands/roles/create.mdx
* docs: Add link to command docs
---------

docs: Add links for multi grant scopes - website

---

website/content/docs/commands/roles/create.mdx
website/content/docs/commands/roles/update.mdx
website/content/docs/release-notes/v0_15_0.mdx

This PR backports the changes from #4368 to `release/0.15.x`.
* docs: Add links for multi grant scopes
* Update website/content/docs/commands/roles/create.mdx
* docs: Add link to command docs
---------

docs: Add links for multi grant scopes - 0.15.x

---

testing/internal/e2e/helpers.go

This will be used for _particularly_ slow tests.

testing/e2e: add option to skip slow test

---

enos/modules/aws_boundary/templates/controller.hcl
enos/modules/aws_boundary/templates/controller_bsr.hcl

This PR applies a fix to https://github.com/hashicorp/boundary/pull/4352/files by moving the `max_page_size` property from the `listener` stanza to the `controller` stanza. 
Reference: https://developer.hashicorp.com/boundary/docs/configuration/controller

test(e2e): Fix where max_page_size is defined

---

internal/bsr/internal/checksum/sha256sums.go

This PR fixes a mistake of not acquiring the mutex lock for the `Close()` & `WriteString()` methods of the Sha256SumWriter object. This fix also prevents the panic we were seeing in a flaky test.

fix(bsr): acquire mutex lock on all methods of Sha256SumWriter

---

website/content/docs/api-clients/client-cache.mdx
website/content/docs/commands/daemon/add-token.mdx

This PR attempts to address some confusion around why search results are not displaying in scenarios where a user does not have permission to view them.
[Client cache](https://boundary-bg4tn2t78-hashicorp.vercel.app/boundary/docs/api-clients/client-cache)
[`daemon add-token`](https://boundary-bg4tn2t78-hashicorp.vercel.app/boundary/docs/commands/daemon/add-token)

docs: Clarify need for permissions to search

---

enos/enos-scenario-e2e-docker-base-plus.hcl
enos/modules/docker_boundary/main.tf
enos/modules/test_e2e_docker/main.tf
enos/modules/test_e2e_docker/test_runner.sh
go.mod
testing/internal/e2e/tests/base_plus/authenticate_no_keyring_test.go
testing/internal/e2e/tests/base_plus/env_test.go

There was a bug discovered where the client cache daemon would try to access the keyring to grab an auth token even though there was no keyring on the system (https://github.com/hashicorp/boundary/pull/4355). This PR adds a test to cover this case.
To achieve this, the test executes an `authenticate -format json` command on the docker container running the boundary controller, which has no keyring. Prior to the fix, we would get an error
```
❯ go test -v -count=1  github.com/hashicorp/boundary/testing/internal/e2e/tests/base -run TestCliAuthenticateNoKeyring
=== RUN   TestCliAuthenticateNoKeyring
authenticate_primary_test.go:132: {"status_code":200,"item":{"attributes":{"account_id":"acctpw_wKPEJfkpMr", ...
authenticate_primary_test.go:133: Error opening keyring: Specified keyring backend …
```

test(e2e): Add test for authentication when no keyring is available

---

website/content/docs/release-notes/v0_13_0.mdx
website/content/docs/release-notes/v0_14_0.mdx

This PR adds information about the patch for [HCSEC-2402-02](https://discuss.hashicorp.com/t/hcsec-2024-02-boundary-vulnerable-to-session-hijacking-through-tls-certificate-tampering/62458) to the v0.13.0 and v0.14.0 release notes.
- [v0.13.0 known issues](https://boundary-7b96cidfu-hashicorp.vercel.app/boundary/docs/release-notes/v0_13_0#known-issues)
- [v0.14.0 known issues](https://boundary-7b96cidfu-hashicorp.vercel.app/boundary/docs/release-notes/v0_14_0#known-issues-and-breaking-changes)

docs: Add HCSEC-2402-02 info to release notes

---

website/content/docs/release-notes/v0_13_0.mdx
website/content/docs/release-notes/v0_14_0.mdx

This PR backports #4386 to the stable-website branch.

docs: Backport #4386 to website

---

website/content/docs/release-notes/v0_13_0.mdx
website/content/docs/release-notes/v0_14_0.mdx

This PR backports #4386 to the release 0.15.x branch.

docs: Backport #4386 to release 0.15.x

---

website/content/docs/install-boundary/install.mdx

This PR updates the instructions for installing Boundary on Ubuntu per [SPE-726](https://hashicorp.atlassian.net/browse/SPE-726).
[View the update in the preview deployment](https://boundary-8i2epkgly-hashicorp.vercel.app/boundary/docs/install-boundary/install).
[SPE-726]: https://hashicorp.atlassian.net/browse/SPE-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Update deprecated install command

---

internal/bsr/internal/sign/sign.go

This PR fixes the following race condition errors:
```
Write at 0x00c005a89e50 by goroutine 4628:
bytes.(*Buffer).Write()
/opt/homebrew/Cellar/go/1.21.7/libexec/src/bytes/buffer.go:176 +0x38
io.(*multiWriter).Write()
/opt/homebrew/Cellar/go/1.21.7/libexec/src/io/multi.go:85 +0xb0
github.com/hashicorp/boundary/internal/bsr/internal/sign.(*Writer).Write()
/Users/ddebko/github/boundary-enterprise/internal/bsr/internal/sign/sign.go:60 +0x80
github.com/hashicorp/boundary/internal/bsr/internal/sign.(*File).Write()
<autogenerated>:1 +0x20
github.com/hashicorp/boundary/internal/bsr/internal/checksum.(*File).WriteAndClose()
/Users/ddebko/github/boundary-enterprise/internal/bsr/internal/checksum/checksum.go:148 +0x6d4
github.com/hashicorp/boundary/internal/bsr.ChunkEncoder.Encode() …
```

fix(bsr): resolve race condition errors in signature file

---

website/content/docs/install-boundary/install.mdx

This PR backports #4409 to the stable-website branch.
* docs: Update deprecated install command
* docs: Update command to add repo

docs: Backport #4409 to website

---

website/content/docs/install-boundary/install.mdx

This PR backports #4409 to the release 0.15.x branch.
* docs: Update deprecated install command
* docs: Update command to add repo

docs: Backport #4409 to release 0.15.x

---

testing/internal/e2e/boundary/session.go

This PR adds an optional parameter to the `WaitForSessionCli` function to make waiting for new sessions more convenient in scenarios where more than 1 session expected to be in the specified scope.
**Usage examples**
`boundary.WaitForSessionCli(t, ctx, newProjectId, boundary.WithExpectedSessionsCount(2))`
or
`boundary.WaitForSessionCli(t, ctx, newProjectId) // expected sessions count defaults to 1`
This change is needed for an e2e storage policies test that will be added to the `boundary-enterprise` repo in this [PR](https://github.com/hashicorp/boundary-enterprise/pull/929) once this PR has been merged.

test(e2e): Add option to wait for multiple sessions

---

internal/daemon/controller/handlers/accounts/account_service_test.go
internal/daemon/controller/handlers/authmethods/authmethod_service.go
internal/daemon/controller/handlers/authmethods/authmethod_service_test.go
internal/daemon/controller/handlers/authtokens/authtoken_service.go
internal/daemon/controller/handlers/authtokens/authtoken_service_test.go
internal/daemon/controller/handlers/credentiallibraries/credentiallibrary_service_test.go
internal/daemon/controller/handlers/credentials/credential_service_test.go
internal/daemon/controller/handlers/credentialstores/credentialstore_service_test.go
internal/daemon/controller/handlers/groups/group_service.go
internal/daemon/controller/handlers/groups/group_service_test.go
internal/daemon/controller/handlers/host_catalogs/host_catalog_service.go
internal/daemon/controller/handlers/host_catalogs/host_catalog_service_test.go
internal/daemon/controller/handlers/host_sets/host_set_service_test.go
internal/daemon/controller/handlers/hosts/host_service_test.go
internal/daemon/controller/handlers/managed_groups/managed_group_service_test.go
internal/daemon/controller/handlers/roles/role_service.go
internal/daemon/controller/handlers/roles/role_service_test.go
internal/daemon/controller/handlers/scopes/scope_service.go
internal/daemon/controller/handlers/scopes/scope_service_test.go
internal/daemon/controller/handlers/sessions/session_service_test.go
internal/daemon/controller/handlers/targets/target_service.go
internal/daemon/controller/handlers/targets/tcp/target_service_test.go
internal/daemon/controller/handlers/users/user_service.go
internal/daemon/controller/handlers/users/user_service_test.go

Ensure that pagination parameters are always returned from successful list calls. Turns out the only affected list endpoint was targets (🙄 of course), but I've also added tests to all the other endpoints. The removed lines are never hit as an error is returned from the called function if there are no scopes available.

handlers: always return pagination parameters in list

---

testing/internal/e2e/tests/base/target_tcp_connect_exec_long_lasting_script_test.go
testing/internal/e2e/tests/base/testdata/long_lasting_test_script.sh

This PR adds an e2e-test to verify that SSH requests sent to target can execute long-lasting scripts successfully.
The test saves a ~10s-long script on the target and sends two SSH requests:
- to execute the script saved on the target
- to execute a script sent with the SSH request
This PR relates to this [bug fix](https://github.com/hashicorp/boundary-enterprise/pull/926). The test for ssh-targets will be added to boundary-enterprise in a separate PR.

test(e2e): Verify long scripts complete successfully on tcp targets

---

testing/internal/e2e/boundary/target.go
testing/internal/e2e/tests/base/target_tcp_connect_session_max_seconds_test.go

This PR adds an e2e test to validate the `-session-max-seconds` option on a target.
The test does the following
- creates a target with `-session-max-seconds` set to 7
- starts a session on a target
- confirms that connections created within the time limit are successful
- confirms that a connection created after the time limit will be refused

test(e2e): Add test to check target's `-session-max-seconds`

---

testing/internal/e2e/tests/base/target_tcp_connect_session_max_seconds_test.go

This PR fixes an e2e test introduced in https://github.com/hashicorp/boundary/pull/4411.
After merging, it was observed that the test would sometimes fail due to the following
```
target_tcp_connect_session_max_seconds_test.go:165: 
Error Trace:	/src/boundary/testing/internal/e2e/tests/base/target_tcp_connect_session_max_seconds_test.go:165
Error:      	"8.637663214" is not less than "8"
Test:       	TestCliTcpTargetConnectTargetWithSessionMaxSecondsRejectNew
target_tcp_connect_session_max_seconds_test.go:165: 
Error Trace:	/src/boundary/testing/internal/e2e/tests/base/target_tcp_connect_session_max_seconds_test.go:165
Error:      	"8.774918861" is not less than "8"
Test:       	TestCliTcpTargetConnectTargetWithSessionMaxSecondsRejectNew
target_tcp_connect_session_max_seconds_test.go:165: …
```

test(e2e): Add extra buffer in -session-max-seconds test

---

internal/tests/cli/boundary/target_aliases.bats

The bats test ordering isn't deterministic; if target_aliases.bats runs before targets.bats, it interferes with the results.
This PR fixes that by using a different target name in target_aliases.bats and deleting the target at the end of the test.

fix(bats): use different target name in alias tests

---

testing/internal/e2e/tests/base/target_tcp_connect_session_max_seconds_test.go

Similar to https://github.com/hashicorp/boundary/pull/4428, this PR adjusts a different `-session-max-seconds` tests to increase the buffer to allow for another second in duration.

fix(e2e): Add extra buffer in -session-max-seconds test again

---

internal/cmd/commands/workerscmd/funcs.go

This does not currently remove the field from the message on the API but since it will now always show `pki` it's meaningless and causing confusion for some users.

Remove worker type from CLI output

---

testing/internal/e2e/boundary/credential.go
testing/internal/e2e/tests/base_with_vault/credential_store_test.go
testing/internal/e2e/tests/base_with_vault/target_tcp_vault_connect_test.go
testing/internal/e2e/tests/base_with_vault/target_tcp_vault_generic_connect_authz_token_test.go
testing/internal/e2e/tests/base_with_vault/target_tcp_vault_generic_connect_ssh_test.go
testing/internal/e2e/tests/base_with_vault/target_tcp_vault_generic_connect_test.go
testing/internal/e2e/tests/base_with_worker/target_tcp_worker_connect_ssh_test.go
testing/internal/e2e/tests/database/migration_test.go

This PR does a refactor in the e2e test suite to create a helper method for creating vault-generic credential libraries. It also continues the new pattern of returning `err`  and giving the entity a random name.

refact(e2e): Create vault-generic credential library helper method

---

website/content/docs/configuration/kms/azurekeyvault.mdx

This PR fixes a typo from this documentation: https://developer.hashicorp.com/boundary/docs/configuration/kms/azurekeyvault

doc(kms): Fix typo

---

internal/cmd/base/initial_resources.go

Alias names need to match a web target address; the `web.boundary.dev` alias was failing to connect.

dev: use URL for web target and add caveat

---

api/accounts/option.gen.go
api/authmethods/option.gen.go
api/authtokens/option.gen.go
api/credentiallibraries/option.gen.go
api/credentials/option.gen.go
api/credentialstores/option.gen.go
api/groups/option.gen.go
api/hostcatalogs/option.gen.go
api/hosts/option.gen.go
api/hostsets/option.gen.go
api/managedgroups/option.gen.go
api/policies/option.gen.go
api/roles/option.gen.go
api/scopes/option.gen.go
api/sessionrecordings/option.gen.go
api/sessions/option.gen.go
api/storagebuckets/option.gen.go
api/targets/option.gen.go
api/users/option.gen.go
api/workers/option.gen.go
internal/api/genapi/templates.go

This PR addresses the following `make-gen-delta` CI error on `release/0.15.x`
```
diff --git a/api/billing/option.gen.go b/api/billing/option.gen.go
index 932777f7f..c3ebdbb28 100644
--- a/api/billing/option.gen.go
+++ b/api/billing/option.gen.go
@@ -15,7 +15,7 @@ import (
// to be used directly, but instead option arguments are built from the
// functions in this package. WithX options set a value to that given in the
// argument; DefaultX options indicate that the value should be set to its
-// default. When an API call is made options are processed in the order they
+// default. When an API call is made options are processed in ther order they
// appear in the function call, so for a given argument X, a succession of WithX
// or DefaultX calls will result in the last call taking …
```

doc: Fix typo in api template

---

testing/internal/e2e/tests/base/alias_test.go

This PR adds an e2e test for aliases.
The test does the following
- creates a target with an address
- creates an alias to that target
- connects to the target (`boundary connect`) using the alias
- connects to the target (`boundary connect ssh`) using the alias
- authorize a session (`boundary targets authorize-session`) using the alias
- add an `-authorize-session-host-id` to the alias and authorize a session using the alias again
- attempt to use an alias that doesn't exist

test(e2e): Add test for alias

---

website/content/docs/configuration/worker/worker-configuration.mdx

This PR fixes a broken link in the worker configuration doc.
[View the update in the preview deployment](https://boundary-ej9p7tih3-hashicorp.vercel.app/boundary/docs/configuration/worker/worker-configuration).

docs: Fix broken link in worker config topic

---

enos/modules/docker_vault/config/config.json
enos/modules/docker_vault/main.tf

This PR updates the e2e test suite to use `vault server` instead of `vault dev` to more closely emulate a production environment. To do so, this PR does the following...
- sets a command to the docker instance to run `vault server`
- after starting the docker image, run `vault operator init`. Extract the data from that output.
- run `vault operator unseal KEY` x3 to unseal vault

test(e2e): Use vault server instead of vault dev

---

enos/enos-scenario-e2e-ui-docker.hcl
enos/modules/docker_openssh_server_ca_key/main.tf
enos/modules/test_e2e_ui/main.tf

This PR updates the `docker_openssh_server_ca_key` module to return the public CA key so that it can be passed to the UI tests. This is to support the an Admin UI SSH certificate injection test.
I was trying to figure out how to generate the public key from the private key within the Admin UI test itself (using `node.js`), but I wasn't able to find a solution that worked for all keys without adding additional dependencies in the UI project. Also, the built-in `crypto` node module didn't supported OpenSSH keys.

test(e2e): Provide public ca key to UI tests

---

internal/ui/VERSION

This PR bumps the UI version in `main` to the commit used in `0.15.1`.

chore: Bump UI commit

---

enos/modules/test_e2e_docker/main.tf

This PR bumps the e2e test suite timeout to `25m`. 
There have been a few instances where the e2e tests runtime hit this limit. For now, we will update the timeout to make things pass more regularly. There will also be some additional activity to reorganize the e2e tests as runtime has become too long.

chore(e2e): Bump e2e test timeout

---

website/content/docs/concepts/workers.mdx

Backports #4487 to release 0.15.x.
* docs(worker): add information about worker status and health
---------

docs: Backport worker doc update - 0.15.x

---

website/content/docs/release-notes/v0_14_0.mdx
website/content/docs/release-notes/v0_15_0.mdx

This PR backports #4505 to release/0.15.x.

docs: Backport #4505 to release 0.15.x

---

internal/cmd/commands/server/listener_reload_test.go
internal/credential/vault/jobs_test.go

It hasn't been investigated why this is happening (getting a number of 403 errors) but for now removing parallel fixes it.

Comment out parallel statements causing test failures

---

enos/enos-scenario-e2e-ui-aws.hcl
enos/enos-scenario-e2e-ui-docker.hcl
enos/modules/aws_boundary/boundary-instances.tf
enos/modules/aws_boundary/templates/worker_bsr.hcl
enos/modules/aws_boundary/variables.tf
enos/modules/test_e2e_ui/main.tf

This PR updates some enos modules to add session recording resources support for UI tests. There will be a follow-up PR to add a `UI_AWS_ENT` scenario.

chore(e2e): Add session recording resources for UI tests

---

internal/daemon/worker/controller_connection.go

At some point we migrated to grpc ConnectParams to control how often retries were happening. One value that we didn't set was the MinConnectTimeout. It turns out that if you don't set this, it won't use the default; instead if will actually use a value of zero, which gRPC internally ups to something that seems to be around 25ms to meet a minimum threshold. This is not documented in the function comments.
This commit simply sets the value of MinConnectTimeout to the unexported gRPC default.

Fix issue with workers connecting in high latency conditions

---

CODEOWNERS

This PR adds the docs team as codeowners for any changes in the `website/content` directory

chore: Add edu team as codeowners for website

---

go.mod
go.sum

This PR updates a docker dependency to address the following vulnerabilities
- GHSA-mq39-4gv4-mvpx
- GO-2024-2659

chore: Update docker dep

---

enos/modules/docker_minio/init.sh

This PR removes a leftover debug line in the `docker_minio` enos module.

test(e2e): Remove leftover debug line

---

website/content/docs/concepts/auditing.mdx

Adding documentation on the BSR chunk files to help users understand how to read BSR files.
While we don't provide a tool that can be used to read all BSR data files, this should hopefully help users figure out how to read data files and develop their own tooling, if desired.

docs(bsr): explain bsr data chunks

---

website/content/docs/enterprise/automated-license-reporting.mdx

Updates information about enterprise license reporting by adding `monthly_active_users` to telemetry collected.
[View the update in the preview deployment](https://boundary-1bpofhda0-hashicorp.vercel.app/boundary/docs/enterprise/automated-license-reporting#example-payloads)

docs: Update license reporting

---

website/content/docs/release-notes/v0_14_0.mdx
website/content/docs/release-notes/v0_15_0.mdx

This PR updates the 0.14.x and 0.15.x known issues with information about the 0.14.6 and 0.15.4 releases.
- [Version 0.14.x known issues](https://boundary-rllxarhs2-hashicorp.vercel.app/boundary/docs/release-notes/v0_14_0#known-issues-and-breaking-changes)
- [Version 0.15.x known issues](https://boundary-rllxarhs2-hashicorp.vercel.app/boundary/docs/release-notes/v0_15_0#known-issues-and-breaking-changes)

docs: Update release notes for April 9 release

---

website/content/docs/install-boundary/terraform-patterns/index.mdx
website/content/docs/install-boundary/terraform-patterns/terraform-credentials-and-credential-stores.mdx
website/content/docs/install-boundary/terraform-patterns/terraform-groups-and-rbac.mdx
website/content/docs/install-boundary/terraform-patterns/terraform-hosts-and-host-management.mdx
website/content/docs/install-boundary/terraform-patterns/terraform-scopes.mdx
website/content/docs/install-boundary/terraform-patterns/terraform-session-recording.mdx
website/content/docs/install-boundary/terraform-patterns/terraform-targets.mdx
website/content/docs/install-boundary/terraform-patterns/terraform-users-and-auth-methods.mdx
website/data/docs-nav-data.json

The automatic backport of #4561 failed. This PR manually recreates it.
* Added using-terraform.mdx to the Install Boundary section
* Initial revision
* formatting on the list and adding in some links to the provider
* Renamed file
* Added assumptions.
* Updated index.
* Fixed some typos
* Folded in Carlos's session recording code
* small changes
* fixes headers
* fixes internal developer links
* style guide and formatting enhancements
* updates Initialize Boundary link
* docs: Updates for style/standards
* docs: Break topic into smaller pieces
* docs: Clean up commented text, rename index file
* docs: Trigger a new Vercel build
---------
Co-authored-by: Daniel Greeninger <daniel.greeninger@hashicorp.com>
Co-authored-by: Adam Bouhmad <adbouhmad@gmail.com>
Co-authored-by: Robin Beck …

docs: Backport #4561 to stable-website

---

website/content/docs/install-boundary/terraform-patterns/index.mdx
website/content/docs/install-boundary/terraform-patterns/terraform-credentials-and-credential-stores.mdx
website/content/docs/install-boundary/terraform-patterns/terraform-groups-and-rbac.mdx
website/content/docs/install-boundary/terraform-patterns/terraform-hosts-and-host-management.mdx
website/content/docs/install-boundary/terraform-patterns/terraform-scopes.mdx
website/content/docs/install-boundary/terraform-patterns/terraform-session-recording.mdx
website/content/docs/install-boundary/terraform-patterns/terraform-targets.mdx
website/content/docs/install-boundary/terraform-patterns/terraform-users-and-auth-methods.mdx
website/data/docs-nav-data.json

The automatic backport of #4561 failed. This PR manually recreates it.
* Added using-terraform.mdx to the Install Boundary section
* Initial revision
* formatting on the list and adding in some links to the provider
* Renamed file
* Added assumptions.
* Updated index.
* Fixed some typos
* Folded in Carlos's session recording code
* small changes
* fixes headers
* fixes internal developer links
* style guide and formatting enhancements
* updates Initialize Boundary link
* docs: Updates for style/standards
* docs: Break topic into smaller pieces
* docs: Clean up commented text, rename index file
* docs: Trigger a new Vercel build
---------
Co-authored-by: Daniel Greeninger <daniel.greeninger@hashicorp.com>
Co-authored-by: Adam Bouhmad <adbouhmad@gmail.com>
Co-authored-by: Robin Beck …

docs: Backport #4561 to release 0.15.x

---

website/content/docs/concepts/credential-management.mdx
website/content/docs/configuration/credential-management/configure-credential-brokering.mdx
website/content/docs/configuration/credential-management/configure-credential-injection.mdx
website/content/docs/configuration/credential-management/index.mdx
website/content/docs/configuration/credential-management/static-cred-boundary.mdx
website/content/docs/configuration/credential-management/static-cred-vault.mdx
website/content/docs/integrations/vault/index.mdx
website/data/docs-nav-data.json

The automatic backport failed, so this PR backports #4579 to the stable website branch.
* add a new cred management files
* adding credential management files
* fixed type-os, added ent labels, grouped cli/ui
* added reference links from concepts section and Vault integration section to new cred management pages
* style guide and formatting enhancements
* style guide and formatting enhancements
* fixes internal link
* docs: Updates for styles and standards
* docs: Fix link structure
* docs: Break out brokering/injection procedures
* docs: Clean up commented out code
* docs: Rename index file per best practices
* docs: Update page description meta content
* docs: Add level 2 …

docs: Backport #4579 to stable website

---

website/content/docs/concepts/credential-management.mdx
website/content/docs/configuration/credential-management/configure-credential-brokering.mdx
website/content/docs/configuration/credential-management/configure-credential-injection.mdx
website/content/docs/configuration/credential-management/index.mdx
website/content/docs/configuration/credential-management/static-cred-boundary.mdx
website/content/docs/configuration/credential-management/static-cred-vault.mdx
website/content/docs/integrations/vault/index.mdx
website/data/docs-nav-data.json

* add a new cred management files
* adding credential management files
* fixed type-os, added ent labels, grouped cli/ui
* added reference links from concepts section and Vault integration section to new cred management pages
* style guide and formatting enhancements
* style guide and formatting enhancements
* fixes internal link
* docs: Updates for styles and standards
* docs: Fix link structure
* docs: Break out brokering/injection procedures
* docs: Clean up commented out code
* docs: Rename index file per best practices
* docs: Update page description meta content
* docs: Add level 2 headings for organization
---------
Co-authored-by: Robin Beck <stellarsquall@protonmail.ch> …

docs: Backport #4579 to release 0.15.x

---

website/content/docs/configuration/kms/aead.mdx
website/content/docs/configuration/kms/alicloudkms.mdx
website/content/docs/configuration/kms/azurekeyvault.mdx
website/content/docs/configuration/kms/gcpckms.mdx
website/content/docs/configuration/kms/ocikms.mdx
website/content/docs/configuration/kms/transit.mdx

Any of the KMS key types can be used as `bsr` recovery keys, however it is only documented for AWS KMS.

docs: Update KMS `purpose` field for BSR

---

.github/workflows/build.yml
Dockerfile
scripts/build.sh

Adds our LICENSE file as LICENSE.txt to our binary .zip files, Docker containers, and RPM files.
I've downloaded the .zip, .rpm, and .deb files and docker tarballs produced and confirmed they contain the LICENSE.txt as expected.

build: include LICENSE.txt in all artifacts

---

website/content/docs/concepts/filtering/worker-tags.mdx

Vault worker filters are not an Enterprise feature, so we're removing it.

Update worker-tags.mdx to remove Enterprise tag on Vault worker filter

---

internal/daemon/worker/controller_connection_test.go

We have observed `TestMonitorUpstreamConnectionState` failing due to the following
```
--- FAIL: TestMonitorUpstreamConnectionState (0.02s)
--- FAIL: TestMonitorUpstreamConnectionState/connection_with_multiple_good_addresses (0.00s)
controller_connection_test.go:105: 
Error Trace:	/home/runner/work/boundary/boundary/internal/daemon/worker/controller_connection_test.go:105
Error:      	Not equal: 
expected: 2
actual  : 1
Test:       	TestMonitorUpstreamConnectionState/connection_with_multiple_good_addresses
```
where...
`1` = Connecting
`2` = Ready
This PR modifies the test to remove the extra check at the end of the test. `waitForConnectionStateCondition` will already have observed the expected state.
https://hashicorp.atlassian.net/browse/ICU-13235

test(worker): Address flake in TestMonitorUpstreamConnectionState

---

testing/internal/e2e/tests/base_plus/rate_limit_test.go

Observed a failure in an e2e test for the following reason
```
=== RUN   TestHttpRateLimit
│     scope.go:85: Created Org Id: o_bIvTZldr5D
│     scope.go:127: Created Project Id: p_PrxnqspsjA
│     host.go:123: Created Host Catalog: hcst_4hOAYpqAeR
│     host.go:188: Created Host: hst_Ee61h11NCX
│     rate_limit_test.go:65: Sending API requests until quota is hit...
│     rate_limit_test.go:85: 3;w=10;comment="auth-token"
│     rate_limit_test.go:89: limit=3, remaining=2, reset=10
│     rate_limit_test.go:109: limit=3, remaining=1, reset=10
│     rate_limit_test.go:109: limit=3, remaining=0, reset=10
│     rate_limit_test.go:119: Checking that next API request is rate limited...
│     rate_limit_test.go:138: Waiting for 10 seconds to retry API request...
│     rate_limit_test.go:142: …
```

test(e2e): Address flake in rate limit test

---

go.mod
go.sum

This PR updates the dependency `github.com/docker/docker` to resolve GHSA-x84c-p2g9-rqv9

chore: Update docker dependency

---

internal/event/context.go
internal/event/context_unexported_test.go

When running into `context deadline exceeded`, Boundary attempts to use the same context to publish events which may lead to further failure. Adding a check to also create a new `context` when `ctx.Err() == context.DeadlineExceeded`

make newSendCtx also handle context.DeadlineExceeded

---

internal/session/repository_connection.go
internal/session/repository_session.go

When closing orphaned connections and checking if a session is not
active, the repository was opening a transaction, but then calling the
original reader instead of using the reader/writer from the transaction.
This would result in a transaction being opend, then a separate
transaction being used to run the query, and finally the original
transaction would commit without any statements being executed.
Co-authored-by: Sorawis Nilparuk (Bo) <sorawis.nilparuk@hashicorp.com>

fix(session): Use active transaction

---

website/content/docs/concepts/domain-model/credential-libraries.mdx

Fixes broken ssh certificates tutorial link on credential libraries page.

fixes broken tutorial link

---

website/content/docs/install-boundary/architecture/recommended-architecture.mdx

Fixed a small typo in `CLI` in Boundary recommended architecture doc

Fix CLI typo in recommended-architecture.mdx

---

enos/modules/aws_boundary/variables.tf

Some e2e tests were failing for the following reason
```
Error: creating RDS DB Instance (boundary-db-djcdlozc): InvalidParameterCombination: Cannot find version 15.3 for postgres
status code: 400, request id: 97d6281e-b440-4885-b6fe-12a03827a6dc
with module.create_boundary_cluster.aws_db_instance.boundary[0],
on ../../modules/aws_boundary/rds.tf line 9, in resource "aws_db_instance" "boundary":
9: resource "aws_db_instance" "boundary" {
Validate: success!
Plan: success!
```
This PR bumps the postgres version.

test(e2e): Update postgres version

---

enos/modules/aws_iam_setup/main.tf

This PR updates an enos module that creates an IAM user to add support for credential rotation. The module was updated with the following
- a new variable to the module to decide whether or not credential rotation support is needed (default: `false`)
- if credential rotation support is enabled, the IAM user needs the `force_destroy` option set to true in order for terraform to successfully clean up afterwards (otherwise you'll get an error like `Cannot delete entity, must delete access keys first.` since new access keys were created)
- if credential rotation is enabled, another policy is added to the user that allows the user to rotate its access keys
There will be a follow-up PR in `boundary-enterprise` to add the associated tests.
There will also be follow-up work to add similar tests …

test(e2e): Add module for iam user with credential rotation support

---

testing/internal/e2e/tests/base_plus/rate_limit_test.go

This PR does some clean up in the e2e rate limit tests to ensure that the test is properly closing http requests.

test(e2e): Close http requests in rate limit test

---

website/content/docs/api-clients/api/index.mdx
website/content/docs/api-clients/api/rate-limiting.mdx

This PR adds the `x-correlation-id` HTTP header to the API Overview docs.
https://boundary-gwxwnbon6-hashicorp.vercel.app/boundary/docs/api-clients/api#http-headers

docs: Revise HTTP header documentation

---

website/content/docs/release-notes/v0_16_0.mdx
website/data/docs-nav-data.json

Adds release notes for release 0.16.0.
[View the update in the preview deployment](https://boundary-bl0nfj3ap-hashicorp.vercel.app/boundary/docs/release-notes/v0_16_0).

docs: Release notes

---

website/content/docs/release-notes/v0_16_0.mdx

This PR adds a note to the 0.16 release notes regarding the deprecation of auto-role creation when new scopes are created in light of multi-scope grants.

Release Notes: adds note about future auto-role creation deprecation

---

testing/internal/e2e/tests/base/alias_test.go

This PR updates the e2e-test for aliases. It adds the following verifications:
- When there is multiple hosts are added to the host set used for the target, an alias with a host id points to the specified one

test(e2e): Verify host id and invalid input for aliases

---

internal/tests/cli/boundary/_aliases.bash
internal/tests/cli/boundary/alias.bats

This PR moves verifications previously added to [the aliases e2e-test](https://github.com/hashicorp/boundary/pull/4691) to the bats test suite

test(bats): Update aliases bats tests

---

website/content/docs/configuration/worker/worker-configuration.mdx

This PR fixes a broken link in the `Worker configuration` page. Addresses a fix reported here: https://github.com/hashicorp/boundary/pull/2550
Preview: https://boundary-7npmbsk73-hashicorp.vercel.app/boundary/docs/configuration/worker/worker-configuration
- Click on the link to `initial_upstreams`

docs: Fix broken link in `Worker configuration` page

---

website/content/docs/install-boundary/configure-workers.mdx

The backport to the new release branch `release/0.16.x` failed for PR #4772. This PR manually cherry picks it to the release branch.

docs: Backport #4772 to release 0.16.x

---

internal/cmd/commands/workerscmd/funcs.go

Noticed the worker tags help output used [sub command] instead of [options]

chore: fix workers tag cmd help strings

---

website/content/docs/commands/session-recordings/delete.mdx
website/content/docs/commands/session-recordings/index.mdx
website/content/docs/commands/session-recordings/read.mdx
website/content/docs/commands/session-recordings/reapply-storage-policy.mdx
website/data/docs-nav-data.json

This PR adds the sub-commands `delete` and `reapply-storage-policy` to the `session-recordings` CLI documentation, and fixes the id in the read command.
- [`delete`](https://boundary-eyr0mu7wp-hashicorp.vercel.app/boundary/docs/commands/session-recordings/delete)
- [`reapply-storage-policy`](https://boundary-eyr0mu7wp-hashicorp.vercel.app/boundary/docs/commands/session-recordings/reapply-storage-policy)
- [`read`](https://boundary-eyr0mu7wp-hashicorp.vercel.app/boundary/docs/commands/session-recordings/read)

docs: Update session-recordings CLI doc

---

website/content/docs/configuration/controller.mdx
website/content/docs/install-boundary/configure-controllers.mdx

This PR attempts to alleviate some confusion about the need for a bsr purpose key to enable session recording. It adds bsr KMS stanzas to the controller configuration examples in the Install guide and the Controller concept topic.
Inspired by Slack conversations [here](https://hashicorp.slack.com/archives/C016ZKNM05T/p1715003124734679) and [here](https://hashicorp.slack.com/archives/C01AQDJF3SA/p1712948354314109?thread_ts=1712947090.165509&cid=C01AQDJF3SA).
Install Boundary > Configure controllers:
- [Prepare KMS keys](https://boundary-p3awwe2kz-hashicorp.vercel.app/boundary/docs/install-boundary/configure-controllers#prepare-kms-keys)
- [Create the controller configuration](https://boundary-p3awwe2kz-hashicorp.vercel.app/boundary/docs/install-bou …

docs: Add bsr purpose key examples

---

internal/cmd/commands/ferry/ferry.go
internal/cmd/commands/ferry/sessions.go
internal/cmd/ferry_cmd_darwin.go
internal/cmd/ferry_cmd_windows.go

Printed output example:
```
% boundary ferry sessions
Session information:
Alias:                     www.hashicorp.com
Session authorization:
Session ID:              s_eGJ0j9F3xQ
Created time:            2024-05-14 23:44:18.324437 +0000 UTC
Alias:                     postgres.boundary.dev
Session authorization:
Session ID:              s_OiXOowfLeh
Created time:            2024-05-14 23:40:40.14733 +0000 UTC
Credentials:
Credential Source ID:  credup_gZSyaTrBdv
Credential Store ID:   csst_yf9ynFIEpx
Credential Store Type: static
Credential Type:       username_password
Secret:
password:   password
username:   postgres
```
JSON output:
```
% boundary ferry sessions -format=json | jq
{
"status_code": 200,
"items": [
{
"alias": "postgres.boundary.dev",
"session_authorization": { …
```

internal/cmd/ferry: add sessions command

---

internal/session/repository_session.go
internal/session/repository_session_test.go
internal/session/rewrapping.go

Several session.Repository methods need to encrypt or decrypt fields
when persisting or retrieving a Session. These encrypt/decrypt
operations where being performed while within a database transaction.
The first step in the encrypt/decrypt operation is to retrieve the
kms.Wrapper. While the wrappers get cached in memory, the retrieval
still results in a database query to check that the kms collection
version has not changed. This query happens with a separate db.Reader,
and therefore uses a separate database connection from the transaction
being used by the session.Repository.
If the controllers are configured with a relatively low
`max_open_connections`, and be under sufficient load interactive with
sessions, the controller can consume all of the available database
connections, and get …

fix(session): Move encryption/decryption out of database transactions

---

.github/workflows/test-cli-ui_oss.yml

We observed the bats tests started failing for the following reason
```
Run unzip /tmp/boundary_0.16.0_linux_amd64.zip -d /usr/local/bin
unzip /tmp/boundary_0.16.0_linux_amd64.zip -d /usr/local/bin
rm /tmp/boundary_0.16.0_linux_amd64.zip
shell: /usr/bin/bash -e {0}
replace /usr/local/bin/LICENSE.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
Archive:  /tmp/boundary_0.16.0_linux_amd64.zip
inflating: /usr/local/bin/boundary  
Error: Process completed with exit code 1.
```
Looking at the log, it points to an issue with a competing file in `/usr/local/bin/LICENSE.txt`. Doing a check [here](https://github.com/hashicorp/boundary/actions/runs/9120111874/job/25077032869), it seems to indicate that the `LICENSE.txt` file is coming from a Packer …

chore(bats): Fix unzip error

---

CHANGELOG.md
internal/daemon/controller/interceptor.go
internal/daemon/controller/listeners.go

The cluster listener supports a `max_request_duration` option, and
defaults to 90 seconds. However, this configuration was not being use
when processing grpc requests from the listener. This meant that
requests from worker to controller could hang indefinitely and
contributed to the recently fixed issue with database connections being
stuck in `idle in transaction`.
This commit adds a grpc interceptor that ensures each request has a
deadline set to the max request duration for the listener.
Refs: 29cd7bc9d6128502f918b2469c71eb6bc3751d72

fix(controller): Use max request duration cluster listener

---

.github/configs/milestone-check.json
.github/workflows/actionlint.yml
.github/workflows/build.yml
.github/workflows/enos-run.yml
.github/workflows/jira.yml
.github/workflows/milestone-checker.yml

This PR updates some GitHub Actions to use a Node20 version of the Action in order to avoid deprecation warnings.

chore: Update to use Node20 version of Actions

---

.github/workflows/build.yml

migrates the darwin builder from macos runners to linux due to how much the macos runners cost - https://hashicorp.atlassian.net/browse/ICU-13634
tested by using the built darwin arm64 binary to run `boundary dev` and add a tcp target and connect to it via `boundary connect` and `ssh`
darwin arm64 action: https://github.com/hashicorp/boundary/actions/runs/9083820967/job/24963374657?pr=4798
built binary available here: https://github.com/hashicorp/boundary/actions/runs/9083820967/artifacts/1502180173

remove macos runners for darwin builds in favor of linux

---

internal/cmd/commands/clientagentcmd/clientagentcmd.go

The client agent serves on `localhost:9300` by default. It appears on some systems this resolves to `::1:9300` and on some systems `127.0.0.1:9300`. We should use the same address on the client as the server to avoid any incompatibilities between systems.

clientagentcmd: use "localhost" to call client agent

---

enos/modules/test_e2e/main.tf

This PR modifies the e2e test suite to remove a call to use `tparse`. It's not necessary and adds another dependency when others try to set it up locally.

chore(e2e): Remove call to tparse

---

internal/gen/controller.swagger.json
internal/gen/controller/api/services/session_recording_service.pb.go
internal/proto/controller/api/resources/sessionrecordings/v1/session_recording.proto
internal/proto/controller/api/services/v1/session_recording_service.proto
sdk/pbs/controller/api/resources/session_recordings/session_recording.pb.go

Recreates auto-generated https://github.com/hashicorp/boundary/pull/4826.
Adds observation tags to fields Session Recording Service messages.

[Manual] Backport of Add observation tags for Session Recording Service into release/0.16.x

---

enos/enos-scenario-e2e-aws-base-with-vault.hcl
enos/enos-scenario-e2e-aws-base.hcl
enos/enos-scenario-e2e-aws.hcl
enos/enos-scenario-e2e-database.hcl
enos/enos-scenario-e2e-ui-aws.hcl
enos/enos-variables.hcl
enos/enos.hcl
testing/internal/e2e/boundary/host.go
testing/internal/e2e/tests/aws/dynamichostcatalog_host_set_empty_test.go
testing/internal/e2e/tests/aws/dynamichostcatalog_host_set_test.go
testing/internal/e2e/tests/database/env_test.go
testing/internal/e2e/tests/database/migration_test.go

This PR modifies the e2e test suite to utilize the AWS region specified by the user from their enos variables (as opposed to hard-coding it to `us-east-1`)

chore(e2e): Use AWS region specified in variable

---

enos/enos-scenario-e2e-ui-aws.hcl

This PR adds something that was missing from https://github.com/hashicorp/boundary/pull/4814.
One e2e scenario (the AWS scenario for Admin UI tests) should also use the AWS region specified.

chore(e2e): Add aws region to UI tests

---

testing/internal/e2e/tests/base/search_test.go

This PR is a follow up to https://github.com/hashicorp/boundary/pull/4808
This PR updates an e2e test that uses the `daemon` command in favor of the new name `cache`.

test(e2e): Rename daemon command to cache

---

enos/modules/test_e2e_ui/main.tf

This PR updates the module that runs Admin UI tests to include some parameters for minio information. 
There will be follow-up PRs in `boundary-enterprise` and `boundary-ui` to add an enos scenario `e2e_ui_docker_ent` and a UI test to add a minio storage bucket.

chore(e2e): Add minio variables to UI test module

---

website/content/docs/release-notes/v0_16_0.mdx

This PR updates the 0.16.0 release notes with a known/resolved issue for release 0.16.1. The issue caused controllers to get stuck when they were under sufficient load from worker requests. This issue is fixed in Community and Enterprise in release 0.16.1. HCP Boundary will be fixed in a subsequent release.
https://boundary-i5g1z0nmi-hashicorp.vercel.app/boundary/docs/release-notes/v0_16_0#known-issues-and-breaking-changes

docs: Update release notes for 0.16.1

---

internal/billing/repository_test.go
internal/daemon/controller/handlers/billing/billing_service_test.go
internal/db/sqltest/tests/hcp/billing/monthly_active_users_all_timezone.sql

This PR addresses two failing tests.
`TestRepository_MonthlyActiveUsers` was failing for the following reason
```
=== RUN   TestRepository_MonthlyActiveUsers/valid-with-start-time
repository_test.go:102: 
Error Trace:    /Users/mycow/Developer/boundary/internal/billing/repository_test.go:102
Error:          "[{2024-05-01 00:00:00 +0000 UTC 2024-05-31 14:00:00 +0000 UTC 0} {2024-04-01 00:00:00 +0000 UTC 2024-05-01 00:00:00 +0000 UTC 6} {2024-03-01 00:00:00 +0000 UTC 2024-04-01 00:00:00 +0000 UTC 6}]" should have 4 item(s), but has 3
Test:           TestRepository_MonthlyActiveUsers/valid-with-start-time
=== RUN   TestRepository_MonthlyActiveUsers/valid-with-start-and-end-time
repository_test.go:131: 
Error Trace:    /Users/mycow/Developer/boundary/internal/billing/repository_test.go:131 …
```

test: Fix tests due to time

---

internal/db/sqltest/tests/hcp/billing/monthly_active_users_all_timezone.sql

This PR is a follow-up to https://github.com/hashicorp/boundary/pull/4855
I observed today that the sql tests are failing for the following reason
```
Test Summary Report
-------------------
/test/hcp/billing/monthly_active_users_all_timezone.sql                               (Wstat: 0 Tests: 11 Failed: 0)
Parse errors: Bad plan.  You planned 27 tests but ran 11.
Files=147, Tests=2175, 21 wallclock secs ( 0.38 usr  0.18 sys +  0.41 cusr  0.56 csys =  1.53 CPU)
```
https://github.com/hashicorp/boundary/actions/runs/9349282645/job/25730230873?pr=4858
Looking back at the PR, I think I had an error using the `skip` command and that it should be set to `skip('', 1)`. I think this makes sense -- by setting it to `skip('', 3`) in 8 tests, that would have increased the number by 16 (i.e. 8 * 2), …

test(db): Fix skip command

---

website/content/docs/concepts/domain-model/targets.mdx

This PR attempts to clarify some confusion about the credentials required to connect to SSH targets. We should note that while injected credentials are required to establish an SSH connection, SSH targets do support brokered credentials for other purposes.
From a Slack conversation:
https://hashicorp.slack.com/archives/CP48EV08Z/p1717371877997419
https://boundary-r6prcoxo9-hashicorp.vercel.app/boundary/docs/concepts/domain-model/targets

docs: Clarify credentials and SSH targets

---

website/content/docs/concepts/domain-model/targets.mdx

Revise wording of recent SSH target update to focus on what is required, rather than what is forbidden. I received some feedback after I merged #4863 that we could be more clear, and I agree. This version is more direct and should be easier for users to understand.
https://boundary-fxbp7ekgg-hashicorp.vercel.app/boundary/docs/concepts/domain-model/targets#ssh-target-attributes

docs: Revise requirements for SSH targets

---

enos/scripts/test_e2e_env.sh

Added a `select(.value != "")` entry to the jq statement to avoid it printing null values. This is to make life easier when copy/pasting the output from the script.
This solves the problem of people overwriting existing values they already may have set and do not want overwritten, namely `VAULT_ADDR` and `VAULT_TOKEN`.
before:
```
➜  enos git:(main) ✗ bash scripts/test_e2e_env.sh               
export BOUNDARY_ADDR='http://some-address:9200'
export BOUNDARY_LICENSE=''
export E2E_AWS_ACCESS_KEY_ID=''
export E2E_AWS_BUCKET_NAME=''
export E2E_AWS_HOST_SET_FILTER=''
export E2E_AWS_HOST_SET_FILTER2=''
export E2E_AWS_HOST_SET_IPS='[""]'
export E2E_AWS_HOST_SET_IPS2='[""]'
export E2E_AWS_REGION=''
export E2E_AWS_SECRET_ACCESS_KEY=''
export E2E_MAX_PAGE_SIZE='10'
export …
```

update script to not print null values

---

enos/modules/docker_ldap/entries/user.ldif
testing/internal/e2e/tests/base_plus/ldap_test.go

This PR adds a check to an e2e test for LDAP account attribute mapping implemented here: https://github.com/hashicorp/boundary/pull/4788.
https://hashicorp.atlassian.net/browse/ICU-13979

test(e2e): Add check for ldap account attribute mapping

---

website/content/docs/troubleshoot/common-errors.mdx

If you launch multiple controller instances, with the same name and then attempt to establish a multi-hop connection to a target, the Boundary controller will return an error message saying `No ingress workers with valid next-hop paths could be found for this multi-hop session.`.
This entry would have saved me a bit of time and I'm hoping to help catch common errors in future enterprise deployments.

docs: multi-hop error message linked to duplicate controller names

---

website/content/docs/concepts/domain-model/host-sets.mdx

This PR updates the host-set domain model docs `sync_interval_seconds` attribute default to 600 seconds.

changes sync_interval_seconds default to 600

---

internal/daemon/controller/handlers/authmethods/authmethod_service.go
internal/daemon/controller/handlers/authmethods/oidc.go
internal/daemon/controller/handlers/authmethods/oidc_test.go

This commit makes modifications to the OIDC request handlers to return appropriate gRPC status codes on errors. Before this change, boundary presents the internal error codes to clients. This causes problems for reverse proxies, as these status codes are mapped to non-standard HTTP response codes which are ultimately all turned into 500 responses when 4xx status codes are more appropriate and descriptive of the error returned.
Some modifications in this commit include calls to `event.WriteError` so that the internal error is written to the controller log for visibility. Comments about potential duplicate logs are now removed as `event.WriteError` is not called when using functions from the `handlers` package.

Use appropriate gRPC error codes for OIDC

---

plugins/boundary/mains/minio/go.mod
plugins/boundary/mains/minio/go.sum

This is a backport of a commit in main that bumps the MinIO plugin to v0.1.2

Bump MinIO Plugin to v0.1.2 (0.16.x Backport)

---

enos/enos-scenario-e2e-aws.hcl
enos/modules/aws_bucket/main.tf
enos/modules/aws_bucket/outputs.tf
enos/modules/aws_bucket/variables.tf
enos/modules/aws_worker/iam.tf
enos/modules/aws_worker/main.tf
enos/modules/aws_worker/outputs.tf
enos/modules/aws_worker/variables.tf
enos/modules/test_e2e/main.tf

This PR adds support for testing dynamic credentials when creating storage buckets.
Summary of changes
- The bucket module now takes a username as an optional argument. If a user is provided, it will set up the user policy to have access to the bucket. This is needed when testing static credentials
- The worker module now takes a bucket arn as an optional argument. If a bucket arn is provided, it will set up a role to gain access to that bucket, create an instance profile for that role, and attach it to the worker. This is needed when testing dynamic credentials]
There will be a follow-up PR to add a test in `boundary-enterprise`
https://hashicorp.atlassian.net/browse/ICU-13420

test(e2e): Add support for dynamic credentials

---

website/content/docs/release-notes/v0_16_0.mdx

This PR updates the 0.16.0 release notes with 3 known/fixed issues for release 0.16.2:
- The controller deadlock issue was updated to reflect the fix going into HCP Boundary.
- The fix for the TLS handshake issue was added.
- The update to OIDC status codes was added.
[View the known/fixed issues in the preview deployment](https://boundary-87r6zryge-hashicorp.vercel.app/boundary/docs/release-notes/v0_16_0#known-issues-and-breaking-changes).

docs: Release notes for 0.16.2

---

enos/modules/aws_boundary/boundary-instances.tf
enos/modules/aws_boundary/scripts/set-up-login-shell-profile.sh
enos/modules/aws_worker/main.tf
enos/modules/aws_worker/scripts/set-up-login-shell-profile.sh

One request from the Support team was to add `boundary` to the PATH on ec2 instances created by enos. This PR borrows the implementation from [vault](https://github.com/hashicorp/vault/blob/main/enos/modules/vault_cluster/main.tf#L268-L321). 
```
> enos scenario launch e2e_aws builder:local
> ssh -i <key> ubuntu@<ec2 instance ip>
> which boundary
/opt/boundary/bin/boundary
```
I checked against the controller/worker created by `aws_boundary` and the "isolated" worker created by `aws_worker`.
https://hashicorp.atlassian.net/browse/ICU-14020

chore(e2e): Add boundary to path

---

website/content/docs/configuration/session-recording/configure-storage-policy.mdx
website/content/docs/configuration/session-recording/create-storage-bucket.mdx
website/content/docs/configuration/session-recording/enable-session-recording.mdx
website/content/docs/configuration/session-recording/index.mdx
website/content/docs/configuration/session-recording/update-storage-policy.mdx

The backports failed on #4556 . This PR backports those changes to the `stable-website` branch.
* added sample terraform code to create storage bucket configuration
* added terraform sample code for target configuration
* Added HCP Boundary Plus as requirement in the note
* added sample TF code to configure a storage policy
* added group attributes to tabs
* added terraform tab for updating a storage policy
* formatting and style guide changes
* docs: Lowercase credential types
* docs: Apply active voice
* docs: Close prefix
---------

docs: Backport #4556 to stable-website

---

website/content/docs/configuration/session-recording/configure-storage-policy.mdx
website/content/docs/configuration/session-recording/create-storage-bucket.mdx
website/content/docs/configuration/session-recording/enable-session-recording.mdx
website/content/docs/configuration/session-recording/index.mdx
website/content/docs/configuration/session-recording/update-storage-policy.mdx

The backports failed on #4556. This PR backports those changes to the `release/0.16.x` branch.
* added sample terraform code to create storage bucket configuration
* added terraform sample code for target configuration
* Added HCP Boundary Plus as requirement in the note
* added sample TF code to configure a storage policy
* added group attributes to tabs
* added terraform tab for updating a storage policy
* formatting and style guide changes
* docs: Lowercase credential types
* docs: Apply active voice
* docs: Close prefix
---------

docs: Backport #4556 to release 0.16.x

---

website/content/docs/commands/billing/index.mdx
website/content/docs/commands/billing/monthly-active-users.mdx
website/data/docs-nav-data.json

A new command was added when we released user-based pricing. The command lets users query the system to find out the number of active users in a given time period (by month) to help predict pricing impacts. This PR adds the `billing` command and the `monthly-active-users` subcommand to the CLI docs.
- [billing](https://boundary-iruh6clzw-hashicorp.vercel.app/boundary/docs/commands/billing)
- [billing monthly-active-users](https://boundary-iruh6clzw-hashicorp.vercel.app/boundary/docs/commands/billing/monthly-active-users)

docs: Document billing command

---

enos/modules/docker_boundary/main.tf
enos/modules/docker_ldap/main.tf
enos/modules/docker_minio/main.tf
enos/modules/docker_openssh_server/main.tf
enos/modules/docker_openssh_server_ca_key/main.tf
enos/modules/docker_postgres/main.tf
enos/modules/docker_vault/main.tf
enos/modules/docker_worker/main.tf

This PR modifies some enos modules to define some docker container attributes to prevent the containers from being regenerated on a second `launch`/`terraform apply`. 
Currently, after launching a docker-based scenario, a subsequent launch would result all of the docker containers in being regenerated, which is not expected if they were generated successfully the first time around. This is caused because of...
```
❯ enos scenario exec --cmd plan e2e_ui_docker builder:local
-/+ resource "docker_container" "boundary" {
+ bridge                                      = (known after apply)
+ container_logs                              = (known after apply)
- cpu_shares                                  = 0 -> null
- dns                                         = [] -> null
- dns_opts …
```

chore(e2e): Define docker attributes to prevent forced replacement on second launch

---

.gitignore
enos/enos-scenario-e2e-aws-base-with-vault.hcl
enos/enos-scenario-e2e-aws-base.hcl
enos/enos-scenario-e2e-aws.hcl
enos/enos-scenario-e2e-database.hcl
enos/enos-scenario-e2e-docker-base-plus.hcl
enos/enos-scenario-e2e-docker-base-with-vault.hcl
enos/enos-scenario-e2e-docker-base-with-worker.hcl
enos/enos-scenario-e2e-docker-base.hcl
enos/enos-scenario-e2e-docker-worker-registration-controller-led.hcl
enos/enos-scenario-e2e-docker-worker-registration-worker-led.hcl
enos/enos-scenario-e2e-ui-aws.hcl
enos/enos-scenario-e2e-ui-docker.hcl
enos/enos-variables.hcl
enos/enos.vars.hcl

This PR makes some updates to `enos.vars.hcl` to clarify comments and make it easier to onboard.
Some additional changes were included to accommodate these changes
- `enos-local.vars.hcl` was added to `.gitignore` to allow a local copy of variables without potentially committing them
- Some variables were made optional so that users who don't need to run e2e tests can ignore them.
https://hashicorp.atlassian.net/browse/ICU-14090

chore(e2e): Clean up comments in enos.vars

---

enos/enos-scenario-e2e-aws-base-with-vault.hcl
enos/enos-scenario-e2e-aws-base.hcl
enos/enos-scenario-e2e-aws.hcl
enos/enos-scenario-e2e-ui-aws.hcl
enos/modules/aws_boundary/boundary-instances.tf
enos/modules/aws_target/main.tf

This PR updates enos scenarios to output IP addresses for the resources it creates. This only applies to AWS-based scenarios.
This PR also addresses a few issues related to multi-worker and multi-target configurations
- Addresses an issue with multi-worker registration. Took a fix from here: https://github.com/hashicorp/terraform-enos-aws-boundary/pull/42
- Modifies some scenarios to respect the `target_count` variable
Example:
```
❯ enos scenario output e2e_aws builder:local
Scenario: e2e_aws [builder:local] ✅
target_ips = [
"3.238.63.109",
"3.80.33.188",
]
test_results = ""
worker_ips = [
"3.231.55.31",
"54.90.134.206",
]
controller_ips = [
"34.201.25.85",
"3.88.140.74",
]
❯ ssh -i <key> ubuntu@34.201.25.85
```
https://hashicorp.atlassian.net/browse/ICU-14021 …

test(e2e): Add resource IPs to output

---

enos/modules/aws_boundary/boundary-instances.tf
enos/modules/aws_boundary/scripts/create-audit-log-dir.sh
enos/modules/aws_boundary/templates/controller.hcl
enos/modules/aws_boundary/templates/controller_bsr.hcl
enos/modules/aws_boundary/templates/worker.hcl
enos/modules/aws_boundary/templates/worker_bsr.hcl
enos/modules/aws_worker/main.tf
enos/modules/aws_worker/scripts/create-audit-log-dir.sh
enos/modules/aws_worker/templates/worker.hcl
enos/modules/aws_worker/templates/worker_bsr.hcl

This PR updates the e2e test suite to enable audit logs on AWS-based boundary instances. Audit logs will be sent to both
- stderr
- /var/log/boundary/audit.log
The bash script was borrowed from vault's implementation: https://github.com/hashicorp/vault/blob/main/enos/modules/vault_cluster/scripts/create-audit-log-dir.sh
https://hashicorp.atlassian.net/browse/ICU-14089

chore(e2e): Add audit logs to aws boundary instances

---

scripts/trigger-merge-to-downstream-gha

The `trigger-merge-to-downstream` workflow had been failing for quite some time, but the workflow was still returning success. As a result, automatic merges from `boundary` to `boundary-enterprise` were not happening and there was no notification of a problem. Example: https://github.com/hashicorp/boundary/actions/runs/9843985789/job/27176402958
This PR makes an adjustment to the script to return a non-zero exit code if the curl request to the downstream repo returns a non 2xx exit code.
Testing locally
```
❯ bash trigger-merge-to-downstream-gha main
{ "message": "Resource not accessible by personal access token", "documentation_url": "https://docs.github.com/rest/actions/workflows#create-a-workflow-dispatch-event", "status": "403" } 403
ERROR: failed to trigger downstream workflow
``` …

chore: Fail workflow if request does not succeed

---

website/content/docs/concepts/domain-model/auth-methods.mdx
website/content/docs/concepts/iam.mdx
website/content/docs/configuration/controller.mdx

We currently do not document the impact the auth token's time-to-live, as set on the controller, has on authentication using an OIDC provider. This recently led to confusion for a customer. This PR attempts to clarify the relationship between the auth token's time-to-live and the OIDC `max_age` attribute.
I added additional text to the domain model topic for auth methods to clarify the `max_age` attribute:
https://boundary-qwmqisfb9-hashicorp.vercel.app/boundary/docs/concepts/domain-model/auth-methods#max_age
I also updated the controller configuration topic to clarify the time-to-live setting:
https://boundary-qwmqisfb9-hashicorp.vercel.app/boundary/docs/configuration/controller#auth_token_time_to_live
Finally, I added a note to the conceptual IAM topic (I am not sure if this is the best …

docs: Explain auth token TTL's impact on OIDC

---

website/content/docs/commands/roles/set-grant-scopes.mdx

There is an error in the documentation where incorrect commands are listed under set-grant-scopes. The correct commands need to be updated.
For reference, please see: https://developer.hashicorp.com/boundary/docs/commands/roles/set-grant-scopes

Update Mistake in set-grant-scopes.mdx

---

enos/enos-variables.hcl
enos/modules/aws_boundary/boundary-instances.tf
enos/modules/aws_boundary/outputs.tf
enos/modules/aws_boundary/security-groups.tf
enos/modules/aws_boundary/templates/worker_hcp_bsr.hcl
enos/modules/aws_boundary/variables.tf
enos/modules/aws_iam_setup/main.tf

This PR updates the e2e test suite to add support for an hcp worker. 
- Update `aws_boundary` module to support having a `controller_count` of 0 (we're using a HCP controller)
- Add variable to pass in a HCP cluster id
- Extract worker tokens from workers
There will be a follow-up PR in `boundary-enterprise` to add a scenario for setting up HCP Session Recording resources.
https://hashicorp.atlassian.net/browse/ICU-14433

test(e2e): Add support for an hcp worker

---

website/content/docs/concepts/security/permissions/index.mdx

Updates the description of roles to reflect multi-scope capabilities.
[View the page in the preview deployment](https://boundary-a30xemddz-hashicorp.vercel.app/boundary/docs/concepts/security/permissions#roles)

docs: Update roles in permissions concept

---

website/content/docs/configuration/identity-access-management/assignable-permissions.mdx
website/content/docs/configuration/identity-access-management/index.mdx
website/content/docs/configuration/identity-access-management/permission-grant-formats.mdx
website/content/docs/configuration/identity-access-management/resource-table.mdx
website/content/docs/configuration/permissions/assignable-permissions.mdx
website/content/docs/configuration/permissions/index.mdx
website/content/docs/configuration/permissions/permission-grant-formats.mdx
website/data/docs-nav-data.json
website/redirects.js

Updates to the following concept topics for clarity/conciseness and to streamline workflow to the updated manage roles usage docs:
- [Permissions in Boundary](https://boundary-aw4ad8712-hashicorp.vercel.app/boundary/docs/configuration/identity-access-management)
- [Assignable permissions](https://boundary-aw4ad8712-hashicorp.vercel.app/boundary/docs/configuration/identity-access-management/assignable-permissions)
- [Permission grant formats](https://boundary-aw4ad8712-hashicorp.vercel.app/boundary/docs/configuration/identity-access-management/permission-grant-formats)
- [Resource table](https://boundary-aw4ad8712-hashicorp.vercel.app/boundary/docs/configuration/identity-access-management/resource-table)

docs: Update permissions concepts

---

internal/bsr/convert/internal/asciicast/asciicast_test.go

This fixes the following test error
```
--- FAIL: TestEventMarshal (0.00s)
--- FAIL: TestEventMarshal/backspace (0.00s)
asciicast_test.go:166: 
Error Trace:	/home/runner/actions-runner/_work/boundary-enterprise/boundary-enterprise/internal/bsr/convert/internal/asciicast/asciicast_test.go:166
Error:      	Not equal: 
expected: []byte{0x5b, 0x30, 0x2e, 0x31, 0x2c, 0x22, 0x6f, 0x22, 0x2c, 0x22, 0x5c, 0x75, 0x30, 0x30, 0x30, 0x38, 0x5c, 0x75, 0x30, 0x30, 0x31, 0x62, 0x5b, 0x4b, 0x22, 0x5d}
actual  : []byte{0x5b, 0x30, 0x2e, 0x31, 0x2c, 0x22, 0x6f, 0x22, 0x2c, 0x22, 0x5c, 0x62, 0x5c, 0x75, 0x30, 0x30, 0x31, 0x62, 0x5b, 0x4b, 0x22, 0x5d}
Diff:
--- Expected
+++ Actual
@@ -1,4 +1,4 @@
-([]uint8) (len=26) {
- 00000000  5b 30 2e 31 2c 22 6f 22  2c 22 5c 75 30 30 30 38  |[0.1,"o","\u0008|
- 00000010 …
```

test(asciicast): Update expected value due to encoding change

---

internal/plugin/loopback/const.go
internal/plugin/loopback/storage.go
internal/plugin/loopback/storage_test.go

Currently, the AWS plugin for storage supports using both static(IAM User) and dynamic(Instance Profile) credentials. This PR is updating the loopback plugin mimic dynamic credentials, allowing us to add more unit tests for storage.

feat(loopback): support dynamic credentials

---

website/content/docs/release-notes/v0_15_0.mdx
website/content/docs/release-notes/v0_16_0.mdx

This pull request adds info about a Desktop bug that is being fixed for the July 31 release. The fix is being back ported to the 0.15.5 release. It was already back ported to the 0.16.0 release. This pull request adds the issue to the release note's Known issues section for both versions.
- [0.15.x known issues](https://boundary-2h5otc59i-hashicorp.vercel.app/boundary/docs/release-notes/v0_15_0#known-issues-and-breaking-changes)
- [0.16.x known issues](https://boundary-2h5otc59i-hashicorp.vercel.app/boundary/docs/release-notes/v0_16_0#known-issues-and-breaking-changes)

docs: Add Desktop fix to known issues 0.15.x and 0.16.x

---

website/content/docs/commands/sessions/list.mdx
website/content/docs/release-notes/v0_16_0.mdx
website/content/docs/release-notes/v0_17_0.mdx
website/data/docs-nav-data.json

Updates the release notes for the 07/31 release. View the updates in the preview deployment:
- [Release 0.16.x feature deprecations and EOL](https://boundary-mni4dnlwa-hashicorp.vercel.app/boundary/docs/release-notes/v0_16_0#feature-deprecations-and-eol) (Per the changelog, these deprecations were made during point releases, but we did not add them to the release notes.)
- Updated [`sessions list` command options](https://boundary-mni4dnlwa-hashicorp.vercel.app/boundary/docs/commands/sessions/list#command-options) to indicate that `include-terminated` is deprecated
- New page [Release 0.17.0](https://boundary-mni4dnlwa-hashicorp.vercel.app/boundary/docs/release-notes/v0_17_0)

docs: Release notes 07-31

---

website/content/docs/release-notes/v0_17_0.mdx
website/redirects.js

Fixes the link to the Permissions in Boundary topic from the 0.17.0 release notes:
https://boundary-dacg2gu3q-hashicorp.vercel.app/boundary/docs/release-notes/v0_17_0

docs: Update link in 0.17.0 release notes

---

internal/db/schema/migrations/oss/postgres/90/01_drop_kms_rewrapping_table.up.sql

The `storage_plugin_storage_bucket_secret-rewrapping-job` table needs to be dropped because the `storage_plugin_storage_bucket_secret` table no longer exists and was replaced by the `storage_bucket_credential_managed_secret` table.

fix(db): remove old rewrapping-job table

---

website/content/docs/concepts/credential-management.mdx

Fixes an old broken anchor link. This is from when titles used to include "HCP only" instead of using the banner.
[Test the update in the preview deployment](https://boundary-r0oo7hcy2-hashicorp.vercel.app/boundary/docs/concepts/credential-management)

docs: Fix broken anchor link in Credential management

---

.github/workflows/backport.yml

I was able to test this successfully here: https://github.com/hashicorp/boundary/actions/runs/10498363248/job/29083143612?pr=5035

ci: refuse to backport if migrations changed

---

internal/daemon/controller/handlers/authmethods/ldap.go
internal/daemon/controller/handlers/authmethods/ldap_test.go

Add validation for the port number in LDAP URLs. If a port number is provided, it is checked to ensure it is a valid integer and within the valid range. This validation helps prevent errors when configuring LDAP authentication.

feat: Validate LDAP URL port number

---

internal/daemon/controller/testing.go
internal/daemon/worker/status.go
internal/daemon/worker/worker.go

Using time.After makes the intent clearer

internal/daemon: simplify time update tests

---

internal/daemon/controller/gateway.go
internal/daemon/controller/gateway_test.go

Add `WithDisablePathLengthFallback()` runtime option to the grpc-gateway mux HTTP server. This prevents the issue where the request method can be overridden with a `X-HTTP-Method-Override` header.

feat: Disable path length fallback

---

internal/clientcache/cmd/search/search.go
internal/clientcache/internal/cache/consts.go
internal/clientcache/internal/cache/options.go
internal/clientcache/internal/cache/options_test.go
internal/clientcache/internal/cache/refresh_test.go
internal/clientcache/internal/cache/repository_resolvable_aliases.go
internal/clientcache/internal/cache/repository_resolvable_aliases_test.go
internal/clientcache/internal/cache/repository_sessions.go
internal/clientcache/internal/cache/repository_sessions_test.go
internal/clientcache/internal/cache/repository_targets.go
internal/clientcache/internal/cache/repository_targets_test.go
internal/clientcache/internal/cache/search.go
internal/clientcache/internal/daemon/404_handler.go
internal/clientcache/internal/daemon/search_handler.go

A query parameter `max_result_set_size` can be specified to set a per-request limit, with `-1` meaning all values. If there were more entries than the max size used for the request, an `incomplete` boolean is set in the response.

Restrict cache results to 250 entries by default

---

go.mod
internal/clientcache/cmd/cache/start.go
internal/clientcache/internal/daemon/options.go
internal/clientcache/internal/daemon/options_test.go
internal/clientcache/internal/daemon/server.go
internal/clientcache/internal/daemon/server_test.go
internal/clientcache/internal/db/db.go
internal/clientcache/internal/db/db_test.go
internal/clientcache/internal/db/options.go
internal/clientcache/internal/db/options_test.go
internal/clientcache/internal/db/schema.sql
internal/clientcache/internal/db/schema_reset.sql

By default, we will use a persistent cache for the client cache. This will allow us to keep the cache across restarts of the server and it will also reduce the amount of time it takes to start the server while reducing the amount of memory used.
This change also includes a validation of the cache schema version. If the schema version is different from the one expected, the cache will be reset/recreated.

feat (clientcache): use a persistent cache

---

internal/clientcache/cmd/search/search.go
internal/clientcache/internal/cache/repository_implicit_scopes.go
internal/clientcache/internal/cache/repository_implicit_scopes_test.go
internal/clientcache/internal/cache/search.go
internal/clientcache/internal/daemon/search_handler.go

This allows getting a list of scope IDs known by the cache via cached targets and sessions. It is not refreshed from the controller. The name contains `implicit` in case we ever want e.g. `scopes`.

Add `implicit-scopes` resource type to cache

---

api/accounts/account.gen.go
api/aliases/alias.gen.go
api/authmethods/authmethods.gen.go
api/authtokens/authtokens.gen.go
api/credentiallibraries/credential_library.gen.go
api/credentials/credential.gen.go
api/credentialstores/credential_store.gen.go
api/groups/group.gen.go
api/hostcatalogs/host_catalog.gen.go
api/hosts/host.gen.go
api/hostsets/host_set.gen.go
api/managedgroups/managedgroups.gen.go
api/policies/policy.gen.go
api/roles/role.gen.go
api/scopes/scope.gen.go
api/sessionrecordings/session_recording.gen.go
api/sessions/session.gen.go
api/storagebuckets/storage_bucket.gen.go
api/targets/target.gen.go
api/users/custom.go
api/users/user.gen.go
api/workers/worker.gen.go
internal/api/genapi/templates.go

The API automatically paginates to the end of a pagination, and would take into account any items updated and subsequently removed since the last pagination. It now also removes any items removed during the current pagination.
This also clarifies the behavior of `removed_ids` during initial pagination (the only pagination supported by the CLI).

api: remove items deleted during refresh pagination

---

internal/clientcache/cmd/search/search_test.go
internal/clientcache/internal/cache/options.go
internal/clientcache/internal/cache/options_test.go
internal/clientcache/internal/cache/refresh.go
internal/clientcache/internal/cache/refresh_test.go
internal/clientcache/internal/daemon/search_handler.go

This ensures we don't have competing update processes running. When doing the inline RefreshForSearch, a specific error will be returned so we can hint in the API that we're in the middle of a refresh.

Ensure only one refresh is running for a user/resource at a time

---

testing/internal/e2e/helpers.go
testing/internal/e2e/tests/base/auth_token_delete_test.go
testing/internal/e2e/tests/base/credential_store_test.go

%q handles quotes inside the quoted strings better.

e2e: replace '%s' with %q

---

internal/daemon/controller/handlers/authmethods/oidc.go
internal/daemon/controller/handlers/authmethods/oidc_test.go

This commit modifies the OIDC authentication start method to return a 400 (Bad Request) error if a client attempts to start the authentication flow against an OIDC auth method that is set to inactive. This is something we noticed in our error logs in HCP Boundary that is impacting our SLOs.
Previously this returned its own error code which is mapped to a 500 response. Tests have been updated to catch this new scenario.

Return HTTP 400 status for inactive OIDC auth methods

---

internal/cmd/commands/server/server.go
internal/daemon/controller/controller.go
internal/daemon/worker/worker.go
internal/session/job_session_cleanup.go
internal/session/jobs.go

Allows changing grace period and a few other things timing-related via HUP instead of just a restart.
Tested manually via config changes and HUP.

Allow reloading some server timings

---

website/content/docs/operations/session-recordings/index.mdx
website/content/docs/operations/session-recordings/manage-recorded-sessions.mdx

[ICU-15008](https://hashicorp.atlassian.net/browse/ICU-15008) document ToB findings regarding using asciicast for session recording. View the following updates in the preview deployment:
- Added a new section **asciicast** to the [Recorded sessions operations](https://boundary-4o7k6eaa6-hashicorp.vercel.app/boundary/docs/operations/session-recordings) topic and merged in some existing asciicast info.
- Deleted the note regarding asciicast format limitations and instead included a link back to the new section in the [Find and view recorded sessions](https://boundary-4o7k6eaa6-hashicorp.vercel.app/boundary/docs/operations/session-recordings/manage-recorded-sessions) topic.
[ICU-15008]: https://hashicorp.atlassian.net/browse/ICU-15008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …

docs: Update session recording docs with asciicast info

---

internal/target/tcp/repository_tcp_target_test.go

A new set of tests were added to the create/update repository methods of the tcp target resources. These tests were added to validate that an IPv6 address can be associated directly to the tcp target.

test(target): validate ipv6 address for tcp targets

---

internal/host/plugin/job_set_sync_test.go
internal/host/plugin/repository_host_test.go
internal/host/plugin/testing.go
internal/host/static/repository_host_test.go

A new set of tests were added to the create/update repository methods of the static host resource. These tests were added to validate that an IPv6 address can be used by a host. The existing UpsertHost test for the dynamic host resource was updated to validate ensure an IPv6 address can be used by a host.

test(host): validate ipv6 address for hosts

---

internal/clientcache/cmd/search/search_test.go
internal/clientcache/internal/daemon/testing.go

Fix ensures that the TestServer returned uses the
correct directory for writing its sqlite files,
which was created via t.TempDir()

test (cache/search): fix NewTestServer(...) storage

---

Makefile
internal/host/plugin/repository_host_test.go
internal/session/job_session_cleanup_test.go
internal/tests/cluster/x509_verification_test.go

This was missed in https://github.com/hashicorp/boundary/pull/5071
These tests will need to be fixed or removed. It is not
clear why they are failing, but they are always failing.
Hosts contain IP addresses in string form, whose
order is not defined.

Some test fixes

---

.github/workflows/security-scan.yml

Fix the workflow conditional for when to run the security scanner workflow:
- `! github.event.pull_request.head.repo.fork` don't run on community pr forks
- `github.actor != 'dependabot[bot]'` don't run for dependabot
- `github.actor != 'hc-github-team-secure-boundary'` don't run for boundary bot

PSA-1311 - update scan workflow conditions

---

website/content/docs/install-boundary/architecture/high-availability.mdx
website/content/docs/install-boundary/architecture/system-requirements.mdx

Some customers have had questions about best practices for configuring the Postgres database for high availability. We do not have any such recommendations internally, but the Postgres documentation on this subject is helpful. 
This PR adds a link to the Postgres documentation to the existing **Database network requirements** section in the topic **System requirements**, and adds a new **Database** section to the **High availability** topic.
- System requirements > [Database network requirements](https://boundary-ox8zkpart-hashicorp.vercel.app/boundary/docs/install-boundary/architecture/system-requirements#database-network-requirements)
- High availability > [Database](https://boundary-ox8zkpart-hashicorp.vercel.app/boundary/docs/install-boundary …

docs: Add link to Postgres HA

---

website/content/docs/concepts/credential-management.mdx
website/content/docs/configuration/credential-management/configure-credential-brokering.mdx
website/content/docs/configuration/credential-management/configure-credential-injection.mdx
website/content/docs/configuration/credential-management/index.mdx

The documentation is not clear about the requirement to use injected credentials for SSH target types. This has led to some confusion internally. This PR attempts to connect some dots between target type requirements and the credential brokering/injection workflows.
It contains the following updates:
- In the [Credential injection](https://boundary-khhhe3zpd-hashicorp.vercel.app/boundary/docs/concepts/credential-management#credential-injection) section of the **Credential management** concepts page, I changed "Credential injection is _available_..." to "Credential injection is _required_..."
- In the [End user workflows](https://boundary-khhhe3zpd-hashicorp.vercel.app/boundary/docs/configuration/credential-management#end-user-workflows) section of the credential management **Overview** …

docs: Clarify credential workflow for SSH target types

---

internal/daemon/controller/controller.go
internal/daemon/worker/status_test.go
internal/daemon/worker/worker.go
internal/daemon/worker/worker_test.go

Propagate the downstream worker timeout into the downstream receiver and downstream ticker so we have a configurable consistent timeout value to use for worker to worker interactions.
Also change the atomic.Pointer to an atomic.Int64 for consistency with other values.

internal/daemon/controller+worker: propagate downstream timeout

---

internal/server/repository_worker_test.go

This PR adds test to validate that an ipv4, ipv6, and an abbreviated ipv6 can be use to update the address field of a worker.

test(server): validate ipv6 address for upsert worker status

---

internal/cmd/commands/targetscmd/funcs.go

Resolve issue facing `boundary targtes authorize-session` where the flag for `-scope-name` was never being set and thus always threw exception `{“error”:“Error trying to authorize-session a session against target: empty targetId value and no combination of target name and scope ID/name passed into AuthorizeSession request”}`

Resolve Scope Name For Target Authorize Session

---

internal/db/schema/migrations/oss/postgres/81/01_deleted_tables_and_triggers.up.sql
internal/db/schema/migrations/oss/postgres/91/02_indexes_fk_delete.up.sql
internal/db/schema/migrations/oss/postgres/91/03_indexes_grants_query.up.sql
internal/db/schema/migrations/oss/postgres/91/04_insert_session_delete_on_statement.up.sql
internal/db/schema/migrations/oss/postgres/91/05_deletion_tables_view.up.sql
internal/db/sqltest/tests/purge/deleted_table_tests.sql
internal/pagination/purge/purge_test.go
internal/pagination/purge/query.go

This PR adds several performance related changes in the form of indexes,
and changes to a delete trigger to run more efficiently. These
improvements should help with several operations, notably:
- The grants query used to fetch grants for a user for controller API
requests.
- Deletion of targets, auth tokens, and sessions.
See the individual commits for additional details.

Indexes and trigger changes to improve performance

---

internal/credential/vault/jobs.go

This commit modifies the credential renewal job to handle a case where the `renewLease` method can return `nil, nil`. Currently, a panic is caused by usage of the `renewedCred` variable in this scenario.
This commit adds a nil check and returns an error if the `renewedCred` variable is returned as `nil`.

Fix panic in credential renewal job

---

internal/daemon/controller/internal/metric/api.go
internal/daemon/controller/internal/metric/api_test.go

The target authorize session endpoint allows for alternative target
identifiers besides the public id. For this to function correctly, the
grpc gateway path definition for the endpoint deviates from the common
pattern used for other endpoints that include ids. When this change was
done, it was not accounted for in the logic used to capture the
prometheus metrics for api requests to this particular endpoint,
resulting in the metrics never incrementing for the authorize session
endpoint.
This fix updates the matching logic used for the metrics to ensure that
the metrics are incremented for this endpoint.
See: c149bc4a7998809e675d0ab6e30d03ef1d53bd0c

fix(metrics): Fix matching logic for authorize session endpoint

---

internal/cmd/base/server_test.go
internal/cmd/base/servers.go
internal/cmd/config/config.go
internal/cmd/config/config_test.go
internal/cmd/ops/server_test.go

This PR ensures that the CLI commands inputed by the user can include field values that contain IPv6 addresses. This PR also ensures that the config file may contain field values that have IPv6 addresses.

test: ensure ipv6 compatibility for cli and config

---

testing/internal/e2e/tests/base/target_tcp_connect_authz_token_test.go

Follow-up to this PR: https://github.com/hashicorp/boundary/pull/5108
This PR updates an e2e test to validate the usage of the following commands
```
boundary targets authorize-session -name ... -scope-id ...
boundary targets authorize-session -name ... -scope-name ...
```
https://hashicorp.atlassian.net/browse/ICU-11482

test(e2e): Add check for target authorize-session using scope name and target name

---

.semgrep/event-with-info-msg.yaml
scan.hcl

Instrument our security scanner with the ability to use custom semgrep
rules. This is inspired by the HVS teams use of semgrep.
The event.WithInfoMsg function expects a set of key value tuples,
but it can easily be misunderstood to accept string interpolation
arguments. This check will error if any string interpolation verbs are
used in calls to event.WithInfoMsg
View this rule in the playground here: https://semgrep.dev/playground/r/YGUpBXB/johan_brandhorst_personal_org.with-info-msg-string-interpolation

Add semgrep rules

---

.github/workflows/jira.yml

This PR updates the use of `hub` in the `jira.yml` workflow. The command is no longer available by default, and the suggestion is to update to use the `gh` command. It would cause this step of the workflow to constantly fail, which would create a JIRA ticket for every PR opened, even if the user was internal.
Example:
```
/home/runner/work/_temp/7e8d2cb7-1460-4712-ae87-25df58ee7218.sh: line 2: hub: command not found
Actor moduli is not a boundary team member
```
I also needed to update the `JIRA_SYNC_GITHUB_TOKEN` secret with a new token (borrowing the same one used in `boundary-ui`)
A similar change was applied in the boundary-ui repo in this PR: https://github.com/hashicorp/boundary-ui/pull/1729/files
https://hashicorp.atlassian.net/browse/ICU-15163

chore: Update use of deprecated `hub` command

---

CHANGELOG.md

Refs: f431d1e22309609baf37333b89d7b341141757a3
Refs: d5817f0adab7f5c1f045fa4a5c15a6dc553b022c

changelog: Add details for cache speedup and performance improvements

---

internal/daemon/worker/status.go

In the event that a worker fails to connect to a controller, update in the worker logs to provide the controllers target that the worker attempted to initialize connection to.

Worker Connection Failure Add Controller Target

---

internal/event/eventer.go

This issue was surfaced through other changes (PR 5137).
Given that the eventer works in a singleton pattern (see sysEventer global variable), performing this shallow object copy can cause a data race because the copy operation reads the underlying eventer data structures. At the same time, given the global nature of this eventer, other goroutines can be writing to those same data structures.
Since we're already using a singleton pattern in this package, and given that the current copy operation is shallow, copying the object doesn't seem necessary, so this commit changes `StandardWriter` to build the `logAdapter` with the `e` eventer directly instead of copying it.

fix(event): Prevent eventer data races by removing shallow object copy

---

internal/db/schema/migrations/oss/postgres/29/01_cancel_session_null_fkey.up.sql
internal/db/schema/migrations/oss/postgres/91/07_cancel_session_trigger.up.sql
internal/db/sqltest/tests/session/cancel_session.sql

When a resource relating to a session is deleted,
notably a target, host, or auth_token, the corresponding sessions are
marked as canceled via a database trigger that calls the cancel_session
function. This function was performing a select as part of the insert
call to ensure that it would not attempt to insert a session_sate of
canceled if it was an invalid state transition. However, since this
function was first introduced, there has been additional constraints
added that would prevent an invalid state transition. In addition,
performing a select as part of an insert increases the chances for
contention with other queries that interact with the session_state
table, especially since a large number of sessions and session_state
rows can be included in a single transaction when things like …

perf(session): Avoid select when canceling session

---

enos/modules/aws_boundary/boundary-instances.tf
enos/modules/aws_target/main.tf
enos/modules/aws_vault/vault-instances.tf
enos/modules/aws_vpc/main.tf

This PR updates several enos modules to add the user's email address to AWS resources in order to make it easier to identify who generated them when looking at the AWS console. This is to assist when investigating who has left lingering resources that can be cleaned up when we are about to reach vpc limits or when costs are high.
Example:
https://hashicorp.atlassian.net/browse/ICU-15225

test(e2e): Add user name to AWS resources

---

website/content/docs/concepts/connection-workflows/multi-hop.mdx

I was unaware until a few weeks ago, after speaking with @jefferai about the pure power of mhop and outbound connectivity. A question that comes up often is that if you have a mhop deployment and maybe a firewall in between, my understanding was that you would have to allow inbound connectivity to the egress worker associated with the target. After speaking with engineering, this is not the case. 
I believe most, if not all of the field are unaware of this and it is a powerful feature. I think more needs to be made of it to highlight this. Certainly colleagues I've spoken to are unaware of it.
This PR is a draft for further review and discussion.

Added new remove the requirement for inbound network rules section

---

website/content/docs/concepts/transparent-sessions.mdx

Changes the link to download the boundary installer from the Downloads page to the Releases page.
[View the preview deployment](https://boundary-n9d2uh9pp-hashicorp.vercel.app/boundary/docs/concepts/transparent-sessions)

docs: Update installer download link

---

enos/ci/service-user-iam/main.tf

When working on e2e tests for ipv6 environments, CI was running into the following error
```
Error: unassigning EC2 Instance (i-053b6fe8a0a671961) IPv6 addresses: operation error EC2: UnassignIpv6Addresses, https response error StatusCode: 403, RequestID: a94a192e-ae2c-4023-91e6-cc51a7fd0a4d, api error UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:sts::173905499206:assumed-role/github_actions-boundary_enterprise_ci/GitHubActions is not authorized to perform: ec2:UnassignIpv6Addresses on resource: arn:aws:ec2:us-east-1:173905499206:network-interface/eni-03717530bd76ef50d because no identity-based policy allows the ec2:UnassignIpv6Addresses action.
```
This PR updates the Terraform files that manage the policy used by the CI user. Note: the CI user …

chore(enos): Add ipv6 cleanup permission

---

website/content/docs/api-clients/client-agent.mdx
website/content/docs/concepts/transparent-sessions.mdx

Identifying the primary network interface is a sub-heading under the
PAN troubleshooting section.
VMs/containers that do not have access to the local network cannot
use aliases through transparent sessions.

Client agent docs updates

---

website/content/docs/api-clients/client-agent.mdx

From a Slack conversation, the difference between restarting the Client Agent vs. reloading the configuration file could be confusing to users. This PR attempts to clarify the difference as well as the benefit to reloading only, when possible.
[View the update in the preview deployment](https://boundary-by3tox9fd-hashicorp.vercel.app/boundary/docs/api-clients/client-agent#change-the-configuration)

docs: Clarify need to reload or restart Client Agent on Mac

---

internal/clientcache/internal/cache/refresh_test.go
internal/clientcache/internal/cache/repository_refresh_token_test.go
internal/clientcache/internal/cache/repository_token.go
internal/clientcache/internal/cache/repository_token_test.go
internal/clientcache/internal/db/db.go
internal/clientcache/internal/db/schema.sql
internal/db/option.go
internal/db/option_test.go
internal/db/read_writer.go

Previously, when all the auth tokens for a user
where deleted, we deleted the user along with all
the cached resources for that user.  This can
create a lot of churn in the cache, especially if
the auth tokens have a short TTL (like 8 hrs), which 
can cause all the resources to be reloaded every
morning when the user logs in.
This change introduces a soft-delete of users in
the cache.  When all the auth tokens for a user are 
deleted, but there's still a valid refresh token
that's less than 20 days old, we mark the user as
deleted in the cache and do not return the user in 
the list of users returned by the cache, but we
still keep the user in the cache (all all their
cached resources). This way, when the user logs in 
again, we can just mark the user as active again
and not have to …

feat (cache): impl. soft-delete of users in cache

---

testing/internal/e2e/tests/base/search_test.go

Potentially with the implementation of https://github.com/hashicorp/boundary/pull/5173, the e2e test for search was impacted and started to fail on `main` (in CI only (?). I couldn't repro locally). 
```
│ === RUN   TestCliSearch
│     search_test.go:40: Stopping daemon...
│     search_test.go:58: Waiting for daemon to start...
│     scope.go:85: Created Org Id: o_Mi5dwTRE8G
│     scope.go:127: Created Project Id: p_swelCH9fAZ
│     search_test.go:109: 
│         	Error Trace:	/src/boundary/testing/internal/e2e/tests/base/search_test.go:109
│         	Error:      	"[]" should have 1 item(s), but has 0
│         	Test:       	TestCliSearch
│ --- FAIL: TestCliSearch (6.15s)
```
This PR makes some modifications to the e2e test to perform some retries for that assertion.

test(e2e): Add retry to search test

---

website/content/docs/api-clients/client-agent.mdx
website/content/docs/concepts/transparent-sessions.mdx

The automatic backports to the `release/0.18.x` branch are failing when we backport to the stable website. This PR manually cherry-picks the most recent docs updates to the `release/0.18.x` branch. This PR supersedes the following auto-generated backport PRs which all failed:
- #5185 
- #5182
- #5178

docs: Manually backport 0.18.0 updates

---

website/content/docs/concepts/domain-model/storage-policy.mdx

Automated backports to the `release/0.18.0` branch are failing. This PR backports #5191 to the `release/0.18.0` branch.

chore(docs): clarify that storage policies must be attached in order to take effect (#5191)

---

internal/daemon/cluster/handlers/worker_service.go
internal/daemon/controller/tickers.go
internal/server/query.go
internal/server/repository_worker.go
internal/server/repository_worker_test.go

The repository function VerifyKnownWorkers replaces the use of ListWorkers in two instances where we are only concerned in confirming the existence of workers

feat(workers): add VerifyKnownWorkers repo function

---

.github/workflows/security-scan.yml

The security-scanner started failing with `no assets to download` (see https://github.com/hashicorp/boundary/actions/runs/11485270903/job/31967837536)

chore: update security scanner

---

internal/cmd/commands/server/worker_initial_upstreams_reload_test.go
internal/cmd/commands/server/worker_tags_reload_test.go
internal/daemon/cluster/handlers/worker_service_status_test.go
internal/server/repository_worker.go
internal/server/repository_worker_test.go
internal/server/testing.go
internal/server/testing_test.go

Removed LookupWorkerByName and replaced it with a test method; since this method is used in tests where there are very few workers, the logic was simplified.

feat(server): refactor LookupWorkerByName to be a test method

---

website/content/docs/api-clients/client-agent.mdx

The previous configuration was known to confuse at least one reader.
It's easy to just copy the first command you see and run it, so
make that the non-destructive reload command.

Clarify client agent config reload docs

---

website/content/docs/api-clients/client-agent.mdx

Backports #5213 to the `release/0.18.x` branch.
* docs/client-agent: clarify configuration reload on MacOS
The previous configuration was known to confuse at least one reader.
It's easy to just copy the first command you see and run it, so
make that the non-destructive reload command.
* docs/client-agent: correct log level config example
* Update website/content/docs/api-clients/client-agent.mdx
---------

Clarify client agent config reload docs (#5213)

---

website/content/docs/api-clients/client-agent.mdx

The override_upstream_dns_servers option is recommended whenever a user needs to override the DNS servers discovered from the system. However, if a user supplies a DNS server that is only useable while connected to a specific network, it will break the internet in cases where it is not able to resolve these DNS servers. Encourage users to supply both the VPN servers and the default DNS servers.

docs/client-agent: clarify use of override_upstream_dns_servers

---

internal/server/repository_worker.go
internal/server/worker.go
internal/server/worker_tags_test.go
internal/server/worker_test.go

Exporting API and Config tags will allow them to be populated by queries defined in query.go for use in domain functions.

refact(worker): export api and config tags

---

enos/ci/service-user-iam/main.tf

Observed that some e2e tests were failing for the following reason
> Error: reading ELBv2 Listener (arn:aws:elasticloadbalancing:us-east-1:271311691044:listener/app/boundary-alb-clerlzdj/2d640b6192460fa9/dadeaa7b29410903) attributes: operation error Elastic Load Balancing v2: DescribeListenerAttributes, https response error StatusCode: 403, RequestID: 04a1faa7-90a5-4b3d-a69f-aae3544ecf38, api error AccessDenied: User: arn:aws:sts::271311691044:assumed-role/github_actions-boundary_ci/GitHubActions is not authorized to perform: elasticloadbalancing:DescribeListenerAttributes because no identity-based policy allows the elasticloadbalancing:DescribeListenerAttributes action
This PR updates some terraform for the CI service user to add the requested permission. This terraform has already been …

chore(e2e): Add required permission to service user

---

internal/auth/oidc/repository_managed_group_members.go
internal/auth/oidc/service_callback.go
internal/auth/oidc/service_callback_test.go

Previously, we would list the managed groups with an implied filter of db.DefaultLimit (10,000), which would incorrectly remove a user from managed group memberships if there were more than 10,000 managed groups in an auth method. Explicitly set the list limit to unlimited to ensure all managed groups are updated appropriately.

internal/auth/oidc: ensure all managed groups are tested on auth

---

enos/modules/aws_boundary/variables.tf
enos/modules/aws_worker/main.tf
enos/modules/aws_worker/variables.tf

This PR updates the e2e test suite to increase the size of the AWS worker instances. There were some AWS SDK updates that increased memory usage on workers, causing them to crash (and subsequently result in e2e test failures). This PR will resolve those failures in boundary-enterprise.
https://hashicorp.atlassian.net/browse/ICU-15786

chore(e2e): Increase worker instance size

---

website/content/docs/api-clients/client-agent.mdx

host key error for man in the middle attack is commonly encountered while connecting ssh target, updated docs to help troubleshoot this issue.

docs: add ssh host key error to known issues

---

website/content/docs/concepts/aliases.mdx
website/content/docs/concepts/transparent-sessions.mdx
website/content/docs/configuration/target-aliases/connect-target-alias.mdx
website/content/docs/configuration/target-aliases/create-target-alias.mdx
website/content/docs/configuration/target-aliases/index.mdx
website/content/docs/configuration/target-aliases/transparent-sessions.mdx
website/data/docs-nav-data.json

[Aliases and transparent sessions overview](https://boundary-1mnmk7a65-hashicorp.vercel.app//boundary/docs/configuration/target-aliases)
[Aliases concepts page](https://boundary-1mnmk7a65-hashicorp.vercel.app/boundary/docs/concepts/aliases)
[Transparent sessions concepts page](https://boundary-1mnmk7a65-hashicorp.vercel.app/boundary/docs/concepts/transparent-sessions)
This PR adds usage docs for target aliases and transparent sessions.
- Adds new configuration/target-aliases book
- Overview
- Create target aliases
- Connect to a target using an alias
- Configure transparent sessions
- Migrates appropriate usage docs content from Concepts pages to the usage docs
- Adds a new configuration example for targets with a host ID specified

adds target aliases and transparent sessions usage docs

---

website/content/docs/install-boundary/configure-controllers.mdx
website/content/docs/install-boundary/configure-workers.mdx
website/content/docs/install-boundary/deploy.mdx
website/content/docs/install-boundary/index.mdx
website/content/docs/install-boundary/initialize.mdx
website/content/docs/install-boundary/install-clients.mdx
website/data/docs-nav-data.json
website/redirects.js

[Install clients deploy preview](https://boundary-9cgc3130q-hashicorp.vercel.app/boundary/docs/install-boundary/install-clients)
This PR adds enhancements for the Install Boundary docs:
- renames the install-boundary/install page to install-boundary/deploy
- adds appropriate redirects
- adds copy to distinguish between installing the binary and installing the clients 
- adds an install-boundary/clients page to detailing which clients to install based on distribution
- updates copy to include TOC and clear deployment steps

Install boundary docs enhancements

---

internal/cmd/commands/server/controller_db_swap_test.go
internal/cmd/commands/server/controller_ratelimit_reload_test.go
internal/cmd/commands/server/listener_reload_test.go
internal/cmd/commands/server/worker_initial_upstreams_reload_test.go
internal/cmd/commands/server/worker_tags_reload_test.go

Previously, if one of these tests failed to start their servers before the timeout, there was a risk that the goroutine started to run the server would invoke t.Errorf after the test itself had concluded. Replace t.Errorf with fmt.Printf to avoid
the panic, and include the test name to help debugging.
These panics seem to have started happening recently - I recorded two instances in just the last two days. You can see the panic summary at the end of the test log, but also note the "timeout" message printed in the tests:
1. https://github.com/hashicorp/boundary/actions/runs/11846826652/job/33015283733?pr=5242#step:9:29792
2. https://github.com/hashicorp/boundary/actions/runs/11847490310/job/33017292501?pr=5245#step:9:12181

internal/commands/server: prevent test panic on timeout

---

testing/internal/e2e/infra/docker.go
testing/internal/e2e/tests/database/migration_test.go
testing/internal/e2e/tests/database/testdata/boundary-config.hcl

This PR addresses an e2e test failure that started appearing around October 14, 2024. The PR adjusts the test to wait for the controller to finish starting up before proceeding.  
https://hashicorp.atlassian.net/browse/ICU-15656

test(e2e): Fix failure in migration test

---

plugins/boundary/mains/gcp/go.mod

The module name for `go.mod` should be `gcp` not `aws` since it is in the `gcp` package

chore: update gcp plugin module name

---

internal/iam/repository_principal_role_test.go

- Simplified code by removing unnecessary if-else conditions in the wantUserIds and wantGroupIds blocks.
Fixes #5205

Refactor redundant append operations in test setup

---

.github/workflows/build.yml

Update the `build.yml` to include the commit sha as part of production tags as part of `ICU-15357`.

Update Tags For CRT

---

internal/event/eventer.go
internal/event/eventer_gate_test.go

Don't error in ReleaseGate if the context used for the original event has been cancelled. Any error in ReleaseGate causes the controller to terminate its startup. If a user was trying to send a request to the Boundary controller as it started up, the context tied to the request would be reused to attempt logging the observation associated with the request after the logging gate was released. This would always fail, as the context associated with the request was canceled.
We now use a new context timeout for events logged after the release gate is released, if the original context was canceled.
Fixes ICU-15809

internal/event: avoid reusing canceled context

---

website/content/docs/api-clients/client-agent.mdx

This pull request updates the macOS client agent documentation to clarify the behavior of `launchctl stop` and `launchctl unload`. It adds a note explaining that `launchctl stop` stops the agent temporarily, but the agent will automatically restart after 60 seconds due to the `StartInterval` setting. Additionally, the update provides information on using `launchctl unload` to permanently disable the client agent, in case users need to do so for specific reasons.

docs: clarify behavior of launchctl stop and unload for client agent

---

enos/modules/aws_bucket/main.tf

This PR updates the s3 bucket configuration to include an object expiration policy of 30 days. This is more specifically for use in the POC for internal long-running tests against the cloud platform. 
https://hashicorp.atlassian.net/browse/ICU-15062

chore(e2e): Add object expiration policy to s3 bucket

---

internal/daemon/controller/auth/auth_test.go
internal/perms/grants.go
internal/perms/grants_test.go

- Add clarifying comment to `GrantHash` --> if GrantTuples is nil, return a slice of empty bytes: `[]byte{0000 0000}`
- Enforce this behavior with additional test cases

chore: Clarify GrantHash behavior when there are no GrantTuples

---

enos/ci/service-user-iam/main.tf

This PR updates the terraform that manages the AWS service user used by CI with a new permission. This was needed after an update to the s3 bucket module that added an expiration date for objects in the bucket.
The change has already been applied to the service user and has resolved the failing e2e tests. This PR is just checking in those changes.

chore(e2e): Update AWS service user with required permission

---

internal/daemon/worker/testing.go

Instead of sleeping, we can poll for the desired state. Also, run shutdowns in parallel. This mostly affects the enterprise tests that start multiple workers.

internal/daemon/worker: speed up multi-worker tests

---

plugins/boundary/mains/gcp/go.mod
plugins/boundary/mains/gcp/go.sum

bump GCP plugin version to the latest

chore: update boundary-plugin-gcp dependency to latest version

---

enos/enos-scenario-e2e-docker-base-with-vault.hcl
enos/modules/docker_vault/config/config.json
enos/modules/docker_vault/main.tf
enos/modules/test_e2e_docker/main.tf
enos/modules/test_e2e_ui/main.tf
testing/internal/e2e/tests/base_with_vault/auth_method_oidc_vault_test.go

This PR adds an e2e test that validates setting up [Vault as an OIDC provider](https://developer.hashicorp.com/vault/tutorials/auth-methods/oidc-identity-provider#create-a-vault-oidc-provider) and creating a Boundary auth method for it. This test does not authenticate using this auth method as it requires access to a browser to complete authentication. I plan on exploring an Admin UI e2e test to see if it's feasible to do there.
```
=== RUN   TestAuthMethodOidcVault
auth_method_oidc_vault_test.go:29: Setting up Vault OIDC provider...
scope.go:85: Created Org Id: o_QTNEIIlw7l
auth_method_oidc_vault_test.go:305: Created OIDC Auth Method: amoidc_M9H2YNLS5Y
--- PASS: TestAuthMethodOidcVault (17.41s)
PASS
ok      github.com/hashicorp/boundary/testing/internal/e2e/tests/base_with_vault …
```

test(e2e): Add test for vault oidc provider

---

website/content/docs/release-notes/v0_18_0.mdx

Go version 1.23 added a new TLS handshake behavior. Some VPN providers struggle with the new behavior, and it may prevent 0.18.x Boundary clients from connecting. This PR adds a workaround to the known issues for 0.18.x that allows users to invoke the old TLS handshake behavior:
[View the update in the preview deployment](https://boundary-9ues2v8a8-hashicorp.vercel.app/boundary/docs/release-notes/v0_18_0)

docs: Update 0.18.x release notes

---

internal/daemon/controller/testing.go
internal/daemon/worker/testing.go
internal/tests/cluster/parallel/anon_listing_test.go
internal/tests/cluster/parallel/doc.go
internal/tests/cluster/parallel/ipv6_listener_test.go
internal/tests/cluster/parallel/multi_controller_worker_test.go
internal/tests/cluster/parallel/package_registry_test.go
internal/tests/cluster/parallel/recursive_anon_listing_test.go
internal/tests/cluster/parallel/unix_listener_test.go
internal/tests/cluster/sequential/doc.go
internal/tests/cluster/sequential/package_registry_test.go
internal/tests/cluster/sequential/session_cleanup_test.go
internal/tests/cluster/sequential/worker_bytesupdown_test.go
internal/tests/cluster/sequential/worker_proxy_test.go
internal/tests/cluster/sequential/worker_tagging_test.go
internal/tests/cluster/sequential/x509_verification_test.go
internal/tests/helper/testing_helper.go

There are a number of tests in the cluster package that must run sequentially (due to global variables that are being manipulated), but there are also many tests that can run in parallel. The golang sdk does not allow us to configure how we want to run these tests in a specific order. Therefore, I split the tests into two sub packages. This has greatly improved the runtime of the tests, without introducing flaky behaviors.
Before:
After:

test(cluster): split tests between parallel and sequential packages

---

internal/clientcache/cmd/cache/addtoken.go
internal/clientcache/cmd/search/search_test.go
internal/clientcache/internal/cache/refresh.go
internal/clientcache/internal/cache/repository.go
internal/clientcache/internal/cache/repository_test.go
internal/clientcache/internal/cache/repository_token.go
internal/clientcache/internal/cache/repository_token_test.go
internal/clientcache/internal/daemon/server.go
internal/clientcache/internal/daemon/token_handler_test.go
internal/cmd/base/base.go
internal/cmd/base/keyring.go
internal/cmd/commands/config/token.go

Reading a token from the keyring can sometimes fail for reasons other than the token not being present in the keyring. This PR introduces a new error used to indicate that the token requested could not be found in the keyring and propagates errors from the keyring up to the caller, so that the caller can act on them.
Additionally, this fixes a bug in the client cache where it would incorrectly assume that a token had been removed from the keyring, when in fact there was an error reading from the keyring.

cmd: propagate keyring reading errors

---

internal/tests/cluster/sequential/session_cleanup_test.go

The cluster session cleanup test would fail randomly due to a worker status context deadline timeout. This update fixes the flaky test by checking the worker status multiple times using a `require.Eventually` check.

test(cluster): check worker status multiple times

---

.github/workflows/test-race.yml
.github/workflows/test.yml

This PR updates the unit test workflow to resolve an error when the cache restores to fail. Here is an example run: https://github.com/hashicorp/boundary/actions/runs/12439588543/job/34735079491.
When the cache fails to restore, the pipeline does not have access to the `tparse` tool, resulting in the error
```
Run nick-fields/retry@7152eba30c6575329ac0576536151aca5a72780e
go test "./..." -tags="" -v -json -cover -timeout 40m | tparse -follow
/bin/sh: 1: tparse: not found
```
This PR adds a step to install tools if the restore happens to fail.

chore: Install tools if cache restore fails

---

internal/daemon/controller/handlers/targets/target_service.go
internal/daemon/controller/handlers/targets/tcp/target_service_test.go

- We weren’t assigning the session connection limit we got from the DB to the `ConnectionLimit` field on the `SessionAuthorization` response object before returning from `AuthorizeSession` [[link](https://github.com/hashicorp/boundary-enterprise/blob/62c41191ffce6ab68fbed810559dd857fa8a2528/internal/daemon/controller/handlers/targets/target_service.go#L1203)]. As a result, the connection limit has a default value of `0` when the connect cmd prints the session info
- We _do_ assign `ConnectionLimit` in a similar object, `SessionAuthorizationData`, but it gets marshalled into an auth token. Instead of decoding & unmarshalling the entire `SessionAuthorizationData` payload for the connection limit, I decided to just copy its value onto the `SessionAuthorization` struct.

fix(target): Assign session connection limit to SessionAuthorization.ConnectionLimit

---

enos/enos-scenario-e2e-aws-base-with-vault.hcl
enos/enos-scenario-e2e-ui-aws.hcl
enos/modules/aws_vault/outputs.tf

This PR updates additional e2e test modules based on some changes by the [e2e vault oidc test PR](https://github.com/hashicorp/boundary/pull/5384/files). It modifies the AWS-based scenarios to pass a full address with a schema.

chore(e2e): Update vault addresses in AWS scenarios

---

enos/modules/gcp_target/main.tf

This PR updates an e2e test terraform module that is used to create GCP instances. We observed the following error on a run.
```
Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.labels': ''. Label value 'hashicorp-tsccr[bot]' violates format constraints. The value can only contain lowercase letters, numeric characters, underscores and dashes. The value can be at most 63 characters long. International characters are allowed., invalid
with module.create_gcp_target.google_compute_instance.boundary_target[0],
on ../../modules/gcp_target/main.tf line 96, in resource "google_compute_instance" "boundary_target":
96: resource "google_compute_instance" "boundary_target" ***
```
https://github.com/hashicorp/boundary/actions/runs/12567797706/job/35034860787?pr=5 …

chore(e2e): Modify gcp label to meet format constraints

---

api/go.mod
api/go.sum
go.mod
go.sum
plugins/boundary/mains/aws/go.mod
plugins/boundary/mains/aws/go.sum
plugins/boundary/mains/azure/go.mod
plugins/boundary/mains/azure/go.sum
plugins/boundary/mains/minio/go.mod
plugins/boundary/mains/minio/go.sum
plugins/kms/mains/alicloudkms/go.mod
plugins/kms/mains/alicloudkms/go.sum
plugins/kms/mains/awskms/go.mod
plugins/kms/mains/awskms/go.sum
plugins/kms/mains/azurekeyvault/go.mod
plugins/kms/mains/azurekeyvault/go.sum
plugins/kms/mains/gcpckms/go.mod
plugins/kms/mains/gcpckms/go.sum
plugins/kms/mains/ocikms/go.mod
plugins/kms/mains/ocikms/go.sum
plugins/kms/mains/transit/go.mod
plugins/kms/mains/transit/go.sum
sdk/go.mod
sdk/go.sum

Fixes CVE-2024-45338, GO-2024-3333

mod: update golang.org/x/net dependency (0.18.x)

---

enos/modules/aws_bucket/main.tf

This PR updates the s3 bucket configuration to use  an object expiration policy of 7 days.

chore(e2e): Modify bucket object expiration policy to 7 days

---

website/content/docs/install-boundary/configure-workers.mdx

[Deploy preview](https://boundary-f2p6b2ire-hashicorp.vercel.app/boundary/docs/install-boundary/configure-workers#adopt-the-workers-optional)
This PR:
- fixes incomplete install worker CLI registration steps
- adds additional step for registering remaining workers in the example

Docs: fix missing worker registration CLI steps

---

.github/dependabot.yml

This PR updates the dependabot configuration to only provide updates for internal Github Action updates. We have an internal tool to provide security approved 3rd party Action updates, so the PRs generated by dependbot are redundant.

chore: Only use dependabot for internal action updates

---

internal/db/schema/internal/edition/edition.go
internal/db/schema/internal/edition/edition_test.go

When building the set of migrations to run as part of executing the
`database migrate` or `database init`, the migrations are collected and
combined to run within a database transaction. As such the `begin` and
`commit` statements in the migration files should get removed from the
final set of statements that get executed. However, when the migrations
files were updated to include copyright and license headers, this broke
the logic that would strip out the `begin` statement.
While this does not cause any issue with executing the statements in a
single transaction, it does result in noise in the database server's
logs, with log messages like:
BEGIN WARNING:  25001: there is already a transaction in progress
BEGIN LOCATION:  BeginTransactionBlock, xact.c:3778
This commit fixes the logic to …

fix(db): Remove begin when assembling migrations

---

testing/internal/e2e/tests/base/bytes_up_down_empty_test.go
testing/internal/e2e/tests/base/bytes_up_down_test.go

This PR updates the bytes up/down tests due to some upcoming changes to worker status reporting. Bytes up/down information will be sent up every 15 seconds, which caused some flakiness in these tests (the tests currently only check up to 6 seconds).
```
=== RUN   TestCliBytesUpDownEmpty
scope.go:85: Created Org Id: o_0FgXGDvowH
scope.go:127: Created Project Id: p_eMqKDSVfJn
target.go:127: Created Target: ttcp_jPWTLvmYmv
session.go:25: Waiting for session to appear...
bytes_up_down_empty_test.go:55: Starting session...
session.go:60: No items are appearing in the session list. Retrying...
session.go:48: Found 1 session(s)
session.go:55: Created Session: s_hh4zZEtfzn
bytes_up_down_empty_test.go:77: Waiting for bytes_up/bytes_down to be greater than 0...
bytes_up_down_empty_test.go:108: …
```

test(e2e): Add increased retries in bytes up/down tests due to worker status report changes

---

enos/modules/aws_boundary/variables.tf

AWS stopped supporting PostgresSQL 15.6 as of today. I bumped the default version to 15.7

fix(enos): bump default db version to new required minimum

---

.github/workflows/test-race.yml
.github/workflows/test.yml

Someone ran into a case where a unit test run failed due to not having `tparse` even though the cache restore was successful.
https://github.com/hashicorp/boundary/actions/runs/12642066509/job/35225823802
We previously addressed a similar issue with [this PR](https://github.com/hashicorp/boundary/pull/5394), but in that instance, the cache failed to restore.
I haven't been able to find the root cause. Prior to the failing job, [this job](https://github.com/hashicorp/boundary/actions/runs/12623460970/job/35172475947) was the most recent run that used this cache key -- in this case, that job created the cache and ran the tests successfully. I'm not sure how `tparse` ended up missing.
In any event, this PR modifies the workflow to check if `tparse` exists regardless if it restores from the …

chore: Modify tparse check

---

enos/modules/docker_openssh_server/custom-cont-init.d/01-allow-tcp-forwarding
enos/modules/docker_openssh_server/main.tf
testing/internal/e2e/tests/base/target_tcp_connect_http_test.go
testing/internal/e2e/tests/base_with_vault/auth_method_oidc_vault_test.go

This PR adds an e2e test for the usage of `boundary connect http`.
The way this is achieved is a little roundabout. The test first connects to the SSH target and enables port forwarding. It then kicks off a process on a target to start a simple web server. Finally, the test creates a new target pointing to the web server and performs a `connect http`.
https://hashicorp.atlassian.net/browse/ICU-10838

test(e2e): Add test for `connect http`

---

scripts/build-ui.sh

`make build-ui` has been failing in `boundary-enterprise` for the following reason
```
❯ make build-ui
./scripts/build-ui.sh
==> Building default UI version from internal/ui/VERSION_ent: b3266a06d02e155773bdf6aab67e4746b4900ffd
Found gh cli, attempting to download ui assets
Downloading artifact: 2426488954
2404259760
2042297073 for admin-ui-ent b3266a06d02e155773bdf6aab67e4746b4900ffd
parse "https://api.github.com/repos/hashicorp/boundary-ui-enterprise/actions/artifacts/2426488954\n2404259760\n2042297073/zip": net/url: invalid control character in URL
make: *** [build-ui] Error 1
```
This is caused by the `gh` command looking artifact ids for a certain commit, which in this case, is returning several artifact ids separated by `\n`. 
```
{
"id": 2426488954,
...
}
{
"id": 2404259760,
...
} …
```

chore: Handle build-ui case when there's multiple artifacts

---

internal/daemon/controller/handlers/aliases/alias_service.go
internal/daemon/controller/handlers/aliases/grants_test.go

set the `ParentScopeId` before fetching authorized actions for alias

fix(alias): set parent scope id for alias resource

---

internal/daemon/controller/handlers/workers/grants_test.go
internal/daemon/controller/handlers/workers/worker_service.go

set the `ParentScopeId` before fetching authorized actions for worker

fix(worker): set parent scope id for worker resource

---

internal/daemon/controller/handlers/users/grants_test.go
internal/daemon/controller/handlers/users/user_service.go

Resources are being filtered out due to missing ParentScopeId when constructing Resource to pass into authResults.FetchActionSetForId.

fix(user): children scopes being filtered out by grants for user

---

internal/daemon/controller/handlers/scopes/grants_test.go
internal/daemon/controller/handlers/scopes/scope_service.go

set the `ParentScopeId` before fetching authorized actions for worker

fix(scope): set parent scope id for worker resource

---

internal/daemon/controller/handlers/targets/target_service.go
internal/daemon/controller/handlers/targets/tcp/grants_test.go

set the `ParentScopeId` before fetching authorized actions for target

fix(target): set parent scope id for target resource

---

enos/ci/service-user-iam/main.tf

Observed some e2e test failures due to the following
> Error: modifying ELBv2 Listener (arn:aws:elasticloadbalancing:us-east-1:173905499206:listener/app/boundary-alb-zynxjceb/e115653ecf1ea789/25bae502218ed4b1) attributes: operation error Elastic Load Balancing v2: ModifyListenerAttributes, https response error StatusCode: 403, RequestID: a8f01fe5-6a15-4de7-beb5-4630fca0f4c4, api error AccessDenied: User: arn:aws:sts::173905499206:assumed-role/github_actions-boundary_enterprise_ci/GitHubActions is not authorized to perform: elasticloadbalancing:ModifyListenerAttributes on resource: arn:aws:elasticloadbalancing:us-east-1:173905499206:listener/app/boundary-alb-zynxjceb/e115653ecf1ea789/25bae502218ed4b1 because no identity-based policy allows the elasticloadbalancing:ModifyListenerAttributes …

chore: Add permissions to CI user

---

testing/internal/e2e/tests/base/bytes_up_down_empty_test.go
testing/internal/e2e/tests/base/bytes_up_down_test.go

This PR is a follow-up to https://github.com/hashicorp/boundary/pull/5424.
This PR attempts to resolve flakiness in the e2e test `TestCliBytesUpDownTransferData`. The test occasionally fails for the following reason
```
│     bytes_up_down_test.go:81: Waiting for bytes_up/bytes_down to be greater than 0...
│     bytes_up_down_test.go:117: bytes_up: 0, bytes_down: 0, bytes_up or bytes_down is not greater than 0. Retrying...
│     bytes_up_down_test.go:117: bytes_up: 0, bytes_down: 0, bytes_up or bytes_down is not greater than 0. Retrying...
│     bytes_up_down_test.go:112: bytes_up: 4728, bytes_down: 4861
│     bytes_up_down_test.go:123: Waiting for bytes_up/bytes_down to increase...
│     bytes_up_down_test.go:159: bytes_up: 4728, bytes_down: 4861, bytes_up/bytes_down is not greater than …
```

test(e2e): Address flakiness in bytes up/down test

---

internal/daemon/controller/handlers/roles/grants_test.go
internal/daemon/controller/handlers/roles/role_service.go

set the `ParentScopeId` before fetching authorized actions for role resource

fix(roles): set parent scope id for roles resource

---

internal/daemon/controller/handlers/managed_groups/grants_test.go
internal/daemon/controller/handlers/managed_groups/managed_group_service.go

set the ParentScopeId before fetching authorized actions for managed-group resource

test(managed-group): add grants test coverage

---

internal/daemon/controller/handlers/hosts/grants_test.go
internal/daemon/controller/handlers/hosts/host_service.go

set the `ParentScopeId` before fetching authorized actions for host resource

fix(host): set parent scope id for host resource

---

internal/daemon/controller/handlers/host_catalogs/grants_test.go
internal/daemon/controller/handlers/host_catalogs/host_catalog_service.go

set the `ParentScopeId` before fetching authorized actions for host-catalog resource

fix(host-catalog): set parent scope id for host-catalog resource

---

internal/daemon/controller/handlers/credentialstores/credentialstore_service.go
internal/daemon/controller/handlers/credentialstores/grants_test.go

set the ParentScopeId before fetching authorized actions for credential-store resource

fix(credential-store): set parent scope id for credential-store resource

---

internal/daemon/controller/handlers/credentials/credential_service.go
internal/daemon/controller/handlers/credentials/grants_test.go

set the `ParentScopeId` before fetching authorized actions for credential resource

fix(credential): set parent scope id for credential resource

---

internal/daemon/controller/handlers/accounts/account_service.go
internal/daemon/controller/handlers/accounts/grants_test.go

fix children grants filtering out results because `parentScopeId` isn't passed into the permissions engine during the output filtering

fix(accounts): bug grants filter children accounts

---

internal/daemon/controller/handlers/authtokens/authtoken_service.go
internal/daemon/controller/handlers/authtokens/grants_test.go

Set Scope ID for resources when performing final auth check in `newOutputOpt`

fix(authtokens): set parent scope ID for auth token resource

---

plugins/boundary/mains/gcp/go.mod
plugins/boundary/mains/gcp/go.sum

Update the GCP plugin dependency to point the latest released version

chore: Update boundary-plugin-gcp to version v0.1.0

---

internal/daemon/controller/handlers/credentiallibraries/credentiallibrary_service.go
internal/daemon/controller/handlers/credentiallibraries/grants_test.go

- **add utility functions for grants tests**
- **use passed in scopeID to create user**
- **add test for groups list**
- **groups: set ParentScopeId before FetchActionSetForId**
- **add comment to TestRoleGrantsForToken**
- **lint and ran make gen**
- **fix import groups**
- **add an additional test case**
- **remove print**
- **changelog**
- **fix(alias): set parent scope id for alias resource (#5434)**
- **fix(worker): set parent scope id for worker resource (#5435)**
- **fix(user): children scopes being filtered out by grants for user (#5436)**
- **fix(scope): set parent scope id for worker resource (#5439)**
- **fix(target): set parent scope id for target resource (#5447)**
- **fix(credential-libraries): set parent scope ID**

fix(credentiallibraries): set parent scope ID

---

CHANGELOG.md
go.mod
go.sum
internal/auth/password/argon2.go
internal/auth/password/argon2_test.go
internal/auth/password/permitpool.go
internal/auth/password/permitpool_test.go
internal/cmd/commands/server/server.go
internal/cmd/config/config.go
internal/cmd/config/config_test.go
internal/daemon/controller/controller.go

The resizable pool wraps the permit pool with a mutex
to allow it to be resized at runtime.
The default concurrency limit is 1, and it can be
set using the SetHashingPermits function.
The new concurrent_password_hash_workers configuration
value can be used to loosen the constraints on the
password auth method hashing operation.
Sets the password hashing concurrency constraints on
startup and config reload.

Restrict concurrent password hashes

---

internal/daemon/controller/common/scopeids/scope_ids.go
internal/daemon/controller/handlers/users/grants_test.go

Fix missing parent Scope ID when calling `FetchActionSetForType`

fix(common) set parent ID before fetching action setsparent ID before fetching action sets

---

enos/ci/hcp-resources/main.tf

This PR updates a Terraform file to update a usage of a module based on some changes from a different PR. This Terraform file is used to generate resources for HCP long-lived tests.

chore(hcp): Update use of license module

---

internal/scheduler/job/repository_job_test.go

This was failing because the compared values weren't pointers. It was probably caused by a depedency version update changing the behavior of this function.

internal/scheduler/job: fix test failure

---

website/content/docs/api-clients/client-agent.mdx

Adds conflicts encountered when using Huntress EDR alongside Boundary Client agent. Detailed analysis can be found here: https://hashicorp.atlassian.net/browse/ICU-15332

docs: Adds conflicts with Huntress EDR

---

.release/security-scan.hcl

Add [CVE-2024-13176](https://ubuntu.com/security/CVE-2024-13176) to the suppress vulnerability list as Alpine hasn't addressed the issue yet

ci(security-scanner): Suppress openssl linux CVE

---

CODEOWNERS

The web team was getting a lot of noise from my recent code owner changes, so we decided together to remove them from the CODEOWNERS for docs content directories. Please let me know if you have questions.

Remove web team from CODEOWNERS for content directories

---

.release/security-scan.hcl

There is currently not a fix for GO-2025-3408. Adding the vulnerability to the suppress list for now
The issue to address the vulnerability is currently open: https://github.com/hashicorp/yamux/issues/142

ci(security-scanner): Suppress GO-2025-3408

---

.release/security-scan.hcl

There is currently not a fix for GHSA-29qp-crvh-w22m. Adding the vulnerability to the suppress list for now

ci(security-scanner): Suppress GHSA-29qp-crvh-w22m

---

website/content/docs/concepts/host-discovery/aws.mdx
website/content/docs/concepts/host-discovery/azure.mdx
website/content/docs/concepts/host-discovery/gcp.mdx
website/content/docs/concepts/host-discovery/index.mdx

This PR updates the usage docs for dynamic host catalogs. It adds a UI workflow to the AWS and Azure procedures which only had CLI and Terraform previously. It also adds Dynamic and Static credential tabs to the AWS procedure "Create a host catalog to connect with AWS" to support `AssumeRole`.
It also updates the new GCP topic to include a tabbed workflow with the UI path.
- [AWS dynamic host catalogs](https://boundary-875xrj850-hashicorp.vercel.app/boundary/docs/concepts/host-discovery/aws)
- [Azure dynamic host catalogs](https://boundary-875xrj850-hashicorp.vercel.app/boundary/docs/concepts/host-discovery/azure)
- [GCP dynamic host catalogs](https://boundary-875xrj850-hashicorp.vercel.app/boundary/docs/concepts/host-discovery/gcp)

docs: Update DHC workflows

---

enos/README.md

This PR updates the enos readme to include a note for modifying `/etc/hosts`. This is needed when using docker-based scenarios to allow the use of container names in addresses.

chore(e2e): Add note for modifying `/etc/hosts`

---

internal/daemon/worker/worker.go
internal/daemon/worker/worker_test.go

The variable `newConf.Worker.SuccessfulControllerRPCGracePeriod` is a any type, which defaults to nil. The case statement would then match on the default case, where the `SuccessfulControllerRPCGracePeriodDuration` was not set. This would then have a cascading affect of causing immediate timeouts for anything that was referencing the `session.CloseCallTimeout` variable.

fix(worker): set session.CloseCallTimeout to non-zero value

---

website/content/docs/api-clients/client-agent.mdx
website/content/docs/concepts/transparent-sessions.mdx

On MacOS 15.1 and 15.2, some users report that all their DNS responses incur the error `sendmsg: broken pipe`

docs: add note about MacOS 15.1, 15.2 incompatibility

---

internal/auth/oidc/repository_auth_method.go
internal/auth/oidc/repository_managed_group_members.go
internal/auth/repository_auth_method.go
internal/credential/repository_store.go
internal/host/options.go
internal/host/options_test.go
internal/host/plugin/options.go
internal/host/plugin/options_test.go
internal/host/plugin/repository_host_catalog.go
internal/host/plugin/repository_host_set.go
internal/host/repository_catalog.go
internal/host/static/repository_host.go
internal/iam/repository.go
internal/iam/repository_grant_scope.go
internal/iam/repository_role.go
internal/iam/repository_role_grant.go
internal/server/options.go
internal/server/options_test.go
internal/server/repository_worker.go
internal/server/repository_worker_storage_bucket_credential_state.go

This PR resolves three things:
1. Remove `context.Background()` from database transactions
2. Propagate the same database transaction reader & writer to helper functions. We need to ensure we are using a single db connection per transaction.
3. Ensure we are using the database transaction reader & writer within the anonymous function call and not the repository reader or writer.

fix: resolve small issues in db transactions

---

website/content/docs/release-notes/v0_17_0.mdx
website/content/docs/release-notes/v0_18_0.mdx

Updates the **Known issues** section of the 0.17.x and 0.18.x release notes.
[Boundary 0.17.x release notes](https://boundary-gyye03fi6-hashicorp.vercel.app/boundary/docs/release-notes/v0_17_0)
[Boundary 0.18.x release notes](https://boundary-gyye03fi6-hashicorp.vercel.app/boundary/docs/release-notes/v0_18_0)

docs: Update 0.17.x and 0.18.x release notes

---

go.mod

Post-release step: Bump`sdk` and `api` based off `0.19.0` release

chore: bump sdk & api deps

---

.github/workflows/actionlint.yml
.github/workflows/backport.yml
.github/workflows/build.yml
.github/workflows/enos-fmt.yml
.github/workflows/enos-run.yml
.github/workflows/fuzz.yml
.github/workflows/linting.yml
.github/workflows/make-gen-delta.yml
.github/workflows/schema-diff.yml
.github/workflows/security-scan.yml
.github/workflows/test-ci-bootstrap-oss.yml
.github/workflows/test-ci-cleanup-oss.yml
.github/workflows/test-cli-ui_oss.yml
.github/workflows/test-race.yml
.github/workflows/test-sql.yml
.github/workflows/test.yml
.github/workflows/trigger-merge-to-downstream.yml

This PR updates github actions to the latest trusted version to avoid errors like https://github.com/hashicorp/boundary/actions/runs/13266812212/job/37036206073
The changes came from running this command
```
tsccr-helper gha update -latest .github/
```

chore: Update github actions to latest trusted (0.18.x)

---

website/content/docs/api-clients/client-agent.mdx

MacOS 15.3 has been known to sometimes block users from using the client agent altogether. Explicitly allowing it access to incoming network connections resolves the issue.

docs/client-agent: add warning about MacOS 15

---

website/content/docs/api-clients/client-agent.mdx

- Issue: Client agent does not start if the given example configurations are used.
- Both the parameters are parsed using `parseutil.ParseDurationSecond`, which parses a duration from a string or numeric value into a time.Duration.
- When units are missing (such as when a numeric type is provided), the duration is assumed to be in seconds.
- Since providing a time format is more readable, updating the example to the corrected string version.
- Providing a string example configuration is more suitable than providing a number example like `alias_refresh_interval=60`; where it is automatically assumed to be seconds, and can become confusing for the consumers.

docs: Fixes examples for alias_refresh_interval & dns_request_timeout

---

website/content/docs/api-clients/client-agent.mdx

Backport of #5544 into Stable website
Supercedes #5545

Backport: fixes examples for alias_refresh_interval & dns_request_timeout

---

website/content/docs/concepts/host-discovery/aws.mdx

this PR corrects the incorrect AWS AssumeRole policy example for the `AmazonEC2ReadOnlyAccess` role.

fixes incorrect AssumeRole policy

---

internal/clientcache/internal/cache/refresh.go
internal/clientcache/internal/cache/repository_token.go
testing/internal/e2e/tests/base/search_test.go

This PR contains a potential fix for the issue of deleted auth tokens preventing re-authentication (introduced with https://github.com/hashicorp/boundary/pull/5173). The biggest change is that previously, if a soft-deleted user authenticated, it would remain soft-deleted. Now we restore the user on authentication.
It also contains some tidying of the token error handling.

Restore soft deleted users on authentication

---

internal/iam/options.go
internal/iam/repository_role_grant.go
internal/iam/repository_role_grant_ext_test.go
internal/iam/repository_role_grant_test.go

Goal: Write direct & indirect tests for the GrantsForUser function against the Group resource
- Direct: Directly associating a user to a role
- Indirect: Associating a user to a role via one of the following:
1. Group
2. Managed Group (e.g. OIDC, LDAP)
___
I created one test for each case: one direct test, one group test, and one managed group test (performed via OIDC). All tests contain grants against the Group resource (and its associated [actions](https://developer.hashicorp.com/boundary/docs/configuration/identity-access-management/resource-table#group))

test(grants): GrantsForUsers tests for Group resource

---

testing/internal/e2e/tests/base/search_test.go

Observed this failure on `release/0.19.x`
```
│ === RUN   TestCliSearch
│     search_test.go:40: Stopping cache...
│     search_test.go:58: Waiting for cache to start...
│     search_test.go:76: ***"error":"The cache process is not running."***. Retrying...
│     scope.go:85: Created Org Id: o_lrIyDpJGjn
│     scope.go:127: Created Project Id: p_AQhm9lWozC
│     search_test.go:150: Creating targets...
│     search_test.go:170: Listing targets...
│     search_test.go:183: Waiting for client cache to populate data...
│     search_test.go:232: Did not see expected number of targets in status, EXPECTED: 13, ACTUAL: 2. Retrying...
│     search_test.go:227: Found 13 target(s)
│     search_test.go:239: Searching targets...
│     search_test.go:312: 
│         	Error Trace: …
```

test(e2e): Address flake in search test

---

enos/modules/aws_boundary/boundary-instances.tf
enos/modules/aws_worker/main.tf

This PR modifies the terraform modules used in end-to-end testing to enable encryption for an ec2 instance's `root_block_device` (i.e. the root storage) (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance). This addresses a minor security warning that discovered that some volumes were not encrypted at rest. While these instances are only used for tests and are short-lived (get destroyed immediately), it wasn't difficult to address the warning. 
https://hashicorp.atlassian.net/browse/ICU-16596

chore(e2e): Set up ec2 instance storage with encryption

---

internal/authtoken/repository.go

Use a constant-time method for comparing secrets. Such an operation will scan the entirety of both strings to be compared rather than returning early as soon as a character is encountered that does not match.

fix(token): utilize a more accurate comparison method

---

internal/daemon/controller/handlers/targets/target_service.go

In the controller’s implementation of the AuthorizeSession operation, the error handling logic contains potential nil pointer dereferences.

fix(handlers): resolve nil reference pointer for authorize session

---

internal/db/schema/internal/postgres/postgres.go

Errors encountered during database migrations applied through the database init and database migrate commands do not display the correct error messages. This issue arises from an incorrect variable reference in the GetMigrationLog function.

fix(db): return expected rows err for migration logs

---

internal/daemon/cluster/handlers/worker_service_status_test.go
internal/daemon/cluster/handlers/worker_service_test.go
internal/daemon/controller/tickers.go
internal/scheduler/job/testing.go
internal/scheduler/testing.go
internal/server/controller.go
internal/server/repository_controller.go
internal/server/repository_controller_test.go
internal/session/service_statistics_test.go
internal/session/service_worker_status_report_test.go

- Normally we don't use `store` structs directly for exported methods as part of a repo. This updates the server controller to use it's domain package instead which itself embeds the store. 
This PR was created as a result of the discussion [here](https://github.com/hashicorp/boundary/pull/5602#discussion_r1999418660).

Migrate Controller Repo Usage From Store To Server

---

internal/clientcache/internal/daemon/server.go

Updated the client cache to create the database file with 0600 permissions. The third-party SQLite driver in use does not support specifying permissions for a new database file. It was necessary to create an empty database on disk with the correct permissions and then reopen it using the SQLite driver.
Note, this fix only applies to the default DB path `.boundary/cache.db`.

fix(daemon): set correct permissions on cache.db file

---

website/content/docs/api-clients/client-agent.mdx

Updated the "Conflicting Software" section in the Boundary Client Agent documentation to include issues caused by macOS Internet Sharing and Parallels Desktop (macOS VM with shared networking). These configurations cause the system's DNS resolver to bind to port 53, preventing the Client Agent from starting.

docs: add macOS Internet Sharing and Parallels Desktop conflicts for Boundary Client Agent

---

website/content/docs/configuration/worker/index.mdx

Added a note that the public_addr is not needed if connecting to HCP worker in multi-hop sessions

Update index.mdx - public_addr note for HCP workers

---

website/content/docs/configuration/worker/index.mdx

* Update index.mdx - public_addr note for HCP workers
Added a note that the public_addr is not needed if connecting to HCP worker in multi-hop sessions
* Update index.mdx
* Update index.mdx
changed to active voice per Robin's suggestion
* fix hcp_boundary_cluster_id note
---------
Co-authored-by: stellarsquall <stellarsquall@protonmail.ch>

Update index.mdx - public_addr note for HCP workers (#5287)

---

internal/daemon/controller/tickers.go
internal/server/query.go
internal/server/repository_controller.go
internal/server/repository_controller_test.go

Rework and fix the original logic of #5602 query split. Initial implementation resulted in failures of controller's updating their status within the `server_controller` as `w.Update` does not automatically cause the [update_time trigger](https://github.com/hashicorp/boundary/blob/8d182ca576901c8886303b59756228d0a61a5427/internal/db/schema/migrations/oss/postgres/34/02_worker_controller_tables.up.sql#L28) to be used if the values of `address` or `description` were not updated. To result this we instead perform an `w.Exec` where the statement is defined as [updateController](https://github.com/hashicorp/boundary/blob/fce36ad57cf06452cd1d3ea56bbcbd1f9f65dcaa/internal/server/query.go#L227) query which will always force `update_time` to be the value of `now()`. 
- Update the …

ICU-16457 Split Liveness Query In Two

---

website/content/docs/commands/targets/create.mdx
website/content/docs/commands/targets/update.mdx
website/content/docs/concepts/domain-model/targets.mdx
website/content/docs/configuration/target-aliases/create-target-alias.mdx

The automatic backport failed for #5105 . This PR manually cherry-picks the commit to the `stable-website` branch.
* docs: Clarify that max duration is required
* docs: Update TCP tabs
* docs: Update newer usage topic

docs: Clarify that max duration is required (#5105)

---

internal/daemon/controller/handlers/targets/target_service.go

Removing dead code. 
`ExtraWorkerFilters` was last used in 0.11
The consts were replaced with `globals.ResourceInfoFromPrefix` in 0.15

chore: remove dead target service code

---

internal/daemon/controller/handlers/authmethods/grants_test.go

Add grants tests for auth methods against the read, list, create, update, delete, and authenticate actions. Each test case also tests grant output fields
Most testcases utilize an `expectedOutput` struct. I wanted to have one common output type for testcases where the output could only be (1) an error or (2) a set of `output_fields` (i.e. no error)

Add grants tests for authmethods

---

internal/daemon/controller/handlers/host_sets/grants_test.go
internal/host/static/testing.go

- CRUDL grants tests for host sets
- Added `TestHostSet()` function in order to create test host sets with names & descriptions for validating `output_fields`
- Added `TestHostCatalog()` function in order to create multiple test host catalogs without running into duplicate name errors from the API

test(hostsets): add grants tests

---

website/content/docs/concepts/iam.mdx
website/content/docs/configuration/controller.mdx

A new feature will allow HCP Boundary users to set time to live and time to stale for auth tokens. This PR updates/removes some caveats where we said this wasn't possible and links out to the new HCP doc.
- [Configure users - OIDC/LDAP](https://boundary-f83zh2dk3-hashicorp.vercel.app/boundary/docs/concepts/iam#configure-users-oidc-ldap) 
- [Controller > `auth_token_time_to_live`](https://boundary-f83zh2dk3-hashicorp.vercel.app/boundary/docs/configuration/controller#auth_token_time_to_live) - Deleted a reference here
**This PR should be merged AFTER HCP-Docs PR [#1213](https://github.com/hashicorp/hcp-docs/pull/1213)**

docs: Update caveats about HCP and TTL

---

enos/modules/aws_vpc/main.tf
enos/modules/aws_vpc_ipv6/main.tf

This PR updates end-to-end test infra to use Ubuntu 22 due to Ubuntu 20 reaching end-of-life. End-to-end tests still pass with this update.
https://hashicorp.atlassian.net/browse/ICU-16897

chore(e2e): Update to use Ubuntu 22

---

internal/db/schema/migrations/oss/postgres/100/01_iam_role_global.up.sql
internal/db/schema/migrations/oss/postgres/100/02_iam_role_org.up.sql
internal/db/schema/migrations/oss/postgres/100/03_iam_role_project.up.sql
internal/db/sqltest/tests/iam/iam_role_global.sql
internal/db/sqltest/tests/iam/iam_role_org.sql

Split `iam_role_global_individual_grant_scope` to `iam_role_global_individual_org_grant_scope` and `iam_role_global_individual_project_grant_scope` and allow `children` to be used in `iam_role_global_individual_project_grant_scope.grant_scope` to support use case where roles at global scope are granted `children` and individual projects grants. 
Add triggers to 
- propagate changing `iam_role_global_individual_project_grant_scope.grant_scope` from `children` to `individual` and vice-versa when `iam_role_global.grant_scope` is updated
- add trigger to delete all `iam_role_global_individual_project_grant_scope` and `iam_role_global_individual_org_grant_scope` when a `iam_role_global.grant_scope` is changed to `descendants`
- add trigger to delete all …

bosorawis sql split global grants scope table

---

internal/tests/cli/boundary/_generics.bash
internal/tests/cli/boundary/generic.bats

Bats test for generic boundary commands using targets
Commands tested
Boundary read
Boundary update
Boundary delete
Test output 
generic.bats
✓ boundary/generic: can login as admin user
✓ boundary/generic: admin user can create target
✓ boundary/generic: admin user can read target with generic read
✓ boundary/generic: admin user can update target with generic update
✓ boundary/generic: admin user can check that the update worked with generic read
✓ boundary/generic: admin user can delete target with generic delete
6 tests, 0 failures

test(bats): Added bats tests for generic commands

---

website/content/docs/concepts/domain-model/credential-stores.mdx

Backport PR failed for #2561
* Correct Static Creds indentation
* Update website/content/docs/concepts/domain-model/credential-stores.mdx
---------

Backport Correct Static Creds indentation (#2561) - stable-website

---

website/content/docs/concepts/domain-model/credential-stores.mdx

Backport PR failed for #2561
* Correct Static Creds indentation
* Update website/content/docs/concepts/domain-model/credential-stores.mdx
---------

Backport Correct Static Creds indentation (#2561) - 0.19.0

---

internal/cmd/commands/database/flags.go
internal/cmd/commands/database/flags_test.go
internal/cmd/commands/database/init.go

This commit refactors the database initialization flags to prevent early exits and ensure explicit handling of flag dependencies. If one flag relies on resources skipped by another, the dependent flag will also be skipped.
Key Changes:
- Introduced a `initFlags` struct to organize existing flags and establish a clear pattern for adding future flags.
- Added receiver functions on the `initFlags` struct to determine whether a flag should be skipped based on provided options or dependencies.
- Refactored the `Run()` function to avoid early returns when a flag skips resource creation. Instead, a log message is provided to indicate the skipped option, and the process continues with resource creation.

Database Init Flags Refactor

---

enos/modules/aws_target/main.tf

This PR is a continuation of https://github.com/hashicorp/boundary/pull/5580
This PR configures encryption on an ec2 instance used as an SSH target. Hopefully, this will fully address that Wiz alert.

chore(e2e): Add encryption to target ec2 instance

---

website/content/docs/concepts/domain-model/credential-stores.mdx

From a Slack conversation:
https://hashicorp.slack.com/archives/C016ZKNM05T/p1744743081610239
The description of how credential libraries interact with credential stores in this topic is unclear. We mention that credential stores can store or generate credentials, but those functions are specific to the static and Vault types respectively. We should clarify how those 2 credential store types differ.
Additionally, I deleted some redundant links, removed a broken note, and fixed a typo.
[Credential stores](https://boundary-e66kan0aw-hashicorp.vercel.app/boundary/docs/concepts/domain-model/credential-stores)

docs: Clarify credential store behavior

---

.release/security-scan.hcl

Suppressing vulnerability warnings from CVEs found in this CRT pipeline: https://github.com/hashicorp/crt-workflows-common/actions/runs/14717736026/job/41305881597
```
- URI: https://nvd.nist.gov/vuln/detail/CVE-2025-46394
- Description: In tar in BusyBox through 1.37.0, a TAR archive can have filenames hidden from a listing through the use of terminal escape sequences.
- Base Score: 3.2 LOW
- URI: https://nvd.nist.gov/vuln/detail/CVE-2024-58251
- Description: In netstat in BusyBox through 1.37.0, local users can launch of network application with an argv[0] containing an ANSI terminal escape sequence, leading to a denial of service (terminal locked up) when netstat is used by a victim.
- Base Score: 2.5 LOW
- URI: https://nvd.nist.gov/vuln/detail/CVE-2025-30258
- Description: In GnuPG …
```

Dkanney CVE suppression for 0.19.2

---

website/content/docs/api-clients/client-agent.mdx
website/content/docs/configuration/target-aliases/transparent-sessions.mdx

From a Slack conversation: https://hashicorp.slack.com/archives/C01AQDJF3SA/p1744830559607819?thread_ts=1744827620.957889&cid=C01AQDJF3SA. 
We should note that both protocols are required by the Client Agent to help alleviate customer confusion.
I added notes in 2 topics. View the updates in the preview deployment:
- [Configure transparent sessions](https://boundary-hr9jwegtk-hashicorp.vercel.app/boundary/docs/configuration/target-aliases/transparent-sessions)
- [Boundary Client Agent](https://boundary-hr9jwegtk-hashicorp.vercel.app/boundary/docs/api-clients/client-agent)

docs: Note that IPv4 and IPv6 are mandatory

---

internal/alias/target/repository_alias_list_resolvable.go
internal/alias/target/service_list_resolvable_ext_test.go
internal/perms/acl.go
internal/perms/acl_test.go

Refactor `ACL` function `ListResolvableAliasesPermissions` to handle direct child scopes (e.g., global → org → project) correctly in the scenario a direct grant is given to a scope under your children, and prevent `500` errors when resolving aliases without proper scope permissions where the current only existing alias type,`Target`, lives.
- In the `ListResolvableAliasesPermissions` function for the `ACL`, the default case was removed and replaced with for edge case for a `global` scoped role with the `children` grant scope:
```go
default:
// Since direct grants must be the same scope or downstream, the
// only possibility left for a children grant is that the parent is
// global and the grant is on the org -- if it was for projects it
// would need to be a descendants grant
if _, ok := …
```

ListResolvableAliasesPermissions Hotfix

---

website/content/docs/api-clients/client-agent.mdx

This PR does the following:
- Updates the WARP client **Conflicting software** section with new clarifying information
- Adds 2 new errors to the **Commonly seen errors** section ([ICU-16234](https://hashicorp.atlassian.net/browse/ICU-16234))
- Renames the **Commonly seen errors** section to **Common error messages** and removes ableist language.
- Adds a new OpenVPN section to the **Conflicting software** section , with subsections for MacOS and Windows ([IND-1784](https://hashicorp.atlassian.net/browse/IND-1784))
- Alphabetizes the existing entries to the **Conflicting software** section to make it easier to read.
- Client Agent > Conflicting software > [Cloudflare WARP client](https://boundary-8b7rvj4ul-hashicorp.vercel.app/boundary/docs/api-c …

docs: Update Client Agent errors and conflicting software

---

website/content/docs/api-clients/client-agent.mdx

Manually backports the updates from #5674 to `stable-website` due to failed backport PR #5715 :
* docs: Document OpenVPN DNS conflict
* docs: Fix name of interface
* docs: Add common errors
* docs: Updates based on review feedback
* docs: Remove abelist language
* docs: Remove ableist language

docs: Update Client Agent errors and conflicting software (#5674)

---

.release/security-scan.hcl

```
found reported vulnerability CVE-2025-47268 from Alpine Linux's Security Issue Tracker in iputils@20240905-r0
/lib/apk/db/installed:1:1
```
https://nvd.nist.gov/vuln/detail/CVE-2025-47268
> ping in iputils through 20240905 allows a denial of service (application error or incorrect data collection) via a crafted ICMP Echo Reply packet, because of a signed 64-bit integer overflow in timestamp multiplication.
>
> Base Score: [6.5 MEDIUM](https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?name=CVE-2025-47268&vector=AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L&version=3.1&source=MITRE)

Add rule to suppress CVE-2025-47268

---

enos/ci/hcp-resources/main.tf
enos/enos-scenario-e2e-aws-base-with-vault.hcl
enos/enos-scenario-e2e-aws-base.hcl
enos/enos-scenario-e2e-aws.hcl
enos/enos-scenario-e2e-database.hcl
enos/enos-scenario-e2e-docker-base-plus.hcl
enos/enos-scenario-e2e-docker-base-with-gcp.hcl
enos/enos-scenario-e2e-docker-base-with-vault.hcl
enos/enos-scenario-e2e-docker-base-with-worker.hcl
enos/enos-scenario-e2e-docker-base.hcl
enos/enos-scenario-e2e-docker-worker-registration-controller-led.hcl
enos/enos-scenario-e2e-docker-worker-registration-worker-led.hcl
enos/enos-scenario-e2e-ui-aws.hcl
enos/enos-scenario-e2e-ui-docker.hcl
enos/enos-variables.hcl
enos/enos.vars.hcl
enos/modules/read_license/main.tf

Created an environment variable that allows you to pass in the boundary license for boundary enterprise without using a file. 
Note that the license in the env will overwrite the license in the file. 
Jira - https://hashicorp.atlassian.net/browse/ICU-16630
Testing - 
Tested a couple different scenarios with the license as an env, license in the file and both envs being set

chore(e2e): Added support for boundary license to be an env for enos

---

website/content/docs/release-notes/v0_17_0.mdx
website/content/docs/release-notes/v0_18_0.mdx
website/content/docs/release-notes/v0_19_0.mdx

The automated backport PR #5724  failed for the 0.19.2 release notes. This PR manually cherry-picks the changes from #5708 into the `release/0.19.x` branch.

docs: Update 0.19.2 release notes in release branch (#5708)

---

website/content/docs/troubleshoot/troubleshoot-recorded-sessions.mdx

The backport to `stable-website` failed for #5732. This PR cherry-picks the following commits from that PR:
* docs: Fix incomplete sentence
* docs: Fix punctuation

docs: Fix incomplete sentence (#5732)

---

go.mod
internal/iam/query.go
internal/iam/repository_role_grant.go
internal/iam/repository_role_grant_test.go

add query to fetch grants for a user for resources that are only globally scoped
**Note**:
DO NOT MERGE until we can create roles by subType from domain code instead of using `setupDB_IamRoles` to manually insert. `setupDB_IamRoles` was used to just validate the query

feat: grantsForUser for Global Resources

---

testing/internal/e2e/tests/base/paginate_account_test.go
testing/internal/e2e/tests/base/paginate_auth_token_test.go
testing/internal/e2e/tests/base/paginate_credential_store_test.go
testing/internal/e2e/tests/base/paginate_credential_test.go
testing/internal/e2e/tests/base/paginate_group_test.go
testing/internal/e2e/tests/base/paginate_host_catalog_test.go
testing/internal/e2e/tests/base/paginate_host_set_test.go
testing/internal/e2e/tests/base/paginate_host_test.go
testing/internal/e2e/tests/base/paginate_managed_group_test.go
testing/internal/e2e/tests/base/paginate_role_test.go
testing/internal/e2e/tests/base/paginate_scope_test.go
testing/internal/e2e/tests/base/paginate_session_test.go
testing/internal/e2e/tests/base/paginate_target_test.go
testing/internal/e2e/tests/base/paginate_user_test.go

This PR skips the pagination e2e tests until the "large estimated count" bug is addressed: https://hashicorp.atlassian.net/browse/ICU-16649. Since that bug is causing OOM on the runner (in boundary-enterprise), the idea is to disable the tests triggering the OOM so that we can at least get the other tests to execute. (This borrows the "SkipSlowTest" method to avoid needing to create another method).
There will be another PR on boundary-enterprise to skip any enterprise-specific pagination tests.

test(e2e): Skip pagination tests until large estimated count bug is addressed

---

testing/internal/e2e/tests/base/paginate_account_test.go
testing/internal/e2e/tests/base/paginate_auth_token_test.go
testing/internal/e2e/tests/base/paginate_credential_store_test.go
testing/internal/e2e/tests/base/paginate_credential_test.go
testing/internal/e2e/tests/base/paginate_group_test.go
testing/internal/e2e/tests/base/paginate_host_catalog_test.go
testing/internal/e2e/tests/base/paginate_host_set_test.go
testing/internal/e2e/tests/base/paginate_host_test.go
testing/internal/e2e/tests/base/paginate_managed_group_test.go
testing/internal/e2e/tests/base/paginate_role_test.go
testing/internal/e2e/tests/base/paginate_scope_test.go
testing/internal/e2e/tests/base/paginate_session_test.go
testing/internal/e2e/tests/base/paginate_target_test.go
testing/internal/e2e/tests/base/paginate_user_test.go

This PR is a modification of https://github.com/hashicorp/boundary/pull/5742.
Better skip message, better reading.

test(e2e): Better skip message

---

internal/iam/query.go
internal/iam/repository_role_grant.go
internal/iam/repository_role_grant_test.go

- Changing the type of the `reqScope` parameter from `Scope` to `string`
- Simplify `grantsForUserGlobalResourcesQuery` & its repo function. Now querying directly into `perms.GrantTuple`

Change reqScope parameter type from `Scope` to `string`

---

internal/iam/repository_role_grant_ext_test.go

Refactored the existing GrantsForUser tests from #5443. The logic between these tests is mostly the same -- the only variables are:
1. The resource being tested
2. The method of association (direct vs group vs managed group)
As a result, it made sense to refactor the existing three tests into one. Now passing in a **principal** (the thing being associated to roles), and a **role association function** (tells us how to associate the principal to its roles)
___
Note: The tests for `resource.Account` will not pass until the GrantsForUser refactor is complete. In its current state, `GrantsForUser()` returns _all_ grants for a user. After the refactor, it'll return a subset of grants based on some new parameters (i.e. resource type, request scope, recursive option). Until then, tests for …

Test: GrantsForUser for Accounts for various user to role relationships

---

website/content/docs/api-clients/client-agent.mdx
website/content/docs/commands/database/init.mdx
website/content/docs/configuration/target-aliases/transparent-sessions.mdx
website/content/docs/release-notes/v0_19_0.mdx

Updates the documentation as part of the effort to remediate HCPb default roles and grants before the transparent sessions GA. This PR adds the following:
- Updates the release notes with an important change and known issue
- Updates the section that describes the grants required for transparent sessions
- Updates the CLI `database-init` documentation, which was missing the `-skip-initial-authenticated-user-role-creation` parameter
- Updates the transparent sessions configuration doc to call attention to the Client Agent's required grants and the known issue with HCPb.
- 0.19.0 release notes > [Important changes](https://boundary-8krdcy9t8-hashicorp.vercel.app/boundary/docs/release-notes/v0_19_0#important-changes)
- 0.19.0 release notes > [Known …

docs: Add HCPb grants issue and fix

---

website/content/docs/api-clients/client-agent.mdx
website/content/docs/commands/database/init.mdx
website/content/docs/configuration/target-aliases/transparent-sessions.mdx
website/content/docs/release-notes/v0_19_0.mdx

I merged #5746 but the back port to `release/0.19.x` failed. This PR cherry picks the following commits to the `release/0.19.x` branch.
* docs: Add HCPb grants issue and fix
* docs: Add important change, revise alertbox
* docs: Updates based on review feedback
* docs: Updates based on review feedback
* docs: Rephrase reference to fix
* docs: Update date of fix
* docs: Update transparent sessions configuration topic

docs: Add HCPb grants issue and fix (#5746)

---

.github/dependabot.yml

Trying to decipher https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference and https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates to let us group dependabot PRs into three groups:
1. Github Actions updates
1. Go version updates
1. Go security updates
No real way to test this other than merging it and checking for new PRs on Sunday 🤷🏻 . I'll open similar PRs for other repos if this one works.

dependabot: add go modules, groups

---

testing/internal/e2e/tests/base/scope_permissions_test.go

This test covers the defect https://hashicorp.atlassian.net/browse/ICU-12561
The test modifies some of the default grants and then adds a grant to a user. That user should then only see their one assigned project when they run the command
boundary scopes list --recursive
Command to run just this test
go test github.com/hashicorp/boundary/testing/internal/e2e/tests/base -v -run 'TestScopePermissions'
Test output: 
=== RUN   TestScopePermissions
scope.go:85: Created Org Id: o_QdBvNI4LV2
scope.go:127: Created Project Id: p_T5JCyqEu6q
scope.go:127: Created Project Id: p_fo5CYYKHiz
account.go:79: Created Account: acctpw_QhFJYTn5jZ
user.go:65: Created User: u_bVsLbSJ67a
role.go:64: Created Role: r_0mswbSD9px in scope o_QdBvNI4LV2
--- PASS: TestScopePermissions (4.70s)
PASS
ok …

test(e2e): Test for scopes permission defect

---

website/content/docs/api-clients/client-agent.mdx
website/content/docs/concepts/connection-workflows/index.mdx
website/content/docs/concepts/transparent-sessions.mdx
website/content/docs/configuration/target-aliases/transparent-sessions.mdx
website/content/docs/install-boundary/install-clients.mdx
website/data/docs-nav-data.json

This PR removes beta tags and references from the transparent sessions documentation. View the updates in the preview deployment:
- [Boundary Client Agent](https://boundary-28vo24gtc-hashicorp.vercel.app/boundary/docs/api-clients/client-agent)
- [Transparent sessions](https://boundary-28vo24gtc-hashicorp.vercel.app/boundary/docs/concepts/transparent-sessions)
- [Configure transparent sessions](https://boundary-28vo24gtc-hashicorp.vercel.app/boundary/docs/configuration/target-aliases/transparent-sessions)
- [Install Boundary clients](https://boundary-28vo24gtc-hashicorp.vercel.app/boundary/docs/install-boundary/install-clients)

docs: Update TS documentation for GA

---

internal/server/rewrapping.go

Remove duplicate `err != nil` check in the `server` package for `workerAuthServerLedActivationTokenRewrapFn` rewrapping. This check is currently unreachable due to the previous `if err != nil` check and is not tested against.

Remove Duplicate Error Check

---

website/content/docs/configuration/worker/index.mdx

The automatic back port for #5730 failed. This PR manually cherry-picks the following commits to the `release/0.19.x` branch:
* rework mini-docs day
* fix note callout
* Update website/content/docs/configuration/worker/index.mdx
Co-authored-by: Johan Brandhorst-Satzkorn <johan.brandhorst@gmail.com>
* docs: Minor edits
---------
Co-authored-by: Johan Brandhorst-Satzkorn <johan.brandhorst@gmail.com>

boundary/mini-docs day 2 - configuration/worker/index (#5730)

---

internal/iam/query.go
internal/iam/repository_role_grant.go
internal/iam/repository_role_grant_test.go

Add query to fetch grants for a user for resources that can be project scoped when the request scope is _not_ a project.
- When `request_scope='global'`, retrieve grant scopes on _all_ projects
- When `request_scope='o_XXXXX'`, retrieve grant scopes on all projects under the specified org

feat: grantsForUser for recursive Project resources

---

website/content/docs/concepts/transparent-sessions.mdx

This PR adds a known issue to the transparent sessions documentation. The issue is being worked on in [ICU-15293](https://hashicorp.atlassian.net/browse/ICU-15293). There is no workaround at this time.
Transparent sessions > [Known issues](https://boundary-5t36xc6n3-hashicorp.vercel.app/boundary/docs/concepts/transparent-sessions#known-issues)
[ICU-15293]: https://hashicorp.atlassian.net/browse/ICU-15293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Document known issue with transparent sessions

---

website/content/docs/concepts/transparent-sessions.mdx

One of the transparent sessions known issues incorrectly says that it affects Ubuntu systems, when it actually affects all Linux systems. We also have a recommended workaround for this issue documented in the **Common errors** section, and it could be helpful for users if we link out to it. This PR updates the known issue with those 2 fixes.
[View the update in the preview deployment](https://boundary-ouoduiovi-hashicorp.vercel.app/boundary/docs/concepts/transparent-sessions#known-issues)

docs: Update transparent session known issue

---

website/content/docs/commands/client-agent/index.mdx
website/content/docs/commands/client-agent/pause.mdx
website/content/docs/commands/client-agent/resume.mdx
website/content/docs/commands/client-agent/sessions.mdx
website/content/docs/commands/client-agent/status.mdx
website/data/docs-nav-data.json

The backports for PR #5826 failed. This PR cherry-picks the following commits to the `release/0.19.x` branch:
* docs: Add Client Agent commands to CLI docs
* docs: Fix typos
* docs: Update status description
* Update website/content/docs/commands/client-agent/index.mdx
* docs: Capitalize Client Agent
* docs: Undo capitalization
---------

docs: Add Client Agent commands to CLI docs (#5826)

---

internal/daemon/controller/handlers/accounts/grants_test.go
internal/daemon/controller/handlers/aliases/grants_test.go
internal/daemon/controller/handlers/authmethods/grants_test.go
internal/daemon/controller/handlers/credentialstores/grants_test.go
internal/daemon/controller/handlers/host_catalogs/grants_test.go
internal/daemon/controller/handlers/scopes/grants_test.go

Add tests to ensure that resources with sub-types return sub-type's grants in authorized actions and authorized collection actions properly

add authorized actions tests for resources with sub-resources

---

internal/iam/query.go
internal/iam/repository_role_grant.go
internal/iam/repository_role_grant_test.go

This change intends to reduce the amount of rows retrieved by only querying each table once per CTE and using aggregate functions (`array_agg`). This should reduce the amount of rows returned from the DB in cases when there are many grants on a role:
Before:
```sql
-- returns one row per grant
select role_id,
role_scope_id,
role_parent_scope_id,
grant_scope,
canonical_grant as grant
from global_and_org_roles
group by role_id,
role_scope_id,
role_parent_scope_id,
grant_scope,
canonical_grant;
```
After:
```sql
-- returns one row per role, with an array of distinct grants for each
select role_id,
role_scope_id,
role_parent_scope_id,
grant_scope,
grant_this_role_scope,
array_agg(distinct(individual_grant_scope)) as individual_grant_scopes,
array_agg(distinct(canonical_grant))        as …
```

Refactor GrantsForUser subqueries to use aggregate functions

---

internal/db/schema/migrations/oss/postgres/85/02_alias_domain.up.sql
internal/db/schema/migrations/oss/postgres/96/01_update_wt_alias_constraints.up.sql

This migration updates the `wt_alias` and `wt_target_alias` domains to include explicit `::text` casting in their constraints. Postgres 16 enforces stricter domain checks, requiring explicit casts to ensure compatibility. 
These changes address Postgres upgrade issues by aligning the constraints with the stricter evaluation rules.
When attempting to upgrade from Postgres 15 -> 16 on Aurora RDS with Boundary `0.19.2` the following error: 
```
...
pg_restore: creating DOMAIN "public.wh_dim_key"
pg_restore: creating COMMENT "public.DOMAIN "wh_dim_key""
pg_restore: creating DOMAIN "public.wh_dim_text"
pg_restore: creating COMMENT "public.DOMAIN "wh_dim_text""
pg_restore: creating DOMAIN "public.wh_inet_port"
pg_restore: creating COMMENT "public.DOMAIN "wh_inet_port""
pg_restore: creating …
```

Postgres 15 -> 16 Migration Update

---

internal/auth/db_test.go
internal/auth/ldap/testing.go
internal/auth/oidc/testing.go
internal/auth/password/testing.go
internal/auth/testing.go
internal/authtoken/testing.go
internal/daemon/controller/handlers/accounts/grants_test.go
internal/daemon/controller/handlers/aliases/grants_test.go
internal/daemon/controller/handlers/authmethods/grants_test.go
internal/daemon/controller/handlers/authtokens/grants_test.go
internal/daemon/controller/handlers/billing/grants_test.go
internal/daemon/controller/handlers/credentiallibraries/grants_test.go
internal/daemon/controller/handlers/credentials/grants_test.go
internal/daemon/controller/handlers/credentialstores/credentialstore_service.go
internal/daemon/controller/handlers/credentialstores/grants_test.go
internal/daemon/controller/handlers/groups/grants_test.go
internal/daemon/controller/handlers/host_catalogs/grants_test.go
internal/daemon/controller/handlers/host_sets/grants_test.go
internal/daemon/controller/handlers/hosts/grants_test.go
internal/daemon/controller/handlers/managed_groups/grants_test.go
internal/daemon/controller/handlers/roles/grants_test.go
internal/daemon/controller/handlers/scopes/grants_test.go
internal/daemon/controller/handlers/targets/tcp/grants_test.go
internal/daemon/controller/handlers/testing.go
internal/daemon/controller/handlers/users/grants_test.go
internal/daemon/controller/handlers/workers/grants_test.go
internal/host/static/testing.go
internal/iam/testing.go
internal/perms/grants.go

Cherrypick the commits from `llb-normalized-grants-tests-only` to `llb-normalized-grants`. 
Note: commits 81a665725328339fbc7151b40f47fa7fee005b17 and 71df2341c3319ba4ba671d1cc12bc90a7976c42c were already cherrypicked to `llb-normalized-grants`

Cherry pick commits from `llb-normalized-grants-tests-only` to `llb normalized grants`

---

internal/iam/repository_role_grant.go
internal/iam/repository_role_grant_ext_test.go
internal/iam/repository_role_grant_test.go

For each grantsForUser repo function, the logic to map from DB object -> `perms.GrantTuple` was very similar.
- This PR reduces code by removing those functions & moves the mapping logic into `GrantsForUser`
- Created a new function, `resolveQuery()`, to determine which query to use based on the request scope & the resources' applicable scopes

Resolve GrantsForUser queries via resolveQuery()

---

internal/daemon/controller/handlers/users/grants_test.go
internal/daemon/controller/handlers/users/user_service.go
internal/perms/acl.go
internal/perms/acl_test.go

add grants tests for list-resolvable aliases
Fix bug in ACL where when a role in a scope is granted `children` grant scope with specific resource IDs, if there is a role in a child scope specifying different resource IDs in its grants, the child scope role permissions are ignored

test: add grants test for user resource and fix ACL bug

---

internal/daemon/controller/handlers/sessions/grants_test.go
internal/daemon/controller/handlers/targets/tcp/grants_test.go
internal/session/repository.go
internal/target/repository.go

Fix issue #5003 
When a resource ID is specified for the same scope, list permissions handling prioritizes the specific resource ID rather than the `ids=*` which grants permissions to more resources causing the query to incorrectly filter out resources that the user should have permissions to take actions on.
- **fix list target not handling all resources permissions**
- **add test**

bug: fix list target permissions resource ID overriding all resource grants

---

.github/pull_request_template.md

To support PCI (Payment Card Industry) certification, add PCI checklist to PR template.

Add PCI review checklist to PR template

---

internal/server/repository_controller.go
internal/server/repository_controller_test.go

- Update `UpdateControllerStatus` to handle empty string descriptions. When reading from the `server_controller` repo, `NULL` descriptions are cast to empty strings. To prevent violating the `wt_description_too_short` constraint in the `wt_description` domain, ensure that empty string descriptions are converted to `nil` before being passed to the appropriate prepared query [updateController](https://github.com/hashicorp/boundary/blob/d4b34b1f50f5ee1dd3a8477123cf6a18284b7f38/internal/server/query.go#L227).
- Add two additional unit tests to account for this scenario.

UpdateControllerStatus:Update Hotfix

---

internal/daemon/controller/handlers/host_catalogs/grants_test.go
internal/daemon/controller/handlers/host_catalogs/host_catalog_service.go

When using 2 different roles to grant permissions to `host-catalog` and its child resources `host` and `host-sets`, collection_authorized_actions do not get populated

 fix(bug): authorized_collection_actions not returning from host-catalog

---

internal/db/schema/internal/postgres/postgres.go
internal/db/schema/internal/postgres/postgres_test.go
internal/db/schema/manager.go
internal/db/schema/manager_test.go
internal/db/schema/testdata/hooks/updated/2/01_another_update.up.sql

- continuation of https://github.com/hashicorp/boundary/pull/5904
- address review comment from #5904 
- add test to `schema` package

fix(bug): database migration does not rollback schema version on hook failure

---

website/content/docs/release-notes/v0_19_0.mdx

This PR updates the 0.19.x release notes for the upcoming 0.19.3 release. It contains the following updates, click the links to see them in the preview deployment:
- Added an item to the [Important changes](https://boundary-kel28fwk3-hashicorp.vercel.app/boundary/docs/release-notes/v0_19_0#important-changes) table to explain that redundant grant scopes are no longer permitted.
- Added an item to the [Known issues](https://boundary-kel28fwk3-hashicorp.vercel.app/boundary/docs/release-notes/v0_19_0#known-issues-and-breaking-changes) section to explain the command to remove redundant grant scopes and the reason for the change

docs: Release notes for 0.19.3

---

website/content/docs/concepts/credential-management.mdx
website/content/docs/configuration/credential-management/configure-credential-injection.mdx

Last week we ran into a somewhat confusing situation with injected SSH credentials that could be helped with some additional documentation. Context here: https://hashicorp.slack.com/archives/C01AQDJF3SA/p1751574938390999?thread_ts=1751340829.616129&cid=C01AQDJF3SA.
I updated the main conceptual topic that explains credential management and the procedure that describes the configuration steps to add statements that the keyboard-interactive auth method is not supported for SSH credential injection.
- Credential management > [Credential injection](https://boundary-5rlmvy3qd-hashicorp.vercel.app/boundary/docs/concepts/credential-management#credential-injection)
- Configuring credential injection > …

docs: Note that keyboard-interactive auth is not supported

---

website/content/docs/concepts/credential-management.mdx
website/content/docs/configuration/credential-management/configure-credential-injection.mdx

* docs: Note that keyboard-interactive auth is not supported
* docs: Updates based on feedback
The automated back port (#5928) for #5926 contained a large number of files that I didn't expect to be included. I am closing #5928 in favor of this PR that includes a manual cherry-pick of the commits in #5928.

docs: Note that keyboard-interactive auth is not supported (#5926)

---

enos/enos-scenario-e2e-aws-base-with-vault.hcl
enos/enos-scenario-e2e-aws-base.hcl
enos/enos-scenario-e2e-aws.hcl
enos/enos-scenario-e2e-database.hcl
enos/enos-scenario-e2e-ui-aws.hcl
enos/modules/aws_az_finder/main.tf

This PR tries to mitigate the following error which occasionally pops up when creating e2e test infra
> Error: creating EC2 Instance: operation error EC2: RunInstances, https response error StatusCode: 400, RequestID: 0242e007-2f30-40f9-81e8-c84e4d856bb7, api error Unsupported: Your requested instance type (t3a.small) is not supported in your requested Availability Zone (us-east-1e). Please retry your request by not specifying an Availability Zone or choosing us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1f.
Two changes are made
- Update scenarios to pass in a full list of all instance types being used 
- Update the availability zone module to only return zones that support ALL instance types passed in (previously, it would return a full list of zones that support any of the …

chore(e2e): Fix availability zone check

---

website/content/docs/concepts/domain-model/aliases.mdx
website/content/docs/concepts/domain-model/index.mdx

The back port PR #5945 contained a number of commits that were not included in the original PR (#5941 ). I closed that PR in favor of this one. This PR manually cherry-picks the commit from #5941.
* docs: add Alias to domain model overview
Also fix a typo in the Aliases page.
* docs: add storage policy to domain model overview

docs: add Alias, Storage Policy to domain model overview (#5941)

---

enos/scripts/test_e2e_env.sh

This PR updates an e2e test helper script that helps extract environment variables after using enos/terraform to create test infrastructure. An additional option was added to output environment variables in a Windows format so that it can be used in Powershell. 
```
❯ . /Users/mycow/Developer/boundary/enos/scripts/test_e2e_env.sh -f windows
$env:BOUNDARY_ADDR='http://boundary:9200';
$env:E2E_AWS_HOST_SET_IPS='[""]';
$env:E2E_LDAP_ADDR='ldap://ldap';
$env:E2E_LDAP_ADMIN_DN='cn=admin,dc=example,dc=org';
$env:E2E_LDAP_ADMIN_PASSWORD='admin';
$env:E2E_LDAP_DOMAIN_DN='dc=example,dc=org';
$env:E2E_LDAP_GROUP_NAME='scientists';
$env:E2E_LDAP_USER_NAME='einstein';
```
Usages:
```
. /Users/mycow/Developer/boundary/enos/scripts/test_e2e_env.sh               # returns linux format
. …
```

chore(e2e): Add option for specifying windows format

---

website/content/docs/release-notes/v0_19_0.mdx

The backport for #5949 failed. I am closing it (#5955 ) in favor of this PR. This PR manually cherry-picks the following commits to the `stable-website` branch:
* docs: Clarify that grants migration is automatic for HCP
* docs: Include versions later than 0.19.3
* docs: Fix word choice for standards

docs: Clarify that grants migration is automatic for HCP (#5949)

---

internal/daemon/controller/handlers/authmethods/grants_test.go
internal/daemon/controller/handlers/managed_groups/grants_test.go

There are a couple of spots in grants tests where, if there's an expected error when iterating over the expected output, we `return` instead of continuing to iterate over the remaining expected outputs. This causes testcases to end prematurely instead of processing the entire testcase.
For example:
```go
expected := map[string]error {
globalAuthMethod.PublicId: handlers.ForbiddenError(),
org1AuthMethod.PublicId:   nil,
org2AuthMethod.PublicId:   nil,
}
for id, wantError := range expected {
result, err := GetAuthMethod(id)
if wantError != nil {
require.ErrorIs(t, wantError, err)
return // <-- if globalAuthMethod is processed first, the other authmethods are skipped.
}
}
```
Examples of changes to security controls include using new access control methods, adding or removing logging …

test(grants): Use 'continue' when iterating over expected outputs

---

enos/modules/aws_rdp_member_server/main.tf
enos/modules/aws_windows_client/main.tf

This PR updates terraform modules for windows instances to automatically enable audio services. This makes it easier to test audio over RDP connections

chore(e2e): Enable audio services in windows instances

---

.github/workflows/test-cli-ui_oss.yml

This PR reverts the node version for one of the github actions that should not have been updates as part of the node updates

revert node version for GHA

---

.github/workflows/test-ci-cleanup-oss.yml

This PR adds the ability to manually kick off this job (cleaning up AWS resources used by CI) in order to test some other changes. When @psekar was rotating some keys due to some security findings, I noticed we had both `secrets.AWS_ACCESS_KEY_ID` and `secrets.AWS_ACCESS_KEY_ID_CI` pairs. I'm not entirely sure why we need both, and I'd like to test if we can remove the use of `secrets.AWS_ACCESS_KEY_ID` (this job is the only place that uses it... and it uses both)
```
aws-nuke:
if: ${{ github.event.repository.name == 'boundary' }}
runs-on: ${{ fromJSON(vars.RUNNER) }}
container:
image: rebuy/aws-nuke
options:
--user root
-t
env:
AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} <------------
AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} <------------
TIME_LIMIT: "48h" …
```

chore(e2e): Add workflow dispatch option to aws-nuke job

---

internal/target/address.go
internal/target/address_ext_test.go

Target address validation was only checking length and allowed DNS names with invalid symbols, leading to a bug.
This PR adds validation to ensure the address is a valid IP or DNS name

target(addr): add validation for ipv4, ipv6, and dns addr

---

website/content/docs/client-agent/conflicting-software.mdx

The backport for #5898 failed. This PR cherry-picks the following updates to the `release/0.19.x` branch:
* updating the doc with anyconnect vpn conflicting software
* addressed pr comments
* done some minor formatting

docs: Backport #5898 to `release/0.19.x`

---

website/content/docs/monitor/index.mdx

The back ports failed for #6044. This PR manually cherry-picks the following updates to the `stable-website` branch:
* docs: Fix broken link in Monitor Boundary
* docs: Fix a typo

docs: Back port #6044 to `stable-website`

---

internal/target/repository.go
internal/target/repository_proxy_server_certificate_test.go

Proxy server certificates are not necessary for or used with CE Targets. As a follow up to https://github.com/hashicorp/boundary/pull/6050 this PR will update LookupTargetForSessionAuthorization to use either a separate function to search for proxy server certificates. In CE this function is empty and returns `nil, nil`. 
The goal of this change is to improve performance by avoiding unnecessary trips to the database for targets that do not have proxy server certificates.

fix(target): Skip fetching proxy server cert

---

website/content/docs/interoperability-matrix/index.mdx

The Client Agent interoperability matrix incorrectly states that Huntress is supported on version 0.19.6 of the Boundary installer and Client Agent. This PR removes that version.
[View the update in the preview deployment](https://boundary-1q8ugbsvj-hashicorp.vercel.app/boundary/docs/interoperability-matrix)

docs: Update Huntress interoperability

---

.github/workflows/backport.yml

The backport action bump appears to have broken the backport runner. Releng suggested reverting the action bump.

chore: revert backport action

---

enos/modules/aws_rdp_member_server/main.tf
enos/modules/aws_rdp_member_server_with_worker/main.tf
enos/modules/aws_windows_client/main.tf

Tony was running into issues SSH'ing onto a Windows box (specifically on Windows Server 2022). After some investigation, I discovered that there may have been some incorrect file permissions on the public key on the Server.
```
> icalcs C:\ProgramData\ssh\administrators_authorized_keys
NT AUTHORITY\SYSTEM:(F)
BUILTIN\Administrators:(F)
NT AUTHORITY\Authenticated Users:(RX)
```
The public key needs to only have permissions for `System` and `Administrators`: github.com/PowerShell/Win32-OpenSSH/wiki/Security-protection-of-various-files-in-Win32-OpenSSH#administrators_authorized_keys.
This PR updates the startup script to remove the `Authenticated Users` group on the file and restarts the sshd service to take the change. 
Examples of changes to security controls include using new access …

chore(e2e): Ensure permissions on key file are correct for windows boxes

---

website/content/docs/client-agent/manage.mdx

The current documented method of disabling the Boundary client conflicts with the Boundary Installer’s client-agent installation process.
If a user stops the Boundary client agent using the legacy command:
`sudo launchctl unload -w /Library/LaunchDaemons/com.hashicorp.boundary.boundary-client-agent.plist
`
then attempting to reinstall (upgrade), using boundary-installer, will result in the following error:
`The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
`
This happens because the Boundary Installer uses the modern launchctl alternatives `(bootstrap / bootout)` instead of the legacy load / …

update the disable client agent command for macos

---

enos/modules/aws_rdp_member_server_with_worker/main.tf
enos/modules/aws_rdp_member_server_with_worker/scripts/worker_hcp_bsr.hcl
enos/modules/aws_rdp_member_server_with_worker/variables.tf

This PR updates the module that creates a windows worker to support using other types of configs for the worker. This PR also includes a config that can be used for HCP testing. 

chore(e2e): Update windows worker module to support other configs

---

enos/modules/aws_rdp_member_server_with_worker/main.tf

This PR makes a fix to the `aws_rdp_member_server_with_worker` module to make sure it uses the worker config specified in the variable. Currently, if a scenario requests to use a different config, it will ignore that and just use `worker.hcl`.

fix(e2e): Use worker config from variable

---

enos/ci/service-user-iam/main.tf

This PR updates the terraform for the CI AWS service user to include the `rds:DescribeDBEngineVersions` permission. This was needed to make some changes for how we select the database version used in AWS tests. That will occur in a subsequent PR.
This terraform has already been applied to the service user and was tested in this run: https://github.com/hashicorp/boundary/actions/runs/18013041897/job/51256355972
https://hashicorp.atlassian.net/browse/ICU-9702

chore(e2e): Add rds:DescribeDBEngineVersions permission to service user

---

CHANGELOG.md
go.mod
go.sum

Pickup latest changes in cap/ldap pkg which address a possible concurrency issue.

chore: update cap pkg to v0.11.0

---

globals/prefixes.go
internal/credential/public_ids.go
internal/daemon/controller/handlers/targets/target_service.go
internal/proto/controller/api/resources/credentials/v1/credential.proto
sdk/pbs/controller/api/resources/credentials/credential.pb.go

Add support for password-only credentials by:
- Adding PasswordAttributes to credential.proto 
- Updating validation in target service handlers to accept password credentials
[ICU-17721](https://hashicorp.atlassian.net/browse/ICU-17721) and [ICU-17722](https://hashicorp.atlassian.net/browse/ICU-17722)
[ICU-17721]: https://hashicorp.atlassian.net/browse/ICU-17721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ICU-17722]: https://hashicorp.atlassian.net/browse/ICU-17722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Password credential type proto def

---

website/content/docs/domain-model/credential-stores.mdx

This PR fixes a broken example on the `domain-model/credential-stores` page.

Docs: fixes controller policy example
