hashicorp/boundary

- website/content/docs/getting-started/installing/production.mdx
I'm not sure if we want to ship this out with the TODO, but if its not implemented I feel like we still want a note right?
> Remove 'TODO' in code example

- website/vercel.json
deploy preview checks will still work as normal, but there will no longer be direct comments on the PR
> website: turn off vercel PR comments

- website/content/docs/getting-started/installing/production.mdx
I found some typo while reading docs. :)
> Fix typo in production.mdx

- README.md
Readme was missing the URL for the releases page
> Add releases page URL to Readme

- CHANGELOG.md
Updates changelog to reflect fix for https://github.com/hashicorp/boundary/issues/727 from https://github.com/hashicorp/boundary/pull/705.
> docs: update changelog with worker controllers setting bug fix

- website/content/docs/concepts/security/data-encryption.mdx
> Fix typo in data-encryption.mdx

- CHANGELOG.md
- internal/cmd/commands/database/init.go
- internal/db/error.go
- internal/db/error_test.go
Fixes https://github.com/hashicorp/boundary/issues/729
> Fix database init when locale isn't english 

- website/content/docs/common-workflows/manage-targets.mdx
Update "Common Workflows>Manage Targets>Define a Host Set" admin console videos to reflect changes in UI in v0.1.1.
---
> docs: Update host set videos in "Manage Targets" to reflect v0.1.1 UI

- CHANGELOG.md
- internal/cmd/base/listener.go
- internal/cmd/base/servers.go
- internal/cmd/commands/dev/dev.go
- internal/cmd/commands/server/server.go
- internal/cmd/config/config.go
- internal/servers/controller/controller.go
- internal/servers/controller/listeners.go
- internal/servers/controller/testing.go
- internal/servers/controller/tickers.go
- internal/servers/worker/testing.go
- internal/tests/cluster/ipv6_listener_test.go
- internal/tests/cluster/unix_listener_test.go
- website/content/docs/configuration/controller.mdx
> Add ability to set public cluster address

- CHANGELOG.md
- internal/ui/VERSION
> Ui next release update

- website/content/docs/installing/no-gen-resources.mdx
fixes https://github.com/hashicorp/boundary/issues/781
> fix docs for adding roles and principals

- website/content/docs/common-workflows/manage-roles.mdx
- website/content/docs/common-workflows/manage-scopes.mdx
Doc clickthroughs updated to reflect IAM resources changes to sidebar and scope grant changes to roles.
> Update doc clickthrough videos for ui v0.1.2 changes

- website/content/docs/common-workflows/manage-sessions.mdx
> Fix old "boundary proxy" CLI example

- internal/servers/worker/controller_connection.go
- internal/servers/worker/worker.go
This has been removed in latest grpc.
> Remove usage of manual.GenerateAndRegisterManualResolver

- CHANGELOG.md
- internal/perms/grants.go
- internal/servers/controller/handlers/roles/role_service_test.go
> Fix IDs being lowercased in role grants

- website/data/docs-navigation.js
Replace the **Common Workflows** docs with Learn link. 
[Deploy Preview Link](https://boundary-git-common-workflow-update.hashicorp.vercel.app/docs)
> [Docs] Common workflow update

- CHANGELOG.md
- internal/cmd/commands/database/init.go
Verifies the controller config block has been defined
Fixes #819 
Repro'ed issue on main:
```
boundary database init --config test.hcl
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1e42b4e]
goroutine 1 [running]:
github.com/hashicorp/boundary/internal/cmd/commands/database.(*InitCommand).Run(0xc000306280, 0xc00003a0d0, 0x2, 0x2, 0x0)
/Users/louisruch/boundary/internal/cmd/commands/database/init.go:230 +0x3ee
github.com/mitchellh/cli.(*CLI).Run(0xc000438dc0, 0xc000438dc0, 0xc000332e40, 0xc000505ee0)
/Users/louisruch/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x1cf
github.com/hashicorp/boundary/internal/cmd.RunCustom(0xc00003a0b0, 0x4, 0x4, 0xc000427e60, 0xc0000480b8) …
```
> ICU-934/Verify controller config block

- website/content/docs/configuration/worker.mdx
Adds quotes around the address value in the worker listener stanze example config
> Fix worker example config

- website/content/docs/installing/postgres.mdx
> Document Postgres permission requirements

- website/content/docs/releases/release-notes/index.mdx
- website/content/docs/roadmap.mdx
PR for adding DT client to public roadmap and cleaning up release notes page.
> Adding roadmap and release notes updates

- internal/iam/repository_scope.go
- internal/iam/repository_scope_test.go
A simple function that returns an appropriate set of scopes based on the
incoming scope ID. Includes a test.
> Add scope repo function to recursively list

- internal/perms/acl.go
- internal/perms/acl_test.go
- internal/perms/grants_test.go
- internal/types/action/action.go
- internal/types/action/action_test.go
- internal/website/permstable/permstable.go
- website/content/docs/concepts/security/permissions.mdx
Update perms table in anticipation of session support for these.
> Add read/list/cancel:self actions and support for ACL subactions.

- go.mod
- go.sum
These are Jeff-managed deps, and the changelogs have been evaluated.
> Upgrade some deps

- website/content/docs/installing/no-gen-resources.mdx
Fixes a couple of typos on the website docs
> Fix examples in website

- internal/servers/controller/handlers/targets/target_service_test.go
Adds a unit test to the create target test suite to include worker filter
> Add worker filter to create target tests

- internal/tests/cluster/anon_listing_test.go
Updates anon listing test to verify `u_anon` can list scopes by default
> Update anon listing test

- website/package-lock.json
- website/package.json
- website/pages/style.css
Upgrading next to v10 and nextjs-scripts to v15.
[_Created by Sourcegraph campaign `bkalow/upgrade-to-next-10`._](https://sourcegraph.hashi-mktg.com/users/bkalow/campaigns/upgrade-to-next-10)
> website: update next and nextjs-scripts

- website/content/docs/index.mdx
> Fix typo Boundary name

- go.mod
- internal/tests/api/accounts/account_test.go
- internal/tests/api/authtokens/authtoken_test.go
- internal/tests/api/groups/group_test.go
- internal/tests/api/hostcatalogs/host_catalog_test.go
- internal/tests/api/hosts/host_test.go
- internal/tests/api/hostsets/host_set_test.go
- internal/tests/api/roles/role_test.go
- internal/tests/api/scopes/scope_test.go
- internal/tests/api/targets/target_test.go
- internal/tests/api/users/user_test.go
PR #957 is required to be merged and tagged first.  Before submitting go.mod must be updated with the new tag.
> API filter tests

- internal/target/repository_tcp_target.go
**Is your feature request related to a problem? Please describe.**
During a failure in creating the target, the exception caused did not come with a description capable of bringing a quick understanding of the problem, just the stacktrace.
**Describe the solution you'd like**
Use the existing module to include messages.
> Inclusion of create target error description

- internal/cmd/commands/dev/dev.go
- internal/servers/controller/handlers/accounts/account_service.go
- internal/servers/controller/handlers/authmethods/authmethod_service.go
- internal/servers/controller/handlers/authtokens/authtoken_service.go
- internal/servers/controller/handlers/groups/group_service.go
- internal/servers/controller/handlers/host_catalogs/host_catalog_service.go
- internal/servers/controller/handlers/host_sets/host_set_service.go
- internal/servers/controller/handlers/hosts/host_service.go
- internal/servers/controller/handlers/roles/role_service.go
- internal/servers/controller/handlers/scopes/scope_service.go
- internal/servers/controller/handlers/sessions/session_service.go
- internal/servers/controller/handlers/targets/target_service.go
- internal/servers/controller/handlers/users/user_service.go
- internal/servers/controller/handlers/verifiers.go
- internal/servers/controller/handlers/verifiers_test.go
This tries to ensure ValidId arguments are passed in the right order
> Create a handlers.Id type for first ValidId parameter.

- internal/auth/oidc/provider.go
- internal/auth/oidc/provider_test.go
- internal/auth/oidc/service.go
- internal/auth/oidc/service_callback.go
- internal/auth/oidc/service_start_auth_test.go
- internal/auth/oidc/service_token_request.go
- internal/auth/oidc/testing.go
@talanknight  I think this should unblock you.  I believe, I got all the dependent bits from the PR #1003
> Ongoing OIDC: full qualify callback paths

- website/content/docs/configuration/controller.mdx
- website/content/docs/configuration/listener/tcp.mdx
> docs: clarify CORS configuration options

- internal/db/schema/migrations/postgres/1/02_domains.up.sql
- internal/db/schema/migrations/postgres/2/01_job.up.sql
- internal/db/schema/postgres_migration.gen.go
Adds `job` and `job_run` table to be used for job scheduling work
> Add job tables

- internal/servers/controller/handlers/scopes/scope_service.go
This fixes a double import in `internal/servers/controller/handlers/scopes`.
> fix scopes double import

- internal/credential/vault/client_certificate_test.go
- internal/credential/vault/credential_library.go
- internal/credential/vault/credential_library_test.go
- internal/credential/vault/query.go
- internal/credential/vault/store/vault.pb.go
- internal/credential/vault/testing.go
- internal/credential/vault/testing_test.go
- internal/credential/vault/vault_lease.go
- internal/credential/vault/vault_lease_test.go
- internal/credential/vault/vault_token.go
- internal/credential/vault/vault_token_test.go
- internal/proto/local/controller/storage/credential/vault/store/v1/vault.proto
Structs added:
* `vault.CredentialLibrary`
* `vault.Lease`
> Vault integration: add CredentialLibrary resources

- website/content/docs/api-clients/api.mdx
- website/content/docs/api-clients/cli.mdx
- website/content/docs/common-workflows/manage-users-groups.mdx
- website/content/docs/concepts/security/connections-tls.mdx
- website/content/docs/getting-started/connect-to-target.mdx
- website/content/docs/getting-started/installing/production.mdx
- website/content/docs/getting-started/run-and-login.mdx
- website/content/docs/installing/high-availability.mdx
- website/content/docs/installing/no-gen-resources.mdx
- website/content/docs/installing/systemd.mdx
Happy Tuesday, Boundary team! As I was going through the Boundary documentation, I noticed a few typos. Please let me know if you'd like anything else changed.
> Fix spelling errors found in the documentation

- internal/servers/controller/handlers/accounts/account_service.go
- internal/servers/controller/handlers/authmethods/authmethod_service.go
- internal/servers/controller/handlers/authtokens/authtoken_service.go
- internal/servers/controller/handlers/groups/group_service.go
- internal/servers/controller/handlers/host_catalogs/host_catalog_service.go
- internal/servers/controller/handlers/host_sets/host_set_service.go
- internal/servers/controller/handlers/hosts/host_service.go
- internal/servers/controller/handlers/mask_manager.go
- internal/servers/controller/handlers/roles/role_service.go
- internal/servers/controller/handlers/scopes/scope_service.go
- internal/servers/controller/handlers/sessions/session_service.go
- internal/servers/controller/handlers/targets/target_service.go
- internal/servers/controller/handlers/users/user_service.go
Reverts hashicorp/boundary#1070 - this PR upset the OIDC branches, will refactor this branch after they merge into main
> Revert "Refactor  internal/servers/controller/handlers errors"

- CHANGELOG.md
- api/accounts/changepassword.go
- api/accounts/setpassword.go
- api/authmethods/authenticate.go
- api/authmethods/changestate.go
- api/targets/custom.go
- internal/cmd/base/format.go
- internal/cmd/commands/targetscmd/funcs.go
> Fix panic in non-generated API calls when printing as JSON

- internal/servers/controller/handler.go
- internal/servers/controller/handlers/authmethods/authmethod_service.go
- internal/servers/controller/handlers/authmethods/oidc.go
- internal/servers/controller/handlers/option_test.go
- internal/servers/controller/handlers/options.go
- internal/servers/controller/handlers/subtypes.go
Some of this is in the form of logging, and some via returning error
messages to users.
Also cleans a couple of linter complaints.
> Add more OIDC error output.

- website/next.config.js
the config value wasn't being caught until moved to the callback
> website: move tip config obj to proper place

- go.mod
- go.sum
Updates to deps I'm responsible for. I've validated these.
> Update websocket, vault/sdk, and hclog deps

- .github/workflows/check-unlinked-content.js
- .github/workflows/check-unlinked-content.yml
- website/components/_temp-enable-hidden-pages/index.js
- website/data/docs-nav-data-hidden.json
- website/pages/docs/[[...page]].jsx
🔍 [Preview](https://boundary-git-fork-zchsh-zshandle-unlinked-content-hashicorp.vercel.app)
This PR fixes an issue where pages that were previously not included in `*-nav-data.json` files were not rendered.
This PR introduces a temporary fix to ensure these pages are rendered, but are not shown in the sidebar navigation, to match previous behaviour. [We plan to revisit this issue more intentionally in the near future](https://app.asana.com/0/1100423001970639/1200197752405255/f).
> Note: `common-workflows` content appears to have been [moved to Learn](https://learn.hashicorp.com/collections/boundary/basic-administration), so possible long-term resolution there is to remove the `.mdx` files from this repository.
- [/docs/common-workflows](https://boundary-git-fork-zchsh-zshandle-unlinked-con …
> website: resolve unlinked content, add check

- CHANGELOG.md
- internal/cmd/config/config.go
- internal/cmd/config/config_test.go
- website/content/docs/configuration/controller.mdx
- website/content/docs/configuration/worker.mdx
Addresses the request at https://discuss.hashicorp.com/t/controller-name-from-variable/23456
> Add ability for the controller/worker name to be read from env/file

- website/components/homepage-hero/HomepageHero.module.css
- website/package-lock.json
- website/package.json
- website/pages/home/index.jsx
- website/public/img/icon-right-arrow.svg
👀 [Preview](https://boundary-git-zsrm-hero-override-hashicorp.vercel.app)
This PR cleans up some minor CSS debt related to the `hero` component.
> patch: clean up css override marked as debt

- website/data/alert-banner.js
Adds info regarding upcoming HashiConf to website's `<AlertBanner />` 
[🔍 Preview](https://boundary-git-jmupdate-hashiconf-alert-banner-hashicorp.vercel.app/)
> Add HashiConf alert banner data

- CHANGELOG.md
- internal/ui/VERSION
This PR bumps the UI committish to latest and adds a changelog entry for OIDC inline authentication flow in admin UI.
> Bump UI version and add changelog entry

- CHANGELOG.md
- internal/ui/VERSION
Reverts hashicorp/boundary#1229
> Revert "Bump UI version and add changelog entry"

- internal/db/schema/migrations/postgres/10/01_sentinels.up.sql
- internal/db/schema/postgres_migration.gen.go
> Sentinel values only have to be greater than 0

- website/content/docs/installing/no-gen-resources.mdx
:memo:  Fix typo in docs/installing/no-gen-resources
> Fix typo in docs/installing/no-gen-resources 

- ci/goinstall.sh
- packages-oss.yml
Go 1.16.5 includes some security updates so it'd be good to keep up.
> Update to Go 1.16.5

- website/data/alert-banner.js
---
Updates the alert banner data for HashiConf europe going live.
> chore: updates alert-banner — hashiconf 

- website/package-lock.json
- website/package.json
Bump `@apidevtools/json-schema-ref-parser` dependency version.
> Bump website @apidevtools/json-schema-ref-parser dependency version

- internal/credential/vault/private_credential.go
- internal/credential/vault/private_library.go
- internal/credential/vault/repository_credentials.go
Adds new privateCredential struct to allow queries against credential_vault_credential_private view
> Add private credential

- internal/db/timestamp/timestamp.go
- internal/scheduler/additional_verification_test.go
- internal/scheduler/job.go
- internal/scheduler/job/additional_verification_test.go
- internal/scheduler/job/query.go
- internal/scheduler/job/repository_job.go
- internal/scheduler/job/repository_job_test.go
- internal/scheduler/job/repository_run_test.go
- internal/scheduler/job/testing_test.go
- internal/scheduler/options.go
- internal/scheduler/scheduler.go
- internal/scheduler/scheduler_test.go
- internal/scheduler/testing.go
- internal/servers/controller/controller.go
Merges a number of changes from the long live mgaffney-vault branch into main.  These are changes to the scheduler interface and repo functions that are needed for other work such as ICU-1259
> Scheduler updates

- internal/servers/controller/handlers/authmethods/authmethod_service_test.go
This fixes a source of test flakiness.
> account_claim_maps are ordered for tests

- website/data/version.js
Update `stable-website` once this is merged to `main`
> Update website pointer to desktop client to version 1.1.0

- website/content/docs/concepts/domain-model/managed-groups.mdx
**Description**
Fixes broken links on [Managed Groups](https://www.boundaryproject.io/docs/concepts/domain-model/managed-groups) page
Requested review scope:
> fixed roles and accounts link references

- internal/credential/vault/testing.go
- internal/credential/vault/testing_test.go
This PR would also [help cleanup one of the tests](https://github.com/hashicorp/boundary/pull/1331/files?file-filters%5B%5D=.go#diff-f3d69b2f4dd5a826401c6992cc8f273ec6806f3811778d5eff8bff3f993e5a72R341-R356) in #1331.
> Add ability to set the token period in the vault test harness

- internal/credential/vault/repository_credential_store.go
Updates update cred store unique error to correct distinguish between token and store unique violation
> Update unique error

- internal/ui/VERSION
This PR introduces the callback URL field to the OIDC form in admin UI.  PR:  hashicorp/boundary-ui#625
> chore: bump UI version

- CHANGELOG.md
- go.mod
- go.sum
> Update shared-secure-libs for kms block fix

- website/content/docs/installing/postgres.mdx
> Document dependency on pgcrypto

- website/content/docs/configuration/controller.mdx
> Update docs for minimum value of max_open_connections

- internal/session/query.go
This simplifies the query in PR #1400
> Simplify SQL query for CloseConnectionsForDeadWorkers

- website/content/docs/common-workflows/manage-targets.mdx
Fixed typo (equivalient -> equivalent)
> Fixed typo on website (equivalient -> equivalent)

- internal/servers/worker/controller_connection.go
> Update createClientConn Op 

- go.mod
- go.sum
- sdk/go.mod
- sdk/go.sum
- website/content/docs/configuration/kms/awskms.mdx
This updates to the latest go-kms-wrapping tag to support these
parameters and documents them.
> Add support for additional awskms parameters

- internal/servers/worker/handler.go
When a session is terminated by the user, the cancel session path is
triggered, in this path the websocket connection is closed, however, If the
connection is already closed, an EOF is returned. In this situation an
EOF is expected and should not be logged to the user.
Example log line:
```
{
"id": "ezqk6w9dOQ",
"source": "https://hashicorp.com/boundary/dev-controller/boundary-dev",
"specversion": "1.0",
"type": "error",
"data": {
"error": "failed to close WebSocket: failed to read frame header: EOF",
"error_fields": {},
"id": "e_n60YPsDkaj",
"version": "v0.1",
"op": "worker.(Worker).handleProxy",
"info": {
"msg": "error closing client connection"
}
},
"datacontentype": "text/plain",
"time": "2021-09-02T10:05:46.587513-07:00"
}
```
> fix(connect): Remove erroneous event error message

- go.mod
- go.sum
> Update various dependencies

- internal/scheduler/additional_verification_test.go
If a new job is started as the test successfully compeltes and begins
the scheduler shutdown process.  The new job will deadlock waiting on
channel reads.
> tests(scheduler): fix unit test deadlock

- internal/ui/VERSION
Bumps the UI commit to latest.
> chore: bump UI commit

- website/pages/home/index.jsx
> website: fix wording

- website/pages/home/index.jsx
Fixes broken link on Home Page
> Fix broken `/downloads` link url

- internal/libs/endpoint/preferencer.go
- internal/libs/endpoint/preferencer_test.go
Rather than pick addresses totally at random, this changes the
preference to be private IP > public IP > DNS. (Ordering is not
guaranteed, but in many cases there will only be one of each type of IP
anyways.)
This seems likely to match the common case where you're getting into a
machine on the private side from the public side. It's harder to know if
DNS is private or not, so IPs are preferred in this case.
> Update preferred endpoint preference order

- internal/servers/controller/handlers/targets/target_service_test.go
This test started failing when the order of the list response changed.
Since the order does not matter, this test was updated to not depend on
the order.
> test(targets): Change test to not depend on response order

- internal/host/plugin/host_catalog.go
No tests, but it unblocks #1634 and fixes tests there.
> populate correct field for host catalog secret

- internal/db/schema/internal/postgres/lock_test.go
- internal/db/schema/internal/postgres/testing_test.go
Add checks for a few errors and cancel a few contexts.
> fix (db): Clean up tests a bit

- Makefile
- internal/gen/controller/servers/services/session_service.pb.go
- internal/observability/event/cloudevents_formatter_node.go
- internal/observability/event/cloudevents_formatter_node_test.go
- internal/observability/event/hclog_formatter_node.go
- internal/observability/event/hclog_formatter_node_test.go
- internal/proto/local/controller/api/resources/targets/v1/target.proto
- internal/proto/local/controller/servers/services/v1/session_service.proto
- internal/servers/controller/interceptor.go
- internal/servers/controller/interceptor_test.go
- internal/servers/controller/listeners.go
- sdk/pbs/controller/api/resources/targets/target.pb.go
- feature (audit events): Add interceptor for auditing worker requests
- feature (events): Add default deny filter for worker status events
- feature (worker audit events): Add tags to SessionService req/resp
> feature (workers): Add audit events for worker requests

- internal/db/option_test.go
- internal/db/read_writer.go
- internal/db/read_writer_ext_test.go
- internal/db/read_writer_test.go
-- feature (db): Add more opts when using Create + WithOnConflict 
-- refactor (db): Migrate Update(...) to use whereClausesFromOpts(...)
-- tests (db): Add missing assert for WithDebug unit tests
> Add more opts when using Create + WithOnConflict

- internal/credential/credential.go
- internal/credential/vault/private_library.go
- internal/credential/vault/private_library_test.go
- internal/credential/vault/repository_credentials.go
- internal/credential/vault/repository_credentials_test.go
- internal/db/schema/migrations/oss/postgres/19/05_vault_private_library.up.sql
- internal/db/sqltest/initdb.d/03_widgets_persona.sql
- internal/db/sqltest/tests/credential/vault/credential_vault_library_user_password_mapping_override.sql
- internal/errors/code.go
- internal/errors/code_test.go
- internal/errors/info.go
This change uses the credential type attribute when issuing credentials
including mapping overrides.
> feat(credential): Use credential type when issuing credentials

- website/content/docs/releases/release-notes/v0_7_0.mdx
- website/data/docs-nav-data.json
> Adding release notes for 0.7

- internal/host/plugin/repository_host_set.go
- internal/servers/controller/handlers/host_sets/host_set_service.go
- internal/servers/controller/handlers/host_sets/host_set_service_test.go
- testing/controller/controller.go
This is the analogue of #1743 but for host sets
> Fix setting nil attributes on host sets

- CHANGELOG.md
> Update CHANGELOG.md for #1736

- internal/cmd/commands/credentiallibrariescmd/funcs.go
Sample output from default list:
```
boundary credential-libraries list -credential-store-id csvlt_n6Nm05R7UG -addr  "http://127.0.0.1:37453"
Credential Library information:
ID:                    clvlt_gawxacA7vH
Version:             1
Type:                vault
no-op
read
update
delete
ID:                    clvlt_z87RiGoUnQ
Version:             1
Type:                vault
Credential Type:     user_password
no-op
read
update
delete
```
Sample output from json format, to show data included:
```
boundary credential-libraries list -credential-store-id csvlt_n6Nm05R7UG -addr  "http://127.0.0.1:37453" -format json | jq .
{
"status_code": 200,
"items": [
{
"id": "clvlt_gawxacA7vH",
"credential_store_id": "csvlt_n6Nm05R7UG",
"scope": {
"id": …
```
> feat(cli): Display credential type in library list

- website/next.config.js
- website/package-lock.json
- website/package.json
- website/pages/docs/[[...page]].jsx
https://boundary-git-kevin-versioned-docs-hashicorp.vercel.app/
> feat(website): versioned-docs

- internal/ui/VERSION
> Bump UI version

- website/redirects.js
[https://boundary-48hvaxan2-hashicorp.vercel.app/home](https://boundary-48hvaxan2-hashicorp.vercel.app/home)
> fix: redirect website `/home` to `/`

- CHANGELOG.md
- internal/servers/controller/handlers/targets/tcp/target_service_test.go
Additionally, I added dns names on the hosts used in the target_service's authorize session test.
> Add recent fixes to changelog

- CHANGELOG.md
- internal/ui/VERSION
Update changelog with latest changes in the UI.
> Update changelog with latest changes in the UI

- .github/workflows/build.yml
- .release/ci.hcl
This has been abstracted into the github action `actions-docker-build`: https://github.com/hashicorp/actions-docker-build/pull/8. 
Link to pipeline that ran for the first commit to this branch: https://github.com/hashicorp/boundary/actions/runs/1862865741
> Remove setup-qemu step from Docker build job

- .release/ci.hcl
https://docs.google.com/document/d/1dUjhfqccvDnfnKkSPxjTu19zn9v4jSMT4_Lfh0mQ1yQ/edit?usp=sharing
> Do not merge - Adding promotion and post-publish events.

- website/content/docs/concepts/domain-model/session-connections.mdx
- website/content/docs/concepts/domain-model/sessions.mdx
- website/data/docs-nav-data.json
Update Boundary's website to include a page on Session Connections.
Update the Sessions page to refer to Session Connections.
> docs(connections): Update domain model for session connections

- internal/servers/worker/status.go
When a worker has failed to send status to the controller for longer then
the grace period, it closes all of its connections. It would then try to send
this updated state to the controller.
This removes that finally update of the connection state, while still
closing the underlying network connections, since it is not likely
that the controller will receive the request, and the state of these
connections will eventually be corrected via controller cleanup
logic, or if the controller is able to resume communication with the
worker.
> feat(worker): Only close network connections on grace period expiration

- website/data/version.js
Bump desktop client version for website docs.
> Bump desktop client version for website docs

- Makefile
Only finding generated files when we need to.
> Speed up all make targets

- go.mod
- go.sum
- internal/gen/controller.swagger.json
- internal/gen/controller/api/services/account_service.pb.gw.go
- internal/gen/controller/api/services/auth_method_service.pb.gw.go
- internal/gen/controller/api/services/authtokens_service.pb.gw.go
- internal/gen/controller/api/services/credential_library_service.pb.gw.go
- internal/gen/controller/api/services/credential_store_service.pb.gw.go
- internal/gen/controller/api/services/group_service.pb.gw.go
- internal/gen/controller/api/services/host_catalog_service.pb.gw.go
- internal/gen/controller/api/services/host_service.pb.gw.go
- internal/gen/controller/api/services/host_set_service.pb.gw.go
- internal/gen/controller/api/services/managed_group_service.pb.gw.go
- internal/gen/controller/api/services/role_service.pb.gw.go
- internal/gen/controller/api/services/scope_service.pb.gw.go
- internal/gen/controller/api/services/session_service.pb.gw.go
- internal/gen/controller/api/services/target_service.pb.gw.go
- internal/gen/controller/api/services/user_service.pb.gw.go
- internal/gen/testing/event/event.pb.gw.go
- internal/gen/testing/event/testing.swagger.json
This new version will let us hide fields from the OpenAPI output
> Upgrade grpc-gateway version to v2.10.0

- internal/cmd/commands/server/worker_shutdown_reload_test.go
- internal/cmd/ops/server_test.go
- internal/servers/controller/handler_test.go
- internal/servers/controller/testing.go
- internal/servers/worker/proxy/tcp/tcp_test.go
- internal/servers/worker/proxy/testing_test.go
It is documented as illegal to use `t.FailNow` in a goroutine: https://pkg.go.dev/testing#T.FailNow. Uses of `require` assertions call `t.FailNow`. This may have led to inconsistent test results as some assertions were subject to undefined behavior.
This changes all instances of `require` in all the goroutine literals I could find, but I may have missed some. Also note that it _is_ allowed to call `assert` assertions in goroutines.
This was discovered because there was an unexpected error in https://github.com/hashicorp/boundary/pull/1973 ([see attached](https://github.com/hashicorp/boundary/files/8431406/1972.txt)):
```
=== RUN   Test_statusCodeInterceptor/hello
--- PASS: Test_statusCodeInterceptor (0.00s)
--- PASS: Test_statusCodeInterceptor/nil-nil (0.00s)
--- PASS: …
```
> fix(test): Remove uses of t.FailNow in goroutines

- .release/ci.hcl
Remove the quality test event since it doesn't really do anything.
Relevant slack conversation:
https://hashicorp.slack.com/archives/C01BWLSMJ03/p1649446474370929
> Remove quality-tests event

- Makefile
- internal/gen/controller/api/services/authtokens_service.pb.go
- internal/proto/controller/api/resources/authtokens/v1/authtoken.proto
- internal/proto/controller/api/resources/scopes/v1/scope.proto
- internal/proto/controller/api/services/v1/authtokens_service.proto
- internal/tests/api/authtokens/classification_test.go
- sdk/pbs/controller/api/resources/authtokens/authtoken.pb.go
- sdk/pbs/controller/api/resources/scopes/scope.pb.go
For https://hashicorp.atlassian.net/browse/ICU-3915
> Add classification to all authtoken fields

- internal/proto/controller/api/resources/authmethods/v1/auth_method.proto
- internal/proto/controller/api/resources/hostcatalogs/v1/host_catalog.proto
- internal/tests/api/authmethods/classification_test.go
- internal/tests/api/hostcatalogs/classification_test.go
- sdk/pbs/controller/api/resources/authmethods/auth_method.pb.go
- sdk/pbs/controller/api/resources/authmethods/auth_method_taggable.go
- sdk/pbs/controller/api/resources/hostcatalogs/host_catalog.pb.go
- sdk/pbs/controller/api/resources/hostcatalogs/host_catalog_taggable.go
Adds taggable for hostcatalog and authmethod.
> Implement taggable for authorized collection actions

- internal/db/read_writer_test.go
- internal/gen/controller/api/services/authtokens_service.pb.go
- internal/gen/controller/api/services/host_set_service.pb.go
- internal/proto/controller/api/resources/authtokens/v1/authtoken.proto
- internal/proto/controller/api/resources/hostcatalogs/v1/host_catalog.proto
- internal/proto/controller/api/resources/scopes/v1/scope.proto
- internal/proto/controller/api/services/v1/authtokens_service.proto
- internal/proto/controller/api/services/v1/host_set_service.proto
- internal/tests/api/authmethods/authenticate_test.go
- internal/tests/api/authmethods/service_classification_test.go
- sdk/pbs/controller/api/resources/authtokens/authtoken.pb.go
- sdk/pbs/controller/api/resources/hostcatalogs/host_catalog.pb.go
- sdk/pbs/controller/api/resources/scopes/scope.pb.go
Some fields were classified when the classification has no effect
> Correct some classification errors

- internal/gen/controller/api/services/auth_method_service.pb.go
- internal/proto/controller/api/resources/authmethods/v1/auth_method.proto
- internal/proto/controller/api/services/v1/auth_method_service.proto
- internal/tests/api/authmethods/authmethod_test.go
- internal/tests/api/authmethods/classification_test.go
- internal/tests/api/authmethods/service_classification_test.go
- sdk/pbs/controller/api/resources/authmethods/auth_method.pb.go
For https://hashicorp.atlassian.net/browse/ICU-3811
> Add classification to all authmethod fields

- internal/auth/oidc/repository_auth_method_operational_state_test.go
- internal/servers/controller/common/scopeids/scope_ids.go
- internal/servers/controller/handlers/targets/target_service.go
- internal/session/repository_session.go
- internal/target/options.go
- internal/target/query.go
- internal/target/repository.go
- internal/target/target.go
This uses the prefetch method to fetch resource IDs and validate them
for authz by the user before then fetching the full list of targets.
> Update targets to new listing method

- internal/ui/VERSION
Update the UI version to consume the nre renamed UI artifacts. Just affects enterprise
> Update UI version to consume the new renamed UI artifacts

- internal/daemon/cluster/handlers/multihop_service.go
- internal/daemon/cluster/handlers/worker_service.go
- internal/daemon/cluster/handlers/worker_service_status_test.go
- internal/daemon/cluster/handlers/worker_service_test.go
- internal/daemon/controller/handlers/targets/tcp/target_service_test.go
- internal/daemon/controller/listeners.go
- internal/daemon/worker/listeners.go
- internal/daemon/worker/worker_proxy_service.go
Move cluster and worker handlers to prepare for worker service handler
> refact(api): move worker handlers

- internal/servers/repository_workerauth_test.go
The signature for registration.AuthorizeNode(...) changed
> chore (servers): update nodeenrollment dep

- internal/servers/repository_workerauth.go
- internal/servers/repository_workerauth_test.go
refactor to export StoreNodeInformationTx(...) which can be used
by other repositories within their transactions to store
node information.
> refactor (servers/workerauth): add StoreNodeInformationTx(...)

- internal/errors/error.go
- internal/errors/option.go
- internal/errors/option_test.go
- internal/servers/options.go
- internal/servers/repository_worker.go
> feature (worker): add WithFetchNodeCredentialsRequest to CreateWorker

- internal/servers/repository_worker.go
- internal/servers/repository_worker_test.go
Added unit tests for CreateWorker(...) when called with
optional WithFetchNodeCredentialsRequest(...)
> tests (servers): additional CreateWorker(...) unit tests

- go.mod
- go.sum
- internal/cmd/commands/dev/dev.go
- internal/cmd/commands/server/server.go
- internal/daemon/worker/listeners.go
- internal/daemon/worker/testing.go
- internal/daemon/worker/worker.go
- internal/daemon/worker/worker_test.go
- internal/servers/repository_worker_test.go
Tests are TODO but throwing this up for review while Jim's around :-D
> Use persistent storage for worker auth credentials

- internal/db/db.go
- internal/db/db_test.go
> Server refuses to start if max_open_connections is below 5

- go.mod
- go.sum
- internal/daemon/worker/controller_connection.go
- internal/daemon/worker/status.go
This PR also updates the nodeenrollment dependency
> feature (worker): add worker events around authentication 

- internal/daemon/worker/controller_connection.go
- internal/daemon/worker/status.go
Addresses comments in https://github.com/hashicorp/boundary/pull/2163
> fix context for worker upstreams

- Makefile
- internal/gen/controller/servers/services/server_coordination_service.pb.go
- internal/proto/controller/servers/services/v1/server_coordination_service.proto
- internal/proto/controller/servers/v1/servers.proto
- internal/servers/servers.pb.go
Classifying the data allows it to appropriately included in
audit events
> feature (byow): classify status msg data

- internal/daemon/controller/handlers/workers/worker_service.go
- internal/daemon/controller/handlers/workers/worker_service_test.go
This updates (for both types of workers) and fixes Get and List.
> Start updates on worker service test

- internal/daemon/controller/handlers/accounts/account_service.go
- internal/daemon/controller/handlers/accounts/validate_test.go
- internal/daemon/controller/handlers/authmethods/oidc.go
- internal/daemon/controller/handlers/authmethods/password.go
- internal/daemon/controller/handlers/authmethods/password_test.go
- internal/daemon/controller/handlers/hosts/host_service.go
- internal/daemon/controller/handlers/hosts/host_service_test.go
- internal/daemon/controller/handlers/managed_groups/managed_group_service.go
Check for nil attributes to prevent panics
> fix (API): check attributes missing appropriately.

- website/content/docs/concepts/service-discovery.mdx
- website/content/docs/getting-started/index.mdx
- website/data/docs-nav-data.json
[Deploy Preview](https://boundary-icioe0ajj-hashicorp.vercel.app/docs)
This PR:
- changes broken docs/common-workflows link to boundary Learn homepage
- directs outstanding getting started links to new HCP collection
> updates learn links

- .github/workflows/build.yml
Generate the metadata file for the rest of the CRT post-build workflow
Signed-off-by: Ryan Cragun <me@ryan.ec>
> build: generate the metadata file

- .github/workflows/build.yml
Signed-off-by: Ryan Cragun <me@ryan.ec>
> build: depend on the right output for metadata

- internal/cmd/commands/connect/ssh.go
Re ICU-5507
This will only attempt to consume ssh credentials for `tcp` type targets. Did a quick validation
On a non tcp target:
```
boundary connect ssh -target-id tssh_JXR3VH8YTI
Credentials:
Credential Source ID:   credspk_aXV3RkPLa9
Credential Source Name: My-spk-cred
Credential Store ID:    csst_f7416lG5NX
Credential Store Type:  static
Credential Type:        ssh_private_key
Secret:
private_key:   <REDACTED>
username:      louis
Credential Source ID:   credup_dggE0VKmyb
Credential Source Name: My-up-cred
Credential Store ID:    csst_f7416lG5NX
Credential Store Type:  static
Credential Type:        username_password
Secret:
password:   pass
username:   louis
```
On a tcp target with same brokered credentials:
```
boundary connect ssh -target-id ttcp_bmZ4SlXtFc
Credentials: …
```
> Only consume ssh brokered credentials if the target is tcp

- CHANGELOG.md
- go.mod
- go.sum
- internal/cmd/base/base.go
- internal/cmd/commands/accountscmd/funcs.go
- internal/cmd/commands/accountscmd/password_funcs.go
- internal/cmd/commands/authenticate/password.go
- internal/cmd/commands/credentialscmd/ssh-private-key_funcs.go
- internal/cmd/commands/credentialscmd/username-password_funcs.go
> Change behavior of `-token` and `-password` to support env/file only

- enos/enos.hcl
- enos/modules/alb_boundary/locals.tf
- enos/modules/alb_boundary/main.tf
- enos/modules/alb_boundary/variables.tf
- enos/modules/aws_nomad/outputs.tf
This change adds a module that can add an ALB to a VPC for use with communicating with Boundary over the internet.
> Add Boundary ALB module

- enos/.gitignore
- enos/modules/alb_boundary/main.tf
* Fix .gitignore to standard for Enos and TF
> Remove static names from module

- internal/perms/acl.go
- internal/perms/acl_test.go
These changes are a building block to enable us to improve Boundary resource listing performance.
> feat(perms): Derive permissions list from user grants

- internal/daemon/controller/auth/auth.go
These changes are a building block to enable us to improve Boundary resource listing performance.
> feat(auth): Get all authorised scope info for a given list request

- enos/modules/alb_boundary/variables.tf
- enos/modules/nomad_job/configs/controller.nomad
This PR is for cosmetic changes. The ALB module had an unused variable and the Nomad job file had extra newlines.
> Remove unused variable

- CHANGELOG.md
- internal/db/schema/migrations/oss/postgres/40/01_credential.up.sql
- internal/db/schema/migrations/oss/postgres_40_01_test.go
- internal/session/testing.go
> bug(db): Fix credential purpose migration

- CHANGELOG.md
- internal/ui/VERSION
> chore: Bump UI commitsh and update changelog

- website/content/docs/release-notes/v0_10_0.mdx
- website/data/docs-nav-data.json
This PR proposes the addition of the 0.10.0 release notes to the Boundary Docs page
> 0.10 release notes

- .github/workflows/enos-run.yml
- enos/enos.hcl
- enos/modules/bats_deps/main.tf
- enos/modules/binary_finder/main.tf
- enos/modules/build_local/main.tf
- enos/modules/test_cli_ui/tests.tf
- enos/modules/test_smoke/main.tf
Signed-off-by: Jaymala Sinha <jaymala@hashicorp.com>
> Update Enos run

- .github/workflows/build.yml
Didn't notice this until it failed on main 🤦🏻
> fix: Use correct yaml

- internal/cmd/base/flags.go
- internal/cmd/common/flags_test.go
This allows a check function to be set to determine whether it is
allowed to be set. This also ensures that if null is allowed it is
either the only value or not set.
> Ensure that "null" can only be specified in "set-" commands

- website/content/docs/configuration/worker/pki-worker.mdx
Added documentation for PKI workers around the use of encrypted cred storage
> docs(workers): add documentation for pki worker cred encryption

- api/scopes/custom.go
- internal/cmd/base/base.go
- internal/cmd/commands.go
- internal/cmd/commands/scopescmd/rotate_keys.go
- internal/tests/cli/boundary/_scopes.bash
- internal/tests/cli/boundary/scopes.bats
Add key rotation CLI command with optional rewrap
> Add Rotate Keys CLI Command

- internal/auth/password/argon2_test.go
- internal/authtoken/authtoken_test.go
- internal/db/schema/migrations/oss/postgres/48/01_add_data_key_foreign_key_references.up.sql
- internal/db/schema/migrations/oss/postgres_40_01_test.go
- internal/db/sqltest/initdb.d/01_colors_persona.sql
- internal/db/sqltest/initdb.d/03_widgets_persona.sql
- internal/session/repository_session_test.go
- internal/session/session.go
The follow tables had foreign key relationships added to `kms_data_key_version (private_id)`
- auth_token
- auth_password_argon2_cred
- session
> Add Missing DEK Foreign Keys

- internal/credential/vault/credential_store.go
- internal/credential/vault/private_credential.go
- internal/credential/vault/private_library.go
- internal/credential/vault/private_store.go
- internal/credential/vault/repository_credential_store_test.go
- internal/credential/vault/testing.go
- internal/credential/vault/testing_test.go
- internal/credential/vault/vault.go
- internal/credential/vault/vault_test.go
- internal/daemon/controller/controller.go
- internal/server/repository_workerauth.go
Note: Worker filter tests have been moved to ENT
> Vault proxy supporting code

- internal/cmd/base/initial_resources.go
- internal/daemon/controller/common/common.go
- internal/daemon/controller/controller.go
- internal/daemon/controller/handlers/targets/target_service.go
- internal/daemon/controller/handlers/targets/tcp/target_service_test.go
- internal/session/repository_session_test.go
- internal/session/service_authorize_connection_test.go
- internal/session/service_close_connections_test.go
- internal/session/testing.go
- internal/target/options.go
- internal/target/options_test.go
- internal/target/repository.go
- internal/target/repository_credential_source_test.go
- internal/target/repository_test.go
- internal/target/tcp/immutable_fields_test.go
- internal/target/tcp/repository_credential_source_test.go
- internal/target/tcp/repository_host_source_test.go
- internal/target/tcp/repository_tcp_target_test.go
- internal/target/tcp/repository_test.go
- internal/target/tcp/testing_test.go
This PR is the `Targets` counterpart of https://github.com/hashicorp/boundary/pull/2381 and contains a set of commits designed to improve Boundary's performance when listing Target resources.
> Target List request performance optimisation

- website/redirects.js
Added documentation links for workers
> chore: Add redirect docs for worker

- CHANGELOG.md
Add items for SIGHUP database reload and performance improvements.
> chore: Add missing items to changelog

- website/Makefile
- website/content/docs/getting-started/deploy-and-login.mdx
- website/content/docs/release-notes/v0_8_0.mdx
- website/content/docs/what-is-boundary.mdx
- website/data/docs-nav-data.json
- website/scripts/website-build.sh
- website/scripts/website-start.sh
This backports #2426 into `stable-website`
> Backport (#2426) into `stable-website`

- website/content/docs/api-clients/api.mdx
- website/content/docs/concepts/filtering/events.mdx
- website/content/docs/configuration/events/common.mdx
- website/content/docs/configuration/kms/aead.mdx
- website/content/docs/configuration/worker/index.mdx
This PR is to cherry-pick the commits made by: 
- [PR2449](https://github.com/hashicorp/boundary/pull/2449)
- [PR2460](https://github.com/hashicorp/boundary/pull/2460)
> Backport: PR 2449 and PR 2460

- website/content/docs/api-clients/api.mdx
- website/content/docs/concepts/filtering/events.mdx
- website/content/docs/configuration/events/common.mdx
- website/content/docs/configuration/kms/aead.mdx
- website/content/docs/configuration/worker/index.mdx
This PR is to cherry-pick the commits made by: 
- [PR2449](https://github.com/hashicorp/boundary/pull/2449)
- [PR2460](https://github.com/hashicorp/boundary/pull/2460)
-
> Manual cherry-pick: PR 2449 and PR 2460

- website/redirects.js
This link is for the AWS host catalog region
> add aws region website redirect

- enos/enos-scenario-e2e-target.hcl
- enos/enos-variables.hcl
- enos/enos.hcl
Signed-off-by: Jaymala Sinha <jaymala@hashicorp.com>
> Add infrastructure tags to Enos scenarios

- go.mod
- go.sum
- internal/daemon/worker/auth_rotation.go
This was previously approved elsewhere.
> Adapt to new nodeenrollment X25519KeyProducer interface

- internal/auth/oidc/account.go
- internal/auth/password/account.go
- internal/auth/password/authmethod.go
- internal/auth/password/options.go
- internal/auth/password/options_test.go
- internal/auth/password/repository.go
- internal/auth/password/repository_account.go
- internal/auth/password/repository_account_test.go
- internal/auth/password/repository_authmethod.go
- internal/auth/subtype.go
- internal/authtoken/options.go
- internal/authtoken/options_test.go
- internal/authtoken/testing.go
- internal/daemon/controller/common/common.go
- internal/daemon/controller/handlers/targets/registry.go
- internal/iam/resource.go
This is a precursor to another upcoming PR that will make use of these changes, but it makes that PR more manageable.
> Add some common account bits and some getOpts -> GetOpts changes

- internal/auth/oidc/account.go
- internal/auth/password/account.go
- internal/auth/password/authmethod.go
- internal/auth/password/options.go
- internal/auth/password/options_test.go
- internal/auth/password/repository.go
- internal/auth/password/repository_account.go
- internal/auth/password/repository_account_test.go
- internal/auth/password/repository_authmethod.go
- internal/auth/subtype.go
- internal/authtoken/options.go
- internal/authtoken/options_test.go
- internal/authtoken/testing.go
- internal/daemon/controller/common/common.go
- internal/daemon/controller/handlers/targets/registry.go
- internal/iam/resource.go
Cherry-pick to main of PR that landed in 0.11 release branch.
> Add some common account bits and some getOpts -> GetOpts changes (#2565)

- internal/db/read_writer.go
This is a cherry-pick from the release branch
> Silence events from DB errors (#2601)

- CHANGELOG.md
- website/content/docs/concepts/security/data-encryption.mdx
This adds a note to the changelog about the new functionality, referring to the docs page. The docs changes give a simple run through of the usage and meaning of each command.
> Add KMS rotation/destruction feature to the changelog and docs

- CHANGELOG.md
- globals/kms.go
- go.mod
- go.sum
- internal/cmd/base/server_test.go
- internal/cmd/base/servers.go
- internal/cmd/commands/server/listener_reload_test.go
- website/content/docs/concepts/security/data-encryption.mdx
- website/content/docs/configuration/kms/aead.mdx
- website/content/docs/configuration/kms/alicloudkms.mdx
- website/content/docs/configuration/kms/awskms.mdx
- website/content/docs/configuration/kms/azurekeyvault.mdx
- website/content/docs/configuration/kms/gcpckms.mdx
- website/content/docs/configuration/kms/ocikms.mdx
- website/content/docs/configuration/kms/transit.mdx
> Create new "previous-root" key purpose for root key migrations (#2639)

- version/feature_manager.go
- version/feature_manager_test.go
- version/testing.go
Partner PR to https://github.com/hashicorp/boundary-enterprise/pull/171
> Add feature manager

- version/feature_manager_test.go
Resolves error seen here around a concurrent map read and map write:
https://app.circleci.com/pipelines/github/hashicorp/boundary/12993/workflows/044e0bad-ec6e-47ea-8f73-4fb3644ad6d4/jobs/156400
> Remove version tests running in parallel

- internal/daemon/controller/internal/metric/cluster.go
- internal/daemon/controller/listeners.go
- internal/daemon/metric/initialize_metrics.go
- internal/daemon/metric/instrument_handlers.go
- internal/daemon/metric/instrument_handlers_test.go
- internal/daemon/worker/internal/metric/cluster_server.go
- internal/daemon/worker/listeners.go
attempt 4 of merging https://github.com/hashicorp/boundary/pull/2593 correctly
>  feat(metric): adds accepted/closed connections counters for controller and worker cluster connections

- website/content/docs/concepts/domain-model/credential-libraries.mdx
Adds information about the Vault credential parameter templating function being added to Boundary in v 0.11.1.
~~[View the preview environment here.](https://boundary-8yzjtehvr-hashicorp.vercel.app/boundary/docs/concepts/domain-model/credential-libraries#vault-credential-library-parameter-templating)~~
[View the new preview here.](https://boundary-55mew97ph-hashicorp.vercel.app/boundary/docs/concepts/domain-model/credential-libraries#vault-credential-library-parameter-templating)
> Document vault credential library templating

- internal/daemon/controller/controller.go
- internal/daemon/worker/worker.go
- internal/server/options.go
- internal/server/options_test.go
- internal/server/root_info.go
Partner PR to https://github.com/hashicorp/boundary-enterprise/pull/166
> add worker version to network graph

- website/Makefile
- website/scripts/should-build.sh
Updates managed website-related files.
- `website/Makefile`
- `website/scripts/should-build.sh`
- `website/scripts/website-build.sh`
- `website/scripts/website-start.sh`
> **Note**
>
> This pull request was opened via the Digital team's automation. If you have questions, please tag @hashicorp/web-platform
> chore: Update Digital Team Files

- testing/internal/e2e/tests/static/key_destruction_test.go
This PR updates the test names for the key destruction tests to match the current convention as well as adds some logging to help with debugging and clarity that something is happening when running locally.
> test(e2e): Minor clerical updates to key destruction tests

- sdk/plugins/host/plugin.go
Cherry-pick of 69ee55053d33ee20c16eed52b3baae8a5e9e3ddd
> Add SIGHUP ignoring to sdk/plugin (#2677)

- website/content/docs/configuration/kms/gcpckms.mdx
Updates our KMS docs for GCP with relevant env var's for configuration parameters.
> docs: update GCP KMS docs with environment variable usage

- internal/daemon/worker/status.go
Partner PR to https://github.com/hashicorp/boundary-enterprise/pull/189
> Move dialingListener setAddresses

- internal/daemon/worker/status.go
> revert 2712

- internal/db/read_writer.go
- internal/db/read_writer_test.go
We were not capturing the errors which happen on commit.  We've changed to a multierror so we should get the commit error and any subsequent rollback errors in the same txn.
> fix (db): Improve error handling for commit errors.

- internal/daemon/metric/instrument_handlers.go
Ensuring change as part of this merge is in OSS: https://github.com/hashicorp/boundary-enterprise/commit/444e861cc3a250feeb1d25b96962f26b83a0215f
> Expose State() *structpb.Struct interface through the metric connecti… …on trackers

- .github/milestone-check.json
- .github/workflows/milestone-checker.yml
Stolen from https://github.com/hashicorp/vault/pull/18406
> Add check to ensure milestone

- internal/cmd/common/flags_test.go
Fixes test failures like: https://app.circleci.com/pipelines/github/hashicorp/boundary/13707/workflows/aa5befbf-761d-412e-9472-ee4e7473fe7e/jobs/162211
> Fix failing attribute flag test

- .github/workflows/milestone-checker.yml
This reverts commit a283e8be5e8edfa843a7dfc838d4294644841d78.
> Revert "fix milestone check"

- internal/cmd/commands/server/worker_shutdown_reload_test.go
- internal/daemon/controller/handler.go
- internal/daemon/controller/handlers/targets/target_service.go
- internal/daemon/controller/handlers/targets/target_service_test.go
- internal/daemon/controller/handlers/targets/tcp/target_service_test.go
- internal/daemon/controller/handlers/targets/testing.go
- internal/tests/api/credentials/credentials_test.go
- internal/tests/cluster/session_cleanup_test.go
- internal/tests/cluster/worker_bytesupdown_test.go
- internal/tests/cluster/worker_proxy_test.go
- internal/tests/cluster/x509_verification_test.go
Partner PR for https://github.com/hashicorp/boundary-enterprise/pull/198
> In absence of ingress filter, use directly connected worker

- internal/server/options.go
- internal/server/options_test.go
Supports https://github.com/hashicorp/boundary-enterprise/pull/198
> Add options for directly connected worker

- internal/db/schema/migrations/oss/postgres/60/01_credential_vault_ssh_cert_library.up.sql
- internal/db/sqltest/tests/credential/vault/credential_vault_ssh_cert_library.sql
This adds additional schema changes including triggers, constraint
checks, and sqltests.
> Schema changes for vault ssh cert credential library

- internal/cmd/commands/server/server.go
Fixes https://github.com/hashicorp/boundary/issues/1603
> Warn if controller and worker name are the same

- internal/daemon/worker/proxy/proxydialer.go
Partner to https://github.com/hashicorp/boundary-enterprise/pull/208
> Update dial function doc to include options

- website/content/docs/concepts/domain-model/targets.mdx
I've also reordered the attributes alphabetically
> Add default port and address to target doc

- internal/daemon/worker/status.go
Encountered this while testing; let the PKI worker sit before registering and it NPE'd
> Fix status NPE if worker has been sitting waiting for registration

- website/content/docs/getting-started/installing/production.mdx
Removes an empty link as part of the docs content link rewrite project (see #2777).
Just a quick manual review of the change is needed. 😊
> [docs] Removing empty link

- internal/target/repository.go
- internal/tests/api/targets/target_test.go
If a call to delete an address from a target (address=null) was issued, the first one would succeed as normal, however if done again on the same target, `updateInRepo` would return 0 `rowsUpdated` (as expected) and we'd fall into the `if rowsUpdated == 0` error case.
> fix(target): Error when deleting an address that's already been deleted

- internal/ui/VERSION
This commit includes all UI changes except target address and multi-hop. Those will be included in a later commit bump PR.
> bump ui commit

- testing/internal/e2e/tests/static/bytes_up_down_empty_test.go
- testing/internal/e2e/tests/static/bytes_up_down_test.go
Observed a failure in `TestCliBytesUpDownTransferData` due to the following reason...
```
--- FAIL: TestCliBytesUpDownTransferData (6.65s)
scope.go:57: Created Org Id: o_caDubtmVem
scope.go:80: Created Project Id: p_TxO4j7FcWe
host.go:82: Created Host Catalog: hcst_OuvHzVqRlE
host.go:102: Created Host Set: hsst_84UMMWoYKG
host.go:124: Created Host: hst_wQjnLe46WA
target.go:59: Created Target: ttcp_7KCbaOtrWg
session.go:64: Waiting for session to be active...
bytes_up_down_test.go:46: Starting session...
session.go:86: Found 1 session(s)
bytes_up_down_test.go:72: Reading bytes_up/bytes_down values...
bytes_up_down_test.go:87: 
Error Trace:	/home/runner/work/boundary/boundary/testing/internal/e2e/tests/static/bytes_up_down_test.go:87
Error:      	"0" is not greater than "0"
Test: …
```
> fix(e2e): Address flake in TestCliBytesUpDownTransferData

- website/content/docs/release-notes/v0_10_0.mdx
- website/content/docs/release-notes/v0_1_0.mdx
- website/content/docs/release-notes/v0_2_0.mdx
- website/content/docs/release-notes/v0_3_0.mdx
- website/content/docs/release-notes/v0_4_0.mdx
- website/content/docs/release-notes/v0_5_0.mdx
- website/content/docs/release-notes/v0_6_0.mdx
- website/content/docs/release-notes/v0_7_0.mdx
- website/content/docs/release-notes/v0_8_0.mdx
- website/content/docs/release-notes/v0_9_0.mdx
This PR manually recreates the failed backport #2836.
[View the updates in the preview deployment.](https://boundary-nyi55tnew-hashicorp.vercel.app/boundary/docs/release-notes/v0_10_0)
> docs: Backport release note updates - 0.11.x

- internal/db/schema/migrations/oss/postgres/59/01_target_ingress_egress_worker_filters.up.sql
Pair PR for https://github.com/hashicorp/boundary-enterprise/pull/223
> Target worker filters migration fix

- internal/daemon/worker/status.go
Partner PR for https://github.com/hashicorp/boundary-enterprise/pull/226
> bug(workers): Check initial upstreams for an HCBP environment

- internal/ui/VERSION
chore: bump ui commit for host set link fixes
> chore: bump ui commit for host set link fixes

- internal/cmd/commands/server/server.go
- internal/daemon/worker/controller_connection.go
- internal/daemon/worker/status.go
Partner PR to https://github.com/hashicorp/boundary-enterprise/pull/226
> Support HCPBInt in hcpb_cluster_id field

- internal/ui/VERSION
chore: bump ui commit to include vault ssh cert feature
> chore: bump ui commit to include vault ssh cert feature

- website/README.md
- website/package-lock.json
- website/package.json
Add a content-check command and document it in the website directory's README file.
> website(README): add content-check command

- internal/daemon/cluster/handlers/worker_service.go
- internal/daemon/cluster/handlers/worker_service_test.go
- internal/daemon/common/const.go
- internal/daemon/controller/handlers/targets/target_service.go
- internal/daemon/controller/handlers/targets/target_service_test.go
Partner PR for https://github.com/hashicorp/boundary-enterprise/pull/233
> Filter managed workers from egress workers

- internal/ui/VERSION
bump ui commit for 0.12.x release
> chore: bump ui commit for 0.12.x release

- internal/db/schema/migrations/oss/postgres/1000/02_wh_user_dimension_ldap.up.sql
- internal/db/schema/migrations/oss/postgres/14/01_wh_user_dimension_oidc.up.sql
- internal/db/sqltest/initdb.d/03_widgets_persona.sql
- internal/db/sqltest/tests/account/ldap/account.sql
- internal/db/sqltest/tests/wh/user_dimension/ldap_auth_new_session.sql
- internal/db/sqltest/tests/wh/user_dimension_views/source.sql
replaces [PR #2911](https://github.com/hashicorp/boundary/pull/2911)
> feature (wh/ldap) add tests for new ldap auth method and accounts

- .github/workflows/build.yml
- version/version.go
Related PR targeting `main` with additional context: https://github.com/hashicorp/boundary/pull/2968
> [release/0.12.x] Update version.go to remove additional oss metadata

- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/enos-fmt.yml
- .github/workflows/enos-run.yml
- .github/workflows/jira.yml
- .github/workflows/labeler.yml
- .github/workflows/linting.yml
- .github/workflows/make-gen-delta.yml
- .github/workflows/milestone-checker.yml
- .github/workflows/security-scan.yml
- .github/workflows/test-ci-bootstrap-oss.yml
- .github/workflows/test-ci-cleanup-oss.yml
- .github/workflows/test-sql.yml
- .github/workflows/test.yml
- .github/workflows/trigger-merge-to-downstream.yml
- CODEOWNERS
- ~Add actionlint workflow~ moving this to a separate PR
- Pin action versions
- Dependabot to notify about action updates
- Update codeowners
> ci: Additional githubaction configuration

- CHANGELOG.md
- internal/ui/VERSION
Updated commitish and changelog for UI.
> Update changelog and UI commitish

- CHANGELOG.md
- internal/ui/VERSION
Cherry picked from [0.12.x](https://github.com/hashicorp/boundary/commit/868d04dcf5bdee8eb39c2e15c14b086b1998f601)
> Update changelog and UI commitish (#3052)

- CHANGELOG.md
- internal/daemon/worker/session/session.go
> Use tofu token from controller

- .github/workflows/trigger-test-cron.yml
Up the workflow run to 10 times per hour. We need to get as much data as we can in the next couple of days.
> [RELENG-483] Increase test workflow run frequency

- .github/workflows/schema-diff.yml
- scripts/schema-diff.sh
This yeilds a better diff when constraints are changed.
> ci(schema-diff): Generate one file per constraint

- website/content/docs/concepts/domain-model/credential-libraries.mdx
- website/content/docs/configuration/worker/pki-worker.mdx
This PR is a cherry-pick of the changes in #3106 to the `stable-website` branch.
> docs: Add links to new tutorials - stable

- website/content/docs/concepts/domain-model/credential-libraries.mdx
- website/content/docs/configuration/worker/pki-worker.mdx
This PR is a cherry-pick of the changes in #3106 to the `release/0.12.x` branch.
> docs: Add links to new tutorials - release 0.12

- website/package-lock.json
- website/package.json
- Install `@hashicorp/platform-content-conformance@latest`
> chore: update dependency

- internal/util/is_nil.go
- internal/util/is_nil_test.go
Support checking for a nil func just incase a caller uses it with a func
> feature (is_nil): support checking func for nil

- internal/cmd/config/config.go
- internal/cmd/config/config_test.go
- internal/cmd/config/options.go
- internal/daemon/controller/cors_test.go
- internal/daemon/controller/testing.go
- internal/daemon/controller/testing_test.go
- internal/daemon/worker/testing.go
- internal/observability/event/context.go
- internal/observability/event/eventer.go
- internal/observability/event/eventer_config.go
- internal/observability/event/eventer_test.go
- internal/observability/event/options.go
- internal/observability/event/testing.go
- internal/test/test.go
- internal/test/test_test.go
Quality of life fix: turn off events for tests and of course provide the ability to turn them back on if needed for specific tests.
> refactor (events): QOL fix: turn off events for tests.

- website/content/docs/api-clients/cli.mdx
- website/content/docs/getting-started/deploy-and-login.mdx
- website/content/docs/oss/installing/run-and-login.mdx
Closes https://github.com/hashicorp/boundary/issues/3159
> docs: Explain -format json behaviour on boundary authenticate cmd

- internal/server/job/options.go
- internal/server/job/options_test.go
This PR adds copyright headers to some new files that were introduced.
> doc: Add missing copyright headers

- internal/ui/VERSION
- website/content/docs/configuration/controller.mdx
- website/content/docs/getting-started/installing/production.mdx
This pull request back ports the changes from #3212 to the stable website.
> Update references to deprecated controllers field (#3212)

- internal/daemon/controller/handlers/scopes/scope_service.go
- internal/daemon/controller/handlers/scopes/scope_service_test.go
This commit fixes the behaviour of scopes where whitespace was allowed (and thus persisted) in the Name and Description fields.
It also adds some more tests for scope Create and Updateto cover more error cases.
For scope update, `handlers.ValidateUpdateRequest` exists, however this was not used as it does not work properly for requests where the `global` scope is updated.
In `ValidateUpdateRequest`, an ID check is performed and it assumes there's always a resource prefix (eg: "p", "o") and an identifier (random numbers and letters) after the prefix. This fails for `global`. See `handlers.ValidId`.
> fix(handlers/scopes): Whitespace on Name and Description fields

- internal/cmd/commands/dev/dev.go
This brings it in line with the updated names that have been settled on in light of deprecating the old KMS method.
> Update dev worker auth flag names

- internal/db/sqltest/tests/hcp/billing/monthly_sessions_all.sql
Certain tests fail when run on the first day of the month because of edge cases in the setup of test data. This adds conditional logic to skip those tests when run on the first day of a month.
> test(db): Conditionally skip monthly billing view tests

- internal/db/schema/migrations/oss/postgres/72/02_session_connection_index.up.sql
This index improves the performance for two queries on the `session_connection` table. The execution time for the first query went from 40.105 ms to 1.405 ms. The execution time for the second query went from 13.808 ms to 0.217 ms.
Query 1 explain plan before index:
Update on session_connection  (cost=6465.17..6557.68 rows=11 width=50) (actual time=38.868..39.147 rows=3 loops=1)
->  Nested Loop  (cost=6465.17..6557.68 rows=11 width=50) (actual time=38.471..38.506 rows=3 loops=1)
->  HashAggregate  (cost=6464.75..6464.86 rows=11 width=40) (actual time=38.447..38.450 rows=3 loops=1)
Group Key: (session_connection_1.public_id)::text
Batches: 1  Memory Usage: 24kB
->  Nested Loop Semi Join  (cost=0.42..6464.72 rows=11 width=40) (actual time=29.184..38.434 rows=3 loops=1)
->  Seq Scan on …
> fix(db): Add index to session connection table

- Makefile
- internal/gen/controller/api/services/session_recording_service.pb.go
- sdk/pbs/controller/api/resources/session_recordings/session_recording.pb.go
> api: add classification to session recordings

- website/content/docs/configuration/session-recording/create-storage-bucket.mdx
- website/content/docs/release-notes/v0_13_0.mdx
Fixes an issue with how some code blocks were displaying on the stable website.
> docs: Fix display issue with code blocks

- website/content/docs/configuration/session-recording/create-storage-bucket.mdx
link PKI worker link to session recoding config
> Update create-storage-bucket.mdx PKI worker to session recording config

- website/content/docs/configuration/session-recording/enable-session-recording.mdx
Update enable-session-recording.mdx to link bsr controler config to bsr kms key doc
> Update enable-session-recording.mdx to link bsr controler config to bsr kms key doc

- go.mod
- go.sum
- internal/server/repository_workerauth.go
- internal/server/repository_workerauth_test.go
Relies on https://github.com/hashicorp/nodeenrollment/pull/46
> chore(server): Update worker auth repository to handle dupe nodes

- internal/bsr/bsr.go
- internal/bsr/bsr_open_test.go
- internal/bsr/container.go
- internal/bsr/container_test.go
- internal/bsr/errors.go
- internal/bsr/ssh/types.go
- internal/bsr/summary.go
- internal/bsr/summary_test.go
- internal/bsr/types.go
- Add support for decoding session, connection and channel summary file
- Introduce base summary interfaces that other protocols can extend
- Add new SSH register allocation function for getting SSH Channel Summary Type
> feat: Decode Summary File

- internal/bsr/types.go
Add missing `Errors` Getter & Setter for Session & Connection Summary interfaces
> chore: Add missing for summary interfaces

- website/content/docs/api-clients/commands/connect/postgres.mdx
> docs/cli-commands-Update postgres.mdx

- website/content/docs/configuration/kms/awskms.mdx
- website/content/docs/configuration/session-recording/create-storage-bucket.mdx
Add configuration requirements to docs for session recording that uses KMS encryption
> docs: BSR KMS Configuration Requirements

- website/content/docs/getting-started/dev-mode/connect-to-dev-target.mdx
- website/content/docs/hcp/get-started/connect-to-target.mdx
Adds separate sections for all the different connect helpers we have. There are quite a lot of videos on this page now, so maybe we need to break out the different helpers into their own sections, but that can follow later.
> Connect option docs

- internal/bsr/types.go
- internal/bsr/types_test.go
Partner PR for https://github.com/hashicorp/boundary-enterprise/pull/666
> fix(session recording): correctly return and join errors

- internal/gen/controller/api/services/user_service.pb.go
- internal/proto/controller/api/resources/users/v1/user.proto
- internal/proto/controller/api/services/v1/user_service.proto
- sdk/pbs/controller/api/resources/users/user.pb.go
This PR add observation gotags into `user.proto` and `user_service.proto` for telemetry purposes
> Telemetry: user.proto

- website/content/docs/concepts/security/data-encryption.mdx
- website/content/docs/enterprise/index.mdx
- website/content/docs/getting-started/dev-mode/dev-mode.mdx
- website/content/docs/getting-started/index.mdx
- website/content/docs/hcp/get-started/deploy-and-login.mdx
- website/content/docs/install-boundary/index.mdx
- website/content/docs/oss/index.mdx
- website/content/docs/overview/what-is-boundary.mdx
- website/content/docs/release-notes/v0_13_0.mdx
- website/content/docs/troubleshoot/faq.mdx
- website/data/docs-nav-data.json
Updating product names (SPE-348).
> docs: Update oss references

- website/content/docs/api-clients/commands/sessions/cancel.mdx
- website/content/docs/api-clients/commands/sessions/index.mdx
- website/content/docs/api-clients/commands/sessions/list.mdx
- website/content/docs/api-clients/commands/sessions/read.mdx
- website/data/docs-nav-data.json
Adds the `sessions` commands on top of the existing assembly branch for CLI commands #3411.
> docs: Add `sessions` commands

- website/content/docs/api-clients/commands/scopes/create.mdx
- website/content/docs/api-clients/commands/scopes/delete.mdx
- website/content/docs/api-clients/commands/scopes/destroy-key-version.mdx
- website/content/docs/api-clients/commands/scopes/index.mdx
- website/content/docs/api-clients/commands/scopes/list-key-version-destruction-jobs.mdx
- website/content/docs/api-clients/commands/scopes/list-keys.mdx
- website/content/docs/api-clients/commands/scopes/list.mdx
- website/content/docs/api-clients/commands/scopes/read.mdx
- website/content/docs/api-clients/commands/scopes/rotate-keys.mdx
- website/content/docs/api-clients/commands/scopes/update.mdx
- website/data/docs-nav-data.json
Adds the `scopes` commands on top of the existing assembly branch for CLI commands #3411.
> docs: Add `scopes` commands

- website/content/docs/install-boundary/configure-controllers.mdx
- website/content/docs/install-boundary/configure-workers.mdx
An update to clarify worker configuration with and without multi-hop using tabs.
> docs: Update worker config with tabs

- website/content/docs/api-clients/commands/managed-groups/create.mdx
- website/content/docs/api-clients/commands/managed-groups/delete.mdx
- website/content/docs/api-clients/commands/managed-groups/index.mdx
- website/content/docs/api-clients/commands/managed-groups/list.mdx
- website/content/docs/api-clients/commands/managed-groups/read.mdx
- website/content/docs/api-clients/commands/managed-groups/update.mdx
- website/data/docs-nav-data.json
Adds the `managed-groups` commands on top of the existing assembly branch for CLI commands #3411.
> docs: Add `managed-groups` commands

- website/content/docs/api-clients/commands/hosts/create.mdx
- website/content/docs/api-clients/commands/hosts/delete.mdx
- website/content/docs/api-clients/commands/hosts/index.mdx
- website/content/docs/api-clients/commands/hosts/list.mdx
- website/content/docs/api-clients/commands/hosts/read.mdx
- website/content/docs/api-clients/commands/hosts/update.mdx
- website/data/docs-nav-data.json
Adds the `hosts` commands on top of the existing assembly branch for CLI commands #3411.
> docs: Add `hosts` commands

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
First phase of modifications requested by TPM to enhance our jira integration.
> Update labels in github issue template

- website/content/docs/install-boundary/system-requirements.mdx
Clarifying multi-hop session proxying wording
> Update multi-hop system-requirements.mdx

- website/content/docs/api-clients/commands/dev.mdx
- website/content/docs/api-clients/commands/index.mdx
- website/content/docs/api-clients/commands/logout.mdx
- website/content/docs/api-clients/commands/server.mdx
Edits to the CLI rough drafts in PR #3411 for consistency and clarity.
> docs: Edit CLI drafts

- website/content/docs/api-clients/commands/accounts/change-password.mdx
- website/content/docs/api-clients/commands/accounts/create.mdx
- website/content/docs/api-clients/commands/accounts/delete.mdx
- website/content/docs/api-clients/commands/accounts/index.mdx
- website/content/docs/api-clients/commands/accounts/list.mdx
- website/content/docs/api-clients/commands/accounts/read.mdx
- website/content/docs/api-clients/commands/accounts/set-password.mdx
- website/content/docs/api-clients/commands/accounts/update.mdx
- website/content/docs/api-clients/commands/dev.mdx
- website/content/docs/api-clients/commands/index.mdx
- website/content/docs/api-clients/commands/logout.mdx
- website/content/docs/api-clients/commands/server.mdx
Edit the `accounts` options in the CLI draft doc #3411.
> docs: Edit `accounts` options

- website/content/docs/api-clients/commands/connect/http.mdx
- website/content/docs/api-clients/commands/connect/index.mdx
- website/content/docs/api-clients/commands/connect/kube.mdx
- website/content/docs/api-clients/commands/connect/postgres.mdx
- website/content/docs/api-clients/commands/connect/rdp.mdx
- website/content/docs/api-clients/commands/connect/ssh.mdx
- website/content/partials/cmd-connect-command-options.mdx
- website/content/partials/cmd-connect-env-vars.mdx
- website/content/partials/cmd-option-note.mdx
Edits the `connect` options in the CLI draft doc #3411.
> docs: Edit `connect` options

- internal/gen/controller/api/services/account_service.pb.go
- internal/gen/controller/api/services/auth_method_service.pb.go
- internal/gen/controller/api/services/group_service.pb.go
- internal/gen/controller/api/services/host_catalog_service.pb.go
- internal/gen/controller/api/services/role_service.pb.go
- internal/gen/controller/api/services/scope_service.pb.go
- internal/gen/controller/api/services/user_service.pb.go
- internal/gen/controller/api/services/worker_service.pb.go
- internal/proto/controller/api/resources/accounts/v1/account.proto
- internal/proto/controller/api/resources/authmethods/v1/auth_method.proto
- internal/proto/controller/api/resources/groups/v1/group.proto
- internal/proto/controller/api/resources/hostcatalogs/v1/host_catalog.proto
- internal/proto/controller/api/services/v1/account_service.proto
- internal/proto/controller/api/services/v1/auth_method_service.proto
- internal/proto/controller/api/services/v1/group_service.proto
- internal/proto/controller/api/services/v1/host_catalog_service.proto
- internal/proto/controller/api/services/v1/role_service.proto
- internal/proto/controller/api/services/v1/scope_service.proto
- internal/proto/controller/api/services/v1/user_service.proto
- internal/proto/controller/api/services/v1/worker_service.proto
- sdk/pbs/controller/api/resources/accounts/account.pb.go
- sdk/pbs/controller/api/resources/authmethods/auth_method.pb.go
- sdk/pbs/controller/api/resources/groups/group.pb.go
- sdk/pbs/controller/api/resources/hostcatalogs/host_catalog.pb.go
This PR will add observation gotags to list recursive boolean fields and remove observation gotags from unnecessary fields
> Telemetry: Fix observation tags

- website/content/docs/api-clients/commands/database/index.mdx
- website/content/docs/api-clients/commands/database/init.mdx
- website/content/docs/api-clients/commands/database/migrate.mdx
Edits the `database` options in the CLI draft doc #3411.
> docs: Edit `database` options

- internal/cmd/commands/authmethodscmd/ldap_funcs.go
Added support for new flags for: max-page-size and deref-aliases
> feat (auth/ldap): add support for new fields to CLI

- internal/event/eventer.go
- internal/event/eventer_test.go
Added convenience struct, node, and preserve the serverName on the Eventer.
> feat(event): add register pipeline

- internal/event/event_type.go
- internal/event/event_type_test.go
This PR adds a new event type for storage, adding the ability to introduce new events for session recording.
> feat(event): new storage event type

- website/content/docs/overview/what-is-boundary.mdx
This PR updates the **How does Boundary work?** video to use the correct name for Community Edition.
View the change in the preview deployment here:
https://boundary-55j6z4had-hashicorp.vercel.app/boundary/docs/overview/what-is-boundary#how-does-boundary-work
To verify the link is the correct version of the video, go to 4:15 and verify that the slide reads "Community Edition".
> docs: Update How does Boundary work? video

- website/content/docs/concepts/domain-model/credential-libraries.mdx
* Update Vault Credential Library Docs with additional Options
* Update credential-libraries.mdx
* docs: Minor copy edits
---------
> Dheath-cherry-pick-cred-lib-stable

- website/content/docs/concepts/domain-model/credential-libraries.mdx
* Update Vault Credential Library Docs with additional Options
* Update credential-libraries.mdx
* docs: Minor copy edits
---------
> Dheath-cherry-pick-cred-lib-13

- internal/daemon/common/handler_test.go
- internal/event/eventer.go
- internal/event/testing.go
Updating the broker interface definition to support removing nodes.
> feat(event): remove node on pipeline failure

- CHANGELOG.md
This PR adds a description of telemetry features with new improvements to deny filters.
> CHANGELOG: Telemetry 

- internal/db/read_writer.go
- internal/db/read_writer_ext_test.go
Writer.IsTx(...) returns true if there's an existing transaction in progress.
> feat (db): add Writer.IsTx(...)

- CHANGELOG.md
- internal/ui/VERSION
Update UI commitsh and update changelog.
> Bump UI commitsh and update changelog

- website/content/docs/commands/connect/ssh.mdx
- website/content/docs/concepts/domain-model/accounts.mdx
- website/content/docs/concepts/domain-model/auth-methods.mdx
- website/content/docs/concepts/domain-model/managed-groups.mdx
- website/content/docs/concepts/domain-model/storage-buckets.mdx
- website/content/docs/configuration/session-recording/create-storage-bucket.mdx
- website/content/docs/operations/health.mdx
- website/content/docs/release-notes/v0_14_0.mdx
- website/content/docs/troubleshoot/troubleshoot-recorded-sessions.mdx
- website/content/partials/release-notes/intro.mdx
- website/data/docs-nav-data.json
Merge hashiconf assembly branch from private repo into Boundary repo.
> Dheath hashiconf assembly

- internal/apptoken/app_token.go
- internal/apptoken/repository.go
- internal/apptoken/repository_create.go
- internal/apptoken/repository_delete.go
- internal/apptoken/repository_list.go
- internal/apptoken/repository_read.go
- internal/db/schema/migrations/oss/postgres/1001/01_app_tokens.up.sql
- internal/db/sqltest/tests/auth/app_token/app_token.sql
Defines the schema for the app token auth method.
> Define app token schema

- internal/db/read_writer.go
- internal/db/read_writer_test.go
The Now() method returns the current transaction timestamp.
> Add Now method to DB handle

- internal/auth/ldap/repository_authenticate.go
- internal/auth/ldap/repository_authenticate_test.go
We need to encode the key as a PEM before initializing cap's ldap client
> fix (auth/ldap): fix encoding of mTLS client key

- CHANGELOG.md
(cherry picked from commit 9f8f81d15f3d88a20e4ea033606a23271108616e)
> chore: add changelog for ldap fix PR #3929

- CHANGELOG.md
Add a changelog entry for the pagination changes.
> Update CHANGELOG for pagination feature

- internal/db/sqltest/tests/history/history_table_tests.sql
Discovered by @mikemountain while working on the deleted tables for list pagination
> sqltest: fix typo

- CHANGELOG.md
- go.mod
- Update changelog for new changes
- Update `go.mod` SDK & API version for new changes introduced in: https://github.com/hashicorp/boundary/pull/3932
> Update changelog & go.mod

- internal/auth/ldap/service_authenticate.go
- internal/auth/ldap/service_authenticate_test.go
- internal/auth/oidc/service_callback.go
- internal/auth/oidc/service_callback_test.go
- internal/daemon/controller/handlers/authmethods/ldap_test.go
* telemetry(observations): Add observations for oidc and ldap authentications
* telemetry(observations): Add tests ldap and oidc observation events
> Telemetry(observations): add oidc and ldap observation events (#3945)

- scan.hcl
Flips OSV scanning back on for Security Scanner.
> turn on osv scanning

- internal/auth/ldap/service_authenticate_test.go
- internal/auth/oidc/service_callback_test.go
- internal/daemon/controller/handlers/authmethods/ldap_test.go
- internal/daemon/controller/handlers/authmethods/password_test.go
- internal/event/context.go
- internal/event/context_test.go
* telemetry(observations): fix the details flag check
* telemetry(observations): fix the test names
> telemetry(observations): fix the details flag check (#3960)

- CONTRIBUTING.md
> fix:typo error in CONTRIBUTING.md

- globals/prefixes.go
- globals/prefixes_test.go
This fixes test failures introduced in a recent refactoring.
Blame: 0bf60996c5f8b2a3fa336ef6f5396a432d53e6c7
> test(globals): Fix failing tests

- globals/prefixes.go
- globals/prefixes_test.go
This reverts commit 274aca755f70d45a4f3c397ca8a5375f39c70fb2.
> Revert "test(globals): Fix failing tests"

- go.mod
- go.sum
this should stop the occasional panic we get from gldap in CI tests.
> chore (deps): update gldap dependency

- website/content/docs/overview/what-is-boundary.mdx
Adds a feature matrix to the What is Boundary documentation.
[View the update in the preview deployment](https://boundary-5umsza2e6-hashicorp.vercel.app/boundary/docs/overview/what-is-boundary#which-edition-of-boundary-is-right-for-me)
> docs: Add feature matrix

- website/content/docs/overview/what-is-boundary.mdx
This PR makes some updates to the feature matrix to make the content easier to read. The headings were updated to be more consistent with existing terminology and the body was center aligned.
[View the update in the preview deployment](https://boundary-ncsmrh177-hashicorp.vercel.app/boundary/docs/overview/what-is-boundary#which-edition-of-boundary-is-right-for-me)
> docs: Update feature matrix

- internal/daemon/controller/handlers/authmethods/authmethod_service_test.go
- internal/kms/kms.go
(cherry picked from commit e2f98de696af6ec06b314383d9e27e82140d76e5)
> refact (kms): convert to the new stdlib slices pkg

- website/content/docs/commands/session-recordings/download.mdx
- website/content/docs/commands/session-recordings/index.mdx
- website/content/docs/commands/session-recordings/list.mdx
- website/content/docs/commands/session-recordings/read.mdx
- website/content/docs/commands/storage-buckets/create.mdx
- website/content/docs/commands/storage-buckets/delete.mdx
- website/content/docs/commands/storage-buckets/index.mdx
- website/content/docs/commands/storage-buckets/list.mdx
- website/content/docs/commands/storage-buckets/read.mdx
- website/content/docs/commands/storage-buckets/update.mdx
- website/content/docs/concepts/credential-management.mdx
- website/content/docs/concepts/domain-model/credential-libraries.mdx
- website/content/docs/concepts/domain-model/session-recordings.mdx
- website/content/docs/concepts/domain-model/storage-buckets.mdx
- website/content/docs/concepts/domain-model/targets.mdx
- website/content/docs/concepts/filtering/worker-tags.mdx
- website/content/docs/concepts/security/data-encryption.mdx
- website/content/docs/concepts/workers.mdx
- website/content/docs/configuration/session-recording/create-storage-bucket.mdx
- website/content/docs/configuration/session-recording/enable-session-recording.mdx
- website/content/docs/configuration/session-recording/index.mdx
- website/content/docs/configuration/worker/index.mdx
- website/content/docs/configuration/worker/pki-worker.mdx
- website/content/docs/operations/session-recordings/index.mdx
- website/content/docs/operations/session-recordings/manage-recorded-sessions.mdx
- website/content/docs/operations/session-recordings/validate-data-store.mdx
- website/content/docs/operations/session-recordings/validate-session-recordings.mdx
* docs: Add enterprise badge (#3981)
* docs: Add enterprise badge
* docs: Add heading-level enterprise alert
* docs: Add some missing tags
* docs: Delete duplicate alert
* docs: Remove stray HCP/ENT tags
* docs: Remove more HCP/ENT tags
> Dheath-pick-ent-label-0.14.x

- website/content/docs/commands/session-recordings/download.mdx
- website/content/docs/commands/session-recordings/index.mdx
- website/content/docs/commands/session-recordings/list.mdx
- website/content/docs/commands/session-recordings/read.mdx
- website/content/docs/commands/storage-buckets/create.mdx
- website/content/docs/commands/storage-buckets/delete.mdx
- website/content/docs/commands/storage-buckets/index.mdx
- website/content/docs/commands/storage-buckets/list.mdx
- website/content/docs/commands/storage-buckets/read.mdx
- website/content/docs/commands/storage-buckets/update.mdx
- website/content/docs/concepts/credential-management.mdx
- website/content/docs/concepts/domain-model/credential-libraries.mdx
- website/content/docs/concepts/domain-model/session-recordings.mdx
- website/content/docs/concepts/domain-model/storage-buckets.mdx
- website/content/docs/concepts/domain-model/targets.mdx
- website/content/docs/concepts/filtering/worker-tags.mdx
- website/content/docs/concepts/security/data-encryption.mdx
- website/content/docs/concepts/workers.mdx
- website/content/docs/configuration/session-recording/create-storage-bucket.mdx
- website/content/docs/configuration/session-recording/enable-session-recording.mdx
- website/content/docs/configuration/session-recording/index.mdx
- website/content/docs/configuration/worker/index.mdx
- website/content/docs/configuration/worker/pki-worker.mdx
- website/content/docs/operations/session-recordings/index.mdx
- website/content/docs/operations/session-recordings/manage-recorded-sessions.mdx
- website/content/docs/operations/session-recordings/validate-data-store.mdx
- website/content/docs/operations/session-recordings/validate-session-recordings.mdx
* docs: Add enterprise badge (#3981)
* docs: Add enterprise badge
* docs: Add heading-level enterprise alert
* docs: Add some missing tags
* docs: Delete duplicate alert
* docs: Remove stray HCP/ENT tags
* docs: Remove more HCP/ENT tags
> [docs] Cherry pick #3981 to website (#4003) (#4017)

- LICENSE
Update LICENSE file to include new Additional Use Grants per https://www.hashicorp.com/bsl. Please contact team-rel-eng for questions.
> RELPLAT-962 Update LICENSE

- internal/event/event_observation.go
- internal/event/event_observation_test.go
* Observation(event): adding op instead of type details paylaod
* Observation(events): removing op check in details
> Observation(event): adding op instead of type details payload (#4043)

- LICENSE
* Update LICENSE
* Update LICENSE
> Update LICENSE (#4062)

- internal/daemon/controller/handlers/list_token.go
- internal/daemon/controller/handlers/list_token_test.go
- internal/daemon/controller/handlers/targets/target_service.go
- internal/target/service_list_ext_test.go
Fix some target tests and move token parsing logic into a helper
> Some pagination tweaks

- go.mod
- go.sum
- internal/cmd/commands/server/controller_ratelimit_reload_test.go
- internal/cmd/commands/server/server.go
- internal/cmd/config/config.go
- internal/daemon/controller/config.go
- internal/daemon/controller/controller.go
- internal/daemon/controller/rate_limiter.go
- internal/daemon/controller/rate_limiter_test.go
- internal/daemon/controller/testdata/Test_rateLimiterConfig_writeSysEvent/defaults.json
- internal/daemon/controller/testdata/Test_rateLimiterConfig_writeSysEvent/disabled.json
- internal/daemon/controller/testdata/Test_rateLimiterConfig_writeSysEvent/max_size.json
- internal/daemon/controller/testdata/Test_rateLimiterConfig_writeSysEvent/override.json
- internal/ratelimit/config.go
- internal/ratelimit/config_test.go
- internal/ratelimit/handler.go
- internal/ratelimit/handler_test.go
- internal/ratelimit/limiter.go
d7373ae03 feat(controller): Emit sys event detailing the rate limit configuration
A sys event will be emitted when the controller is constructed, and if the
rate limits are changed via a SIGHUP. The event contains the details of the
rate limits for each combination of resource and action. This event can be
used by operators to confirm the limits are set as they would expect based
on the controller config.
092ab0c53 feat(ratelimier): Support disabling rate limiting
b11847260 refact(ratelimiter): Updates due to refactor in go-rate
> ratelimit: Emit a sys event and allow disabling the limiter

- api/client.go
If the api.Client receives a 429 or 503 along with a Retry-After header,
the client will automatically wait the amount of time specified, and
then re-try the request.
Note that by default the boundary cli does not perform any retries. In
order for the cli to automatically retry when rate limited, users must
set the `BOUNDARY_MAX_RETRIES` environment variable.
> feat(api): Use Retry-After header when retrying a request

- internal/credential/service_list_credentials_ext_test.go
> internal/credential: fix comment

- website/content/docs/configuration/session-recording/create-storage-bucket.mdx
* docs: Update session recording reqs for HCP
* docs: Update link
* docs: Add note for HCP Boundary
* docs: Update with proper Note format
* Update website/content/docs/configuration/session-recording/create-storage-bucket.mdx
---------
> docs: Backport #4088 to stable website

- website/content/docs/configuration/session-recording/create-storage-bucket.mdx
* docs: Update session recording reqs for HCP
* docs: Update link
* docs: Add note for HCP Boundary
* docs: Update with proper Note format
* Update website/content/docs/configuration/session-recording/create-storage-bucket.mdx
---------
> docs: Backport #4088 to release 0.14.x

- testing/internal/e2e/tests/base_plus/rate_limit_test.go
The e2e rate limit test was running into failures in `boundary-enterprise` due to what seems like the GitHub Actions runner taking longer to execute CLI commands. The test had some hard-coded assumptions about timing that were incorrect.
This PR updates the test to not rely on those assumptions.
> test(e2e): Modify rate limit test due to timing issues

- website/content/docs/release-notes/v0_14_0.mdx
This pull request adds the enhancements from the 0.14.2 and 0.14.3 releases to the 0.14.x release notes.
[View the update in the preview deployment](https://boundary-41u2qrbp3-hashicorp.vercel.app/boundary/docs/release-notes/v0_14_0#new-features).
> docs: Update release notes for 0.14.x

- website/content/docs/concepts/domain-model/scopes.mdx
There has been some ongoing confusion about how and why to use projects in Boundary. This PR makes a minor update to the domain model documentation to help clarify.
I also made a minor update to the topic's metadata to bring it up to our new standards.
[View the preview deployment](https://boundary-flg5tm422-hashicorp.vercel.app/boundary/docs/concepts/domain-model/scopes)
> docs: Clarify projects' purpose

- website/content/docs/concepts/domain-model/scopes.mdx
This pull request backports the projects update from #4049 to the `release/0.14.x` branch:
* docs: Clarify projects' purpose
* docs: Update meta content
* docs: Add more context
> docs: Backport projects update to release branch

- enos/enos-scenario-e2e-docker-base-plus.hcl
- enos/modules/docker_boundary/boundary-config-rate-limit.hcl
- testing/internal/e2e/boundary/boundary.go
- testing/internal/e2e/boundary/http.go
- testing/internal/e2e/helpers.go
- testing/internal/e2e/tests/base_plus/rate_limit_test.go
(cherry picked from commit 9bf350d622a14ea39feaca29861c738a5deff9bb) - merging to `main`
> test(e2e): Add rate limit test (#4135)

- internal/db/schema/migrations/oss/postgres/80/10_host_set_table_updates.up.sql
- internal/host/plugin/query.go
- internal/host/plugin/repository_host_set.go
- internal/host/static/repository_host_set.go
I missed this in the last PR it seems 😬. Also includes a revert of some logic from the old pagination pattern.
> Sort host sets descending

- testing/internal/e2e/boundary/host.go
- testing/internal/e2e/tests/base/paginate_host_set_test.go
This PR adds an e2e test that paginates host sets.
> test(e2e): Add test for paginating host sets

- testing/internal/e2e/tests/base/paginate_credential_store_test.go
- testing/internal/e2e/tests/base/paginate_host_set_test.go
- testing/internal/e2e/tests/base/paginate_host_test.go
- testing/internal/e2e/tests/base/paginate_user_test.go
This PR adds an e2e test that paginates users.
> test(e2e): Add test to paginate users

- internal/db/schema/migrations/oss/postgres/80/02_target_base_table_updates.up.sql
- internal/db/schema/migrations/oss/postgres/80/03_credential_static_base_table_updates.up.sql
- internal/db/schema/migrations/oss/postgres/80/04_credential_library_base_table_updates.up.sql
- internal/db/schema/migrations/oss/postgres/80/07_credential_store_base_table_updates.up.sql
Ensure the new create_time and update_time columns are marked as not null after populating the data.
Also ensure that the data is populated safely with an updated query pattern inspired by the auth method
pattern.
> internal/db: ensure new columns are not null

- .copywrite.hcl
- LICENSE
- internal/proto/controller/api/.copywrite.hcl
- internal/proto/controller/custom_options/.copywrite.hcl
- internal/proto/plugin/.copywrite.hcl
DO NOT MERGE UNTIL EOY 2023
Updates text in license and copywrite bot files for 2024.
> [DO NOT MERGE UNTIL EOY] EOY license updates v.0.14.x

- internal/db/schema/migrations/oss/postgres/80/16_storage_bucket_updates.up.sql
- internal/db/sqltest/tests/pagination/storage_bucket.sql
Adds the community edition pagination changes for storage buckets
> internal/db: storage bucket pagination migrations

- go.mod
- internal/authtoken/authtoken.go
- internal/authtoken/gorm.go
- internal/clientcache/cmd/daemon/status.go
- internal/clientcache/cmd/daemon/stop_nonwindows.go
- internal/clientcache/cmd/daemon/stop_windows.go
- internal/clientcache/internal/client/client_test.go
- internal/clientcache/internal/daemon/server.go
- internal/credential/vault/repository_credential_library_test.go
- internal/host/static/host_set.go
- internal/host/static/immutable_fields_test.go
Fix linter warnings reported in https://github.com/hashicorp/boundary/pull/4217
> Fix linter warnings

- internal/daemon/controller/handlers/scopes/scope_service.go
- internal/daemon/controller/handlers/scopes/scope_service_test.go
- internal/db/schema/migrations/oss/postgres/82/05_storage_policy_override.up.sql
> Storage Policy Updates

- CHANGELOG.md
- Update changelog with UI notes to the New and Improved section.
> Update changelog with UI notes

- internal/ui/VERSION
- Update Boundary UI to lates commit
> Update Boundary to latest UI

- version/feature_manager.go
- version/version_base.go
> feat(features): Add DeletePlugin feature

- website/redirects.js
Testing this after Vercel builds failed on #4283.
> docs: Backport #4280 to stable web

- website/redirects.js
Second attempt at this backport after Vercel builds failed on #4282.
> docs: Backport #4280 to release 0.14.x

- .github/workflows/backport.yml
PR to test changes to backport assistant runner
> [draft] website bug fix: PR for testing purposes

- CHANGELOG.md
Will wait to merge until after release later today
> Add note about breaking list change

- website/content/docs/enterprise/supported-versions.mdx
Update supported-versions for client <-> control plane support policy
> Client-control-plane-support-policy.mdx

- website/content/docs/concepts/filtering/events.mdx
- website/content/docs/configuration/events/common.mdx
Fixes https://github.com/hashicorp/boundary/issues/4363.
> Fix docs for event filters

- website/content/docs/api-clients/client-cache.mdx
- website/content/docs/commands/daemon/add-token.mdx
Backports #4367 to the stable website.
> docs: Backport search permissions to web

- website/content/docs/api-clients/client-cache.mdx
- website/content/docs/commands/daemon/add-token.mdx
Backports #4367 to release 0.15.x.
> docs: Backport search permissions to 0.15.x

- website/content/docs/release-notes/v0_15_0.mdx
This PR adds the known issue #4364 to the release notes for 0.15.0.
[View the update in the preview deployment](https://boundary-ix6c0osf6-hashicorp.vercel.app/boundary/docs/release-notes/v0_15_0#known-issues-and-breaking-changes)
> docs: Add max # of connections to known issues

- website/content/docs/release-notes/v0_15_0.mdx
This PR backports #4405 to the stable website.
> docs: Add known issue to website

- website/content/docs/release-notes/v0_15_0.mdx
This PR backports #4405 to release 0.15.x.
> docs: Add known issue to release 0.15.x

- website/content/docs/configuration/kms/azurekeyvault.mdx
Cherry picks the docs fix in #4449 to the stable website branch.
> docs: Backport #4449 to stable website

- website/content/docs/configuration/kms/azurekeyvault.mdx
Cherry picks the docs fix in #4449 to the release/0.15.x branch.
> docs: Backport #4449 to release 0.15.x

- website/content/docs/configuration/worker/worker-configuration.mdx
This pull request backports PR #4464 to the stable website.
> docs: Backport #4464 to stable website

- website/content/docs/configuration/worker/worker-configuration.mdx
This pull request backports PR #4464 to release/0.15.x.
> docs: Backport #4464 to release 0.15.x

- website/content/docs/release-notes/v0_15_0.mdx
Updates the 0.15.x release notes with the fix to a documented known issue. Scheduled to be released with 0.15.1.
[View the update in the preview deployment](https://boundary-ec5mv2eze-hashicorp.vercel.app/boundary/docs/release-notes/v0_15_0#known-issues-and-breaking-changes)
> docs: Update 0.15.x release notes

- website/content/docs/release-notes/v0_15_0.mdx
This PR backports #4460 to the stable-website branch.
> docs: Backport 0.15.1 release notes update to website

- website/content/docs/release-notes/v0_15_0.mdx
Ths PR backports #4460 to the 0.15.x branch.
> docs: Backport 0.15.1 release notes update to 0.15.x

- website/content/docs/concepts/workers.mdx
Backports #4487 to the stable website.
* docs(worker): add information about worker status and health
---------
> docs: Backprt worker doc update - stable

- website/content/docs/concepts/auditing.mdx
> docs: update session recording link

- website/content/docs/concepts/auditing.mdx
Backports #4495 to the stable website.
* docs: update session recording link
* docs: Update link
---------
> docs: Backport #4495 - website

- website/content/docs/concepts/auditing.mdx
Backports #4495 to the release 0.15.x branch.
* docs: update session recording link
* docs: Update link
---------
> docs: Backport #4495 - release 0.15.x

- website/content/docs/release-notes/v0_14_0.mdx
- website/content/docs/release-notes/v0_15_0.mdx
This PR backports #4505 to the stable website.
> docs: Backport #4505 to website

- website/content/docs/concepts/auditing.mdx
- website/content/docs/operations/session-recordings/validate-session-recordings.mdx
Edited the file listing to make it a bit more readable (the example BSR was long) and included a break down and explanation of each file in each subdirectory
> docs(bsr): explain BSR files in detail

- website/content/docs/release-notes/v0_14_0.mdx
- website/content/docs/release-notes/v0_15_0.mdx
Documents fixes to known issues. View the preview deployment:
https://boundary-1paytpexf-hashicorp.vercel.app/boundary/docs/release-notes/v0_15_0
> docs: Update release notes

- internal/session/service_worker_status_report.go
Return at first error in WorkerStatusReport.
> fix(session): return from workerStatusReport on first error

- internal/alias/target/service_list_ext_test.go
- internal/auth/oidc/service_list_accounts_ext_test.go
- internal/auth/oidc/service_list_managed_groups_ext_test.go
- internal/credential/service_list_stores_ext_test.go
- internal/host/plugin/service_list_host_sets_ext_test.go
- internal/host/plugin/service_list_hosts_ext_test.go
- internal/host/static/service_list_host_sets_ext_test.go
- internal/iam/service_list_ext_test.go
This PR makes some fixes to `TestStoreService_List` to hopefully resolve some race conditions in these tests.
https://hashicorp.atlassian.net/browse/ICU-13237
> test(credential): Potential fix for race condition

- go.mod
- go.sum
[GO-2024-2631](https://pkg.go.dev/vuln/GO-2024-2631)
> chore: Update deps

- internal/ui/VERSION
Bump UI version to include MinIO CRUD support in Admin UI
> Bump UI version to include MinIO support

- website/content/docs/commands/aliases/create.mdx
- website/content/docs/commands/aliases/delete.mdx
- website/content/docs/commands/aliases/index.mdx
- website/content/docs/commands/aliases/list.mdx
- website/content/docs/commands/aliases/read.mdx
- website/content/docs/commands/aliases/update.mdx
- website/content/docs/commands/index.mdx
- website/content/docs/commands/targets/create.mdx
- website/content/docs/concepts/aliases.mdx
- website/content/docs/concepts/domain-model/aliases.mdx
- website/content/docs/concepts/domain-model/targets.mdx
- website/data/docs-nav-data.json
* docs: Aliases overview and domain model
* docs: Add new topics to TOC
* docs: Updates
* docs: Update CLI topics, add usage
* docs: Edits to value description
* docs: Add how-to for creating new target
* docs: Add procedure to update existing alias from CLI
* docs: Update targets domain model topic
* docs: Fix spelling
* docs: Remove ferry references
* docs: Remove note about aliases not working with generic commands
* docs: Updates to naming conventions
* switches Tabs order and adds tab groups
* fixes shell-session line breaks
* Apply batch of suggestions from code review
* docs: Delete redundant sentence
* docs: Fix jump links
---------
> docs: Aliases overview, domain model, CLI docs (#4705)

- website/content/docs/configuration/session-recording/enable-session-recording.mdx
> docs: fix broken session recording link

- internal/gen/controller.swagger.json
- internal/gen/controller/api/services/session_recording_service.pb.go
- internal/proto/controller/api/resources/sessionrecordings/v1/session_recording.proto
- internal/proto/controller/api/services/v1/session_recording_service.proto
- sdk/pbs/controller/api/resources/session_recordings/session_recording.pb.go
Adds observation tags to fields Session Recording Servicemessages.
> Add observation tags for Session Recording Service

- CHANGELOG.md
Adds the telemetry work done in ICU-13864 to the changelog for release 0.16.1.
> docs: Add new telemetry to changelog

- plugins/boundary/mains/minio/go.mod
- plugins/boundary/mains/minio/go.sum
This PR backports the main commit to the `release/0.16.x` branch
> feat(plugins): Update MinIO plugin to v0.1.3 (#4887)

- go.mod
- go.sum
- internal/daemon/worker/auth_rotation.go
- internal/daemon/worker/auth_rotation_test.go
- internal/server/repository_workerauth.go
- internal/server/repository_workerauth_test.go
Note: this is waiting on the corresponding nodee changes; test will fail until the node deps are updated here
> worker auth: use new previous pkix field

- internal/ui/VERSION
This sets the UI to use the latest version (includes some attribute changes for e2e tests)
> chore: Update UI version

- internal/ui/VERSION
> chore: bump ui commit to cc0edf3

- website/content/docs/configuration/session-recording/configure-worker-storage.mdx
document new remote storage state on the worker
> docs: remote storage state

- CHANGELOG.md
add new features and bugfixes for the 0.17.0 changelog
> 0.17.0 Changelog

- CHANGELOG.md
- plugins/boundary/mains/minio/go.mod
- plugins/boundary/mains/minio/go.sum
fixes https://github.com/hashicorp/boundary/issues/5004
> Fix Minio Plugin Upload Large Session Recordings

- internal/daemon/controller/interceptor.go
Update GRPC Gateway tickets to compare tickets in constant-time
> fix: constant-time comparison of grpc-gateway tickets

- CHANGELOG.md
I will add the changelog changes to the release branches after this PR is approved. Adding all authors of the PRs to verify the changelog additions.
> Update changelog for `0.16.3` & `0.17.1`

- enos/README.md
This PR updates the enos readme to assist with new user setup.
https://hashicorp.atlassian.net/browse/ICU-14375
> doc(e2e): Update enos readme

- internal/bsr/ssh/chunk_decode_test.go
> update bsr tests to use ::1

- website/content/docs/configuration/session-recording/create-storage-bucket.mdx
This PR adds:
- Terraform tabs for the minio and s3-compliant storage tabs
- links to the worker filters examples page
Deploy preview:
https://boundary-9f89998da-hashicorp.vercel.app/boundary/docs/configuration/session-recording/create-storage-bucket
> Rab create bucket add filters link

- internal/clientcache/cmd/cache/wrapper_register.go
Restart the client cache if it is found to be a version below the version of the CLI during client cache hook execution.
> internal/clientcache/cmd/cache: restart cache on version mismatch

- website/content/docs/configuration/session-recording/configure-worker-storage.mdx
- website/content/docs/configuration/session-recording/enable-session-recording.mdx
Backports #5195 to the `release/0.18.x` branch.
> docs: Session recording updates (#5195)

- internal/daemon/cluster/handlers/worker_service.go
- internal/daemon/controller/handlers/workers/worker_service_test.go
- internal/server/repository_worker.go
- internal/server/repository_worker_test.go
- internal/server/testing.go
- internal/session/job_session_cleanup_test.go
CE changes for https://github.com/hashicorp/boundary-enterprise/pull/1295
> refact(server): return worker id from UpsertWorkerStatus

- website/content/docs/overview/use-cases.mdx
- website/content/docs/overview/vs/bastion-hosts.mdx
- website/content/docs/overview/vs/other-software.mdx
- website/content/docs/overview/vs/pam.mdx
- website/content/docs/overview/vs/sdp.mdx
- website/content/docs/overview/vs/secrets-management.mdx
- website/content/docs/overview/vs/vpn.mdx
- website/content/docs/overview/vs/zero-trust.mdx
- website/content/docs/overview/what-is-boundary.mdx
Updates the page level meta content for all pages in the **Overview** section of the docs.
> docs: Update meta content - Overview

- website/content/docs/install-boundary/architecture/fault-tolerance.mdx
- website/content/docs/install-boundary/architecture/high-availability.mdx
- website/content/docs/install-boundary/architecture/recommended-architecture.mdx
- website/content/docs/install-boundary/architecture/system-requirements.mdx
- website/content/docs/install-boundary/configure-controllers.mdx
- website/content/docs/install-boundary/configure-workers.mdx
- website/content/docs/install-boundary/index.mdx
- website/content/docs/install-boundary/initialize.mdx
- website/content/docs/install-boundary/install.mdx
- website/content/docs/install-boundary/terraform-patterns/index.mdx
- website/content/docs/install-boundary/terraform-patterns/terraform-credentials-and-credential-stores.mdx
- website/content/docs/install-boundary/terraform-patterns/terraform-groups-and-rbac.mdx
- website/content/docs/install-boundary/terraform-patterns/terraform-hosts-and-host-management.mdx
- website/content/docs/install-boundary/terraform-patterns/terraform-scopes.mdx
- website/content/docs/install-boundary/terraform-patterns/terraform-session-recording.mdx
- website/content/docs/install-boundary/terraform-patterns/terraform-targets.mdx
- website/content/docs/install-boundary/terraform-patterns/terraform-users-and-auth-methods.mdx
Updates the page level meta content for all pages in the **Install Boundary** section in the docs.
> docs: Update meta content - Install

- website/content/docs/getting-started/dev-mode/connect-to-dev-target.mdx
- website/content/docs/getting-started/dev-mode/dev-mode.mdx
- website/content/docs/getting-started/dev-mode/run-and-login.mdx
- website/content/docs/getting-started/index.mdx
Updates the page level meta content for all pages in the **Get started** section of the docs.
> docs: Update meta content - Getting started

- CHANGELOG.md
I missed Gaffneys scheduler batch fix
> more 0.18.x changelog

- plugins/boundary/mains/gcp/go.mod
- plugins/boundary/mains/gcp/go.sum
This picks up latest GCP Plugin bug fixes
> chore: bump gcp plugin dependency

- website/content/docs/release-notes/v0_18_0.mdx
Documents the update for inc-3800
[View the update in the preview deployment](https://boundary-3qyx6y69m-hashicorp.vercel.app/boundary/docs/release-notes/v0_18_0#known-issues-and-breaking-changes)
> docs: Add resolved issue to release notes

- enos/modules/docker_openssh_server_ca_key/custom-cont-init.d/00-trust-user-ca
- enos/modules/docker_openssh_server_ca_key/custom-cont-init.d/01-allow-tcp-forwarding
- enos/modules/docker_openssh_server_ca_key/main.tf
The linux openssh server docker container made some directory changes in a recent update. This broke some of our e2e tests. These changes assist in resolving those failures.
There will be a follow-up PR in boundary-enterprise.
> test(e2e): Update openssh module to account for image changes

- CODEOWNERS
The old group only contains a service account. I removed this code owner to unblock us.
> Update release dir owner group

- website/content/docs/release-notes/index.mdx
- website/content/docs/release-notes/v0_10_0.mdx
- website/content/docs/release-notes/v0_11_0.mdx
- website/content/docs/release-notes/v0_12_0.mdx
- website/content/docs/release-notes/v0_13_0.mdx
- website/content/docs/release-notes/v0_14_0.mdx
- website/content/docs/release-notes/v0_15_0.mdx
- website/content/docs/release-notes/v0_16_0.mdx
- website/content/docs/release-notes/v0_17_0.mdx
- website/content/docs/release-notes/v0_18_0.mdx
- website/content/docs/release-notes/v0_1_0.mdx
- website/content/docs/release-notes/v0_2_0.mdx
- website/content/docs/release-notes/v0_3_0.mdx
- website/content/docs/release-notes/v0_4_0.mdx
- website/content/docs/release-notes/v0_5_0.mdx
- website/content/docs/release-notes/v0_6_0.mdx
- website/content/docs/release-notes/v0_7_0.mdx
- website/content/docs/release-notes/v0_8_0.mdx
- website/content/docs/release-notes/v0_9_0.mdx
Updates the page level meta content for all pages in the **Release notes** section in the docs.
> docs: Update meta content - Release notes

- website/content/docs/developing/building.mdx
- website/content/docs/developing/index.mdx
- website/content/docs/developing/ui.mdx
- website/content/docs/integrations/index.mdx
- website/content/docs/integrations/vault/index.mdx
Updates the page level meta content for all pages in the **Integrations** and **Develop Boundary** sections in the docs.
> docs: Update meta content - Integrations and Develop Boundary

- website/content/docs/api-clients/api/index.mdx
- website/content/docs/api-clients/api/pagination.mdx
- website/content/docs/api-clients/api/rate-limiting.mdx
- website/content/docs/api-clients/client-agent.mdx
- website/content/docs/api-clients/client-cache.mdx
- website/content/docs/api-clients/desktop.mdx
- website/content/docs/api-clients/go-sdk.mdx
- website/content/docs/api-clients/index.mdx
Updates the page level meta content for all pages in the **API and Clients** section in the docs.
> docs: Update meta content - API and clients

- website/content/docs/troubleshoot/common-errors.mdx
- website/content/docs/troubleshoot/faq.mdx
- website/content/docs/troubleshoot/troubleshoot-recorded-sessions.mdx
Updates the page level meta content for all pages in the **Troubleshoot** section in the docs.
> docs: Update meta content - Troubleshoot

- website/content/docs/operations/health.mdx
- website/content/docs/operations/index.mdx
- website/content/docs/operations/metrics.mdx
- website/content/docs/operations/session-recordings/index.mdx
- website/content/docs/operations/session-recordings/manage-recorded-sessions.mdx
- website/content/docs/operations/session-recordings/validate-data-store.mdx
- website/content/docs/operations/session-recordings/validate-session-recordings.mdx
Updates the page level meta content for all pages in the **Operations** section in the docs.
> docs: Update meta content - Operations

- CHANGELOG.md
- website/content/docs/concepts/host-discovery/gcp.mdx
- website/content/docs/concepts/host-discovery/index.mdx
- website/data/docs-nav-data.json
- Add documentation for GCP dynamic host catalog
- Add changelog for GCP dynamic host catalog
> docs: Add docs for GCP DHC

- internal/daemon/worker/testing.go
Unfortunately, this started causing the enterprise tests to break in an unexpected way. Reverting to spend some more time testing the changes.
> Revert "internal/daemon: speed up multi-worker tests (#5370)"

- internal/daemon/worker/auth_rotation_test.go
TestRotationTicking would previously wait for 5 rotations, which is pretty slow considering each rotation takes 20 seconds. Reduce the number to 3, and use require instead of assert to remove noise during flaky test runs.
This doesn't fix the flakiness of this test, but it should reduce the log spam.
> internal/daemon/worker: improve runtime and reduce noise

- internal/session/job_session_cleanup.go
The totalClosed variable was access in both the Status and the Run functions, which may be called from independent goroutines.
> internal/session: fix race condition in connection cleanup

- CHANGELOG.md
Update CHANGELOG with an entry detailing the fix merged in #5396
> docs(CHANGELOG): Add session connection limit fix

- Dockerfile
Should hopefully resolve the wget warning (see https://github.com/hashicorp/crt-workflows-common/actions/runs/12641806438/job/35225836565)
> Dockerfile: bump alpine version

- internal/event/cloudevents_formatter_node.go
- internal/event/cloudevents_formatter_node_test.go
The cloud events formatter Process function would call the signer without protecting it, which was racy with the Rotate function.
> internal/event: fix log processor race

- internal/ui/VERSION
In preparation for 0.19.0 release.
> bump-ui-commit-904864b14

- internal/daemon/controller/handlers/host_sets/grants_test.go
- internal/daemon/controller/handlers/host_sets/host_set_service.go
set the ParentScopeId before fetching authorized actions for host-set resource
> fix(host-set): set parent scope id for host-set resource

- CHANGELOG.md
Add UI changelog entries for 0.19.0 release.
N/A
> Add ui changelog entries for 0.19.0 release

- CHANGELOG.md
> chore: update changelog for version 0.19.0 and reorganize bug fixes

- internal/ui/VERSION
In preparation for the 0.19.0 release.
> bump ui commit 064375d45

- internal/ui/VERSION
In preparation for 0.19.0 release.
N/A
> bump ui commit fed32aa57

- internal/alias/target/repository_alias_list_resolvable.go
The original refresh queries contained a sub-select that was performing a full table scan on the target table. This scan was time consuming given the number of targets. It was also unnecessary given the constraints on the target alias table, where it is sufficient to simply filter by destination_id = null, which was also already included in the query. This unnecessary sub-select was removed
> fix(alias): remove unnecessary subquery from alias refresh

- internal/ui/VERSION
In preparation for 0.19.0 release.
N/A
> bump ui commit 639aa47e1

- internal/daemon/worker/worker.go
Enable worker to run GCP host plugin
> fix(worker): add GCP plugin support on the worker

- internal/ui/VERSION
This PR fixes a bug reported, in preparation for 0.19.0 release.
N/A
> bump ui commit c72d4f35a

- internal/ui/VERSION
> bump ui commit ae1e6d2

- website/content/docs/commands/credentials/index.mdx
Added note about `Boundary credentials` command not supporting vault cred store
> Update index.mdx, added note about credentials command

- internal/ui/VERSION
In preparation for 0.19.0 release.
> bump ui commit 835b302c1

- .release/security-scan.hcl
Add currently open vulnerabilities to suppression list
> ci(security-scanner): Triage open vulnerabilities

- internal/auth/ldap/repository_auth_method_create.go
- internal/auth/oidc/repository_auth_method.go
- internal/auth/oidc/repository_auth_method_create.go
- internal/auth/oidc/repository_managed_group_members.go
- internal/auth/repository_auth_method.go
- internal/credential/repository_store.go
- internal/credential/vault/jobs.go
- internal/credential/vault/vault_token.go
- internal/daemon/controller/handler.go
- internal/host/options.go
- internal/host/options_test.go
- internal/host/plugin/job_set_sync.go
- internal/host/plugin/options.go
- internal/host/plugin/options_test.go
- internal/host/plugin/repository_host_catalog.go
- internal/host/plugin/repository_host_set.go
- internal/host/repository_catalog.go
- internal/host/static/repository_host.go
- internal/iam/repository.go
- internal/iam/repository_grant_scope.go
- internal/iam/repository_role.go
- internal/iam/repository_role_grant.go
- internal/iam/repository_user.go
- internal/oplog/writer.go
- internal/server/options.go
- internal/server/options_test.go
- internal/server/repository_worker.go
- internal/server/repository_worker_storage_bucket_credential_state.go
This is a manual backport of the following [PR](https://github.com/hashicorp/boundary/commit/acc40e0d08641fdd557f671e89493bf72136f285). We need to manually apply these changes to 0.18.x because the worker domain refactor is not apart of the 0.18.x branch.
> backport fixes for the database transactions issue

- internal/auth/ldap/repository_auth_method_create.go
- internal/auth/oidc/repository_auth_method.go
- internal/auth/oidc/repository_auth_method_create.go
- internal/auth/oidc/repository_managed_group_members.go
- internal/auth/repository_auth_method.go
- internal/credential/repository_store.go
- internal/credential/vault/jobs.go
- internal/credential/vault/vault_token.go
- internal/daemon/controller/handler.go
- internal/host/options.go
- internal/host/options_test.go
- internal/host/plugin/job_set_sync.go
- internal/host/plugin/options.go
- internal/host/plugin/options_test.go
- internal/host/plugin/repository_host_catalog.go
- internal/host/plugin/repository_host_set.go
- internal/host/repository_catalog.go
- internal/host/static/repository_host.go
- internal/iam/repository.go
- internal/iam/repository_grant_scope.go
- internal/iam/repository_role.go
- internal/iam/repository_role_grant.go
- internal/iam/repository_user.go
- internal/oplog/writer.go
- internal/server/options.go
- internal/server/options_test.go
- internal/server/repository_worker.go
- internal/server/repository_worker_storage_bucket_credential_state.go
This is a manual backport of the following [PR](https://github.com/hashicorp/boundary/commit/acc40e0d08641fdd557f671e89493bf72136f285). We need to manually apply these changes to 0.17.x because the worker domain refactor is not apart of the 0.17.x branch.
> backport database transaction fix

- website/content/docs/release-notes/v0_19_0.mdx
Updates the release date on the release notes.
> docs: Update release date

- CHANGELOG.md
Update changelog with date and security fixes
> chore: 0.19.x changelog update

- testing/internal/e2e/tests/base/search_test.go
This PR updates the e2e search test to catch an issue fixed by this PR: https://github.com/hashicorp/boundary/pull/5549. (it addresses an issue where the desktop client would be unable to search on close/reopen). This PR adds the following...
- log out and confirm you CANNOT use search
- while logged in, restart the cache and confirm you CAN search
- log out and restart cache. log back in and confirm you CAN search
https://hashicorp.atlassian.net/browse/ICU-16380
Confirmed that this test fails using a build prior to the linked fix. 
Confirmed that this passes when the fix is included.
> test(e2e): Update search test to catch bug

- website/content/docs/concepts/domain-model/storage-policy.mdx
> docs: Fix a typo in page title

- website/content/docs/getting-started/index.mdx
Revises the description of HCP Boundary in the Get started topic.
[View the preview deployment](https://boundary-b5lo2e26n-hashicorp.vercel.app/boundary/docs/getting-started)
> docs: Revise description of HCP Boundary

- internal/db/schema/migrations/oss/postgres/100/01_iam_role_global.up.sql
- internal/db/schema/migrations/oss/postgres/100/02_iam_role_org.up.sql
- internal/db/schema/migrations/oss/postgres/100/03_iam_role_project.up.sql
add name-scope unique constraint to all role subtypes
> Grants: SQL: add missing unique index

- internal/auth/oidc/auth_method.go
- internal/auth/oidc/auth_method_test.go
- internal/auth/oidc/provider_test.go
- internal/clientcache/internal/cache/consts.go
- internal/clientcache/internal/cache/repository_token_test.go
- internal/cmd/commands/aliasescmd/funcs.go
- internal/cmd/commands/connect/connect.go
- internal/daemon/controller/handlers/accounts/account_service.go
- internal/daemon/controller/handlers/accounts/account_service_test.go
- internal/daemon/controller/handlers/host_sets/host_set_service.go
- internal/oplog/testing.go
- internal/types/subtypes/attributes_test.go
Found a few more instances of dead code (not used in ENT)
> chore: remove more dead code

- internal/ui/VERSION
bump ui commit to fix workflow errors and allow expired artifacts to be rebuilt.
no ui changes!
> bump ui commit to cef0424

- testing/internal/e2e/tests/aws/dynamichostcatalog_host_set_test.go
Modified Dynamic Host catalog test to use credential store rather than user/key to connect to target. 
Jira: https://hashicorp.atlassian.net/browse/ICU-16904
Test output:
=== RUN   TestCliCreateAwsDynamicHostCatalogWithHostSet
scope.go:85: Created Org Id: o_AfpNU4bkvh
scope.go:127: Created Project Id: p_w8G9VbXVy1
host.go:251: Created Host Catalog: hcplg_xuXFIgFVDB
host.go:303: Created Host Set: hsplg_iXGEm9PYxt
host.go:353: Looking for items in the host set...
host.go:383: Found 2 host(s)
host.go:303: Created Host Set: hsplg_A5z86aznPL
host.go:353: Looking for items in the host set...
host.go:383: Found 1 host(s)
dynamichostcatalog_host_set_test.go:73: Updating host set 2 with host set 1's filter...
host.go:353: Looking for items in the host set...
host.go:383: Found 2 host(s) …
> test(e2e): Added credential store to host catalog test

- CHANGELOG.md
Manual cherry-pick of [88fca27](https://github.com/hashicorp/boundary/commit/88fca27c2da1a400e421a4fc43bd88953d490606) to resolve merge conflict in this [backport PR](https://github.com/hashicorp/boundary/pull/5698)
> backport: update CHANGELOG with ui entries

- enos/modules/aws_target/main.tf
This PR is a backport of #5672 into `release/0.19.x`
> Backport of chore(e2e): Add encryption to target ec2 instance into release/0.19.x

- website/content/docs/troubleshoot/troubleshoot-recorded-sessions.mdx
The troubleshooting topic for session recording has a sentence fragment. This PR completes the sentence.
[View the update in the preview deployment](https://boundary-nyzrrrnr0-hashicorp.vercel.app/boundary/docs/troubleshoot/troubleshoot-recorded-sessions).
> docs: Fix incomplete sentence

- internal/iam/query.go
- internal/iam/repository_role_grant.go
- internal/iam/repository_role_grant_test.go
add query to fetch grants for a user for resources that are only org scoped
> feat: grantsForUser for Org resources

- internal/iam/query.go
- internal/iam/repository_role_grant.go
- internal/iam/repository_role_grant_test.go
Add query to fetch grants for a user for resources that are only project scoped. Also remove some extra whitespace in `grantsForUserOrgResourcesQuery`
> feat: grantsForUser for Project resources

- internal/db/schema/migrations/oss/postgres_96_03_test.go
also make sure project roles are correctly added
> update tests to not check a table that will be dropped in the migration

- internal/daemon/controller/handlers/scopes/grants_test.go
Grants tests against the scopes service
> add grants tests for scope resource

- internal/cmd/commands/connect/postgres.go
Small fix to close passfile unconditionally for postgres command
> Closing file unconditionally

- internal/ui/VERSION
Bump ui commit (bd1b854) for 0.19.3 release.
> bump ui commit bd1b854

- testing/internal/e2e/infra/docker.go
- testing/internal/e2e/tests/base/target_tcp_connect_mysql_test.go
> Bgajjala mysql e2etest v2

- website/content/docs/concepts/domain-model/aliases.mdx
- website/content/docs/concepts/domain-model/index.mdx
Also fix a typo in the Aliases page.
> docs: add Alias, Storage Policy to domain model overview

- internal/cmd/commands/connect/cassandra.go
- Update the UI warning to display they correct command flag.
> Cassandra Connect Warn Hotfix

- testing/internal/e2e/infra/docker.go
Update the wait in the health check in the caller start cassandra function.
> Update Test Func Hotfix

- website/content/docs/concepts/transparent-sessions.mdx
- website/content/docs/configuration/target-aliases/interoperability-matrix.mdx
- website/content/docs/release-notes/v0_19_0.mdx
Version 0.19.6 of the Client Agent was released last week. The new release resolved 2 of the known issues with transparent sessions. The new release was also tested for compatibility with third-party products.
This PR updates the Client Agent/transparent sessions docs to reflect those changes:
- Deletes the 2 known issues that were resolved from the Transparent sessions > [Known issues](https://boundary-56cxrr5s5-hashicorp.vercel.app/boundary/docs/concepts/transparent-sessions#known-issues) documentation
- Documents the resolution of the known issues in the Release notes > [Known issues](https://boundary-56cxrr5s5-hashicorp.vercel.app/boundary/docs/release-notes/v0_19_0#known-issues-and-breaking-changes) section
- Updates the [Interoperability …
> docs: Client Agent 0.19.6 updates

- enos/modules/aws_rdp_domain_controller/main.tf
This PR updates the domain controller module to ensure that it reboots after creating the domain. 
> chore(e2e): Ensure domain controller reboots

- website/content/security.mdx
- website/redirects.js
> [DOCS] Troubleshooting redirects

- website/content/docs/index.mdx
> [DOCS] Small content change

- website/content/docs/index.mdx
> docs: Back port #6016 to stable-website

- internal/ui/VERSION
Bump internal/ui/VERSION commit to 46d477e
> Bump internal/ui/VERSION commit

- internal/db/schema/migrations/oss/postgres/99/01_credential_static_password_credential.up.sql
DB migration to create new tables for password credential type
> feat(db): Add new tables for password credential type

- website/content/docs/credentials/static-cred-boundary.mdx
This PR fixes a broken link on the `credentials/static-cred-boundary` page.
> fixes broken link
