hashicorp/boundary

- internal/servers/controller/handler_test.go
This fixes a dropped test error in `internal/servers/controller/`.
> internal/servers/controller: fix dropped test error

- website/content/docs/getting-started/index.mdx
- website/pages/docs/[[...page]].jsx
The "Edit this page" link actually still links to 'master' branch
but that seems to be a harder problem to solve as the template
seems to be shared.
> docs: Fix a typo & broken link

- website/content/docs/installing/high-availability.mdx
Fixing typo (missing word in sentence) in high-availability installation guide
> Fix typo in docs

- website/package-lock.json
- website/package.json
This PR updates the `<HashiStackMenu />` 
[🔍  Preview link](https://boundary-git-jmbump-hsm-version-107.hashicorp.vercel.app)
> [Website] Bump HSM version to include waypoint

- Makefile
- README.md
`make dev` requires `build-ui` which executes a script that requires `go-bindata` binary that isn't installed without executing `make tools`. This pr ensures the `tools` make target is executed first.
> ensure make tools executes before build-ui

- website/.env
Vercel will build previews for all PRs (incl forks) as long as we don't include env vars in the Vercel UI. This moves our one and only env var to a `.env` file.
> Add env file for vercel vars

- website/vercel.json
This will make build logs for deploy previews public which should allow easier troubleshooting for contributors. 
Appending `/_logs` to the deploy preview URL will show the Vercel build logs.
> Set vercel config

- website/content/docs/getting-started/run-and-login.mdx
Also adds tabs to cleanup the CLI/UI/TF flows for getting started.
> docs: add details on not saving token to system key manager

- website/components/temporary_docs-page/index.jsx
Right now we're using a codename for our product name (which will be updated back to boundary in the near future).  Plugging this hardcoded hotfix to get our "Edit this Page" button working again, while keeping our styles working.
> Fix link to 'Edit this Page' for Docs

- CHANGELOG.md
- internal/cmd/common/help.go
> Fix hyphenation of resource subcommand output

- website/content/docs/common-workflows/manage-targets.mdx
host_catalog_id was doubled in hcl code snippet.
> Fix typo in target documentation

- CHANGELOG.md
- internal/cmd/base/listener.go
- internal/cmd/base/servers.go
- internal/cmd/commands/connect/connect.go
- internal/cmd/commands/dev/dev.go
- internal/servers/controller/listeners.go
- internal/servers/controller/testing.go
- internal/servers/worker/controller_connection.go
- internal/servers/worker/handler.go
- internal/servers/worker/listeners.go
- internal/tests/cluster/ipv6_listener_test.go
- internal/tests/cluster/unix_listener_test.go
The client already supports protocol-agnostic transport so handles unix:/// schemes.
Fixes #699
> Support for Unix domain socket listeners

- internal/servers/controller/handlers/accounts/account_service_test.go
This fixes two dropped `err` variables.
> internal/servers/controller/handlers/accounts: fix dropped test errors

- CHANGELOG.md
- internal/docker/supported.go
Allows connecting to the postgres container forked in `dev` mode to be accessed from a remote docker host if set. 
Fixes https://github.com/hashicorp/boundary/issues/720
> feat: override PG host Docker-advertised address when set

- CHANGELOG.md
- internal/cmd/base/listener.go
We have behavior that causes "0.0.0.0" to only listen on IPv4, however,
it also assumed there was a port suffixed. This changes it so that it
also works with a port-less address.
> Fix IPv4-only check when no port is specified

- .github/workflows/backport.yml
`backport-assistant` enables us to merge documentation around future releases into `main`, and selectively automerge documentation for the current release into `stable-website.`
If there are no merge conflicts it will create and automerge the targeted PR into stable-website - [example automerged PR](https://github.com/krantzinator/waypoint/pull/3)
If there are merge conflicts, it will leave the PR open - [example open PR](https://github.com/krantzinator/waypoint/pull/5)
This action runs if a merged PR has the label `website/cherrypick` (which I created prior to opening this PR), and it targets the branch `stable-website` for automerging.
I also added the referenced secret to the repo Secrets.
> add workflow file for backport-assistant github action

- internal/servers/controller/handlers/groups/group_service_test.go
This fixes a dropped test error.
> internal/servers/controller/handlers/groups: fix dropped test error

- website/content/docs/installing/no-gen-resources.mdx
My nvim setup appears to have removed a bunch of trailing spaces as well. The only change I was interested in addressing was at line 345.
> docs: update installation steps with templated account.id grant string

- internal/ui/VERSION
This bumps the commit hash for the UI for the upcoming v0.1.2 release.
> ui: bump UI release commit for 0.1.2

- Makefile
- scripts/errorid.go
Small go file to generate unique error IDs (10 digit alpha-numeric)
Adds `make rand` to make file to print above-mentioned IDs
The output of successful `make rand`:
```
$ make rand
==> Generating random boundary error ID
7w4DR9AmwJ
$ make rand
==> Generating random boundary error ID
6xLoaB7ocE
```
introducing a `fake error` to show the failure case:
```
$ make rand
==> Generating random boundary error ID
failed to generate errorID: fake error
exit status 1
Makefile:31: recipe for target 'rand' failed
make: *** [rand] Error 1
```
> Create common errorID generation

- internal/errors/error.go
- internal/errors/error_test.go
- internal/errors/is_test.go
- internal/errors/match.go
- internal/errors/match_test.go
- internal/errors/option.go
- internal/errors/option_test.go
- internal/errors/sentinels.go
Refactors boundary domain errors to include the new `errorId` field
Removes withOp option
Adds a new `errors.Wrap` function
Updated and added new unit tests
Deprecate sentinel errors, with the addition of the `errorId` sentinel errors no longer provide adequate information to be uniquely identified
> Refactor domain error to use errorId

- Makefile
- docker/Release.dockerfile
Updates the docker build to 0.1.2 and adds the docker build step for tagging and publishing `latest`.
> Update docker build to 0.1.2

- website/content/docs/concepts/domain-model/roles.mdx
Fixes misleading documentation surfaced in https://discuss.hashicorp.com/t/documentation-inconsistent-about-roles-at-org-level-project-level/17859.
> docs: fix misleading statement about what scope a role can be created

- CHANGELOG.md
- internal/cmd/base/base.go
Fixes #791 
There were two avenues I considered for this:
1. Check `c.flagFormat` and print the info level statement if the value is not `json` or `yaml`
1. Remove the info level output all together
I went with #2 because it was more simple, but I'm open to other possible paths too.
> fix: do not print info in output that could be JSON or YAML format

- CHANGELOG.md
- internal/auth/password/repository_account.go
- internal/auth/password/repository_account_test.go
Resolves #759 
Relaxes the regex constraint to allow `-` (dash) as a valid character in an account login name
Updated unit tests
I verified that password do accept all characters mentioned in the issue (hyphen, underscore and period)
Performed manual testing:
Before changes:
```
boundary accounts create password -auth-method-id ampw_1234567890 -login-name admin-tester
Password is not set as flag, please enter it now (will be hidden):
Error from the controller when performing create on password-type account:
Error information:
Code:                Internal
Error ID:            YqlVyFuvqc
Message:
Status:              500
```
Server logs error:
```
2020-12-01T13:10:23.671-0800 [ERROR] controller: internal error returned: error id=YqlVyFuvqc error="unable to create user: create: password …
```
> Allow dash in account name

- CHANGELOG.md
- internal/cmd/commands/database/init.go
- internal/cmd/commands/dev/dev.go
This makes the initial testing workflow less confusing for users
> Switch connection limit for default target to -1

- website/content/docs/configuration/worker.mdx
This fixes: The address wrongly being documented as part of the `worker` block, despite belonging into the listener
> Move listener address in worker config example

- CHANGELOG.md
- internal/cmd/commands/server/server.go
Fixes the issue raised at https://www.boundaryproject.io/docs/configuration/worker#complete-configuration-example
> Remove erronious IsGlobalUnicast check.

- internal/db/read_writer_test.go
- internal/db/timestamp/scanners_test.go
- internal/kms/repository_test.go
- internal/oplog/oplog_test.go
- internal/oplog/queue_test.go
- internal/oplog/ticketer_gorm_test.go
- internal/oplog/type_catalog_test.go
- internal/oplog/writer_test.go
- internal/session/repository_test.go
- internal/target/repository_test.go
Updates a number of usages of `assert.Equal` where error checks incorrectly had `actual` as the first paramter and `expected` as the second parameter.  This avoids confusing error messages in failed tests such as:
```
Not equal: 
expected: "actual error string"
actual  : "expected error string"
```
> Correct assert.Equal actual/expected

- CHANGELOG.md
- Makefile
- api/accounts/account.gen.go
- api/accounts/option.gen.go
- api/authmethods/authmethods.gen.go
- api/authmethods/option.gen.go
- api/authtokens/authtokens.gen.go
- api/authtokens/option.gen.go
- api/client.go
- api/groups/group.gen.go
- api/groups/option.gen.go
- api/hostcatalogs/host_catalog.gen.go
- api/hostcatalogs/option.gen.go
- api/hosts/host.gen.go
- api/hosts/option.gen.go
- api/hostsets/host_set.gen.go
- api/hostsets/option.gen.go
- api/options.go
- api/roles/option.gen.go
- api/roles/role.gen.go
- api/scopes/option.gen.go
- api/scopes/scope.gen.go
- api/sessions/option.gen.go
- api/sessions/session.gen.go
- api/targets/option.gen.go
- api/targets/target.gen.go
- api/users/option.gen.go
- api/users/user.gen.go
- internal/api/genapi/templates.go
This makes it so that the actual output is the update/delete.
Fixes #856
> Skip curl output when using automatic versioning and reading

- internal/ui/VERSION
While there are no user-facing changes in admin, let's bump the commitish anyway to stay up-to-date.
> chore: bump ui commitish to latest from boundary-ui/main

- api/client.go
The client from go-cleanhttp does not set TLSClientConfig. This can be a possible fix or go-cleanhttp can create the config at client creation.
> Fix nil TLSClientConfig

- CHANGELOG.md
- internal/cmd/commands/server/server.go
Right now you don't need to specify a controller address and we use the
cluster listener address; this allows overriding it to the
public_cluster_addr if one is given.
If `controllers` is specified we allow it to be either the cluster
listener or the public cluster address if one is specified before trying
to parse and use it.
> When running single-server mode, use public_cluster_addr if given

- docker/config.hcl
- Removes the `controllers` setting from the worker configuration because in docker we're running in single server mode
- Updates the bind address for all listeners to localhost
Fixes issue #903
Important caveats:
- When running in docker this requires `--hostname boundary` to be passed in on `docker run`
We will be adding the ability to use env:// in the listener address field in 0.1.6.
> update docker config for boundary to remove the controllers setting

- CHANGELOG.md
- internal/cmd/base/initial_resources.go
- internal/cmd/commands/scopes/funcs.go
- internal/iam/repository_scope.go
Adds `read` action to default scope role grants
Removes additional `s` from authorized actions in table view output (an `s` was being added in both the `populateCollectionAuthorizedActions` func and the print)
```
boundary scopes read -id global
Scope information:
Created Time:        Thu, 04 Feb 2021 14:07:08 PST
ID:                  global
Name:                global
Updated Time:        Thu, 04 Feb 2021 14:07:53 PST
Version:             2
Scope (parent):
ID:                global
Name:              global
Type:              global
read
Authorized Actions on Scope's Collections:
auth-methodss:
list
scopess:
list
```
> Scope role grants

- internal/types/action/action.go
- internal/types/resource/resource.go
- internal/types/scope/scope.go
The internal types `action.Type`, `resource.Type`, and `scope.Type` all start at zero, but aren't the same integer type. This is to align them all on `uint`.
> Use uint for internal types

- go.mod
- internal/cmd/base/initial_resources.go
- internal/cmd/base/ui.go
- internal/servers/controller/handlers/targets/target_service.go
This prevents a session being created when no workers are available to
handle it.
> Move worker selection above session creation

- CONTRIBUTING.md
- Makefile
- README.md
Howdy,
Some other Hashicorp products ([Waypoint](https://github.com/hashicorp/waypoint#running-the-unit-tests),[Consul](https://github.com/hashicorp/consul/blob/master/.github/CONTRIBUTING.md#testing),[Terraform](https://github.com/hashicorp/terraform/blob/master/.github/CONTRIBUTING.md#acceptance-tests-testing-interactions-with-external-services),[Nomad](https://github.com/hashicorp/nomad#testing),[Vault](https://github.com/hashicorp/vault#developing-vault), [Packer](https://github.com/hashicorp/packer/blob/master/.github/CONTRIBUTING.md#running-unit-tests),[Vagrant](https://github.com/hashicorp/vagrant/blob/main/.github/CONTRIBUTING.md#running-tests)) provide testing documentation in either their main readme or contributing documentation to help both operators and developers alike. We …
> Add testing section for individual/user testing 

- CHANGELOG.md
- internal/db/schema/migrations/postgres/1/01_server_tags_migrations.up.sql
- internal/db/schema/postgres_migration.gen.go
- internal/docker/supported.go
This fixes an issue with running migrations (likely in 0.1.5 and 0.1.6) against Postgres 11.
It also changes our dev environment to be using the PG 11 Docker image rather than PG 12.
> Fix migration for Postgres 11

- scripts/uiclone.sh
- When using a branch name rather than a commit, the branch was not being
updated to the latest version.
> fix 'make update-ui-version'

- website/package-lock.json
- website/package.json
- website/pages/community/index.jsx
This PR bumps `@hashicorp/react-vertical-text-block-list` and `@hashicorp/react-hero` to recently published versions which do not process markdown within the component.
- [`/` (home page)](https://boundary-git-zsbump-components.hashicorp.vercel.app/), should be identical to [live site](https://www.boundaryproject.io/)
- [`/community`](https://boundary-git-zsbump-components.hashicorp.vercel.app/community), should be identical to [live site](https://www.boundaryproject.io/community)
> Bumps components to remove internal md processing

- internal/db/schema/manager_test.go
This fixes a dropped test error in `internal/db/schema`.
> internal/db/schema: fix dropped test error

- internal/kms/kms.go
- internal/kms/kms_ext_test.go
- internal/kms/kms_test.go
- internal/kms/repository_root_key.go
- internal/servers/controller/handlers/workers/worker_service.go
- internal/session/repository_session.go
- internal/session/repository_session_test.go
- internal/session/session.go
Currently this would validate that a KeyId was in the returned wrapper
but then return the base wrapper; and if it required a database lookup
it wouldn't validate it anyways.
All uses of this were for decryption so it didn't actually affect
anything to this point (because of the multiwrapper) but for any
case where we need to _encrypt_ against a specific version or derive a key
against a specific version this would be broken because you'd end up using the base of the multiwrapper -- unless you then casted to a multiwrapper, pulled out the wrapper you wanted, and did it that way. That's a lot for implementers to know so it makes sense to just return that wrapper if the option is given.
This also properly sends the Key ID around sessions. This worked
currently for the same reason as above …
> Fix WithKeyId option

- internal/auth/oidc/repository_auth_method_update.go
- internal/auth/oidc/repository_auth_method_update_test.go
This PR resolves a TODO for updates around errors for incomplete auth methods vs those that failed validation against their provider's discovery doc
> Ongoing OIDC work: resolve some ambiguity around errors during AuthMethod updates.

- internal/session/repository.go
- internal/session/repository_session.go
- internal/tests/cli/boundary/user.bats
Fixing the session passing around its key ID (which had previously been
blank) exposed another issue which was caught during bats tests:
WithKeyId statements using the wrong key, which prior to now had been
ignored because the argument was empty, resulting in an ineffective
option. This fixes those situations.
It also updates a bats test that didn't get updated in the CLI return
status PR.
> Fix WithKeyId after recent PR

- internal/cmd/commands/dev/dev.go
The recent refactor made it impossible to run `boundary dev`.  @talanknight you may want to recheck all references to `handlers.InValidId(...)`
> fix order of parameters... refactor sort of makes this defect hard to detect

- website/content/docs/configuration/worker.mdx
Workers connect to controllers on 9201, not 9202.
> Small docs update

- internal/db/schema/migrations/generate/generate.go
I was testing migrations and after opening the migrations directory in finder I started getting this error:
```
louisruch@Louis:~/boundary (main)$ make migrations
/Library/Developer/CommandLineTools/usr/bin/make --environment-overrides -C internal/db/schema/migrations/generate migrations
go run .
error reading major schema version directory ".DS_Store".  Must be a number: strconv.Atoi: parsing ".DS_Store": invalid syntax
exit status 1
make[1]: *** [migrations] Error 1
make: *** [migrations] Error 2
```
This forces me to rm the `.DS_Store`.  
However, since I can see this happening in the future I decided to added a check to skip all hidden directories (dirs prefixed with `.`)  in case there are other auto generated dirs that could be created by another OS or application.  
I can change …
> Skip hidden directories when generating version numbers

- CONTRIBUTING.md
Update contributing guidelines with pronoun expectation and link to HashiCorp community guidelines.
> docs: update contributing guide with pronoun expectations

- website/content/docs/configuration/kms/transit.mdx
A slight update for clarity regarding the wording of the note regarding the recommendation of using the 'VAULT_TOKEN' environment variable as opposed to using the 'token' parameter in the configuration file.
> docs: Clarify note on VAULT_TOKEN env variable

- internal/auth/auth.go
- internal/auth/testing.go
- internal/iam/repository_scope.go
- internal/servers/controller/common/scopeids/scope_ids.go
- internal/servers/controller/handlers/accounts/account_service_test.go
- internal/servers/controller/handlers/authmethods/authmethod_service_test.go
- internal/servers/controller/handlers/authtokens/authtoken_service_test.go
- internal/servers/controller/handlers/groups/group_service_test.go
- internal/servers/controller/handlers/host_catalogs/host_catalog_service_test.go
- internal/servers/controller/handlers/host_sets/host_set_service_test.go
- internal/servers/controller/handlers/hosts/host_service_test.go
- internal/servers/controller/handlers/roles/role_service_test.go
- internal/servers/controller/handlers/scopes/scope_service_test.go
- internal/servers/controller/handlers/sessions/session_service_test.go
- internal/servers/controller/handlers/targets/target_service_test.go
- internal/servers/controller/handlers/users/user_service_test.go
When using a disabled verifier context we were faking scope information. Due to other recent changes, this was now causing test errors. This adjusts that flow to actually query the DB, fixing tests and making them more like real code.
> Fix test scope errors

- CHANGELOG.md
- internal/cmd/commands/database/funcs.go
- internal/cmd/commands/database/funcs_test.go
- internal/cmd/commands/database/init.go
This matches the migrations code, which treats the operation as
idempotent.
> If the database is already initialized, use 0 as the return value

- internal/servers/controller/handler.go
- internal/servers/controller/handler_test.go
This mechanism intercepts any request with the path ending in
`:callback`.
Currently this is limited to GET (but can support others), but in this
case will parse the form, and put the resulting variables in a
predictable format that is then sent along as JSON to grpc-gateway for
normal handling.
> Add a callback mechanism

- internal/errors/code.go
- internal/errors/code_test.go
- internal/errors/info.go
- internal/iam/repository_user.go
- internal/iam/repository_user_test.go
- internal/servers/controller/handlers/errors.go
- internal/servers/controller/handlers/errors_test.go
We should return a 400 on account already associated errors as per: https://hashicorp.atlassian.net/browse/ICU-701
> 400 if account already assocaited

- internal/db/schema/migrations/postgres/2/01_credential.up.sql
- internal/db/schema/migrations/postgres/2/02_vault_credential.down.sql
- internal/db/schema/migrations/postgres/2/02_vault_credential.up.sql
- internal/db/schema/migrations/postgres/2/03_target.up.sql
- internal/db/schema/migrations/postgres/2/04_session.up.sql
- internal/db/schema/postgres_migration.gen.go
* Rename foreign key constraint names to use `_fkey` suffix 
* Add `credential_vault_token_status_enm` table
* Add `token_sha256` to `credential_vault_lease` table as foreign key to `credential_vault_token` table
* Give `tls_skip_verify` a default value of `false` in the `credential_vault_store` table
> Vault integration: database fixes

- internal/cmd/commands/connect/connect.go
- internal/servers/controller/controller.go
- internal/servers/worker/worker.go
BK clued me into the fact that for some types, similar alignment
problems exist as with the normal atomic package (e.g. 64-bit types on
32-bit architectures) if they are not pointer values. So change the few
places they weren't pointers to pointers.
None of these are 64-bit, but it feels like best practice for using the
library and should just standardize on it.
> Use pointers for any Uber atomic values

- website/package-lock.json
- website/package.json
Remove the badges from the HCP products on the HashiStackMenu, as they are no longer needed.
[🔍 Preview](https://boundary-git-brstackmenu-hashicorp.vercel.app/)
> Updates the StackMenu to the latest

- scripts/uigen.sh
The UI build is I/O heavy and thus runs much faster outside of a container.  Since the build script succeeds on WSL2, I think it's safe to end our reliance on Docker to build the UI.
> chore: build directly on the hose rather than Docker

- api/output_string.go
- website/content/docs/concepts/filtering/resource-listing.mdx
I'm not sure why it was doing it the other way with assuming the string
being built would always have a space at the end, but, this way is
easier to understand and fixes a bug where there wasn't a space being
left between some fields.
> Fix curl string building

- website/next.config.js
adds proper configuration for tip.boundaryproject.io which will be a subdomain to showcase upcoming/unreleased documentation being prepared for the latest version. this documentation will be pulled from `origin/main`
this should be a simple review. i have not configured the actual domain DNS yet because i want this logic in place which to prevent indexing before the DNS change makes the actual subdomain propagate. In effect, you're just making sure this change doesn't break the site build and that i got the config option name correct
> website: add support for tip.boundaryproject.io

- internal/cmd/config/config.go
- internal/cmd/config/config_test.go
- website/content/docs/configuration/listener/tcp.mdx
- website/content/docs/configuration/listener/unix.mdx
This also adds support for a flag to disable this behavior.
Fixes #1093
> By default, add Boundary Desktop's origin to allowed CORS origins

- internal/servers/controller/handlers/authmethods/authmethod_service.go
- internal/servers/controller/handlers/authmethods/authmethod_service_test.go
- internal/servers/controller/handlers/option_test.go
- internal/servers/controller/handlers/options.go
This keeps only essential information in list output for auth methods
when the user is u_anon. Boundary's default is to allow listing of
auth methods for anonymous users to allow discovery of authentication
points, but there's no need to return more information about internal
configuration than necessary.
> Restrict auth method listing for u_anon

- README.md
The used path shouldn't be relative. Currently, it does not work.
> Update README.md: fix the command to run boundary

- CHANGELOG.md
- internal/cmd/base/base.go
- internal/cmd/base/initial_resources.go
- internal/cmd/base/keyring.go
- internal/cmd/commands.go
- internal/cmd/commands/authtokenscmd/authtokens.gen.go
- internal/cmd/commands/authtokenscmd/funcs.go
- internal/cmd/commands/config/token.go
- internal/cmd/commands/logout/logout.go
- internal/cmd/gencli/input.go
- internal/iam/repository_scope.go
- internal/perms/grants.go
- internal/servers/controller/handlers/authtokens/authtoken_service.go
- internal/servers/controller/handlers/authtokens/authtoken_service_test.go
- internal/servers/controller/handlers/sessions/session_service.go
- internal/tests/cli/boundary/_auth_tokens.bash
- internal/tests/cli/boundary/auth_token.bats
- internal/tests/cli/boundary/roles.bats
- internal/types/action/action.go
- internal/types/action/action_test.go
I'm not convinced `boundary logout` is the right place to put this. It doesn't have symmetry with `authenticate` but it's shorter and easier to type than `deauthenticate`, and they're not really symmetric actions anyways. But I'm happy to be convinced otherwise.
Minor TODO: fix bats tests. The local variables don't seem to be capturing properly.
> Add read:self and delete:self to auth tokens and add logout command

- docker/Release.dockerfile
This adopts the new HashiCorp PGP key, as described at https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512/2 and https://hashicorp.com/security.
Please merge after reviewing 🙏
> Adopt new pgp key

- internal/auth/oidc/provider.go
- internal/auth/oidc/provider_test.go
- internal/auth/oidc/service.go
- internal/auth/oidc/service_callback.go
- internal/auth/oidc/service_callback_test.go
- internal/auth/oidc/service_start_auth.go
- internal/auth/oidc/service_start_auth_test.go
- internal/auth/oidc/service_test.go
- internal/auth/oidc/service_token_request.go
- internal/auth/oidc/testing.go
- internal/cmd/commands/dev/dev.go
- internal/servers/controller/handler.go
- internal/servers/controller/handlers/authmethods/authmethod_service.go
- internal/servers/controller/handlers/authmethods/authmethod_service_test.go
- internal/servers/controller/handlers/authmethods/oidc_test.go
All ODIC callbacks will now have the same predictable PATH:  `/v1/auth-methods/oidc:authenticate:callback`
@stellarsquall @randallmorey -> this has positive impacts on the admin UI and docs.
> OIDC: make callback URL paths deterministic. 

- website/content/docs/installing/no-gen-resources.mdx
when setting the grants for the anonymous listing role it's only setting is 'type=scope;actions=list'. But I think it should be 'id=*;type=scope;actions=list,read'
With 'type=scope;actions=list', it's not possible to read the orgs in the global scope unauthenticated.
when initializing a server without skipping the default roles and in the dev server these permission are also set to 'id=*;type=scope;actions=list,read'
> Incorrect Grants when setting anonymous read permissions

- .circleci/Makefile
This broke staging, which was relying on `make` not re-generating config when source timestamps indicated it was not necessary. We should remove this reliance on timestamps because it doesn't play well with Git in other contexts, but for now this gets staging working again.
> circleci: don't force config regeneration

- CHANGELOG.md
- internal/cmd/commands/database/init.go
The output was ready for json format but the flag wasn't included.
> Fix `boundary database init` respecting format flag

- internal/cmd/commands/authenticate/oidc.go
Fixes #1193
Fixes that the openid connect authenticate command formatted as json returns
disturbing text. Therefore it can not be piped and parsed by another tool
> Remove text in oidc command on json format

- internal/cmd/commands/groupscmd/funcs.go
> Fix cmd help for groups: rename user to member

- internal/servers/query.go
- internal/servers/repository.go
This ensures that we are using consistent ideas of time regardless of
the local time on each worker (for this query).
> Migrate the server upsert query to use database time

- CHANGELOG.md
- internal/servers/controller/handlers/sessions/session_service.go
- internal/servers/controller/handlers/sessions/session_service_test.go
This validates it's not already canceled or in terminated state.
> Add missing API-level state checks during session cancel

- internal/api/genapi/input.go
- internal/api/genapi/templates.go
- internal/auth/subtype.go
- internal/auth/subtype_test.go
- internal/cmd/common/help.go
- internal/cmd/gencli/input.go
- internal/cmd/gencli/templates.go
- internal/host/subtype.go
- internal/servers/controller/handlers/accounts/account_service.go
- internal/servers/controller/handlers/authmethods/authmethod_service.go
- internal/servers/controller/handlers/sessions/session_service_test.go
- internal/servers/controller/handlers/targets/target_service.go
- internal/servers/controller/handlers/targets/target_service_test.go
- internal/target/repository.go
- internal/target/subtype.go
- internal/target/target.go
The **t** in `Subtype` should not be capitalized unless `SubType` is referring to a type of submarine.
> Fix spelling of SubType

- CHANGELOG.md
- internal/cmd/config/config.go
- internal/cmd/config/config_test.go
This ensures that cors_allowed_origins can be set when cors_enabled is
not explicitly specified and allowed to be its default (currently true).
The current behavior is to clobber this value when cors_enabled is not
explicitly set, ultimately setting it to the default of
"serve://boundary" only.
> internal/cmd/config: allow explicit origin list w/implicit CORS toggle

- CHANGELOG.md
- internal/cmd/config/config.go
- internal/cmd/config/config_test.go
Reverts hashicorp/boundary#1247
We're going to actually be changing this logic to `*` to fix some user issues so these extra additions aren't necessary.
> Revert "internal/cmd/config: allow explicit origin list w/implicit CORS toggle"

- CHANGELOG.md
- internal/servers/controller/handlers/sessions/session_service.go
- internal/servers/controller/handlers/sessions/session_service_test.go
If a session is already canceled or terminated, attempting to cancel it
will return the current session state and a 200, instead of an error.
> Already-canceled sessions return 200

- internal/credential/vault/repository_credential_store.go
- internal/db/schema/migrations/postgres/10/03_vault_credential.down.sql
- internal/db/schema/migrations/postgres/10/03_vault_credential.up.sql
- internal/db/schema/postgres_migration.gen.go
This change renames two database views and associated go structs to use a consistent naming pattern. Views ending in 'private' contain encrypted credentials needed for connecting to Vault. Views ending in 'public' mirror the 'private' views but do not include any encrypted values.
This change does not include any changes to functionality or behavior.
> Vault integration: Refactor: rename database views and associated structs

- internal/observability/events/context.go
- internal/observability/events/context_test.go
- internal/observability/events/event_audit.go
- internal/observability/events/event_audit_test.go
- internal/observability/events/event_error.go
- internal/observability/events/event_error_test.go
- internal/observability/events/event_observation.go
- internal/observability/events/event_observation_test.go
- internal/observability/events/eventer.go
- internal/observability/events/eventer_test.go
This is third of 3 PRs to add the events package and they should be reviewed in order. Before this was #1275 and #1276.
This PR will be merged into the branch for #1276, which will be merged to the branch for #1275, which will be merged intowhen all three have been reviewed/approved.
> add support for writing events via the context

- internal/observability/events/context.go
- internal/observability/events/context_test.go
- internal/observability/events/event_audit.go
- internal/observability/events/event_audit_test.go
- internal/observability/events/event_delivery_guarantee.go
- internal/observability/events/event_delivery_guarantee_test.go
- internal/observability/events/event_error.go
- internal/observability/events/event_error_test.go
- internal/observability/events/event_observation.go
- internal/observability/events/event_observation_test.go
- internal/observability/events/event_type.go
- internal/observability/events/eventer.go
- internal/observability/events/eventer_config.go
- internal/observability/events/eventer_config_test.go
- internal/observability/events/eventer_retry.go
- internal/observability/events/eventer_retry_test.go
- internal/observability/events/eventer_test.go
- internal/observability/events/options.go
- internal/observability/events/sink_config.go
- internal/observability/events/sink_config_test.go
- internal/observability/events/sink_format.go
- internal/observability/events/sink_type.go
- internal/observability/events/testing.go
This is second of 3 PRs to add the events package and they should be reviewed in order.  Before this was #1275 and after this one there's #1277.
This PR will be merged into the branch for #1275, which will be merged to main when all three have been reviewed/approved.
> add support for Eventer along with all of its dependencies

- CHANGELOG.md
- docker/Dev.dockerfile
- docker/Release.dockerfile
- docker/docker-entrypoint.sh
* Add entrypoint script with logic borrowed from Vault's.  This script adds
IPC_LOCK capability at runtime and then executes Boundary under its own user.
* Modify Dockerfiles to use the entrypoint script.
* Remove USER directives from the Boundary Dockerfiles.  This is required to
allow the entrypoint to run setcap.
Because Boundary itself is no longer the entrypoint, the behavior of the
container with respect to passing or overriding arguments is different now.
The Vault script's logic around handling this was not copied entirely -- only
to the extent required to allow the `server` subcommand to run properly.
> Add a Docker entrypoint script and modify Dockerfiles to mimic Vault, to enable mlock inside Docker containers

- website/data/version.js
To be merged once desktop 1.1.0 appears on [releases](https://releases.hashicorp.com/boundary-desktop/).
> chore:  bump desktop version to 1.1.0

- website/content/docs/concepts/security/permissions.mdx
- website/content/docs/getting-started/connect-to-target.mdx
- website/package-lock.json
- website/package.json
Bump `@types/node` to latest release of v14.
There is a [v15 available](https://www.npmjs.com/package/@types/node/v/15.12.2) and I am happy to bump to that, as initial PR I tough is safer to first bump to latest v14. Please let me know any thoughts on this.
> Bump @types/node to latest release of v15

- internal/credential/vault/jobs_test.go
- internal/credential/vault/repository_credential_store.go
- internal/credential/vault/repository_credential_store_test.go
- internal/credential/vault/repository_credentials_test.go
- internal/credential/vault/vault_capabilities.go
- internal/credential/vault/vault_capabilities_test.go
- internal/credential/vault/vault_test.go
Adds a stringer method and paths method to pathCapabilities
Adds check and returns error on missing capabilities when updating token in a cred store or creating cred store
Sample error if missing:
```
vault.(Repository).CreateCredentialStore: missing capabilites: sys/leases/revoke: update: vault token issue: error #3013
```
See unit test of `String` for more examples of how it would display
> Error on missing capabilities

- internal/credential/vault/jobs.go
- internal/credential/vault/jobs_test.go
- internal/credential/vault/query.go
- internal/credential/vault/store/vault.pb.go
- internal/db/domains_test.go
- internal/db/read_writer.go
- internal/db/schema/migrations/postgres/12/03_vault_credential.down.sql
- internal/db/schema/migrations/postgres/12/03_vault_credential.up.sql
- internal/db/schema/postgres_migration.gen.go
- internal/proto/local/controller/storage/credential/vault/store/v1/vault.proto
- internal/scheduler/scheduler_test.go
- Allows library_id and session_id to be null on a credential
- On delete set null on both library_id and session_id instead of cascade
- Adds a trigger to set status to revoke when moving to null session_id
- Adds job to delete cred stores that are soft deleted and have no active tokens
- Adds job to delete credentials that have been soft deleted and are not active
> Vault job credential and credential store cleanup

- internal/db/read_writer.go
- internal/db/read_writer_test.go
Updates `SearchWhere` to allow a where clause with no provided args
> Allow where without args in searchWhere

- internal/credential/vault/repository_credential_store.go
- internal/credential/vault/repository_credential_store_test.go
- internal/credential/vault/supported.go
- internal/credential/vault/testing.go
- internal/credential/vault/testing_test.go
- internal/servers/controller/handlers/credentialstores/credentialstore_service_test.go
Validates current token when there is an address change
Validates client cert / key is valid on change
Adds WithClientKey TestOption, this option was needed to allow the test where we change a cert but not a key, since this is validated now it was failing.
> Validate current vault token on addr update

- website/package-lock.json
- website/package.json
- website/pages/style.css
👀 [Preview](https://boundary-git-fork-zchsh-zsupgrade-code-block-hashicorp.vercel.app/docs)
This PR upgrades all MDX code snippets to use [our latest `code-block` component](https://github.com/hashicorp/react-components/pull/205), which contains a number of new features detailed in [[MKTG-035] Improvements to our Code Blocks](https://docs.google.com/document/d/1b2ROeAoy708dSqpJZjZRvuhJm9FB86skKEeQC3ZkLMY/edit?ts=5fadaaee).
We've also converted our `code-block` component to use CSS modules, which removes the need for global code-block related style imports.
> website: upgrade code-block

- internal/servers/controller/handlers/targets/target_service_test.go
Moved the worker status update closer to the call to Authorize session so the time it takes to setup the vault test server doesn't cause the worker to timeout.
> Get failing test passing

- internal/credential/vault/testing.go
This fixes a dropped `err` variable in `internal/credential/vault`.
> internal/credential/vault: fix dropped error

- website/components/openapi-page/index.jsx
- website/package-lock.json
- website/package.json
- website/pages/_app.js
- website/pages/_document.js
- website/pages/downloads/index.jsx
[Preview](https://boundary-po1gn88uf-hashicorp.vercel.app/)
Upgrading `react-head` and dependencies to set the new Safari theme-color feature.
[_Created by Sourcegraph campaign `kstraut/upgrade-react-head`._](https://sourcegraph.hashi-mktg.com/users/kstraut/campaigns/upgrade-react-head)
**After**
**Before**
> website: upgrade react-head

- internal/servers/worker/session.go
- internal/servers/worker/session_test.go
- internal/servers/worker/status.go
- internal/servers/worker/testing.go
- internal/servers/worker/testing_test.go
- internal/session/connection_state.go
- internal/tests/cluster/session_cleanup_test.go
This backports some test work that is being added in #1340 to assert
that the worker is actually marking connections closed in its *local*
state on a failure to contact the controller. This was missed in #1357
during some late-stage refactoring.
Summary of the changes:
* If we can't actually contact the controller during connection closure
to mark the connections as closed, we actually construct a "fake"
response that just simply includes a closed state for all connections
requested. This is then used to update the local connection state.
* Added a 3 second timeout to the CloseConnection request to the
controller to ensure the call to close connections completed in a
timely manner and did not hang indefinitely.
Testing enhancements:
* Added a new helper in TestHelper called LookupSession …
> worker: ensure connections are closed in local state on controller fail

- internal/servers/worker/session.go
- internal/servers/worker/session_test.go
This adds a return when aborting from closeConnections, which should
have happened as a part of #1369.
Note that it's currently inconsequential that it's not happening right
now, save some misleading log entries. setCloseTimeForResponse will
effectively no-op on empty or nil input maps.
> internal/servers/worker: actually return when aborting closeConnections

- website/content/docs/configuration/controller.mdx
Add explicit language that we try to connect via SSL=required and how to workaround
> Clarify default Postgres behavior

- website/content/docs/configuration/controller.mdx
Per https://www.boundaryproject.io/docs/configuration/listener/tcp#tls - having this here is invalid.
All tls parameters are valid only for the api listener. cluster and proxy connections use their own ephemeral TLS stacks
> Remove errant tls_disable 

- internal/cmd/base/servers.go
- internal/cmd/commands/dev/dev.go
- internal/cmd/commands/server/server.go
- internal/cmd/config/config.go
- internal/db/schema/migrations/postgres/12/01_timestamp_sub_funcs.up.sql
- internal/db/schema/migrations/postgres/12/01_timestamp_sub_funcs_test.go
- internal/db/schema/postgres_migration.gen.go
- internal/servers/controller/controller.go
- internal/servers/controller/handlers/workers/worker_service.go
- internal/servers/controller/session_cleanup_job.go
- internal/servers/controller/session_cleanup_job_test.go
- internal/servers/controller/testing.go
- internal/servers/options.go
- internal/servers/repository.go
- internal/servers/repository_test.go
- internal/servers/worker/status.go
- internal/servers/worker/status_test.go
- internal/servers/worker/testing.go
- internal/servers/worker/worker.go
- internal/session/query.go
- internal/session/repository_connection.go
- internal/session/repository_connection_test.go
- internal/tests/cluster/session_cleanup_test.go
This commit adds the support to do the following:
* Mark connections for non-reporting workers as closed. This is the
controller counterpart to the worker functionality (see #1330). This is
written as a scheduled job that does most of the work DB-side, save some
rudimentary checking of individual workers' last update times.
* Works to reconcile states if such a broken controller-worker
connection resumes and a worker reports a connection as connected that
should be disconnected. In this case, the controller will send an update
request, and the worker will honor it and terminate the connection.
* Further refinement of the grace period setting has been added here.
We have converged on the current server "liveness" setting as our
default here, which is half of the previous 30s (15 seconds, …
> internal/servers/controller: Worker failure connection cleanup

- internal/cmd/base/servers.go
- internal/cmd/config/config_test.go
As @tmessi reported in slack CI builds on `main` are currently failing:
```
Tim Messier Today at 07:50
It looks like ed6c59a0539ecfba54835cd3c04b04f709303c60 is causing CI to fail on main (and any new branch since that commit). It updated the version of github.com/hashicorp/go-secure-stdlib/configutil which has this commit: 1b80d53b4662d4b15ea0c23754dd81e3ae21d58b that removes configutil.Telemetry but the tests in internal/cmd/config are using that struct so the tests fail to compile
```
Commit https://github.com/hashicorp/boundary/commit/9ba1948298b8d0d57919fe480b41c9aeb97fa03b removed telemetry as it was not being used but config_tests still used it, but it is only failing now that it has been removed from go-secure-stdlib
> Remove Telemetry from config tests

- internal/scheduler/additional_verification_test.go
- internal/scheduler/job/additional_verification_test.go
- internal/scheduler/job/query.go
- internal/scheduler/job/repository_run.go
- internal/scheduler/job/repository_run_test.go
- internal/scheduler/scheduler.go
Adds a `WithProgress` option to the `CompleteRun` and `FailRun` calls so the final job status is always persisted.  Currently progress is only updated in the `MonitorJobs` loop, fast running jobs often start and finish before a single monitor job loop is triggered.  Even for long running jobs the final status should not be left to a race between `CompleteRun` and the `MonitorJobs` loop
> Ensure job progress is always reported

- internal/servers/worker/status_test.go
This fixes this test which was failing intermittently.
* Ups the grace period timeout to 2s.
* Re-positions the testify require.New() so that incorrect code path
warnings are not given.
> internal/servers/worker: fix TestWorkerWaitForNextSuccessfulStatusUpdate

- .circleci/config.yml
- .circleci/config/jobs/test-sql.yml
- .circleci/config/workflows/default.yml
- Makefile
- internal/db/sqltest/Makefile
- internal/db/sqltest/README.md
- internal/db/sqltest/initdb.d/00_schema.sh
- internal/db/sqltest/initdb.d/01_wtt_load.sql
- internal/db/sqltest/initdb.d/02_colors_persona.sql
- internal/db/sqltest/initdb.d/03_widgets_persona.sql
- internal/db/sqltest/tests/setup/wtt_load.sql
- internal/db/sqltest/tests/wh_user_dimension.sql
This sets up the configuration for running a new suite of tests that are
written in sql, to test the sql logic implemented in plpgsql functions
and triggers. It is primarily designed to provides tests for the data
warehouse functionality that is implemented purely in sql.
The infrasturture to run these tests leverages docker. It creates one
docker container using the `library/postgres` image and provisions the
database with the boundary sql migrations and test helper functions.
A separate docker container is run that has the pgtap extension and
pg_prove cli to execute the tests.
As noted, pgtap is used for the tests. This postgresql extension
provides a number of helpful assertion functions to make writting sql
tests easier. It also, along with the pg_prove cli, provides readable
test …
> test(db): Thin line for new sql testing suite

- internal/db/read_writer.go
- internal/servers/controller/testing.go
- internal/servers/worker/status.go
- internal/session/query.go
- internal/session/repository_connection.go
- internal/tests/cluster/session_cleanup_test.go
This PR applies review feedback made by @jefferai for #1340.
> Apply extra review feedback from #1340

- internal/boundary/boundary.go
- internal/credential/credential.go
This PR creates a new internal package named `boundary` and moves three interfaces from the `credential` package into it. The intent is to put the interfaces and types that define the Boundary domain into this package over time.
> Move base interfaces of the domain into a new boundary package

- internal/db/schema/migrations/postgres/13/00_wh_user_dimension_oidc.up.sql
- internal/db/sqltest/initdb.d/03_widgets_persona.sql
- internal/db/sqltest/tests/wh/upsert_user/upsert.sql
- internal/db/sqltest/tests/wh/user_dimension/oidc_auth_new_session.sql
- internal/db/sqltest/tests/wh/user_dimension/password_auth_description_change.sql
- internal/db/sqltest/tests/wh/user_dimension/password_auth_new_session.sql
- internal/db/sqltest/tests/wh/user_dimension_views/source.sql
- internal/db/sqltest/tests/wh/user_dimension_views/target.sql
This adds new columns to the wh_user_dimension to provide additional
data from OIDC that does not apply to Password Auth.
Note: Given the specifics of the data, it is possible these columns may
be used by other auth methods in the future, hence the lack of `oidc` in
the column names.
The specific columns are:
- auth_method_external_id
For OIDC this is the Issuer
- auth_account_external_id
For OIDC this is the Subject
- auth_account_full_name
For OIDC this is the account's Full Name, and can be `None`.
- auth_account_email
For OIDC this is the account's Email, and can be `None`.
For all of these new columns, they will be `Not Applicable` if the auth
method is Password.
> feat(wh): Add oidc related columns to wh_user_dimension

- website/pages/home/index.jsx
Now that we offer both a Windows and macOS desktop client, the CTA button didn't make sense.
> Update homepage desktop client CTA language

- website/content/docs/common-workflows/workflow-ssh-proxycommand.mdx
- website/content/docs/configuration/kms/aead.mdx
- website/content/docs/configuration/kms/index.mdx
I found these little spelling mistakes:
- website/content/docs/common-workflows/workflow-ssh-proxycommand.mdx  （idomatic -> idiomatic, varibles -> variables）
- website/content/docs/configuration/kms/aead.mdx  (specifc -> specific)
- website/content/docs/configuration/kms/index.mdx  (specifc -> specific)
They look inconspicuous and seem unimportant. But I thought Boundary is a nice work,  I wanted to help it get better. So I fix them. Thanks ^_^
> fixed typo: specifc -> specific, varibles -> variables, idomatic -> idiomatic.

- CHANGELOG.md
- Makefile
- docker/Release.dockerfile
- I've updated the release Dockerfile to support multiple architectures.
- I've also added a snippet in the Makefile called `docker-multiarch-build` that will build and push multiple architectures of the image to our Dockerhub. I've done it with Docker's `buildx` feature.
> Adding support to build multi-arch Boundary images

- internal/scheduler/additional_verification_test.go
- internal/scheduler/scheduler.go
Skips final job run update if the base context is no longer valid.  All repo actions are dependent on the base context, attempting to perform an update without a valid context will always fail.
The following error was found intermittently in [circle-ci](https://circleci.com/api/v1.1/project/github/hashicorp/boundary/71541/output/102/0?file=true&allocation-id=61004daab3df255367f81b9d-0-build%2F5F75C3D6):
```
testing.go:54: 
Error Trace:	testing.go:54
testing.go:901
testing.go:1007
testing.go:1187
Error:      	Received unexpected error:
write tcp 127.0.0.1:36706->127.0.0.1:33410: use of closed network connection
Test:       	TestSchedulerJobProgress
Messages:   	Got error closing gorm db.
--- FAIL: TestSchedulerJobProgress (11.85s)
```
Running the test in a loop locally would hit this error …
> Fix race with base context cancel and final run update in scheduler

- Makefile
This fixes the broken Makefile (bad space added in docker-multiarch-build).
> Fix Makefile target (docker-multiarch-build)

- website/redirects.js
This small PR introduces documentation redirects for credential stores and sources (libraries) intended for use by Boundary product UIs.  And it resolves an inconsistency with the redirect for sessions documentation.
> docs:  add credential doc redirects and fix session redirect

- CHANGELOG.md
This adds the changelog entries associated with the following PRs:
#1340 
#1354
#1400
#1410
> Add session cleanup changes to CHANGELOG.md

- CHANGELOG.md
- internal/cmd/commands/server/server.go
This adds back the controller shutdown call on worker failure.
This was added in a15961e4 to address a panic discovered in testing, and
was mistakenly thought to be unnecessary. This, however, covers
multi-role scenarios where we have already started the controller, which
needs to be shut down gracefully if possible if we can't start the
worker.
A nil check has been added to ensure the panic does not resurface.
> server: Add back controller shutdown on worker startup failure

- website/content/docs/getting-started/connect-to-target.mdx
Currently, the documentation is linking to a page that errors with a 404. This fix brings people to the anticipated page.
> Update next steps in connect to target documentation

- .circleci/config.yml
- .circleci/config/jobs/test-sql.yml
- .circleci/config/workflows/default.yml
- Makefile
- internal/db/sqltest/Makefile
- internal/db/sqltest/README.md
- internal/db/sqltest/initdb.d/00_schema.sh
- internal/db/sqltest/initdb.d/01_wtt_load.sql
- internal/db/sqltest/initdb.d/02_colors_persona.sql
- internal/db/sqltest/initdb.d/03_widgets_persona.sql
- internal/db/sqltest/tests/setup/wtt_load.sql
- internal/db/sqltest/tests/setup/wtt_load_colors.sql
- internal/db/sqltest/tests/setup/wtt_load_widgets.sql
- internal/db/sqltest/tests/wh/upsert_user/errors.sql
- internal/db/sqltest/tests/wh/upsert_user/insert.sql
- internal/db/sqltest/tests/wh/upsert_user/upsert.sql
- internal/db/sqltest/tests/wh/user_dimension/oidc_auth_new_session.sql
- internal/db/sqltest/tests/wh/user_dimension/password_auth_description_change.sql
- internal/db/sqltest/tests/wh/user_dimension/password_auth_new_session.sql
- internal/db/sqltest/tests/wh/user_dimension/session_multiple_sessions.sql
- internal/db/sqltest/tests/wh/user_dimension/session_multiple_sessions_different_auth.sql
- internal/db/sqltest/tests/wh/user_dimension/session_update.sql
- internal/db/sqltest/tests/wh/user_dimension_views/source.sql
- internal/db/sqltest/tests/wh/user_dimension_views/target.sql
This sets up the configuration for running a new suite of tests that are
written in sql, to test the sql logic implemented in plpgsql functions
and triggers. It is primarily designed to provides tests for the data
warehouse functionality that is implemented purely in sql.
The infrastructure to run these tests leverages docker. It creates one
docker container using the `library/postgres` image and provisions the
database with the boundary sql migrations and test helper functions.  A
separate docker container is run that has the pgtap extension and
pg_prove cli to execute the tests.
As noted, pgtap is used for the tests. This postgresql extension
provides a number of helpful assertion functions to make writing sql
tests easier. It also, along with the pg_prove cli, provides readable
test …
> test(db): Add baseline tests for wh_user_dimension

- internal/db/schema/migrations/postgres/14/01_wh_user_dimension_oidc.up.sql
- internal/db/schema/migrations/postgres/14/warehouse_user_dim_test.go
- internal/db/schema/postgres_migration.gen.go
Four new columns were added to the `wh_user_dimension` table to support
OIDC. The data type for the columns was originally `wh_dim_text` which
is a domain type with a `not null` restriction. Adding the new columns
caused the migration to fail if the `wh_user_dimension` table had any
rows in it because the existing rows would violate the `not null`
restriction.
Closes #1469
> Fix db migration that adds support for OIDC in the data warehouse

- CHANGELOG.md
- internal/servers/controller/handlers/targets/target_service.go
- internal/servers/controller/handlers/targets/target_service_test.go
Fixes #1488 
The panic is occurring here https://github.com/hashicorp/boundary/blob/main/internal/cmd/commands/targetscmd/funcs.go#L822 and the issue is at this point the target service has populated the `CredentialLibrary` struct and not the `CredentialSource` struct.  We could also update the targetscmd to support both in the interim...
Panic for reference:
```
boundary targets authorize-session -id ttcp_5PS2dktESb
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1f99a31]
goroutine 1 [running]:
github.com/hashicorp/boundary/internal/cmd/commands/targetscmd.printCustomActionOutputImpl(0xc00046c0a0)
/Users/louisruch/boundary/internal/cmd/commands/targetscmd/funcs.go:822 +0x9d1 …
```
> bug(targets): fixes bug that caused a panic in authorize-session

- website/package-lock.json
- website/package.json
this enables the website `start` script to reload the app on save of `./content/**/*.mdx` files
🎟 [task](https://app.asana.com/0/1100423001970639/1200899528748349/f)
- https://github.com/hashicorp/vault/pull/12476
- https://github.com/hashicorp/nomad/pull/11119
- https://github.com/hashicorp/consul/pull/10973
- https://github.com/hashicorp/vagrant/pull/12507
- https://github.com/hashicorp/packer/pull/11244
- https://github.com/hashicorp/sentinel/pull/437
- https://github.com/hashicorp/terraform-website-next/pull/90
- https://github.com/hashicorp/boundary/pull/1499
- https://github.com/hashicorp/waypoint/pull/2193
> chore(website): add `next-remote-watch` - this enables auto-reloading on specified file changes

- CHANGELOG.md
- internal/perms/acl.go
- internal/perms/grants.go
- internal/perms/grants_test.go
- internal/servers/controller/handlers/scopes/scope_service.go
- internal/servers/controller/handlers/scopes/scope_service_test.go
- internal/types/resource/resource.go
This also affected credential libraries and managed groups. It seems
that any end-to-end tests of these grants currently had them included in
wildcards instead of individually, but these types were never added to
the valid list for resources. Additionally, credential store wasn't
added as a valid top level type for pinning purposes.
> Fix unknown permission issue with credential-store

- go.mod
- go.sum
- internal/libs/endpoint/doc.go
- internal/libs/endpoint/matcher.go
- internal/libs/endpoint/matcher_test.go
- internal/libs/endpoint/option.go
- internal/libs/endpoint/options_test.go
- internal/libs/endpoint/preferencer.go
- internal/libs/endpoint/preferencer_test.go
This library allows specifying address preferences and then, given a set of IPs and/or DNS names, choosing the best one to use, with behavior specified for no preferences set and for no preferences matching.
> Add endpoint preferencer

- internal/servers/controller/listeners.go
This PR sets the controllers CancelCtx to something besides nil, which I'm not sure it was ever set.  This ctx is passed to all grpc-gateway service registrations in handleGrpcGateway.
> fix (controller): Set controller CancelCtx

- internal/credential/credential.go
- internal/credential/redact.go
- internal/credential/redact_test.go
This adds interfaces for the following credential types:
- Username and password
- Username and private key
- Certificate and private key
It also adds the following types for redacting secret data:
- Password
- PrivateKey
> feat(credential): Add specific credential types

- internal/db/schema/migrations/postgres/16/01_wh_credential_dimension.up.sql
- internal/db/schema/migrations/postgres/16/02_wh_credential_dimension.up.sql
- internal/db/schema/migrations/postgres/16/03_wh_credential_dimension.up.sql
- internal/db/schema/migrations/postgres/16/04_wh_credential_dimension.up.sql
- internal/db/schema/migrations/postgres/16/05_wh_credential_dimension.up.sql
- internal/db/schema/migrations/postgres/16/warehouse_credential_dim_test.go
- internal/db/schema/postgres_migration.gen.go
- internal/db/sqltest/initdb.d/01_colors_persona.sql
- internal/db/sqltest/initdb.d/03_widgets_persona.sql
- internal/db/sqltest/tests/wh/credential_dimension/dimension.sql
- internal/db/sqltest/tests/wh/credential_dimension/session_multiple_sessions.sql
- internal/db/sqltest/tests/wh/credential_dimension/session_update.sql
- internal/db/sqltest/tests/wh/credential_dimension/three_credentials_one_change.sql
- internal/db/sqltest/tests/wh/credential_dimension_views/source.sql
- internal/db/sqltest/tests/wh/credential_dimension_views/target.sql
- internal/db/sqltest/tests/wh/session_credential_dynamic/insert.sql
- internal/db/sqltest/tests/wh/session_credential_dynamic/insert_multiple.sql
- internal/session/query.go
- internal/session/repository_session.go
This adds new dimension table to record credential information. Since a
session can have multiple credentials, the wh_session_accumulating_fact
is is linked to the credential_dimensions via bridge tables,
wh_credential_group and wh_credential_group_membership. When a session
is inserted, the credental group and credential dimensions will be
upserted. If the group changed in any way, a new group is inserted along
with all of the corresponding credentials.
> wh: Add wh_credential_dimension and bridge tables

- internal/servers/worker/handler.go
- internal/servers/worker/proxy/proxy.go
- internal/servers/worker/proxy/proxy_test.go
- internal/servers/worker/proxy/tcp/tcp.go
- internal/servers/worker/proxy/tcp/tcp_test.go
Instead of requiring the each proxy handler to handle the webSocket
connection closure.  On error the worker handler will appropriately
close the connection and event any errors.
> refact(worker): update worker porxy handler signature to return an error

- testing/dbtest/docker/Makefile
After running make test-database-up, the output gave the
incorrect command to run to see docker logs.
> docs(dbtest): corrects echo in makefile

- internal/host/plugin/loopback.go
- internal/host/plugin/loopback_test.go
- internal/host/plugin/testing.go
This adds a simple "loopback" test that can be used with e.g. CLI tests for testing attributes and plugin functionality. It could be enhanced in a bunch of ways and may be as the CLI work goes on, but for now it keeps things simple.
> Add basic loopback test plugin

- internal/cmd/commands/version/version.go
If the VersionMetadata is set, include it in the output of the `boundary
version` subcommand.
> feat(cmd): Include version metadata in output

- website/content/docs/getting-started/index.mdx
- website/data/docs-nav-data.json
- website/redirects.js
:tickets: [Asana ticket](https://app.asana.com/0/563192436488770/1200984485270757/f)
:mag: [Docs deploy preview](https://boundary-46vj9ua5h-hashicorp.vercel.app/docs)
This PR:
- updates the docs sidebar to redirect API-Clients/Desktop to the Install Boundary Desktop Learn tutorial
- fixes an internal link to API-Clients/Desktop in `index.mdx`
- adds a permanent redirect to the learn tutorial in `redirects.js`
Requested review scope:
Review urgency:
I have:
> Docs: redirect Desktop install links to Learn

- internal/cmd/base/initial_resources.go
- internal/cmd/base/option.go
- internal/cmd/base/servers.go
- internal/cmd/commands/dev/dev.go
- internal/host/plugin/client.go
- internal/host/plugin/immutable_fields_test.go
- internal/host/plugin/repository.go
- internal/host/plugin/repository_host_catalog_test.go
- internal/host/plugin/repository_host_set.go
- internal/host/plugin/repository_host_set_test.go
- internal/host/plugin/repository_test.go
- internal/host/plugin/testing.go
- internal/host/plugin/testing_test.go
- internal/host/preferred_endpoint_test.go
- internal/servers/controller/controller.go
- internal/servers/controller/handlers/host_catalogs/host_catalog_service_test.go
- internal/servers/controller/handlers/host_sets/host_set_service_test.go
- internal/servers/controller/handlers/targets/target_service_test.go
- internal/servers/controller/testing.go
We've been using the server interface for in-memory testing, but in actuality we need to use the client interface to be able to swap between in-memory and external.
This PR simply changes the interface references to the client side, and adds a wrapper that can be used when we are using in-memory plugins.
> Swap host plugin server interface for client

- website/content/docs/configuration/events/file.mdx
- website/content/docs/configuration/events/overview.mdx
This PR fixes typos in the events HCL stanza that is prevents a controller/worker from starting.
Current config:
```
sink = {
name = "obs-sink"
description = "Observations sent to a file"
event_types = ["observation"]
format = "cloudevents-json"
file {
file_name = "file-name"
}
}
```
The assignment operator `sink = {` on the first line causes an error `Error parsing config file: At 51:17: nested object expected: LBRACE got: ASSIGN`
This PR corrects the HCL to `sink {}` in :
- /docs/configuration/events/overview
- /docs/configuration/events/file
> fixed hcl config examples for sink

- internal/db/schema/migrations/oss/postgres/19/03_hostplugin.up.sql
- internal/db/schema/migrations/oss/postgres/19/07_wh_session_dimensions.up.sql
- internal/db/sqltest/initdb.d/03_widgets_persona.sql
- internal/db/sqltest/tests/wh/host_dimension_views/source.sql
Updates the comments for the migration script which updates the whx_host_dimension_source view as well as changes the value for host_address to "Unsupported". 
Since this view is now likely to be used with the release of plugins please consider redoing the review of the whole view as part of this PR.
> Warehouse contains "Unsupported" host_address for plugin based hosts

- internal/db/common/update.go
- internal/db/common/update_test.go
- internal/db/db_test/db.go
- internal/db/db_test/db_test.pb.go
- internal/db/read_writer.go
- internal/db/read_writer_test.go
- internal/db/schema/migrations/oss/postgres/19/01_db.up.sql
- internal/proto/local/controller/storage/db/db_test/v1/db_test.proto
- internal/session/immutable_fields_test.go
Add support for the db layer operations like lookup, delete, update,
etc to support resources with mulit-column primary keys.  It also
adds support for PKs which are not either public_id or private_id.
These new capabilities are needed for things in #1634 ( FYI: @talanknight @vancluever)
> feature (db): Add support for multi-column PKs

- CHANGELOG.md
- internal/credential/vault/vault.go
The namespace was plumbed all the way through the API but isn't actually
set on the client when it is created.
For various reasons this is hard to test right now except manually (although that will change in the future), but it works in my testing and works for @joatmon08 too.
Fixes #1597
> Pass namespace to the Vault client

- internal/auth/oidc/auth_method.go
- internal/auth/oidc/service.go
- internal/credential/vault/client_certificate.go
- internal/credential/vault/vault_token.go
- internal/kms/kms.go
- internal/kms/kms_test.go
- internal/libs/crypto/derived_reader.go
- internal/libs/crypto/derived_reader_test.go
- internal/libs/crypto/error.go
- internal/libs/crypto/hmac_sha256.go
- internal/libs/crypto/hmac_sha256_test.go
- internal/libs/crypto/options.go
- internal/libs/crypto/options_test.go
- internal/libs/crypto/testing.go
- internal/session/util.go
- internal/session/util_test.go
We needed to create a new lib/crypto package and move
kms.NewDerivedReader into the new pkg. This will allow us to
use NewDerivedReader in the events pkg without a circular
dependency.
Also, consolidate the implementations of hmac-sha256 into the
lib/crypto pkg and refactor existing stuff to use the new refactored
version.
> refactor: Move functions from kms pkg to new libs/crypto pkg

- internal/servers/controller/handlers/mask_manager.go
- internal/servers/controller/handlers/mask_manager_test.go
This will be useful when updating plugin based host catalog and sets since attributes and secrets cannot be contained in the mask manager mapping.
> Mask manager can now include mask paths w/ a specified prefix which would be filtered otherwise

- internal/host/plugin/repository_host_catalog.go
Was being caught by my linters. Looks like the error wasn't being
checked after getCatalog.
> fix ineffectual assignment to err in DeleteCatalog

- internal/db/schema/internal/edition/edition.go
- internal/db/schema/internal/edition/edition_test.go
- internal/db/schema/internal/edition/testdata/invalid/duplicate-versions/0/01_initial.up.sql
- internal/db/schema/internal/edition/testdata/invalid/duplicate-versions/0/01_initial_also.up.sql
This should help prevent issues like the one fixed in
f2ad4de554d5e10365bd39c110f29f9a4c481fa5.
A version for a particular edition should only exist once, previously
which ever file was read last for a version would be included, which
would lead to some migrations not running.
> fix(schema): Prevent duplicate versions per edition

- internal/host/plugin/repository_host_catalog_test.go
This is to mainly get coverage on the empty description case, but it
follows the same logic as the "update name to same" test.
> internal/host/plugin: add update catalog test for empty/same description

- website/content/docs/installing/no-gen-resources.mdx
The existing documentation references this command to initialize the database without generated resources:
```shell
boundary database init -skip-initial-login-role-creation -config /etc/boundary.hcl
```
This is no longer supported and has been superceded with the following:
```shell
boundary database init \
-skip-auth-method-creation \
-skip-host-resources-creation \
-skip-scopes-creation \
-skip-target-creation \
-config /etc/boundary.hcl
```
I was getting errors when following the existing example and had to look into the code to figure out its been changed so updating the docs to reflect this change.
> updating db init without generated resources example

- go.mod
- go.sum
- internal/cmd/base/option.go
- internal/cmd/base/servers.go
- internal/cmd/commands/dev/dev.go
- internal/libs/crypto/error.go
- internal/observability/event/cloudevents_formatter_node.go
- internal/observability/event/cloudevents_formatter_node_test.go
- internal/observability/event/eventer.go
- internal/observability/event/eventer_test.go
- internal/observability/event/hclog_formatter_node.go
- internal/observability/event/hclog_formatter_node_test.go
- internal/observability/event/signer.go
- internal/servers/controller/controller.go
- sdk/go.mod
- sdk/go.sum
This PR will add "signing" via hmac-sha256 of Boundary audit entries.
-  chore: Update go-eventlogger dependency
- feature: Add audit wrapper
- feature: Add hmac-sha256 of entries to hclogFormatterFilter
- feature: Add hmac-sha256 of entries to cloudEventsFormatterFilter
> feature: Add signing (hmac-sha256) of audit entries

- go.mod
- go.sum
- internal/observability/event/cloudevents_formatter_node.go
- internal/observability/event/cloudevents_formatter_node_test.go
- sdk/go.mod
- sdk/go.sum
We should only "sign" audit events.  This fix required the latest version of go-eventlogger.
> fix (events): Only "sign" audit events

- website/redirects.js
Add redirect to domain model documentation for managed groups. This is used when the user click the icon help in the managed group screen.
> Add redirect to managed groups domain model documentation

- internal/host/plugin/repository_host_catalog.go
- internal/host/plugin/repository_host_catalog_test.go
- internal/host/plugin/repository_host_set.go
- internal/host/plugin/repository_host_set_test.go
This move the calls which could potentially mutate data into the transaction so our db constraints can be checked prior.  The plugins are only called once if successful even if the transaction is retried later.  This doesn't solve all failure cases but arguably avoids calling the plugin when there is a clear error with the request.
> Call OnCreate or OnUpdate on the plugin after db constraints are checked

- internal/host/plugin/repository_host_set.go
- internal/host/plugin/repository_host_set_test.go
This adds the UpdateSet repository function.
UpdateSet runs the OnUpdateSet plugin call within the transaction as per
the changes in #1683.
The plugin call returns the updated set, the hosts in the set, the rows
updated, and any error.
> internal/host/plugin: add UpdateSet

- website/content/docs/common-workflows/workflow-ssh-proxycommand.mdx
Not sure if this is a general issue or a macOS issue, but when using the default SSH settings on macOS Monterey (12.0.1), `%h` causes the hostname to be lowercased before being substituted into `ProxyCommand`, which then fails for any target IDs that contain uppercase letters.
Instead, use `%n` because it preserves the case of the hostname.
Ref: https://man7.org/linux/man-pages/man5/ssh_config.5.html#TOKENS
> doc: [ssh] Use `%n` for ProxyCommand

- internal/db/schema/migrations/oss/postgres/20/06_plugin_host_views.up.sql
- internal/db/schema/migrations/oss/postgres/20/08_plugin_host_views.up.sql
- internal/host/plugin/host.go
- internal/host/plugin/job_set_sync.go
- internal/host/plugin/job_set_sync_test.go
- internal/host/plugin/repository_host_test.go
- internal/host/plugin/repository_host_util.go
- internal/host/plugin/store/host.pb.go
- internal/host/plugin/testing.go
- internal/proto/local/controller/storage/host/plugin/store/v1/host.proto
- internal/servers/controller/handlers/hosts/host_service.go
- internal/servers/controller/handlers/hosts/host_service_test.go
Currently host does not use a version, which means it's not protected
against race conditions of either itself or its value objects. This adds
and plumbs through version to ensure that if a host or its value objects
change that they are not going to be affected by a race condition.
> Increment version of host during updates

- internal/db/schema/migrations/oss/postgres/20/01_session_list_view.up.sql
- internal/session/query.go
- internal/session/repository.go
- internal/session/repository_session.go
- internal/session/repository_session_test.go
- internal/session/session.go
Update the session_with_state database view to session_list and includes connection information into the view. 
Updates the repo layer to utilize this view, and return the connection information in the response.
> repo: Return connection informat in Session response object

- internal/kms/kms.go
- internal/kms/kms_ext_test.go
- internal/kms/repository.go
- internal/servers/controller/controller.go
- internal/servers/controller/controller_test.go
- internal/servers/controller/testing.go
This fix address the situation where an existing boundary database
doesn't have the audit DEKs in the global scope.
> fix (kms): Add kms.ReconcileKeys(...) to fix missing audit DEK scenario

- docker/Dev.dockerfile
Trying to run the docker image built with `make docker-build-dev` would
result in an error at startup:
standard_init_linux.go:228: exec user process caused: no such file or directory
This was due to the dev docker image lacking `dumb-init` which is used
by `docker-entrypoint.sh`.
This commit updates the dev dockerfile to add dumb-init. It also adds
additional packages so that the dev image aligns with the release image.
> fix(docker): Add missing packages to dev docker image

- internal/api/genapi/input.go
- internal/api/genapi/templates.go
This updates the API generation code to allow the same option names to
be used in subtype-scoped options. This means if we have attribute
structs with the same fields, they won't overwrite each other, but will
instead create attribute-specific options.
> Handle same-named options across subtypes

- .gitignore
- packages-oss.yml
- plugins/host/assets/README.md
- scripts/build.sh
This prevents errors when reaching into the main package to use testing code.
There are still some issues with respect to updating the test code to e.g. not expect to be able to create plugins not embedded into the test provider, which will be fixed in a more comprehensive set of changes to the test controller.
> Add a static README file to the host assets dir

- internal/cmd/base/base.go
- internal/cmd/base/servers.go
- internal/cmd/commands/dev/dev.go
- internal/cmd/commands/server/server.go
- internal/servers/controller/controller.go
- internal/servers/controller/testing.go
When running test controllers from e.g. Terraform tests we don't have the external plugins built in, so don't always include them. Additionally, add the loopback plugin to the test controller.
> Don't always assume plugins should be activated

- internal/db/schema/migrations/base.go
The embed package always uses Unix-style forward slashes. filepath.Join
utilization looking for files would cause the slashes to be the wrong
direction on Windows and result in the files not being found.
> Fix Windows

- internal/cmd/base/base.go
- internal/cmd/base/dev.go
- internal/cmd/commands/dev/dev.go
- internal/servers/controller/controller.go
- internal/servers/controller/testing.go
The previous PR only initialized plugins if they were required, which
meant that there may not actually be a plugin manager running because a
second node would not actually create the dev database, which is where
the plugin was being added. The assumption that a plugin manager is
running is still a fine one at the moment, but we just need to make sure
it's running in _all_ cases.
> Fix tests using multiple controllers

- internal/host/plugin/repository_host_set_test.go
Now asserts on error on the last lookup check and removes the plugin
lookup since we're not asserting on that.
> internal/host/plugin: Fix TestUpdateSet

- internal/cmd/commands/dev/dev.go
- internal/cmd/commands/server/server.go
Although this was fixed for TestController earlier, in the dev flow the set of enabled plugins was being overridden after Loopback was added, if it was enabled via flags. This fixes it.
> Actually enable loopback plugin in dev

- internal/host/plugin/repository_host_catalog.go
- internal/libs/patchstruct/patchstruct.go
- internal/libs/patchstruct/patchstruct_test.go
- internal/servers/controller/handlers/host_catalogs/host_catalog_service_test.go
Internally attributes are not allowed to be the null value. However, as
currently implemented, this then breaks our normal model of sending an
explicit `null` in the JSON to reset/clear a field. This is a problem
because the CLI doesn't have a way to say "set this but to empty"
without a lot of hoops, and causes some issues for API users and TF as
well.
This changes PatchBytes and PatchStruct to return an empty value (or
marshaled empty value in the case of PatchBytes) if the source is null
or empty. In the host catalog update function we then always set this
value if it's in the db mask (removing the nil check). Together this
means a null value ends up coming out as an empty value (and thus valid
for the DB) from PatchStruct/PatchBytes, and our API translation
function already returns …
> Fix setting plugin host catalog attributes to nil

- internal/db/schema/migrations/oss/postgres/0/01_domain_types.up.sql
- internal/db/schema/migrations/oss/postgres/21/01_default_time.up.sql
Raising a warning in the default trigger used for setting the value in
create_time columns creates unnecessary noise in the PostgreSQL log
files.
Closes #1744
> fix(sql): Remove warning from create_time trigger

- .circleci/config.yml
- .circleci/config/commands/install-go.yml
- .circleci/config/jobs/build.yml
- .circleci/config/jobs/test-api.yml
- .circleci/config/jobs/test-sdk.yml
- .circleci/config/workflows/ci.yml
- CONTRIBUTING.md
- Makefile
- api/Makefile
- sdk/Makefile
This adds new makefile targets and configuration to run the tests in the 
api and sdk modules. These do not run by default since `go test ./...` does
not cross module boundaries.
> ci: Run sdk and api tests in ci

- internal/cmd/base/initial_resources.go
- internal/cmd/commands/server/worker_shutdown_reload_test.go
- internal/credential/vault/jobs_test.go
- internal/credential/vault/repository_credentials_test.go
- internal/credential/vault/testing_external_test.go
- internal/servers/controller/handlers/sessions/session_service_test.go
- internal/servers/controller/handlers/targets/options.go
- internal/servers/controller/handlers/targets/registry.go
- internal/servers/controller/handlers/targets/target_service.go
- internal/servers/controller/handlers/targets/tcp/target_service_test.go
- internal/servers/controller/handlers/targets/tcp/tcp.go
- internal/session/testing.go
- internal/target/registry.go
- internal/target/repository_credential_source_test.go
- internal/target/targettest/target.go
- internal/target/tcp/exports_test.go
- internal/target/tcp/immutable_fields_test.go
- internal/target/tcp/register.go
- internal/target/tcp/repository_credential_source_test.go
- internal/target/tcp/repository_host_source_test.go
- internal/target/tcp/repository_tcp_target_test.go
- internal/target/tcp/repository_test.go
- internal/target/tcp/target.go
- internal/target/tcp/target_test.go
- internal/target/tcp/testing.go
- internal/target/tcp/testing_test.go
- internal/tests/api/targets/target_test.go
- internal/tests/cluster/package_registry_test.go
- internal/types/subtypes/registry.go
This follows a similar pattern as the target domain package, providing a 
subpackage for the tcp target functionality, allowing this to be pluggable.
> refact(controller/targets): Move tcp functionality into subpackage

- CHANGELOG.md
- internal/cmd/config/config.go
- internal/cmd/config/config_test.go
- website/content/docs/concepts/filtering/worker-tags.mdx
- website/content/docs/configuration/worker.mdx
We do this by taking a look at the HCL before the actual tag parsing and resolving the string to whatever value exists underneath, and then pass it on to the actual parsing.
This ensures that previous functionality is not affected.
> feat(config): Add env and file support to Worker Tags

- .github/workflows/backport.yml
This introduces a workflow that leverages the already-implemented [backport-assistant](https://github.com/hashicorp/backport-assistant) to backport changes (primarily docs changes) to designated release/branches and/or stable-website
The incoming behavior is identical to [Waypoint](https://github.com/hashicorp/waypoint/blob/main/.github/workflows/backport.yml)
Labels:
- <kbd>backport/website</kbd>
- will backport changes to `stable-website` **AND** `release/{LATEST}`
- `{LATEST}` is determined by the greatest semver out of all GitHub labels that begin with `"backport/"`
- <kbd>backport/0.6.x</kbd>
- will backport changes to `release/0.6.x`
- <kbd>backport/{TARGET}</kbd>
- will backport changes to `release/{TARGET}`
- <kbd>backport/website</kbd>
- <kbd>backport/0.7.x</kbd>
- …
> feat: updated backport assistant

- internal/credential/vault/fields.go
- internal/credential/vault/repository_credential_library.go
- internal/credential/vault/repository_credential_library_test.go
- internal/db/schema/migrations/oss/postgres/10/04_vault_credential.up.sql
- internal/db/schema/migrations/oss/postgres/22/05_vault_private_library.up.sql
An alternative implementation is in #1761. This version treats a credential mapping override as a value object which only allows the mapping override to be updated as a whole, not the individual fields of a credential mapping override.
> Add support for credential mapper overrides to the domain for update and lookup

- CHANGELOG.md
- internal/cmd/commands/server/server.go
- internal/cmd/config/config.go
- internal/cmd/config/config_test.go
- website/content/docs/configuration/worker.mdx
Similar to the other fields, we apply the same pattern here: 
We Introduce a `ControllersRaw interface{}` field and then use that to resolve the data within and put it in `Controllers` when we're done. 
We expect that the data could be of type `[]interface{}`, in which case the user specified the addresses directly in the config file; and now we also accept `string`, in which case we assume we have to check an env var/file to get a JSON array with the actual controller addresses.
> feat(config): Add env and file support to Worker Controllers

- internal/cmd/commands/credentiallibrariescmd/vault_funcs.go
- internal/credential/vault/fields.go
- internal/credential/vault/repository_credential_library.go
- internal/credential/vault/setup_manual_test.go
- internal/servers/controller/handlers/credentiallibraries/credentiallibrary_service.go
- internal/servers/controller/handlers/credentiallibraries/credentiallibrary_service_test.go
Some results from manual testing:
Updating from nothing to a user and password mapping:
```
boundary credential-libraries update vault -addr  "http://127.0.0.1:40783" -id clvlt_sy0SWemkbS -credential-mapping-override username_attribute=user -credential-mapping-override password_attribute=pass
Credential Library information:
Created Time:          Wed, 08 Dec 2021 18:00:04 PST
Credential Store ID:   csvlt_jnEvaiatyw
ID:                    clvlt_sy0SWemkbS
Type:                  vault
Updated Time:          Wed, 08 Dec 2021 18:00:43 PST
Version:               2
Scope:
ID:                  p_1234567890
Name:                Generated project scope
Parent Scope ID:     o_1234567890
Type:                project
no-op
read
update
delete
Attributes:
HTTP Method:         GET …
```
> Add support for update/lookup to credential library API/SDK/CLI

- CHANGELOG.md
- internal/cmd/config/config.go
- internal/cmd/config/config_test.go
- website/content/docs/configuration/worker.mdx
Mostly for completeness and consistency, since the Controller description already supports it.
> feat(config): Env/file support for Worker description

- CHANGELOG.md
- plugins/host/mains/aws/go.mod
- plugins/host/mains/aws/go.sum
This updates the AWS host provider to include https://github.com/hashicorp/boundary-plugin-host-aws/pull/7.
> Update AWS host provider

- internal/credential/vault/private_library.go
- internal/credential/vault/repository_credentials_test.go
- internal/errors/code.go
- internal/errors/code_test.go
- internal/errors/info.go
Vault KV backend returns a nil secret and no error if the secret does not
exist. This caused a panic in during Issue:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xf68eae]
panic({0x1823340, 0x4028a00})
/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/boundary/internal/credential/vault.(*privateLibrary).retrieveCredential(0xc0009a0960, {0x3276ea0, 0xc0001b8000}, {0x1adb341, 0x18}, {0xc000560110, 0xc})
/home/louis/boundary/internal/credential/vault/private_library.go:266 +0x12e
github.com/hashicorp/boundary/internal/credential/vault.(*Repository).Issue(0xc000713440, {0x3276ea0, 0xc0001b8000}, {0xc000560110, 0xc}, {0xc000de8ba0, 0xc00069aed0, 0xf}) …
> bug(credential): Fix panic in credential Issue

- internal/servers/controller/gateway.go
- internal/servers/controller/interceptor.go
I added some panic causing code in target list:
```
func (s Service) ListTargets(ctx context.Context, req *pbs.ListTargetsRequest) (*pbs.ListTargetsResponse, error) {
var myMap map[string]interface{}
myMap["Louis"] = "hello"
.....
```
Running list with the grpc_recovery:
```
boundary targets list -scope-id p_1234567890
Error from controller when performing list on targets
Error information:
Kind:                Internal
Message:             rpc error: code = Internal desc = assignment to entry in nil map
Status:              500
context:             Error from controller when performing list on targets
```
In server logs:
```
{
"id": "KpfKq6ZnIw",
"source": "https://hashicorp.com/boundary/dev-controller/boundary-dev",
"specversion": "1.0",
"type": "error",
"data": {
"error": "rpc error: …
```
> feat(server): Add grpc_middleware recovery interceptor

- internal/cmd/commands/targetscmd/funcs.go
Before this fix, calling `boundary targets read -id ttcp_1234567890` in the boundary dev environment would produce duplicate Host Catalog ID and ID values in the Host Sources section. Now, the same output should look like the sample below:
Target information:
Created Time:               Fri, 17 Dec 2021 19:05:14 PST
Description:                Provides an initial target in Boundary
ID:                         ttcp_1234567890
Name:                       Generated target
Session Connection Limit:   -1
Session Max Seconds:        28800
Type:                       tcp
Updated Time:               Fri, 17 Dec 2021 19:05:14 PST
Version:                    2
Scope:
ID:                       p_1234567890
Name:                     Generated project scope
Parent Scope ID:          o_1234567890
Type: …
> fix(cli): Remove duplication of target host sources

- CHANGELOG.md
- internal/db/schema/migrations/oss/postgres/24/01_session_valid_state.up.sql
- internal/db/schema/migrations/oss/postgres_24_01_test.go
- internal/db/sqltest/initdb.d/01_colors_persona.sql
- internal/db/sqltest/initdb.d/02_colors_persona.sql
- internal/db/sqltest/initdb.d/03_widgets_persona.sql
- internal/db/sqltest/tests/session/invalid_state_transition.sql
- internal/db/sqltest/tests/session/valid_state_transition_canceling.sql
- internal/db/sqltest/tests/session/valid_state_transition_pending_active.sql
- internal/db/sqltest/tests/session/valid_state_transition_pending_canceling.sql
- internal/db/sqltest/tests/session/valid_state_transition_terminated.sql
- internal/db/sqltest/tests/wh/session/update_state.sql
- internal/session/immutable_fields_test.go
- internal/session/state_test.go
- internal/session/testing_test.go
Fixes errors that allows for invalid session state transitions (from ‘canceling’ to ‘active) and duplicate session_id/states (ex: two rows with the same session_id and state of ‘active')
These sessions were unable to be cancelled or terminated, as canceling a session in this condition resulted in constraint violation error messages such as `duplicate key value violates unique constraint "session_state_session_id_end_time_key”`
Changes:
* Added `session_valid_state table` with valid state transitions
* `session_state` table updated with `prior_state` column and constraints to only allow valid state transitions and unique `session_id`,`state` 
* Updated sqltests to include session state changes
* Updated tests in internal/session - they were failing with a pkey violation as test sessions …
> bug(session): Allow only valid state transitions

- Makefile
- website/content/docs/developing/building.mdx
This replaces any remaining references to XC_OSARCH with GOOS and GOARCH
since the build script was updated to use the latter.
> Replace XC_OSARCH with GOOS and GOARCH

- internal/session/repository_session.go
If statement on number of found states executed **!=1** before **== 0**. Error for no found states would never be returned as 0 is not equal to 1.
Fixed ordering to check for 0 states first.
> bug(session): Fix CreateSession foundStates logical ordering

- internal/cmd/commands/connect/connect.go
Sessions that time out were printing the message `"No connections left in session"` instead of `"Session has expired"`
termInfo.Reason was using a select on <-timer.C, which will never receive a value if the session has timed out; changing to use `!timer.Stop()` to detect if the timer has already finished.
Fixes #1817
> bug(connect): Fix Session has expired messaging

- internal/db/schema/migrations/oss/postgres/25/01_static_host_view.up.sql
- internal/host/host.go
- internal/host/plugin/host.go
- internal/host/static/host.go
- internal/host/static/repository_host.go
- internal/host/static/repository_host_test.go
- internal/servers/controller/handlers/hosts/host_service.go
- internal/servers/controller/handlers/hosts/host_service_test.go
- internal/tests/api/hostsets/host_set_test.go
Updates LookupHost and ListHost API to include sets a static host is part of, as like with plugin hosts.
> feat(host): Add host set information to static host

- .github/workflows/build.yml
Some OS build steps were not compiling the plugins before compiling the
boundary binary. This resulted in binaries that did not have plugins
included, and would result in an error when starting a boundary server.
> ci: Add plugin compile step

- .github/workflows/build.yml
This modifies the logic by which version strings are created in docker builds, for parity with the enterprise build change here: https://github.com/hashicorp/boundary-enterprise/pull/18
> RDX 223 crt dockerversion parity

- internal/host/plugin/job_set_sync.go
- internal/host/plugin/query.go
- internal/host/plugin/repository_host_util.go
- internal/host/plugin/repository_host_util_test.go
During the plugin_host_set_sync job, a single set failing to sync
can cause all following syncs to fail.
> bug(host): Fix sync job failure blocking other set syncs

- .circleci/config.yml
- .circleci/config/commands/install-protobuf.yml
- .circleci/config/jobs/make-gen-deltas.yml
- .circleci/config/workflows/ci.yml
Addition of workflow job, `make-gen-deltas`, to run `make gen` and detect diffs, in case proto changes are made but generated files are not checked in.
> ci(proto): Detect unchecked API and proto changes

- internal/host/plugin/repository_host_set.go
- internal/host/plugin/repository_host_set_test.go
When creating the options for the preferencer, this used WithIpAddrs for both the host addresses and also DNS names. This causes errors when a host contains DNS names that are not IP addresses (ie: whenever dns names are present).
This change will:
- Replace WithIpAddrs with WithDNSNames option for DNS Names when constructing options for the preferencer.
- Add a test which includes a DNS name to prevent regressions
Fixes #1848
> bug(plugin): Fix incorrect use of WithIpAddrs in Repository.Endpoints

- internal/servers/controller/handlers/targets/target_service.go
- internal/servers/controller/handlers/targets/tcp/target_service_test.go
The targets controller previously only allowed hosts from a static catalog
since it checked for the ID subtype from the static package.
This change validates host ids with the plugin.Subtype as well
Fixes: #1850
> fix(controller/targets): authorize-session should allow h_ ids

- website/redirects.js
This pr adds doc link for dynamic host catalogs to be shown in the helper text for ex:
> add doc link for dynamic host catalog hosts setup

- scripts/plugins.sh
When moving to the new CRT build process, this was missed from the older
build scripts. When building the plugins for Windows, if the files do
not have the `.exe` suffix, boundary fails with errors like the
following:
Error initializing controller: error creating aws host plugin: error fetching host plugin rpc client: exec:
"C:\\Users\\alice\\AppData\\Local\\Temp\\441718622\\boundary-plugin-host-aws": file does not exist
> fix(build): Include .exe suffix when building plugins for Windows

- .github/workflows/build.yml
- .release/ci.hcl
There’s a pesky UI build issue where `yarn install` times out with a network issue causing folks to have to re-run the build manually in the Github UI. This is kind of build failure is easy to miss and this PR is a fix for that. 
I'd like to merge in this fix + have the Boundary team notify our team (release engineering) if they're still running into this issue. This error is sporadic and hard to reproduce unfortunately. 😕
The error looks like this:
> [RDX-309] UI build timeout fix

- internal/cmd/commands/connect/connect.go
Passthrough args looks for the an instance of -- and re-slices the arg
list to pass through those args to the underlying connect exec command.
However such commands may also need to parse their own '--', such as
kubectl exec.
This change updates the logic so that boundary arg parser only considers
the first instance of '--' when deciding which args to pass to the
-exec= commands.
Fixes: #1857
> fix(connect): do not panic on multiple `--` args

- website/redirects.js
This pr updates the existing dynamic host catalog doc link for azure and adds a new doc link for aws.
> chore: updates to azure and AWS doc links

- website/content/docs/concepts/domain-model/targets.mdx
Remove Targets doc reference to a default port attribute - there is no way for the user to specify a port at connect time and we don't currently plan on allowing it either.
> docs(targets): remove default port option

- internal/cmd/commands/server/worker_shutdown_reload_test.go
- internal/db/schema/migrations/oss/postgres_24_01_test.go
- internal/servers/controller/common/common.go
- internal/servers/controller/controller.go
- internal/servers/controller/handlers/targets/tcp/target_service_test.go
- internal/servers/controller/handlers/workers/worker_service.go
- internal/servers/controller/handlers/workers/worker_service_test.go
- internal/servers/controller/listeners.go
- internal/servers/controller/session_cleanup_job.go
- internal/servers/controller/session_cleanup_job_test.go
- internal/servers/controller/testing.go
- internal/session/query.go
- internal/session/repository_connection.go
- internal/session/repository_connection_test.go
- internal/session/repository_session.go
- internal/session/repository_session_test.go
- internal/session/service_authorize_connection.go
- internal/session/service_authorize_connection_test.go
- internal/tests/cluster/session_cleanup_test.go
- internal/tests/helper/testing_helper.go
- Create a new repository, connection_repository, for Session Connections in the Session package.
- Have repository_connection functions use the new Session Connection repo
- Rename sessionCleanupJob to sessionConnectionsCleanupJob for clarity.
- Move AuthorizeConnection from repository_session.go into repository_connection.go.
- Creation of domain service, AuthorizeConnection()
- authorizeConnectionCte refactored so that constraints are more explicit.
> refact(session connections): Create session connection repository

- website/content/docs/api-clients/cli.mdx
I noticed that the Boundary CLI connection options are currently only displayed when `boundary dev -h` is ran. Not sure if this should also be included in the output when `boundary -h` is ran, but is currently not. As part of this commit, I did mention running `boundary dev -h` will display connection options. 
I'm not sure if we should include that in this page given the intention is to have it displayed only when `boundary -h` is ran. We can leave it out for now or keep it as is and update it in the future if we need to.
> updated CLI connection options, including addr

- internal/api/genapi/templates.go
The removeDups template function converts a slice into a map and
back into a slice in order to leverage the map keys to remove
duplicates. However, since the iteration order over a map is not
specified it would be possible to get different orders for multiple runs
of `make api`. While this would not have an impact on any functionality,
it is causing sporadic failures for the new make-gen-deltas CI job.
See: https://go.dev/ref/spec#For_statements
Ref: d57603022a317c99ac4feb0bcb78727e08f9dcfb
> fix(genapi): Sort slice in removeDups template function

- .release/security-scan.hcl
Related slack discussion: https://hashicorp.slack.com/archives/C010VJT0FRP/p1646414431447969
OSV scanning on the boundary binaries needs to be turned off, as it's currently blocking the pipeline. The security team plans to address the underlying issues soon. 
Link to successful run in a test commit: https://github.com/hashicorp/boundary/pull/1894/checks?check_run_id=5455113119
> Turn security scanner osv off

- Makefile
- scripts/build.sh
* `make dev` now shows a message indicating the new commands
* `make build` builds the binary into bin/
* `make install` will subsequently `mv` (not copy) the binary into
GOPATH/bin
The reason for the `mv` is that M1 Macs seem to get pretty unhappy about
executing a copied binary if it's been modified, so an initial binary is
fine, then after changing and recompiling the command keeps getting
killed.
> Update make targets:

- website/content/docs/getting-started/connect-to-target.mdx
This docs PR:
- adds an example of connecting to the default ssh target in dev mode using `target-name` and `target-scope-name`
- removes some passive and ableist language from the copy
On the boundary docs day Task List this task is labeled as:
> target-name and scope-name as arguments for boundary connect
> Docs: Update connect-to-target page with target-name example

- Makefile
- testing/dbtest/docker/Makefile
This adds a new makefile target to build and publish the test database
docker image for multiple architectures. It will create images for:
- linux/amd64
- linux/arm64
The target uses docker buildx to build the images. To build the images:
docker buildx create --driver docker-container --use
make docker-buildx
docker buildx rm
See: https://docs.docker.com/buildx/working-with-buildx/
> chore(dbtest): Build test database docker image for arm64

- internal/db/schema/migrations/oss/postgres/0/51_connection.up.sql
- internal/db/schema/migrations/oss/postgres/0/69_wh_session_facts.up.sql
- internal/db/schema/migrations/oss/postgres/16/05_wh_credential_dimension.up.sql
- internal/db/schema/migrations/oss/postgres/27/01_disable_terminate_session.up.sql
- internal/db/schema/migrations/oss/postgres/27/02_wh_session_facts.up.sql
- internal/servers/controller/handlers/workers/worker_service.go
- internal/session/query.go
- internal/session/repository_connection.go
- internal/session/repository_connection_test.go
- internal/session/repository_session.go
- internal/session/repository_session_test.go
- internal/session/service_close_connections.go
- internal/session/service_close_connections_test.go
Under heavy load, we saw deadlocks as competing processes attempted to close the same connection. A connection was closed on proxy exit at the same time as the Worker failed to make its status call and attempted to close all its connections. Connections and sessions were also closed in the same transactions.
This PR resolves this issue by breaking apart transactions for sessions and connections, and removing the Worker connection closure requests on status failure to prevent the resource contention causing the deadlocks.
- Creation of domain service, CloseConnections, which closes connections in the Connection repo and then attempts to terminate sessions if possible using the Sessions repo
- The Session repository function CloseConnections() has been moved to the Session Connection …
> refactor(session connections): Refactor connection closure

- CHANGELOG.md
- internal/scheduler/job/immutable_fields_test.go
- internal/scheduler/job/query.go
- internal/scheduler/job/repository_run_test.go
- internal/scheduler/job/testing.go
- internal/servers/controller/controller.go
Updates the `RunJobs` query to include an `on conflict do nothing` when the `job_run_status_constraint` is triggered.  Racing controllers can attempt to run the same jobs before they are put into a [running state](https://github.com/hashicorp/boundary/blob/main/internal/db/schema/migrations/oss/postgres/7/03_job.up.sql#L93)
Fixes #1903
> fix(scheduler): Update job run query to not error on running conflict

- internal/servers/controller/controller.go
- internal/servers/controller/handlers/workers/worker_service.go
- internal/servers/controller/handlers/workers/worker_service_status_test.go
- internal/servers/controller/multi_test.go
- internal/servers/controller/session_cleanup_job.go
- internal/servers/controller/session_cleanup_job_test.go
- internal/session/options.go
- internal/session/query.go
- internal/session/repository_connection.go
- internal/session/repository_connection_test.go
- internal/session/repository_session.go
- internal/session/service_worker_status_report.go
- internal/session/service_worker_status_report_test.go
- internal/tests/cluster/session_cleanup_test.go
This creates a domain service function `session.WorkerStatusReport`. The
service performs two functions:
1. Checks the status for all of the reported sessions, returning a
report of the sessions that are in a "non-active" state, i.e.
"cacneling" or "terminated".
2. Looks for any "orphaned" session connections, i.e. connections that
are active but were not reported by the worker. These connections are
marked as closed.
This also removes the "ShouldCloseConnectionsOnWorker" logic, as this
was determined to not be a possible state, and was unnecessary.
Also includes some refactoring to speed up some tests.
> refact(session): Move domain logic of Worker Status into domain service

- README.md
- internal/adding-a-new-field-readme.md
- website/content/docs/developing/building.mdx
"make dev" has been replaced with "make install" since b53e4d4c3ef151a65ac198fb45dc3ed5645aa0c6.
> Update references to "make dev"

- CHANGELOG.md
- internal/servers/worker/handler.go
- Create new error if no tofu token found to prevent `event.newError: missing error: invalid parameter`
- Handle session cancellation before tofu token, to fix error where session was cancelled without making a connection (erred on no tofu token)
Fixes #1902
> bug(worker): create error and handle session cancel with no tofu token

- internal/session/repository_connection_test.go
- internal/session/service_authorize_connection_test.go
This fixes six dropped `err` variables in `internal/session`.
No changelog updates are warranted.
> internal/session: fix dropped test errors

- go.mod
- go.sum
https://github.com/zalando/go-keyring/issues/73 fixed the freebsd issue, I have confirmed locally that it works as expected now.
> Update zalando/go-keyring with freebsd fix

- .release/release-metadata.hcl
Same as https://github.com/hashicorp/boundary/pull/1939 targetting the release/0.7.x branch, since auto-backporting failed in that PR.
> [RelAPI Onboarding release/v0.7.x] Add release API metadata file

- Makefile
Use the standard Go heuristic for determining
whether a file should be ignored by formatting
for being a generated file.
This is effectively a no-op change today, but
if we add new generated files in the future,
we should automatically ignore them in formatting.
> Refactor file formatting target

- internal/cmd/commands/dev/dev.go
- internal/cmd/commands/server/server.go
- internal/servers/controller/controller.go
- internal/servers/controller/listeners.go
- internal/servers/controller/listeners_test.go
- internal/servers/controller/testing.go
- internal/tests/cluster/ipv6_listener_test.go
- internal/tests/cluster/multi_controller_worker_test.go
- internal/tests/cluster/unix_listener_test.go
In general, these changes were introduced in the same vein of the changes to controller `startListeners`.
Specifically, these changes also decouple the Controller and the Worker shutdown processes. Currently, a call to `stopListeners` on an instance that is running as both a Controller and a Worker would stop the listeners for both.
Lastly, we also add unit/integration tests to the shutdown code.
> refactor(controller): Decouple listeners/servers shutdown from Worker

- Makefile
This reverts commit 90297206648218192a9c386419b6798b8c7b1408. It
was causing unexpected errors on some platforms. More investigation
will be necessary.
> Revert "Refactor file formatting target (#1941)"

- Makefile
Use the standard Go heuristic for determining whether a file should be ignored by formatting for being a generated file.
This is effectively a no-op change today, but if we add new generated files in the future, we should automatically ignore them in formatting.
This is a slightly updated version of #1941 that should work across all versions of grep.
> Refactor file formatting target (round 2)

- website/content/docs/api-clients/go-sdk.mdx
There was only a full example for using credentials, this also adds the recovery KMS full example. This also fixes the code example typos.
> docs: Add full example for using recovery KMS workflow

- website/content/docs/configuration/listener/tcp.mdx
- website/content/docs/installing/high-availability.mdx
Apologies in advance if they are not but I believe these changes are correct.
I was recently running through https://github.com/hashicorp/learn-boundary-target-aware-workers/pull/2 and thought these might be discrepancies or opportunity for further clarification.
These 2 changes are regarding https://www.boundaryproject.io/docs/configuration/listener/tcp#listening-on-multiple-interfaces and https://www.boundaryproject.io/docs/installing/high-availability#network-requirements.
> website: clarification on default TCP ports

- internal/cmd/commands/dev/dev.go
- internal/cmd/commands/server/server.go
- internal/servers/worker/controller_connection.go
- internal/servers/worker/listeners.go
- internal/servers/worker/listeners_test.go
- internal/servers/worker/testing.go
- internal/servers/worker/worker.go
- internal/servers/worker/worker_test.go
- internal/tests/cluster/ipv6_listener_test.go
- internal/tests/cluster/multi_controller_worker_test.go
- internal/tests/cluster/unix_listener_test.go
- internal/tests/cluster/worker_replay_test.go
This PR is the Worker equivalent to the following controller change PRs: https://github.com/hashicorp/boundary/pull/1907 and https://github.com/hashicorp/boundary/pull/1908
It affects the same changes, but on the Worker side. These changes are done for consistency purposes, as well as the same reasons they were initially done in the controller.
> refactor(worker): Startup, shutdown and cluster tests changes

- internal/servers/controller/handlers/accounts/account_service.go
- internal/servers/controller/handlers/accounts/validate_test.go
This is unusual and idiomatic, so lets use the keyed literal form
> fix(accounts): correct use of unkeyed literals

- internal/types/subtypes/attribute_transform.go
- internal/types/subtypes/interceptor.go
- internal/types/subtypes/interceptor_test.go
When the attrs oneof was unset, we would populate a zero
value attributes struct. Fixes the behavior and adds a test.
> fix(subtypes): Do not transform unset oneof

- internal/cmd/commands.go
- internal/cmd/commands/config/encryptdecrypt.go
- internal/cmd/commands/database/funcs_test.go
- internal/cmd/commands/database/init.go
- internal/cmd/commands/database/migrate.go
Init was using a local server variable but not passing in the existing
command, resulting in the context being lost. This caused the command to
fail to run since the changes to add logging to KMS plugins were
introduced.
This also fixes a couple of places that were not using the global const
value for config KMS.
> Pull up Server to top level of Init command

- website/content/docs/operations/metrics.mdx
This PR suggests edits for [PR 1977](https://github.com/hashicorp/boundary/pull/1977)
How about using tables for readability?  That's what [Vault Telemetry docs](https://www.vaultproject.io/docs/internals/telemetry#audit-metrics) does. 
🔍 [Deploy Preview](https://boundary-git-use-table-hashicorp.vercel.app/docs/operations/metrics)
> Use table to list metrics

- internal/servers/controller/interceptor.go
It is not unreasonable for downstream users of the request and response
messages to mutate them, indeed we mutate the response
on the way out to get the desired external API. To avoid
inconsistent messages being audited, make a copy of the
entire message before returning from the interceptor.
This was discovered while testing the new subtype transformation
interceptor.
> fix(controller): Clone messages before auditing

- internal/db/read_writer.go
- internal/db/read_writer_test.go
- internal/errors/option.go
Fixes #1925 
@jimlambrt I have been fixing a couple of related scheduler error spam and also thought that perhaps NotFound should be suppressed as well. This is going off your comment left in #1925 happy to discuss if you like
> feat(db): Suppress not found events during db lookups

- CHANGELOG.md
- internal/kms/const.go
- internal/kms/kms.go
- internal/kms/kms_ext_test.go
- internal/kms/options.go
- internal/servers/controller/controller.go
- internal/servers/controller/controller_test.go
When new DEKs are added to boundary we need to ensure that the keys
for existing scopes are reconciled.
This fix should address:
https://github.com/hashicorp/boundary/issues/1856
> fix (kms): properly reconcile DEKs for existing scopes

- internal/servers/controller/testing.go
When requesting a token, any error is fatal to the test.
The previous behavior would return a nil token, which
could cause subsequent uses to panic. This will instead
interrupt any test immediately on error.
> Cancel test on fatal errors

- internal/servers/controller/internal/metric/cluster.go
- internal/servers/controller/internal/metric/cluster_test.go
- internal/servers/controller/listeners.go
gRPC status.Handler gives us visibility into gRPC returned errors. In contrast, there are some situations where no metric would be counted at all using the interceptor approach (for example, in out of memory cases where gRPC would return a resource exhausted error).
This PR also removes the request size and response size metrics.  This is because those are difficult to observe along with the status code label.  In the future, we may revisit recording observations for the request and response sizes to the cluster server.
> Update the cluster server metrics to use the gRPC status.Handler.

- internal/servers/controller/internal/metric/cluster.go
- internal/servers/worker/controller_connection.go
- internal/servers/worker/internal/metric/cluster_client.go
- internal/servers/worker/internal/metric/cluster_client_test.go
- internal/servers/worker/worker.go
Adds request latency observations to the worker side (client) of
worker <-> controller cluster communications by integrating a new
grpc client interceptor.
> feat(worker): Instrumentation for Controller Cluster Communication

- website/redirects.js
This creates a redirect from `/help/admin-ui/targets/worker-filters` to `/docs/concepts/filtering/worker-tags#target-worker-filtering`. This is related to [PR](https://github.com/hashicorp/boundary-ui/pull/1053) which will direct users to the docs for worker filters on targets.
> chore: Add redirect for targets worker filtering

- scripts/build.sh
- scripts/plugins.sh
This causes the build.sh script to chain to plugins.sh which makes
plugin building behave the same for both local and release builds.
> Unify plugin building

- internal/servers/controller/gateway.go
- internal/tests/api/accounts/account_test.go
The new `subtype.AttributeTransformerInterceptor` can return an error if
it fails to transform the attributes. This is mainly if invalid
attribute fields were included for a particular subtype. This error case
used to be checked in the grpc service handler functions. However, now
that it is happening in the interceptor, the `errorInterceptor` needs to
be moved up in the stack so that it will process the response of the new
transformation interceptor.
The `errorInterceptor` used to be after the `auditRequestInterceptor`
and prior to the `auditResponseInterceptor`, meaning that the
`auditResponseInterceptor` would have access to the result of the
`errorInterceptor`. But it seems the `auditRequestInterceptor` does not
use or need any of the headers set by the `errorInterceptor` so it
should …
> feat(controller): Reorder interceptor stack

- internal/cmd/base/servers.go
- internal/cmd/commands.go
Since we call base.NewServer multiple times when building the Commands map this was returning
an error "duplicate metrics collector registration attempted".  This PR only creates a single
server which is used for both the "server" command as well as "dev".
> Do not register the build_info collectors multiple times.

- api/client.go
- internal/servers/common/handler.go
- internal/servers/controller/handler.go
The Go docs now say to use request.Clone (introduced in Go
1.13) instead of request.WithContext (introduced in Go 1.7) as it deep
copies instead of shallow copies.
> Switch request.WithContext to request.Clone

- Makefile
- internal/gen/controller/api/services/role_service.pb.go
- internal/gen/controller/api/services/session_service.pb.go
- internal/gen/controller/api/services/user_service.pb.go
- internal/proto/controller/api/resources/roles/v1/role.proto
- internal/proto/controller/api/resources/sessions/v1/session.proto
- internal/proto/controller/api/resources/users/v1/user.proto
- internal/proto/controller/api/services/v1/role_service.proto
- internal/proto/controller/api/services/v1/session_service.proto
- internal/proto/controller/api/services/v1/user_service.proto
- internal/servers/controller/handlers/authmethods/oidc_test.go
- internal/tests/api/roles/classification_test.go
- internal/tests/api/sessions/classification_test.go
- internal/tests/api/users/classification_test.go
- sdk/pbs/controller/api/resources/roles/role.pb.go
- sdk/pbs/controller/api/resources/sessions/session.pb.go
- sdk/pbs/controller/api/resources/users/user.pb.go
These did not require and refactors since they do not use subtypes, so
they could just be classified.
This also includes a lint fix that came from running `make gen` which
runs `gofumpt`.
> Classification for role, session, users

- internal/cmd/base/option.go
- internal/cmd/base/option_test.go
- internal/cmd/base/servers.go
- internal/cmd/commands.go
This fixes errors related to calling NewServer or NewCommand multiple times when using autocomplete.
> Register the build info metrics using prometheus.DefaultRegistry in an init function

- internal/cmd/commands/connect/client_tls_config.go
- internal/cmd/commands/connect/connect.go
- internal/servers/worker/listeners.go
- internal/servers/worker/worker.go
- internal/tests/cluster/x509_verification_test.go
- internal/tests/helper/testing_helper.go
This reduces the chance that we'll hit a failure due to a mismatched
worker address, on the certificate, especially if a worker has multiple
addresses. We aren't relying on IP/DNS for security anyways, so let's
not have it be a hindrance.
Note: I have some tests I need to port over, will not poke reviewers
until I have them in. But I wanted to get it milestoned so we didn't
forget about it.
> Use custom X.509 verification logic for proxy connections

- internal/cmd/config/config.go
- internal/cmd/config/config_test.go
- internal/observability/event/audit_config.go
This updates the config parsing for this stanza so prevent panics like
the following:
panic: reflect.Value.MapIndex: value of type string is not assignable to type event.DataClassification
goroutine 1 [running]:
reflect.Value.assignTo({0x13fbb20, 0xc000a28700, 0x461367}, {0x1693f9d, 0x16}, 0x14375c0, 0x0)
/usr/lib/go/src/reflect/value.go:2810 +0x2ad
reflect.Value.MapIndex({0x145b1c0, 0xc000a16570, 0xc00072ff20}, {0x13fbb20, 0xc000a28700, 0x98})
/usr/lib/go/src/reflect/value.go:1535 +0x7e
github.com/hashicorp/hcl.(*decoder).decodeMap(0x8, {0xc00012b0b0, 0x28}, {0x67b40a8, 0xc0005fdc80}, {0x14bac80, 0xc0005fdc20, 0x1})
/go/pkg/mod/github.com/hashicorp/hcl@v1.0.0/decoder.go:380 +0xa95
github.com/hashicorp/hcl.(*decoder).decode(0xc000731360, {0xc00012b0b0, 0x28}, {0x67b40a8, 0xc0005fdc80}, …
> fix(config): Prevent panic when setting audit config filter orverrides

- .github/workflows/build.yml
These github actions run on Ubuntu based machine. Ubuntu by default links
`/bin/sh` to dash. So by invoking the plugin.sh script as `/bin/sh ./plugins.sh` 
the script would run under `dash` despite the shebang line. A recent change
that unified some of the build process, introduced additional bashisms into
this script which is caused the build to fail.
This updated the build system to just run the script directly, which will
honor the shebang line. This seems like the best approach since the ubuntu
machine has bash and the shebang line points to bash, so it is natural for
developers to assume bashisms will work.
See:
f370abc1dace6f28b2de81d079de86a98a2bfd93
https://github.com/actions/virtual-environments/blob/ubuntu20/20220410.2/images/linux/Ubuntu2004-Readme.md …
> fix(build): Run plugin script directly instead of with sh

- .github/workflows/build.yml
- internal/ui/VERSION
Depends on: [chore: 🤖 Add build admin UI workflow](https://github.com/hashicorp/boundary-ui/pull/1043).
**This PR is missing:** Update the UI SHA [in version file](https://github.com/hashicorp/boundary/blob/main/internal/ui/VERSION). We need to unlock the dependency on the UI PR (mentioned above) first. I will update this from draft to PR when is ready.
- Refactors `build` workflow to decouple UI build from Boundary. Now consumes the artifacts generated by the UI.
UPDATE: the version of all GH actions will be updated in a separate PR [here](https://github.com/hashicorp/boundary/pull/2030)
> Refactor build ci worfklow to decouple UI build

- internal/cmd/base/servers.go
- internal/observability/event/audit_config.go
- internal/observability/event/audit_config_test.go
- internal/observability/event/eventer_test.go
The wrapper is sometimes unset at the time when the
audit config is validated, so it is impossible for us
to validate that a valid wrapper is configured. The wrapper
is configured by later setup steps because of a dependency
on the eventer in our KMS setup.
> fix(event): Remove wrapper validation

- .github/workflows/build.yml
- Updated all github actions from `@v2` to `@v3`, as per changelogs seems safe and recommended to upgrade:
- `actions/checkout` [changelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md).
- `actions/setup-go` [v3 info](https://github.com/actions/setup-go#v3).
- `actions/setup-node` [v3 release notes](https://github.com/actions/setup-node/releases/tag/v3.0.0).
> Update from v2 to v3 all gh actions

- internal/servers/controller/internal/metric/api.go
- internal/servers/controller/internal/metric/api_test.go
Previously we were matching what boundary considers an id, but that is determined after requests are routed by grpc-gateway.
This changes the regexp to match any path segment to try to behave the same way that grpc-gateway would when assigning values
to the {id} variable declared in the protobuf.
> Make the metrics regexp less strict when matching against the {*id} vars for the "path" label.

- testing/dbtest/docker/Makefile
- testing/dbtest/docker/init-db.sh
This is no longer needed, so we can clean up this script a bit.
The existing environment variable clashes with the one used in the top level Makefile. The new name prevents confusing behavior when setting the env var and creating the test database from the root of the repository.
> Remove old migration code & Avoid db test image confusion

- .github/workflows/build.yml
- ci/goinstall.sh
This fixes security issues and other bugs so we should do so before our next release.
> Bump Go to latest 1.17(.9)

- internal/db/schema/migrations/oss/postgres/28/01_session_create_time_idx.up.sql
- internal/session/query.go
- internal/session/repository_session.go
When applying the limit and order by, the where clause also needs to be
applied to yield the correct results. This can be seen with an example.
Assuming a data set where there are 100 sessions, with 10 sessions
belonging to a user with id `u_user1` and 90 sessions belonging to
`u_user2`. If the constructed query is like:
select *
from
(select public_id from session limit 10) s,
session_list ss
where
s.public_id = ss.public_id
and s.user_id = 'u_user1'
order by create_time asc;
The initial sub-query with the limit could return sessions only
belonging to `u_user2`, then it would apply the where clause and exclude
all of the rows.
Instead if the query is:
with
session_ids as (
select public_id
from sessions as s
where
s.user_id = 'u_user1'
order by create_time asc
limit 10
)
select *
from …
> fix(session): Include where clause with order and limit

- CHANGELOG.md
- internal/db/schema/migrations/oss/postgres/0/50_session.up.sql
- internal/db/schema/migrations/oss/postgres/28/02_prior_session_trigger.up.sql
- internal/db/schema/migrations/oss/postgres_28_02_test.go
- internal/session/repository_session_test.go
Fixes #2040 
Session state trigger is updated to set prior state to the most recent session state. 
In the prior version of the trigger, prior_state was set to the last most recent state that represented a valid state transition for the inserted state (Ex: A session could go through pending, active, terminated, and then canceling would be inserted with active as prior)
With this change, canceling will fail on insert as terminated-> canceling is an invalid state transition
> fix(session): Update session state transition trigger

- CHANGELOG.md
- internal/daemon/controller/intercepting_listener.go
Removing the ALPN muxer exposed the underlying listener directly to the
gRPC server, which means that a quirk of the ALPN muxer (not surfacing
errors on accept) turned into the gRPC server receiving errors on
accept, and it turns out if the error does not satisfy a special
temporary interface the listener will be closed.
The obviously better thing to do would be to let the listener close
itself if there was truly a fatal error rather than relying on
undocumented interfaces, but here we are.
> Leave cluster listener up when bad data is sent

- CHANGELOG.md
- internal/db/schema/migrations/oss/postgres/0/50_session.up.sql
- internal/db/schema/migrations/oss/postgres/29/01_cancel_session_null_fkey.up.sql
- internal/db/schema/migrations/oss/postgres_29_01_test.go
- internal/db/sqltest/tests/session/delete_session_target.sql
- internal/session/repository_session_test.go
Function cancel_session() cancels sessions on deletion of foreign key constraints. It checked whether a session was in a canceling state but not terminated (sessions can transition to terminated without going through canceling).
This update adds a check for a terminated state to prevent attempts to cancel already terminated sessions.
Fixes https://github.com/hashicorp/boundary/issues/2064
> bug(session): null fkey trigger also checks for session terminated state

- .github/workflows/build.yml
- Makefile
- internal/ui/VERSION
Update the UI artifacts consumption within the Boundary CI using a make script to get Boundary Edition.
Updated May 13.
To be aware:
- This PR updates the UI version. **Why?** In the UI we start generating both artifacts (`admin-ui-oss` and `admin-ui-enterprise`) hours before this PR. So there are no artifacts with that naming available for previous SHA's.
Screenshot of the test branch using the make script and the `get-product-edition` job and retrieving the proper UI artifact succesfully:
> Update UI artifacts consumption

- internal/cmd/commands/database/funcs.go
- internal/cmd/commands/database/init.go
- internal/cmd/commands/database/migrate.go
Both the init and migrate commands were ignoring
the configured max_open_connections database
setting. This fix ensures that both commands
respect the limits.
> Respect max open connection limits in migrate and init

- .dockerignore
Since the Dockerfile is now at the repository root, when running
building a docker image, the entire repository was being added to the
context sent to the docker daemon. However, only the compiled binary and
a few configs in `.release/docker` are needed to build the docker
images.
This ignore file will only send necessary fields into the context. This
helps speed up the docker image building.
For example, when building the dev image, without the ignore file:
Sending build context to Docker daemon  2.043GB
And with this ignore file:
Sending build context to Docker daemon  130.7MB
See:
https://docs.docker.com/engine/reference/builder/#dockerignore-file
> chore(docker): Add dockerignore file to reduce context size

- internal/cmd/commands/database/funcs_test.go
This seems to have been missed when #2094 was reviewed and merged.
> Fix build error

- internal/daemon/worker/status.go
- internal/daemon/worker/worker_proxy_service.go
* Don't assume it's non-empty or that this is an issue
* Ensure it's empty if the response is coming back through the multihop
service so that it simply uses what is in the config file, at least
for now
> Update controller address handling

- internal/daemon/controller/handlers/scopes/scope_service.go
- internal/daemon/controller/handlers/scopes/scope_service_test.go
- internal/daemon/controller/handlers/workers/worker_service.go
- internal/perms/acl.go
- internal/perms/acl_test.go
- internal/perms/grants.go
- internal/perms/grants_test.go
- internal/types/action/action.go
- internal/types/action/action_test.go
- internal/types/resource/resource.go
This is a bit more than simply adding the action; we had some
checks to ensure that list/create could only happen/not happen
in some cases and those had to be modified to account for
subactions.
> Add worker creation ACLs

- internal/daemon/controller/controller.go
- internal/servers/job/jobs.go
- internal/servers/job/rotate_roots_job.go
- internal/servers/job/rotate_roots_job_test.go
- internal/servers/service_rotate_roots.go
- internal/servers/service_rotate_roots_test.go
- Create RotateRoots domain function 
- Create RotateRoots job. The current default certificate lifetime is set to 1 year; rotation will occur every 6 months. Rotation should occur on first start up and from then on at the job frequency
- Remove rotate roots call on startup; this is now achieved by the rotate roots job
> feature(WorkerAuth): Create RotateRoots domain and job

- internal/daemon/controller/testing.go
- internal/daemon/controller/testing_test.go
- internal/observability/event/eventer.go
- internal/observability/event/options.go
- internal/observability/event/testing.go
- internal/observability/event/testing_test.go
TestWithoutEventing allows the caller to "disable" all eventing for
a test. You must not run the test in parallel (no calls to t.Parallel)
since the function relies on modifying the system wide default eventer.
> feature (events): add TestWithoutEventing(t)

- .github/workflows/build.yml
- ci/goinstall.sh
- internal/db/db.go
- internal/db/db_test.go
Go 1.18.3 has some security patches over 1.18.1.
See https://go.dev/doc/devel/release#go1.18.minor
> Bump Go version to v1.18.3

- .circleci/config.yml
- .circleci/config/jobs/build.yml
- Makefile
The tparse library adds a nice summary of the test output,
which should hopefully make it easier to find errors in the tests.
> test: Use tparse to simplify test failure analysis

- internal/daemon/controller/handlers/targets/target_service.go
- internal/daemon/controller/handlers/targets/tcp/target_service_test.go
- internal/target/query.go
- internal/target/repository_credential_source.go
- internal/target/repository_credential_source_test.go
- internal/target/tcp/repository_credential_source_test.go
- internal/tests/api/targets/target_test.go
- internal/tests/cli/boundary/_target_credential_sources.bash
- internal/tests/cli/boundary/target_credential_sources.bats
Results from running the new bats tests:
```
bats -p boundary/target_credential_sources.bats
✓ boundary/login: can login as admin user
✓ boundary/credential-stores: can create test-for-add-credential-sources static store in default project
✓ boundary/credentials: can create first-credential credential in test-for-add-credential-sources store
✓ boundary/target: can add first-credential credential source
✓ boundary/target: validate only first-credential credential source present
✓ boundary/target: cannot add duplicate credential source
✓ boundary/target: can delete first-credential credential source
✓ boundary/target: validate first-credential credential source removed
✓ boundary/credentials: can create additional credentials in test-for-add-credential-sources store
✓ boundary/target: can …
```
> Add support static credentials in DeleteCredentialSource and SetCredentialSource 

- internal/cmd/commands/server/server.go
- internal/cmd/config/config.go
- internal/daemon/worker/controller_connection.go
- internal/daemon/worker/status.go
- `hcp_boundary_cluster_id` can be set and used as an intial upstream.
- Adds comparison of old vs new upstreams and emits event.
- Testing will be added to this PR.
> feat(worker): Map cluster ID in config to upstream address

- website/content/docs/configuration/events/file.mdx
- website/content/docs/configuration/events/overview.mdx
Including the "path" in the file example makes it clear that you need to use both of these.
> Clarify audit logging file sink doc

- internal/cmd/commands/targetscmd/funcs.go
- internal/daemon/controller/handlers/targets/target_service.go
Validated manually as well (note I removed the checks to stop egress credential on TCP for validation):
```
boundary targets read -id ttcp_1234567890
Target information:
Created Time:               Thu, 09 Jun 2022 16:59:29 PDT
Description:                Provides an initial target in Boundary
ID:                         ttcp_1234567890
Name:                       Generated target
Session Connection Limit:   -1
Session Max Seconds:        28800
Type:                       tcp
Updated Time:               Thu, 09 Jun 2022 16:59:49 PDT
Version:                    4
Scope:
ID:                       p_1234567890
Name:                     Generated project scope
Parent Scope ID:          o_1234567890
Type:                     project
no-op
read
update
delete
add-host-sets …
```
> fix(target): Correctly return egress credentials assocaited with target

- CHANGELOG.md
- internal/observability/event/cloudevents_formatter_node.go
- internal/observability/event/cloudevents_formatter_node_test.go
- internal/observability/event/context_test.go
- internal/observability/event/hclog_formatter_node.go
- internal/observability/event/hclog_formatter_node_test.go
- internal/servers/repository_workerauth.go
- internal/servers/repository_workerauth_test.go
- internal/servers/worker.go
- website/content/docs/concepts/filtering/events.mdx
Previously a global setting for the `structs` lib was causing the `json`
tag to be used, but this could have side effects from other packages, or
could be affected by other packages' behavior. This behavior was removed
earlier but it means this format call no longer uses `json` tags; this
behavior reverts it.
It also normalizes using mapstructure in a few other places.
> Have hclog payloads use `json` tags

- internal/cmd/commands.go
- internal/cmd/commands/workerscmd/funcs.go
- internal/cmd/commands/workerscmd/workers.gen.go
- internal/cmd/common/help.go
- internal/cmd/gencli/input.go
Current output of `boundary --help` 
Comparison of `boundary workers --help` vs `boundary hosts --help`
CLI after changes in this PR- `boundary --help`  has a value populated for workers, and `boundary workers --help` has an example
> cli(workers): Add extra help func

- CHANGELOG.md
- internal/cmd/commands/connect/connect.go
- internal/cmd/commands/connect/credentials.go
- internal/cmd/commands/connect/credentials_test.go
- internal/cmd/commands/connect/postgres.go
- internal/cmd/commands/connect/ssh.go
Adds support for brokered credentials from the static credential store for postgres
Adds new `sshpass` style for brokering username_password credentials for ssh:
https://user-images.githubusercontent.com/6704214/173732755-d7f5fec0-5853-4731-b261-e1b459f2b221.mp4
> feat(cli): Support credential brokering with sshpass

- CHANGELOG.md
- internal/cmd/base/servers.go
- internal/daemon/controller/controller_test.go
- sdk/plugins/host/load.go
- sdk/wrapper/wrapper.go
Plugin options were previously only applied to the
BuildPluginMap call, resulting in the plugin
execution_dir variable being ineffective.
Also add a test to verify functionality
Previously, only external host plugins would respect
the plugin execution dir. Now, all uses of the embedded
plugins respect the configuration.
> Propagate plugin execution dir to CreatePlugin

- internal/cmd/commands/database/init.go
- internal/cmd/commands/database/migrate.go
- internal/cmd/commands/dev/dev.go
- internal/cmd/commands/server/server.go
- internal/cmd/config/config.go
- internal/daemon/controller/controller.go
- internal/daemon/controller/testing.go
- internal/daemon/worker/testing.go
- internal/daemon/worker/worker.go
* Don't automatically create worker names, as this is now invalid for
PKI workers
* Fix a check in dev that clears out name/description in exactly the
wrong cases
* Change eventing setup to use a hostname-based ID instead of the name
(which could change on every start anyways)
> Fix eventing and worker name setup

- go.mod
- go.sum
- internal/cmd/base/servers.go
- internal/cmd/commands/dev/dev.go
- internal/cmd/commands/server/server.go
- internal/daemon/worker/auth_rotation.go
- internal/daemon/worker/controller_connection.go
- internal/daemon/worker/testing.go
- internal/daemon/worker/worker.go
- internal/daemon/worker/worker_test.go
This essentially worked for non-dev mode before but would create storage
directories that weren't actually used or needed, and it didn't work in
dev mode because it made assumptions about the presence of a worker auth
kms or not. This fixes those behaviors.
> Allow a worker to use KMS auth but accept PKI for proxy

- internal/daemon/controller/handlers/workers/worker_service_test.go
- internal/servers/repository_worker.go
- internal/servers/repository_worker_test.go
- internal/servers/testing.go
- Removes description from upsert to prevent update_version_column trigger firing
- KMS workers are invalid for Update
- Fix tests
> bug(workers): KMS workers cannot be updated

- Makefile
- internal/proto/buf.breaking.json.yaml
- internal/proto/buf.breaking.wire.yaml
- internal/proto/buf.yaml
We generally care about preserving JSON compatibility for protobuf
files, but for some files, where we only use pure gRPC, we only
care about preserving wire compatibility.
Split our buf breaking invocation into two invocations, one that checks
for WIRE_JSON compatibility, and one that checks only for WIRE
compatibility. The former check ignores protos in controller/servers,
since they do not need to adhere to this stricter definition.
> Split proto breaking change detection config

- internal/daemon/controller/controller.go
If a worker starts up and tries to connect to a controller before the
controller has a chance for its rotate roots job to run, it'll spit out
a nasty-looking error. It's harmless (things just retry and then work)
but scary (`tls: internal error`).
Rotating at creation time ensures that it's ready by the time a worker
is able to perform any connection against the cluster port.
> Fix harmless but nasty-looking error

- .release/ci.hcl
Currently, darwin arm binaries are not being notarized. Thanks to Louis for the call-out. This PR adds that in.
> [CI-only] Notarize darwin arm

- .github/workflows/build.yml
The intention for the `version` input is for it to find the correct zip artifact name, so it shouldn't be the `dockerversion`, that's only needed for the tags. This also means no need to explicitly config the zip artifact name.
> fix actions-docker-build invocation

- CHANGELOG.md
- internal/db/schema/migrations/oss/postgres/34/02_worker_controller_tables.up.sql
- internal/db/schema/migrations/oss/postgres/35/01_job_migrations.up.sql
- internal/db/sqltest/Makefile
- internal/db/sqltest/tests/controller/controller_id.sql
- internal/scheduler/job/repository_run_test.go
- internal/scheduler/job/testing.go
- internal/server/repository_controller_test.go
The job_run table has a foreign key to the server_controller private_id.
While this column is called a prviate_id it does not implement the wt_private_id
postgres domain type, and therefore does not have a minimum length of 10 characters.
> bug(scheduler): Fix controller id length check

- go.mod
- go.sum
This includes https://github.com/hashicorp/go-secure-stdlib/pull/41, which fixes https://discuss.hashicorp.com/t/latest-boundary-versions-ignoring-plugins-execution-dir/41281
> Upgrade configutil dependency

- internal/cmd/base/servers.go
- internal/cmd/commands/server/server.go
- internal/cmd/config/config.go
- internal/cmd/config/config_test.go
- internal/db/db.go
- internal/db/db_test.go
- internal/db/option.go
- internal/db/option_test.go
- internal/db/schema/migrations/oss/postgres_26_01_test.go
- internal/db/schema/migrations/oss/postgres_30_01_test.go
- internal/db/schema/migrations/oss/postgres_32_01_test.go
- internal/db/testing.go
- website/content/docs/configuration/controller.mdx
This adds two new config options for the `database` stanza:
- `max_idle_connections`
- `max_idle_time`
These correspond to settings for the underlying `sql.DB` instance. They
can be used to have finer control over the controller's database
connection pool. For example this can be used to mitigate the high
connection overhead when connecting to postgres by setting a high
`max_idle_connections` and either setting `max_idle_time` to zero or to
a high duration.
Alternatively, if using a connection pool like pgpool-II or pgbouncer,
`max_idle_connections` can be set to 0.
See:
https://pkg.go.dev/database/sql#DB.SetMaxIdleConns
https://pkg.go.dev/database/sql#DB.SetConnMaxIdleTime
https://www.pgpool.net/mediawiki/index.php/Main_Page
https://www.pgbouncer.org/
> feat(config): Add database config options for idle connection management

- CHANGELOG.md
- internal/daemon/controller/handlers/targets/tcp/target_service_test.go
- internal/db/schema/migrations/oss/postgres/0/41_targets.up.sql
- internal/db/schema/migrations/oss/postgres/37/01_set_unlimited_connections_limit.up.sql
- internal/db/sqltest/tests/wh/credential_dimension_views/source.sql
- internal/db/sqltest/tests/wh/host_dimension_views/source.sql
- internal/session/repository_session_test.go
- internal/session/service_authorize_connection_test.go
- internal/session/service_close_connections_test.go
- internal/target/options.go
- internal/target/tcp/target_test.go
- website/content/docs/concepts/domain-model/targets.mdx
Updates the default connection limit on a target from 1 to 5 in order to reduce the first time user gotcha that most things require multiple connections to work.
> feat: set default connection limit to -1 instead of 1

- go.mod
- go.sum
- internal/daemon/controller/intercepting_listener.go
- internal/daemon/controller/worker_tls_config.go
This builds on the previous change in the nodeenrollment library to
allow KMS connections to store incoming ALPN NextProto information.
> Add client next protos to KMS connection info

- Makefile
Now developers on the M1 can use
```
DEV_DOCKER_GOARCH=arm64 make docker-build-dev
```
> Support building docker images on M1

- website/content/docs/api-clients/cli.mdx
- website/content/docs/api-clients/go-sdk.mdx
- website/content/docs/concepts/domain-model/groups.mdx
- website/content/docs/concepts/domain-model/managed-groups.mdx
- website/content/docs/concepts/domain-model/roles.mdx
- website/content/docs/concepts/domain-model/scopes.mdx
- website/content/docs/concepts/domain-model/sessions.mdx
- website/content/docs/concepts/filtering/events.mdx
- website/content/docs/concepts/filtering/oidc-managed-groups.mdx
- website/content/docs/concepts/filtering/resource-listing.mdx
- website/content/docs/concepts/filtering/worker-tags.mdx
- website/content/docs/concepts/security/connections-tls.mdx
- website/content/docs/concepts/security/data-encryption.mdx
- website/content/docs/configuration/kms/aead.mdx
- website/content/docs/configuration/kms/alicloudkms.mdx
- website/content/docs/configuration/kms/transit.mdx
- website/content/docs/configuration/listener/unix.mdx
- website/content/docs/configuration/worker/kms-worker.mdx
- website/content/docs/configuration/worker/pki-worker.mdx
- website/content/docs/getting-started/connect-to-target.mdx
- website/content/docs/getting-started/deploy-and-login.mdx
- website/content/docs/getting-started/index.mdx
- website/content/docs/oss/index.mdx
- website/content/docs/oss/operations/metrics.mdx
- website/content/docs/what-is-boundary.mdx
In preparation to migrate boundary docs to devdot in August, I'm taking the liberty of cleaning up some glaring content issues before the migration.
:mag: [Deploy Preview](https://boundary-git-docs-update-learn-to-tutorial-hashicorp.vercel.app/docs)
> Boundary documentation: content cleanup in prep for devdot migration

- .github/workflows/build.yml
- ci/goinstall.sh
Go 1.18.4 has some security patches over 1.18.3.
[Go Release Change Logs](https://go.dev/doc/devel/release#go1.18.minor)
> Bump Go version to v1.18.4

- internal/cmd/commands/accountscmd/funcs.go
- internal/cmd/commands/groupscmd/funcs.go
- internal/cmd/commands/hostsetscmd/funcs.go
- internal/cmd/commands/rolescmd/funcs.go
- internal/cmd/commands/userscmd/funcs.go
In the code snippet below, we were getting panics from `result.GetResponse()` because we weren't checking the err value. When an error value is returned, then result is nil, which causes a panic.
```
func executeExtraActionsImpl(c *Command, origResp *api.Response, origItem *users.User, origItems []*users.User, origError error, userClient *users.Client, version uint32, opts []users.Option) (*api.Response, *users.User, []*users.User, error) {
switch c.Func {
case "add-accounts":
result, err := userClient.AddAccounts(c.Context, c.FlagId, version, c.flagAccounts, opts...)
if err != nil {
return nil, nil, nil, err
}
return result.GetResponse(), result.GetItem(), nil, err
case "set-accounts":
result, err := userClient.SetAccounts(c.Context, c.FlagId, version, c.flagAccounts, opts...)
if err != …
```
> fix(cli) check error value in executeExtraActionsImpl funcs

- .github/workflows/build.yml
- .github/workflows/enos-fmt.yml
- .github/workflows/enos-run.yml
- .gitignore
- enos/Makefile
- enos/README.md
- enos/enos-variables.hcl
- enos/enos.hcl
- enos/enos.vars.hcl
- enos/modules/az_finder/main.tf
- enos/modules/bats_deps/main.tf
- enos/modules/binary_finder/main.tf
- enos/modules/build_crt/main.tf
- enos/modules/build_local/main.tf
- enos/modules/build_local/templates/build.sh
- enos/modules/random_stringifier/main.tf
- enos/modules/target/main.tf
- enos/modules/test_cli_ui/tests.tf
- enos/modules/test_smoke/README.md
- enos/modules/test_smoke/main.tf
- enos/templates/connect-target.sh
- enos/templates/get-token.sh
- internal/tests/cli/boundary/_helpers.bash
- internal/tests/cli/boundary/groups.bats
- internal/tests/cli/boundary/roles.bats
- internal/tests/cli/boundary/sessions.bats
- internal/tests/cli/boundary/target.bats
On pull requests that originate from branches of the `hashicorp/boundary`
repo, we now conditionally dispatch infrastructure integration tests using
the Enos framework. The `integration` Enos scenario includes two `builder`
variants which allow developers or CI to deploy a Boundary cluster in AWS
using either a local `boundary` install bundle or that which is produced
in the `build` workflow for CRT. The `test` variants determine which type
of infrastructure integration test to run. At present those options are
`cli_ui` (Bats CLI tests) or `smoke` (creates target instances and a
target host catalog and verifies that `boundary` works).
In addition to the new workflow and quality scenarios, we simplified the
some `build` workflow steps and added Go module caching to speed up the
build …
> [QTI-220] Add infrastructure integration testing

- internal/cmd/base/base.go
Token values can be shown in output of `ps` and so, and we support env
vars and keyrings, so remove it.
> Remove `-token` flag

- internal/ui/VERSION
Bumps the UI version to the latest on main.
> chore: bump UI version to latest

- internal/cmd/commands/server/server.go
#2288 introduced some safety precautions for a nil controller, this included not starting an ops listener if the controller was nil. However, the current `ops.NewServer` code is valid for a nil controller (i.e. a worker only definition). In this state it starts a `/metrics` endpoint ([see](https://github.com/hashicorp/boundary/blob/main/internal/cmd/ops/server.go#L133)) which is used by HCPb to check the worker health and to not keep restarting it
> bug(server): Start ops listener even if controller is nil

- internal/cmd/config/config.go
- internal/cmd/config/config_test.go
- internal/daemon/worker/auth_rotation_test.go
- internal/daemon/worker/testing.go
- internal/daemon/worker/testing_test.go
Although it didn't matter in the combined state, the KMS for auth
storage was not actually being set properly if only a worker was being
instantiated.
> Clean up some dev config kms code

- internal/cmd/commands/accountscmd/funcs.go
- internal/cmd/commands/accountscmd/password_funcs.go
- internal/cmd/commands/authenticate/password.go
* Account password create/set/change
* Authenticate
Also fixes a bug where confirmation on a change-password call would run
for the current password instead of the new one.
> Add parsepath logic to password in various places

- CHANGELOG.md
- internal/cmd/commands/database/init.go
- internal/cmd/commands/dev/dev.go
- internal/cmd/commands/server/server.go
Fixes #2332
- `database init` was not calling cleanup at all
- `server` and `dev` only called it after setting up listeners but if we error before then we never cleanup
> bug(cmd): Ensure RunShutdownFuncs is called when an early error occurs

- internal/daemon/worker/status.go
The intention of the code was to have one-hop-away workers list KMS
workers to get initial upstreams, and have other workers continue using
what was in their config file. However, nothing stops people from having
initial_upstreams but _also_ adding a cluster ID in their config file,
in which case we'd always run this check and replace the config-set
initial upstreams. So, ensure the config-set initial upstreams is also
len zero.
> Ensure initial upstreams is empty before hcpb worker listing

- internal/daemon/controller/handlers/sessions/session_service_test.go
- internal/daemon/controller/handlers/targets/tcp/target_service_test.go
Disabling the auth was resulting in some unrealistic tests setup and 
expectations. It also makes it difficult to refactor any behavior in the 
authn/authz flow since this option can bypass most of it.
> Remove auth.DisabledAuthTestContext from session and target service tests

- enos/modules/aws_nomad/nomad-instances.tf
- enos/modules/aws_nomad/variables.tf
- enos/modules/nomad_job/configs/init.nomad
- enos/modules/nomad_job/main.tf
- enos/modules/nomad_job/scripts/deploy-job.sh
- enos/templates/install-docker.sh
* Move jq deps to our earlier dependency installation
* Add more guards around installation
* Try and make job module more generic-er for the future
* Make controller group count configurable
> Enos: break out init job, cleanup

- CHANGELOG.md
- internal/cmd/base/flags.go
- internal/cmd/common/flags_test.go
For a flag type used for attributes/secrets, values have always been
able to be used with env:// or file:// format, but the error check to
see whether the value was successfully parsed was doing a simple string
equality rather than `errors.Is`. As a result a value containing a colon
would trip up this check and cause an error, rather than allowing it to
be used as a bare value.
Fixes ICU-5629
> Fix error validation code in attr parsing

- Dockerfile
This is necessary since the merge of https://github.com/hashicorp/actions-docker-build/pull/25
Note that our `build-docker` job uses the `version` input correctly, I think: https://github.com/hashicorp/boundary/blob/369f818f4c39f303e4d41af8130982b765b1c18d/.github/workflows/build.yml#L316-L344.
> Update Dockerfile to use new PRODUCT_VERSION arg

- .github/workflows/build.yml
Enos jobs are still a bit unstable, we should use them as
advisory for now. When they have gained more stability,
we can let them fail pipelines again.
Uses https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error
> feat: Stop enos jobs from failing CI pipelines

- .github/workflows/build.yml
- .github/workflows/enos-run.yml
Maybe this will fix it? This doesn't make any sense.
Apparently the last fix was wrong too: https://github.com/hashicorp/boundary/actions/runs/2879194545. I think this should be it!
> fix: Move enos job attribute into enos-run workflow

- enos/templates/get-token.sh
Previously, we would see failures when the ALB in front of a cluster was alive and passing healthchecks, but the database behind had not been initialized yet.  This adds a check with an unauth'd call to `auth-methods list` to validate the DB is up before auth.
> Enos: add additional guards before authentication

- Makefile
- scripts/build.sh
`make docker-build-dev` cross-compiles for linux amd64 and fails when printing the Boundary version.  This PR removes the version print.
> Fix dev Docker build

- internal/cmd/commands/authmethodscmd/oidc_funcs.go
- internal/cmd/commands/workerscmd/worker-led_funcs.go
Fix panic if invalid token is passed:
```
% boundary workers create worker-led -worker-generated-auth-token=bogus
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x10533ce24]
goroutine 1 [running]:
github.com/hashicorp/boundary/internal/cmd/commands/workerscmd.executeExtraWorkerLedActionsImpl(0x14000b6cfc0?, 0x0?, 0x10535e532?, {0x0?, 0x0?}, 0x18?, 0xc0fb18?, {0x0?, 0x14000c0fb88?, 0x1044c4f20?})
/boundary/internal/cmd/commands/workerscmd/worker-led_funcs.go:67 +0x84
```
> bug(workers): Create worker-led panics on invalid token

- internal/daemon/controller/handlers/managed_groups/validate_test.go
This fixes occurences of a loop variable being captured in parallel
tests. With the previous code, only the last test case is actually
exercised. To work around this problem, we create a local copy of the
range variable before the parallel test, as suggested in the
documentation for the `testing` package:
https://pkg.go.dev/testing#hdr-Subtests_and_Sub_benchmarks
Issues were found automatically using the `loopvarcapture` linter.
> Fix incorrect use of loop variable in parallel tests

- internal/daemon/controller/handlers/managed_groups/managed_group_service.go
- internal/daemon/controller/handlers/managed_groups/validate_test.go
The logic would panic if no attributes were specified. Ensure that attributes are non-nil before checking any sub fields.
> Fix validation function panic

- internal/db/sqltest/Makefile
- testing/dbtest/pgtap-docker/Dockerfile
- testing/dbtest/pgtap-docker/LICENSE
- testing/dbtest/pgtap-docker/Makefile
- testing/dbtest/pgtap-docker/README.md
- testing/dbtest/pgtap-docker/test.sh
This forks pgtap-docker and builds the image locally, and updates our references to use our forked image. The old repository is archived: https://github.com/subzerocloud/pgtap-docker
> Fork pgtap-docker to support arm64

- internal/cmd/commands/server/server.go
- internal/cmd/commands/server/worker_initial_upstreams_reload_test.go
- internal/daemon/worker/status.go
- internal/daemon/worker/worker.go
On a SIGHUP, if the worker's `initial_upstreams` config option has changed,
it will use the new values as the address to send its status. Any
previously discovered upstream addresses from previous status requests are
dropped. Once a successful status request is made to the new addresses, the
worker will resume its normal behavior of using the addresses from the
response to the status request.
This allows a worker to be deployed in a more stable way in a dynamic
environment where controller IPs could change. In particular this helps
with a case where all controllers are replaced with new controllers running
on new IPs.
To illustrate with an example, suppose there is an instance group of
controllers instances. And there are worker instances that have their
config rendered from …
> feat(worker): Support reloading of initial upstreams on SIGHUP

- .github/workflows/enos-run.yml
Disable the fail-fast feature for the matrix strategy. This prevents a
single failure to cascade to all jobs in the matrix. This prevents cases
where other jobs fail before they're able to clean up resources.
Signed-off-by: Ryan Cragun <me@ryan.ec>
> enos: don't fail fast in enos integration matrix

- internal/proto/buf.lock
This fixes some CI issues. See https://docs.buf.build/faq#googleapis-failure for more information. There are no functional changes here, since any effect of the update would only be seen through changes in generated files, of which there are none.
> Update googleapis/grpc-gateway dependency

- internal/cmd/commands/server/controller_db_swap_test.go
- internal/cmd/commands/server/listener_reload_test.go
- internal/cmd/commands/server/server.go
- internal/db/changesafe_reader_writer.go
- internal/db/db.go
- internal/db/db_test.go
- internal/db/read_writer.go
- internal/db/read_writer_oplog.go
- internal/db/testing.go
- internal/kms/kms.go
- internal/kms/kms_ext_test.go
- internal/kms/kms_test.go
This allows atomically swapping to the new object. A timeout is introduced so that if the object is swapped after the existing one has been looked up it isn't immediately invalidated. The timeout is arbitrary but has been set to five minutes as anything running that long probably _should_ be interrupted.
This could be done with mutexes to avoid the arbitrary timeout, but that carries its own risk: if a write lock is attempted to be acquired while a query is holding a read lock, the write lock will block, and any subsequent read locks will also block since write locks take priority. As a result, if a query is long-running or timing out, all other queries in the system will become blocked. Our default user request timeout is 90 seconds and some jobs have no timeout at all, so this is not a …
> Use an atomic.Pointer to store wrapped DB objects

- internal/cmd/base/dev.go
- internal/cmd/base/servers.go
- internal/cmd/commands/database/funcs_test.go
- internal/cmd/commands/database/init.go
- internal/cmd/commands/server/controller_db_swap_test.go
- internal/cmd/commands/server/listener_reload_test.go
- internal/cmd/commands/server/server.go
- internal/daemon/controller/testing.go
- internal/db/changesafe_reader_writer.go
- internal/db/db.go
- internal/db/db_test.go
- internal/db/read_writer.go
- internal/db/read_writer_oplog.go
- internal/db/schema/internal/postgres/postgres.go
- internal/db/schema/manager.go
- internal/db/testing.go
- internal/kms/kms.go
- internal/kms/kms_ext_test.go
- internal/kms/kms_test.go
If the database url is updated on Boundary's config and then a SIGHUP
triggered, we now connect to the new database, ensure it's OK to use
and use that one going forwards instead.
> Reload database on SIGHUP

- internal/cmd/commands/dev/dev.go
- internal/cmd/config/config.go
- internal/cmd/config/config_test.go
- internal/daemon/controller/controller.go
- internal/daemon/controller/testing.go
- internal/scheduler/scheduler_test.go
- website/content/docs/configuration/controller.mdx
Run a manual test with the following config locally:
```
controller {
name = "d1"
description = "A controller for a demo 1!"
database {
url = "postgresql://127.0.0.1/boundary?sslmode=disable"
}
scheduler {
job_run_interval = "1s"
monitor_interval = "1s"
}
}
```
I also added a log every-time the ticker was reset and got an event each second from both loops
> feat(scheduler): set intervals from config

- internal/credential/vault/jobs_test.go
- internal/credential/vault/repository_credential_store.go
- internal/scheduler/scheduler.go
Currently the Vault credential store API accepts any token TTL, we validate the TTL and store the next renewal time during create and update. We should return an error if that TTL cannot be honored due to the scheduler interval for running jobs.
Now we compare the ttl value to the runJobsInterval value and return an error to the user when we cannot honor the token renewal.
`scheduler interval must be greater than token ttl. scheduler jobs interval value: 2s`
> fix: return an error for vault tokens that will expire before the scheduler can run

- internal/cmd/commands/targetscmd/ssh_funcs.go
- internal/daemon/worker/handler.go
Output from CLI target help
```
$ boundary targets update
Usage: boundary targets update [type] [sub command] [options] [args]
This command allows update operations on Boundary target resources. Example:
Update a tcp-type target:
$ boundary targets update tcp -id ttcp_1234567890 -name devops -description "For DevOps usage"
Please see the typed subcommand help for detailed usage information.
Subcommands:
ssh    Create a ssh-type target (HCP only)
tcp    Update a tcp-type target
$ boundary targets create
Usage: boundary targets create [type] [sub command] [options] [args]
This command allows create operations on Boundary target resources. Example:
Create a tcp-type target:
$ boundary targets create tcp -name prodops -description "For ProdOps usage"
Please see the typed subcommand help for …
```
> chore(targets): Improve help and errors around ssh targets

- internal/perms/acl.go
- internal/perms/acl_test.go
When generating permissions from the grants, if a single grant was
limited to the set of "self" actions, the permission would be marked as
only self, even if additional grants were given for non-self actions.
This would result in the generated permissions being more limiting then
they should be based on the grants. This only impacts the sessions list
endpoint. It would result in users that have been granted access to list
other user's sessions to be unable to see these results in the list
results.
> fix(perms): Properly resolve "only self" for permissions

- website/content/docs/concepts/filtering/events.mdx
- website/content/docs/configuration/events/common.mdx
- website/content/docs/configuration/kms/aead.mdx
- website/content/docs/configuration/worker/index.mdx
This PR address the reported issues:
- Remove [broken link](https://www.boundaryproject.io/docs/concepts/filtering/events) -- since there is a link to [common sink parameter]() doc page, I removed the hyperlink on `sink`
-  For now, made the `https://hashicorp.com/boundary.io/ServerName/Path/FileName` to be a text (not a hyperlink) --> we probably need little more description though...
- Add missing title on [AEAD KMS](https://www.boundaryproject.io/docs/configuration/kms/aead) doc page
- Flip the order of KMS worker and PKI worker
> [docs] Address reported bugs

- internal/credential/vault/repository_credentials.go
The scheduler by default only runs every minute, if a credential is Issued by Vault that has a lower TTL of 1 minute or what every the scheduler interval is set to, we should warn the user that this credential will expire before we can renew it.
Check the metadata from the vault secret to validate the token period is greater than the runJobsInterval. When we cannot renew the token in time, we log the issue.
> fix: show user warning log when token period is less than jobRunInterval

- internal/cmd/commands/connect/postgres.go
- internal/cmd/commands/connect/ssh.go
Came up during a demo, I see we mark the copied cred as consumed but never set it in the returned creds
> cli(ssh): Do not print private key if consumed

- website/redirects.js
[Jira](https://hashicorp.atlassian.net/browse/ICU-5993)
This link is used on the `learn more` vault credential store worker filter
> chore: add worker tags redirect

- internal/scheduler/scheduler.go
We log when the scheduling and monitor loop go down so it makes sense to log when they start. Also since these values are configurable it is good to log:
```
{
"id": "AguTiArdEX",
"source": "https://hashicorp.com/boundary/louisruch-C02DF0BSML85/controller+worker",
"specversion": "1.0",
"type": "system",
"data": {
"version": "v0.1",
"op": "scheduler.(Scheduler).monitorJobs",
"data": {
"interrupt threshold": "5m0s",
"monitor interval": "30s",
"msg": "monitor loop running",
"server id": "dev-controller"
}
},
"datacontentype": "text/plain",
"time": "2022-09-15T08:29:42.078339-07:00"
}
{
"id": "LvcWbEfftP",
"source": "https://hashicorp.com/boundary/louisruch-C02DF0BSML85/controller+worker",
"specversion": "1.0",
"type": "system",
"data": {
"version": "v0.1",
"op": …
```
> scheduler: log details when starting scheduler

- internal/daemon/controller/handlers/targets/target_service.go
- internal/db/schema/migrations/oss/postgres/51/01_server_worker_release_version.up.sql
- internal/server/options.go
- internal/server/options_test.go
- internal/server/repository_worker.go
- internal/server/repository_worker_test.go
Add view migration comment
Only use active workers for the target service; allow workers in an unknown state if they have no release version for backwards compatibility.
> address op state review feedback

- website/Makefile
This fixes both `io` and `developer` local preview not having a `controller.swagger.json` present in the Docker container.
```bash
make website/build-local && make website/local
make website/build-local && PREVIEW_MODE=developer make website/local
```
> fix(Makefile): mount `/../internal/gen`

- website/content/docs/api-clients/api.mdx
This makes it easier to find the generated API docs from the API description page.
> doc: Add link to generated API docs on API page

- .github/workflows/build.yml
- Makefile
- internal/tests/cli/Makefile
- internal/tests/cli/README.md
- internal/tests/cli/boundary/sessions.bats
- internal/tests/cli/test.sh
Several of these tests are being skipped in the enos run. This seems to be
due to differences in the setup that is performed. When these tests were
run manually, `boundary dev` was used which performs some setup of
resources automatically. However since enos uses a non-dev controller, a
similar setup is performed via the enos modules.
Until the discrepancies between the setup can be investigated, this adds a
separate CI job to run the tests against `boundary dev`. These tests are
all passing, without any being skipped. This test suite can still be useful
even if the enos version is fixed, since this test suite will run much
faster, and therefore identify failures sooner.
> chore(cli): Run bats tests against boundary dev in CI

- CHANGELOG.md
- internal/db/schema/migrations/oss/postgres/54/02_session_defer.up.sql
- internal/db/sqltest/Makefile
- internal/db/sqltest/initdb.d/04_foodtruck_persona.sql
- internal/db/sqltest/tests/org/org-delete.sql
- internal/db/sqltest/tests/wh/session/update_state.sql
The schema changes introduced in 0.10.2 introduced a bug where an org
could not be deleted if there was a session for an org scoped user. It
would result in an error like:
scope.(Service).deleteFromRepo: unable to delete scope: \
iam.(Repository).DeleteScope: failed for o_VkNy46KwfS: \
iam.(Repository).delete: db.DoTx: iam.(Repository).delete: \
db.Delete: insert or update on table "session" violates foreign key constraint "target_fkey": integrity violation: error #1003
A worker around would be to first delete all projects in the org, then
finally delete the org.
This fix adds a regression test to the sqltests and updates several
constraints on the session table to be deferrable. Since the org delete
is a single transaction, this allows all of the necessary resources to
be deleted before …
> fix(org): Address bug that prevented deleting an org

- internal/cmd/base/base.go
- internal/cmd/base/dev.go
- internal/cmd/base/initial_resources.go
- internal/cmd/base/servers.go
- internal/cmd/commands.go
- internal/cmd/commands/dev/dev.go
- internal/cmd/commands/server/controller_db_swap_test.go
- internal/cmd/commands/server/listener_reload_test.go
- internal/cmd/commands/server/server.go
- internal/cmd/commands/server/server_test.go
- internal/cmd/commands/server/worker_initial_upstreams_reload_test.go
- internal/cmd/commands/server/worker_shutdown_reload_test.go
- internal/cmd/commands/server/worker_tags_reload_test.go
- internal/daemon/controller/testing.go
- internal/daemon/worker/worker.go
- internal/tests/helper/testing_helper.go
- Changed the shutdown channel so that it stays open to listen for more interrupts
- Addition of worker graceful shutdown- on first ctrl+c, worker will start graceful shutdown (waiting for active connections to drain). Second will cause the worker to move on to shutdown. Third will force shutdown immediately.
> Worker graceful shutdown

- Dockerfile
The container image published at https://hub.docker.com/r/hashicorp/boundary is based on an older Alpine 3.13.6 release with a number of known CVEs. The most recent version in that branch is 3.13.12.
This moves to using the `3.13` tag, which will automatically adopt new minor Alpine releases as they are published.
(Per https://alpinelinux.org/releases/, 3.13 is supported until November 2022; we can handle moving to a newer major release separately.)
> update Dockerfile to use more recent Alpine 3.13 releases

- internal/credential/vault/repository_credentials.go
Logs being outputted are:
```
{"id":"emh1hZlzfl","source":"https://hashicorp.com/boundary/louisruch-C02DF0BSML85/controller+worker","specversion":"1.0","type":"error","data":{"error":"WARNING: credential will expire before job scheduler can run","error_fields":{},"id":"e_UmCnoQYSkb","version":"v0.1","op":"vault.(Repository).Issue","request_info":{"id":"gtraceid_45EE3dmtLXHqArr18oXF","method":"POST","path":"/v1/targets/ttcp_yQ3Uqi9m3b:authorize-session","public_id":"at_hTNClxu0se","client_ip":"127.0.0.1"},"info":{"runJobsInterval":36000000000000}},"datacontentype":"application/cloudevents","time":"2022-09-21T11:22:50.984607-07:00"}
```
> log(vault): Log formatted duration instead of nanoseconds

- internal/db/schema/migrations/oss/postgres/55/03_create_kms_key_destructions.up.sql
- internal/db/sqltest/Makefile
- internal/db/sqltest/initdb.d/03_widgets_persona.sql
- internal/db/sqltest/tests/kms/kms_data_key_destruction_job.sql
The schema lets us manage destruction jobs per-table while providing a guarantee that only one run is running at a time.
> Add schema for new kms destruction jobs

- Dockerfile
The container image published at https://hub.docker.com/r/hashicorp/boundary has broad read permissions for the `/boundary/` directory, which may contain sensitive configuration information.
```
/ # ls -al /boundary/
total 12
drwxr-xr-x    2 boundary boundary      4096 Sep 19 17:29 .
drwxr-xr-x    1 root     root          4096 Sep 19 17:29 ..
-rw-r--r--    1 boundary boundary      2222 Sep 14 00:39 config.hcl
```
This sets more restrictive permissions for files in that directory.
> tighten access to /boundary/config.hcl in container images

- Makefile
- testing/dbtest/docker/Makefile
Previously, building this target on an ARM machine would produce an image with a amd64 binary inside an arm OS.
Note: there's no need for the user to explicitly run `docker buildx create --driver docker-container --use` in my testing, docker automatically creates a builder if there is none:
```
$ make docker-load 
docker buildx build \
--load \
-t docker.io/hashicorpboundary/postgres:11-alpine \
-f Dockerfile.11-alpine .
[+] Building 3.6s (11/11) FINISHED                                                                                                                                                                                                                                                                                                                                   
=> [internal] …
```
> Build docker dev images for specified platform

- internal/cmd/commands/connect/ssh.go
The OSS Boundary CLI cannot get the SubtypeFromId for non tcp targets
> cli(ssh): Use type instead of SubtypeFromId

- enos/enos-modules.hcl
- enos/enos-scenario-e2e-vault.hcl
- enos/enos-variables.hcl
- enos/modules/test_e2e/main.tf
- testing/internal/e2e/README.md
- testing/internal/e2e/boundary/boundary.go
- testing/internal/e2e/boundary/scopes.go
- testing/internal/e2e/credential/vault/vault_test.go
- testing/internal/e2e/helpers.go
- testing/internal/e2e/target/target_test.go
- testing/internal/e2e/vault/boundary-controller-policy.hcl
- testing/internal/e2e/vault/vault.go
This PR adds a new enos scenario and two new tests that use Vault as a credential store. 
- The first test uses the boundary and vault clis to set up vault as a credential store, create a set of credentials, attach those credentials to a target, and connect to that target using what was provided by boundary/vault.
- The second test is similar but uses the bounday go api
As a design philosophy, we wanted to minimize the amount of setup done in enos in order to maintain as much flexibility as possible with regards to how the infrastructure gets created.
We opted not to use the vault go api for the following reasons
- the vault cli is more readable than the vault api
- it enables flexibility in using the corresponding vault cli version with the vault server version
- boundary itself has a …
> Add vault test to e2e test suite

- internal/daemon/worker/countingconn.go
- internal/daemon/worker/countingconn_test.go
- internal/daemon/worker/handler.go
- internal/daemon/worker/proxy/proxy.go
- internal/daemon/worker/proxy/proxy_test.go
- internal/daemon/worker/proxy/tcp/tcp.go
- internal/daemon/worker/proxy/tcp/tcp_test.go
This commit introduces a new net.Conn implementation (countingConn) that will keep track of bytes read and written for a particular client connection. This is then implemented into the worker code using interface composition.
> feat(worker): net.Conn implementation to count Bytes Read and Written

- go.mod
- go.sum
- internal/kms/rewrapping.go
The new RegisterTableRewrapFn can be used by a domain to register a callback to use when rewrapping data in a specific table name.
> Add key version rewrapping function registry

- internal/daemon/worker/countingconn.go
- internal/daemon/worker/handler.go
- internal/daemon/worker/session/manager.go
- internal/daemon/worker/session/manager_test.go
- internal/daemon/worker/session/session.go
- internal/daemon/worker/session/session_test.go
- internal/daemon/worker/status.go
Introduces data about bytes read and written to the connection close payload on the Worker's side. No changes are required in the Controller because the RPC messages already contained the required fields. As of this commit, bytes_up and bytes_down columns in the session_connection table are now populated when a connection closes.
> feat(worker): Report bytes up/down on Worker <-> Client connection closure

- enos/enos-modules.hcl
- enos/enos-scenario-e2e-credential-vault.hcl
- enos/enos-scenario-e2e-host-aws.hcl
- enos/enos-scenario-e2e-host-static.hcl
- enos/enos-variables.hcl
- enos/modules/generate_aws_host_tag_vars/main.tf
- enos/modules/iam_setup/main.tf
- enos/modules/random_stringifier/main.tf
- enos/modules/target/main.tf
- enos/modules/test_e2e/main.tf
- go.mod
- testing/internal/e2e/README.md
- testing/internal/e2e/boundary/boundary.go
- testing/internal/e2e/boundary/scopes.go
- testing/internal/e2e/credential/vault/vault_test.go
- testing/internal/e2e/helpers.go
- testing/internal/e2e/host/aws/dynamichostcatalog_test.go
- testing/internal/e2e/host/static/statichost_test.go
- testing/internal/e2e/vault/vault.go
This PR adds some tests that set up an AWS Dynamic Host Catalog (https://developer.hashicorp.com/boundary/tutorials/access-management/aws-host-catalogs). The test performs the following...
- Uses Enos to spin up 2 hosts with one tag and 1 host with another tag
- Creates an AWS Dynamic Host Catalog with two host sets, one for each tag, and confirms that the number of hosts in each host set match what is expected
- Checks that listing all of the hosts in the host catalog match the expected number of hosts
- Creates a target for one of the host sets
- Connects to the target
```
❯ enos scenario run e2e_host_aws builder:local
```
```
❯ go test -v github.com/hashicorp/boundary/testing/internal/e2e/host/aws -count=1
=== RUN   TestCreateAwsDynamicHostCatalogCli
dynamichostcatalog_test.go:93: …
```
> Add AWS Dynamic Host Catalog e2e test

- .github/workflows/enos-run.yml
- enos/enos-scenario-e2e-credential-vault.hcl
- enos/enos-scenario-e2e-host-static.hcl
- enos/modules/test_e2e/main.tf
This PR is related to adding a GitHub Action workflow that executes the Enos End to End scenario.
We have chosen to add on to the existing Enos Run workflow that also runs integration tests. In the process, we have inverted some logic that previously checked the affirmative case of "a" and now checks the negative case of "b". This was necessary to add more than 2 types of filters to the workflow.
Additionally, another deviation from previous implementations is that we will only run the Destroy step if either the Run or its retry step have failed. This is because `enos scenario run` will execute a destroy action if it completes its apply action successfully.
Other than that, the only other change is that we have added a new filter to the existing scenario in order to execute this new …
> Extend enos-run.yml to cover E2E testing

- internal/tests/cli/boundary/_connect.bash
- internal/tests/cli/boundary/_sessions.bash
- internal/tests/cli/boundary/sessions.bats
The `sessions.bats` tests were seeing some flaky tests due to the following reasons...
```
boundary/session: verify read and cancellation permissions on un... 93/149 ✗ boundary/session: verify read and cancellation permissions on unpriv session
(in test file boundary/sessions.bats, line 91)
`id=$(echo "$output" | jq -r "[.items[]|select(.user_id == \"$DEFAULT_UNPRIVILEGED_USER\")][0].id")' failed with status 5
{"status_code":200,"items":null}
jq: error (at <stdin>:1): Cannot iterate over null (null)
```
```
boundary/session: verify admin and unpriv user see different counts 91/149 ✗ boundary/session: verify admin and unpriv user see different counts
(in test file boundary/sessions.bats, line 54)
`[ "$unpriv_sessions" -lt "$admin_sessions" ]' failed
```
After some investigation, it …
> fix(bats): Fix flakiness in sessions.bats tests

- internal/kms/rewrapping.go
This makes it much easier for rewrap functions to look up the correct wrapper and limit the number of rows searched.
> Add scopeId to RewrapFn

- CHANGELOG.md
- internal/daemon/controller/handlers/targets/target_service.go
- internal/daemon/worker/status.go
* Randomize order of worker output. This uses the standard rand.Shuffle() call; cribbed from https://pkg.go.dev/math/rand#example-Shuffle
* Have some error/eventing in the worker status path use the base context instead of the status-call-specific context to allow eventing after a timeout event
> Fix two items:

- internal/proto/controller/storage/servers/store/v1/root_certificate.proto
- internal/server/store/root_certificate.pb.go
- internal/server/workerauth_store_test.go
update root cert proto definition to properly identify public_key as the table primary key
the [pk already exists](https://github.com/hashicorp/boundary/blob/main/internal/db/schema/migrations/oss/postgres/34/03_worker_authentication.up.sql#L53) in sql, just not in the proto file
> Update Root Cert Proto Definition

- internal/auth/oidc/repository_auth_method_update.go
- internal/auth/oidc/rewrapping.go
- internal/auth/oidc/rewrapping_test.go
- internal/auth/password/rewrapping.go
- internal/auth/password/rewrapping_test.go
- internal/authtoken/rewrapping.go
- internal/authtoken/rewrapping_test.go
- internal/credential/static/rewrapping.go
- internal/credential/static/rewrapping_test.go
- internal/credential/vault/rewrapping.go
- internal/credential/vault/rewrapping_test.go
- internal/db/schema/migrations/oss/postgres/0/11_auth_token.up.sql
- internal/db/schema/migrations/oss/postgres/10/04_vault_credential.up.sql
- internal/db/schema/migrations/oss/postgres/23/01_session_credential.up.sql
- internal/db/schema/migrations/oss/postgres/34/03_worker_authentication.up.sql
- internal/db/schema/migrations/oss/postgres/43/01_session_credentials.up.sql
- internal/db/schema/migrations/oss/postgres/56/01_worker_auth_create_time.up.sql
- internal/db/schema/migrations/oss/postgres/56/05_mutable_ciphertext_columns.up.sql
- internal/host/plugin/rewrapping.go
- internal/host/plugin/rewrapping_test.go
- internal/server/query.go
- internal/server/rewrapping.go
- internal/server/rewrapping_test.go
- internal/session/credential.go
- internal/session/query.go
- internal/session/rewrapping.go
- internal/session/rewrapping_test.go
root cert pk change has been moved to [boundary#2542](https://github.com/hashicorp/boundary/pull/2542) <img src="https://emoji.slack-edge.com/TF1GCKJNM/merged-intensifies/8d585e215a72515a.gif" width="24px" title="merged-intensifies"/>
> Rewrap Functions for Encrypted Tables

- internal/tests/cli/boundary/credential_stores.bats
- testing/internal/e2e/boundary/credential.go
- testing/internal/e2e/boundary/host.go
- testing/internal/e2e/boundary/scope.go
- testing/internal/e2e/boundary/target.go
- testing/internal/e2e/helpers.go
- testing/internal/e2e/host/static/connect_authz_token_test.go
- testing/internal/e2e/host/static/connect_ssh_test.go
- testing/internal/e2e/host/static/session_cancel_test.go
- testing/internal/e2e/host/static/static_credential_store_test.go
The `boundary/credential-stores: can not read deleted $NEW_STORE static store` test in `credential_stores.bats` would occasionally fail due to the following error
```
14/149 ✗ boundary/credential-stores: can not
read deleted test static store
(in test file
/home/runner/work/boundary/boundary/internal/tests/cli/boundary/credential_stores.bats,
line 46)
`[ "$status" -eq 1 ]' failed
{"status_code":200,"item":{"id":"csst_cRjGVFTVh2","scope_id":"p_0cG1T4CPcH","scope":{"id":"p_0cG1T4CPcH","type":"project","name":"Generated
project scope","description":"Provides an initial project scope in
Boundary","parent_scope_id":"o_TBZZ3mIHd1"},"name":"test","description":"test
static credential
store","created_time":"2022-10-05T21:26:51.703003Z","updated_time":"2022-10-05T21:26:51.703003Z","version":1,"type …
```
> test(e2e): Fix flaky test in `credential_stores.bats`

- internal/credential/static/query.go
- internal/credential/static/rewrapping.go
- internal/credential/static/rewrapping_test.go
- internal/daemon/controller/rewrapping_test.go
- internal/db/schema/migrations/oss/postgres/48/01_worker_auth_activation_token.up.sql
- internal/db/schema/migrations/oss/postgres/56/05_mutable_ciphertext_columns.up.sql
- internal/kms/kms.go
- internal/server/query.go
- internal/server/rewrapping.go
- internal/server/rewrapping_test.go
- internal/server/worker_auth_server_led_activation_token_test.go
- [added new rewrapping test to check that all encrypted tables have assigned rewrapping functions](https://github.com/hashicorp/boundary/pull/2555/files#diff-deb54d5881ef6b4457f12626325966134e5902bb01da879c15278be1ec0be50b)
- [added ListDataKeyVersionReferencers function to kms](https://github.com/hashicorp/boundary/pull/2555/files#diff-65fa95abdd78accdc6b1f3ac98751fe4700c8abc1ee696b8d6ae7e5403af0831)
- added new rewrapping functions on [`credential_static_json_credential`](https://github.com/hashicorp/boundary/pull/2555/files#diff-231e7485c6e362d7d68a2bd4c5ba36aa93f2b77923cb51c656b1ecbb2d728f01R102) ([test](https://github.com/hashicorp/boundary/pull/2555/files#diff-af94db4dbe7299f4cf0e078eab23a2b9a10abf0007a9d1926589483efc4d2543)) and …
> Rewrapping Registered Tables Test

- testing/internal/e2e/boundary/account.go
- testing/internal/e2e/boundary/boundary.go
- testing/internal/e2e/boundary/credential.go
- testing/internal/e2e/boundary/host.go
- testing/internal/e2e/boundary/scope.go
- testing/internal/e2e/boundary/target.go
- testing/internal/e2e/boundary/user.go
- testing/internal/e2e/credential/vault/vault_test.go
- testing/internal/e2e/helpers.go
- testing/internal/e2e/host/aws/dynamichostcatalog_test.go
- testing/internal/e2e/host/static/connect_authz_token_test.go
- testing/internal/e2e/host/static/connect_ssh_test.go
- testing/internal/e2e/host/static/connect_test.go
- testing/internal/e2e/host/static/session_cancel_admin_test.go
- testing/internal/e2e/host/static/session_cancel_test.go
- testing/internal/e2e/host/static/session_cancel_user_test.go
- testing/internal/e2e/host/static/static_credential_store_test.go
- testing/internal/e2e/vault/vault.go
This PR adds a test to the e2e test suite that does the following
- creates a new user
- attempts to connect to a target without the right permissions
- sets up the right role/grant
- confirms user can start a session
- confirms admin can cancel the session
```
=== RUN   TestSessionCancelUserCli
scope.go:66: Created Org Id: o_E0AQUpH6FZ
scope.go:87: Created Project Id: p_mJNMPco87s
host.go:76: Created Host Catalog: hcst_BQaIYWYpeC
host.go:93: Created Host Set: hsst_7sj5IuZUDm
host.go:112: Created Host: hst_zTPJdCNo2a
target.go:56: Created Target: ttcp_r2dgoUmC8o
account.go:46: Created Account: acctpw_Zs3gAWWbbf
user.go:35: Created User: u_DLTGNKedw3
session_cancel_user_test.go:59: Successfully received an error when connecting to target as a user without permissions …
```
> test(e2e): Add test that creates a user with permissions to start a session

- internal/db/schema/migrations/oss/postgres/12/01_timestamp_sub_funcs.up.sql
- internal/db/schema/migrations/oss/postgres/57/01_fix_comments.up.sql
- internal/db/schema/migrations/oss/postgres/7/01_functions.up.sql
Fixes the comments on functions wt_add_seconds, wt_add_seconds_to_now, wt_sub_seconds, and wt_sub_seconds_from_now which were the tragic victims of a copypasta error.
> docs(db): fix comments on database functions

- internal/db/schema/migrations/oss/postgres/2/04_oidc.up.sql
- internal/db/schema/migrations/oss/postgres/57/01_fix_comments.up.sql
Fixes the comments on the auth_oidc_method and auth_oidc_account tables.
> docs(db): fix comments on oidc database tables

- internal/db/schema/migrations/oss/postgres/30/04_kms_keys.up.sql
- internal/db/schema/migrations/oss/postgres/57/01_fix_comments.up.sql
Fixes the comments on the kms_data_key and kms_data_key_version tables.
> docs(db): fix comments on kms database tables

- internal/db/schema/migrations/oss/postgres/0/01_domain_types.up.sql
- internal/db/schema/migrations/oss/postgres/57/01_fix_comments.up.sql
Fixes the comments on the wt_scope_id, wt_user_id, and wt_role_id domain types.
> docs(db): fix comments on database domain types

- .github/workflows/enos-run.yml
Based around [this Slack convo](https://hashicorp.slack.com/archives/C016MAUKHG8/p1666367835776389), it was determined that the AWS TF provider has various intermittent issues. In order to make a proper bug report, this change alters the Enos Run workflow to output Terraform and TF provider information before executing an Enos run.
In the future, we can use this information when lodging provider bug reports.
> QT-351 - Output Terraform and provider version information in Enos workflows

- internal/auth/oidc/repository_auth_method_update.go
- internal/auth/password/repository_password.go
- internal/credential/static/repository_credential.go
- internal/session/repository_session.go
- internal/tests/api/credentials/credentials_test.go
When updating a secret, it is paramount that the key ID is also updated, as it is the only means we have of ensuring that we only destroy keys once there is no more data associated with the key.
I used three different methods for finding instances of secret updates:
1. Audit all uses of `(db.Writer).Update` manually for updates of secrets.
2. (As a backup) audit all uses of `kms.GetWrapper(ctx, <scopeId>, kms.KeyPurpose)` for all key purposes.
3. (As a backup) search for all instances of `update xxx set` to find any extra SQL literal statements.
The test I've added shows a scenario where we would end up with irrecoverable data without these fixes.
> Ensure all secret updates include key ID

- CHANGELOG.md
- internal/cmd/base/initial_resources.go
- internal/credential/credential.go
- internal/credential/options.go
- internal/credential/options_test.go
- internal/credential/vault/private_library.go
- internal/credential/vault/repository_credentials.go
- internal/daemon/controller/auth/auth.go
- internal/daemon/controller/gateway.go
- internal/daemon/controller/handlers/targets/target_service.go
- internal/daemon/controller/handlers/targets/tcp/target_service_test.go
- internal/daemon/controller/handlers/users/user_service.go
- internal/daemon/controller/interceptor.go
- internal/daemon/controller/interceptor_test.go
- internal/daemon/controller/listeners.go
- internal/iam/repository_scope.go
- internal/perms/grants.go
- internal/util/pointer.go
- internal/util/template/doc.go
- internal/util/template/funcs.go
- internal/util/template/generate.go
- internal/util/template/generate_test.go
- internal/util/template/types.go
- website/content/docs/concepts/security/permissions/permission-grant-formats.mdx
- website/content/docs/oss/installing/no-gen-resources.mdx
Add initial templating support to Vault credential libraries
This adds support for templating various account and user values into Vault dynamic credential library POST bodies and GET/POST paths.
It also unifies how parameters are used in grants, with backwards compatibility.
> Add initial templating support to Vault credential libraries (#2569)

- website/content/docs/what-is-boundary.mdx
in the topic "[What is Boundary](https://developer.hashicorp.com/boundary/docs/what-is-boundary)", the bullet point for _Consistent Workflow for Access_ uses the word "securely" twice:
> Boundary securely connects the user securely to their infrastructure regardless of cloud platform
This PR suggests removing the second instance.
> docs: Remove redundant word

- .github/workflows/enos-run.yml
- enos/enos-scenario-e2e-aws.hcl
- enos/enos-scenario-e2e-static-with-vault.hcl
- enos/enos-scenario-e2e-static.hcl
- testing/internal/e2e/boundary/boundary.go
- testing/internal/e2e/tests/aws/dynamichostcatalog_test.go
- testing/internal/e2e/tests/static/connect_authz_token_test.go
- testing/internal/e2e/tests/static/connect_ssh_test.go
- testing/internal/e2e/tests/static/connect_test.go
- testing/internal/e2e/tests/static/credential_store_test.go
- testing/internal/e2e/tests/static/env_test.go
- testing/internal/e2e/tests/static/session_cancel_admin_test.go
- testing/internal/e2e/tests/static/session_cancel_user_test.go
- testing/internal/e2e/tests/static_with_vault/connect_authz_token_test.go
- testing/internal/e2e/tests/static_with_vault/connect_ssh_test.go
- testing/internal/e2e/tests/static_with_vault/connect_test.go
- testing/internal/e2e/tests/static_with_vault/credential_store_test.go
- testing/internal/e2e/tests/static_with_vault/env_test.go
This PR does the following
- Adds a workflow to `static/credential_store_test.go` to create a username/password credential
- Adds a check in `static/credential_store_test.go` and `static_with_vault/credential_store_test.go` to validate that `authorize-session` does not return any credentials when no credentials are associated with a target
- Adds various `connect` tests in `static_with_vault` to ensure that users can connect to targets using the various options when credentials are stored by vault
- Reorganizes the test directory to better align with enos scenarios and have more clarity for where to add tests
- Fixes a flake in `static/session_cancel_user_test.go` due to a misunderstanding in how goroutines work. Instead, the goroutine will now authenticate via token instead of utilizing …
> test(e2e): Add more checks in credential store tests

- website/content/docs/getting-started/connect-to-target.mdx
- website/content/docs/getting-started/deploy-and-login.mdx
This PR updates the `/docs/getting-started/deploy-and-login` page:
- fixes h1 header issue
- replaces Origin URL with Cluster URL
- removes references to Beta
- removes content duplicated in the dev-portal page sub-heading
- fixes various code snippet styles
This PR updates the `/docs/getting-started/connect-to-target` page:
- Changes the header to an h1
- Adds an additional section header for clarity
> Docs deploy and login updates

- testing/internal/e2e/tests/static/connect_localhost_test.go
This PR adds another test case that starts a `boundary connect` followed by a `ssh localhost -p PORT` to connect to the target. This is another common way that users access targets.
> test(e2e): Add `ssh localhost` test

- testing/internal/e2e/boundary/role.go
- testing/internal/e2e/tests/static/session_cancel_group_test.go
- testing/internal/e2e/tests/static/session_cancel_user_test.go
This PR adds another test to the e2e test suite that is similar to the test added here: https://github.com/hashicorp/boundary/pull/2559. This test does the following...
- creates a new user
- attempts to connect to a target without the right permissions
- create a role/grant
- create a new group and apply 
- add the user to the group
- confirms user can start a session
- confirms admin can cancel the session
This is different than the existing test in that the existing test creates a user and adds the role to the user (as opposed to a group).
> test(e2e): Add test that creates a role for a group

- .github/workflows/enos-run.yml
This PR is a follow-up to https://github.com/hashicorp/boundary/pull/2572 and updates the enos jobs to use the latest version of the Vault CLI (1.12.0)
> chore(e2e): Update to use latest version of Vault CLI

- internal/cmd/commands/server/worker_shutdown_reload_test.go
- internal/tests/helper/testing_helper.go
We have observed several unit tests occasionally fail when trying to read a handshake due to the following error:
```
worker_shutdown_reload_test.go:148: 
Error Trace:	testing_helper.go:138
testing_helper.go:312
worker_shutdown_reload_test.go:148
Error:      	Received unexpected error:
failed to read protobuf message: failed to get reader: received close frame: status = StatusProtocolError and reason = "received header with unexpected rsv bits set: false:false:true"
Test:       	TestServer_ShutdownWorker
--- FAIL: TestServer_ShutdownWorker (1.78s)
```
This also occurs in `TestWorkerSessionProxyMultipleConnections` and `TestSessionCleanup/default/multi_controller`.
After an investigation, it's still unclear how this happens. The `wspb.Write` seemed to work ok, but the `Read` contained some …
> fix(test): Retry websocket connection due to flaky failure

- testing/internal/e2e/tests/aws/dynamichostcatalog_test.go
- testing/internal/e2e/tests/static/connect_localhost_test.go
- testing/internal/e2e/tests/static/credential_store_test.go
- testing/internal/e2e/tests/static/session_cancel_admin_test.go
- testing/internal/e2e/tests/static/session_cancel_group_test.go
- testing/internal/e2e/tests/static/session_cancel_user_test.go
This PR addresses a flaky failure in `TestCliSessionCancel` with the following error
```
=== RUN   TestCliSessionCancelUser
scope.go:70: Created Org Id: o_p1imR5XwmY
scope.go:93: Created Project Id: p_SrsSL68EJx
host.go:79: Created Host Catalog: hcst_jqhgbzwluh
host.go:99: Created Host Set: hsst_yuzvyNaP1J
host.go:121: Created Host: hst_CsIzTKxZL7
target.go:59: Created Target: ttcp_pOKJAR32eC
account.go:75: Created Account: acctpw_2IjDCeDgs6
user.go:56: Created User: u_MjKYLz572K
session_cancel_user_test.go:66: Successfully received an error when connecting to target as a user without permissions
role.go:30: Created Role: r_QTTDFPI1ru
session_cancel_user_test.go:79: Starting session as user...
session_cancel_user_test.go:122: Found 1 session(s)
session_cancel_user_test.go:138: 
Error …
```
> fix(e2e): Add retry when checking if session is active

- testing/internal/e2e/boundary/session.go
- testing/internal/e2e/boundary/user.go
- testing/internal/e2e/tests/static/connect_localhost_test.go
- testing/internal/e2e/tests/static/credential_store_test.go
- testing/internal/e2e/tests/static/session_cancel_admin_test.go
- testing/internal/e2e/tests/static/session_cancel_group_test.go
- testing/internal/e2e/tests/static/session_cancel_user_test.go
- testing/internal/e2e/tests/static/session_end_delete_user_test.go
This PR adds a test to the e2e test suite that does the following...
- Start a session as a user
- Delete the user with the active session
- Check that the session is automatically ended
```
=== RUN   TestCliSessionEndWhenUserIsDeleted
scope.go:68: Created Org Id: o_OIEuW2gkIL
scope.go:91: Created Project Id: p_WpjOpdXQnl
host.go:79: Created Host Catalog: hcst_KmKLcK9vMS
host.go:99: Created Host Set: hsst_wtKRjm46h9
host.go:121: Created Host: hst_wfdSLWIPnk
target.go:59: Created Target: ttcp_N4kcy0sIWP
account.go:73: Created Account: acctpw_oGa6iPHkQs
user.go:54: Created User: u_2U5qCF8o5Y
role.go:30: Created Role: r_b9G0wRWFtc
session.go:18: Waiting for session to be active...
session.go:71: No items are appearing in the session list. Retrying...
session_end_delete_user_test.go:47: …
```
> test(e2e): Check that an active session ends if the user is deleted

- internal/cmd/commands/hostsetscmd/plugin_funcs.go
Create expects a host catalog id, not a plugin id
> fix host sets command sample command

- internal/daemon/cluster/handlers/worker_service.go
- internal/daemon/cluster/handlers/worker_service_test.go
- internal/daemon/controller/controller.go
- internal/daemon/controller/handlers/sessions/session_service.go
- internal/daemon/controller/handlers/targets/target_service.go
- internal/db/schema/migrations/oss/postgres/44/04_sessions.up.sql
- internal/db/schema/migrations/oss/postgres/56/06_add_session_private_key_column.up.sql
- internal/db/schema/migrations/oss/postgres_40_01_test.go
- internal/db/schema/migrations/oss/postgres_56_02_test.go
- internal/db/testing.go
- internal/session/options.go
- internal/session/options_test.go
- internal/session/query.go
- internal/session/repository.go
- internal/session/repository_session.go
- internal/session/repository_session_test.go
- internal/session/repository_test.go
- internal/session/rewrapping.go
- internal/session/rewrapping_test.go
- internal/session/session.go
- internal/session/session_test.go
- internal/session/testing.go
- internal/session/testing_test.go
Previously, we would derive a session certificate private key from the session key used in each project, and not store the key. We would also encrypt the tofu token with the database key but not store a reference to this key in the database.
This change fixes this by replacing our key derivation with a key generation step, and instead store the generated key, encrypted, in the database. We also ensure that any new tofu tokens are encrypted with the same key.
To handle existing sessions, we lazily rewrite the sessions whenever a user lists them. There is a minor risk that a user could end up destroying the database key that encrypts the tofu token before that session has been rewrapped, but this is going to be rare and temporary.
> Store cert private key, encrypt tofu token

- internal/db/read_writer.go
If callers want errors to create events, they can do so by wrapping the error. Sometimes we don't want db
errors to be events, and before this there was no way to suppress them.
> Silence events from DB errors

- website/content/docs/concepts/filtering/events.mdx
- website/content/docs/concepts/filtering/oidc-managed-groups.mdx
- website/content/docs/concepts/filtering/resource-listing.mdx
- website/content/docs/concepts/filtering/worker-tags.mdx
Per a Slack conversation:
https://hashicorp.slack.com/archives/C8DK5PR0B/p1668182567733029
Some of the pages in the Boundary docs have content above the H1 heading. Per Kyle McDonald, this is causing the version pull-down to overlap content and there is an upcoming rule that will warn that all pages must begin with an H1. 
This PR moves the H1 heading above any other content. The following pages in the Filtering section all have this issue:
- [OIDC managed groups](https://developer.hashicorp.com/boundary/docs/concepts/filtering/oidc-managed-groups)
- [Resource Listing](https://developer.hashicorp.com/boundary/docs/concepts/filtering/resource-listing)
- [Worker Tags](https://developer.hashicorp.com/boundary/docs/concepts/filtering/worker-tags)
- …
> Fix pull-down placement

- website/content/docs/getting-started/installing/production.mdx
Per the following Slack conversation, the Boundary Network Requirements are incorrect:
https://hashicorp.slack.com/archives/C016ZKNM05T/p1668000335382949
This pull request:
- Removes redundant entries for ports 9200 and 9201
- The Slack conversation mentioned that the client -> controller info re. port 9200 is repeated, but I think this is redundant as well: `:9201 must be open between Worker and Controller`. Please correct me if I am wrong.
- Adds the Client to Worker traffic with a required port of 9202
- Fixes the direction of the traffic flow from Worker -> Controller
Asana task: https://app.asana.com/0/563192436488770/1203340202571850/f
> Update Boundary network requirements

- internal/db/schema/migrations/oss/postgres/44/04_sessions.up.sql
- internal/db/schema/migrations/oss/postgres/56/02_add_data_key_foreign_key_references.up.sql
- internal/session/options.go
- internal/session/repository.go
- internal/session/repository_session.go
- internal/session/repository_session_test.go
- internal/session/repository_test.go
- internal/session/rewrapping.go
- internal/session/rewrapping_test.go
Unsetting the key ID allows the session to live beyond the lifetime of the scope, while allowing the scope to cascade delete its keys.
We also stop decrypting session fields if the session is missing a project or user, since decryption cannot always succeed in these cases.
Note that removing the relationship to the key means that the encrypted data in the (now canceled) session may become unrecoverable. This is an acceptable consequence of this change.
> Unset session key ID when deleting the scope, ignore decryption when session has no project or user

- internal/ui/VERSION
Bumps the UI version to the latest commit in [boundary-ui](https://github.com/hashicorp/boundary-ui).
> bump up ui commit

- CHANGELOG.md
- internal/daemon/worker/worker.go
- internal/daemon/worker/worker_test.go
Previously, it was possible for an empty private key to be used when the session had no user or project associated with it. The new checks guarantee that we will fail gracefully in these cases.
> fix(worker): Verify contents of loaded session

- internal/db/schema/migrations/oss/postgres/56/02_add_data_key_foreign_key_references.up.sql
The session cancelation trigger would not set the key_id to null appropriately if another one of the fields on the session was already null, since that case statement would be matched first. The new structure matches all statements, in case any of them have special logic (such as in the project case).
> fix(session): Always invoke all parts of session cancel trigger

- CHANGELOG.md
I fixed some typos in #2636, but forgot to backport them to the 0.11.x branch. This PR does that.
> Backport changelog typo fixes to 0.11.x

- CHANGELOG.md
- globals/kms.go
- go.mod
- go.sum
- internal/cmd/base/server_test.go
- internal/cmd/base/servers.go
- internal/cmd/commands/server/listener_reload_test.go
- website/content/docs/concepts/security/data-encryption.mdx
- website/content/docs/configuration/kms/aead.mdx
- website/content/docs/configuration/kms/alicloudkms.mdx
- website/content/docs/configuration/kms/awskms.mdx
- website/content/docs/configuration/kms/azurekeyvault.mdx
- website/content/docs/configuration/kms/gcpckms.mdx
- website/content/docs/configuration/kms/index.mdx
- website/content/docs/configuration/kms/ocikms.mdx
- website/content/docs/configuration/kms/transit.mdx
The new purpose combined with the `root` purpose lets a user migrate from one root key to another. This also adds errors for existing duplicate purposes.
I have tested this change manually with `boundary-local-env`.
> Create new "previous-root" key purpose for root key migrations

- go.mod
- go.sum
Automatic ENT merging fails in part due to a difference in the go.mod files for github.com/cenkalti/backoff/v4 
ENT version: https://github.com/hashicorp/boundary-enterprise/blob/main/go.mod#L94
> update backoff to match ENT

- CHANGELOG.md
git merged [boundary#2587](https://github.com/hashicorp/boundary/pull/2587) changelog under `0.11.1` incorrectly, this moves it under the `Next` section
> move custom response headers to next in changelog

- CHANGELOG.md
- internal/daemon/controller/internal/metric/cluster.go
- internal/daemon/controller/listeners.go
- internal/daemon/metric/initialize_metrics.go
- internal/daemon/metric/instrument_handlers.go
- internal/daemon/metric/instrument_handlers_test.go
- internal/daemon/worker/internal/metric/cluster_client.go
- internal/daemon/worker/internal/metric/cluster_server.go
- internal/daemon/worker/internal/metric/proxy_http.go
- internal/daemon/worker/listeners.go
> feat(metric): adds accepted/closed connections counters to worker and controller servers

- internal/cmd/commands/connect/ssh.go
Targets are not guaranteed to have Host Ids anymore, so we now use Target Id when a Host Id is not present.
> fix(cmd): boundary connect SSH depending on a host id for ssh aliasing

- sdk/plugins/host/plugin.go
After this is merged I will have to point the aws/azure mains to a commit with this (I am assuming we save tags for `main`). I've verified via boundary-local-env that when referencing this sdk code it successfully ignores HUPs.
> Add SIGHUP ignoring to sdk/plugin

- enos/modules/test_e2e/main.tf
- testing/internal/e2e/README.md
- testing/internal/e2e/boundary/account.go
- testing/internal/e2e/boundary/credential.go
- testing/internal/e2e/boundary/host.go
- testing/internal/e2e/boundary/scope.go
- testing/internal/e2e/boundary/target.go
- testing/internal/e2e/boundary/user.go
- testing/internal/e2e/helpers.go
- testing/internal/e2e/tests/aws/dynamichostcatalog_test.go
- testing/internal/e2e/tests/static/connect_authz_token_test.go
- testing/internal/e2e/tests/static/connect_localhost_test.go
- testing/internal/e2e/tests/static/connect_ssh_test.go
- testing/internal/e2e/tests/static/connect_test.go
- testing/internal/e2e/tests/static/credential_store_test.go
- testing/internal/e2e/tests/static/session_cancel_admin_test.go
- testing/internal/e2e/tests/static/session_cancel_group_test.go
- testing/internal/e2e/tests/static/session_cancel_user_test.go
- testing/internal/e2e/tests/static/session_end_delete_user_test.go
- testing/internal/e2e/tests/static_with_vault/connect_authz_token_test.go
- testing/internal/e2e/tests/static_with_vault/connect_ssh_test.go
- testing/internal/e2e/tests/static_with_vault/connect_test.go
- testing/internal/e2e/tests/static_with_vault/credential_store_test.go
- testing/internal/e2e/vault/vault.go
This is the 1st of 2 PRs to support the new automated migration test (A draft PR containing all of the changes can be found here: https://github.com/hashicorp/boundary/pull/2627). The migration test intends to do the following
- Set up a boundary database using the latest released version of Boundary
- Populate the boundary database with a number of resources (org, project, host catalog, host set, target, static credentials, an AWS dynamic host catalog, and some vault credentials)
- Use the newest version of Boundary to migrate the database (i.e. `boundary database migrate`)
This PR does some refactoring to make creating the migration test easier. These changes were split off to simplify the review process. The changes include the following
- Cleanup calls were moved out of methods and …
> refact(e2e): Changes to support an automated migration test

- testing/internal/e2e/tests/static/session_end_delete_host_set_test.go
- testing/internal/e2e/tests/static/session_end_delete_host_test.go
- testing/internal/e2e/tests/static/session_end_delete_user_test.go
This PR adds two more e2e tests to validate that an active session ends when the corresponding host set or host is deleted. The idea for this came about during the key destruction work. There will be future PRs to add additional tests for deleting other resource types.
> test(e2e): Add tests to validate that session ends after host source is deleted

- website/content/docs/concepts/security/data-encryption.mdx
The "root" identifier is how we identify the root key in configuration, so it is the phrase we should use in this documentation.
This naming is already in place on the release branch (0.11.x).
> fix(docs): Use "root" to reference the root key

- internal/daemon/metric/initialize_metrics.go
- internal/daemon/metric/initialize_metrics_test.go
- internal/daemon/worker/internal/metric/cluster_client.go
* adds exclude and include filters to initialize grpc metric function
* ensures that the same metrics belong to the same subsystems after proto file revert in commit 0f89b1
> refactor(metric): adds exclude and include maps to metric init function 

- .github/workflows/enos-ci-bootstrap-oss.yml
The `bootstrap-ci-oss` workflow should only have been running in the `boundary` repo. This PR adds a condition to the workflow to ensure that is the case.
> [QT-396] Ensure oss enos ci bootstrap workflow only runs in the oss repo

- internal/cmd/commands/credentialscmd/json_credentials.gen.go
- internal/cmd/commands/hostcatalogscmd/plugin_hostcatalogs.gen.go
- internal/cmd/commands/hostsetscmd/plugin_hostsets.gen.go
- internal/cmd/common/flags.go
- internal/cmd/common/flags_test.go
- internal/cmd/gencli/templates.go
This removes a bunch of copypasta. Diffs below:
```diff
--- hostcatalogs-before 2022-12-15 10:29:16.391945146 -0500
+++ hostcatalogs-after  2022-12-15 10:54:28.405221449 -0500
@@ -103,11 +103,11 @@
Attribute Options:
-attr
-      A key=value attribute to add to the request's attributes map. The type
-      is automatically inferred. Use -string-attr, -bool-attr, or -num-attr
+      A key=value pair to add to the request's attributes map. The type is
+      automatically inferred. Use -string-attr, -bool-attr, or -num-attr
if the type needs to be overridden. Can be specified multiple times.
Supports sourcing values from files via "file://" and env vars via
-      "env://"
+      "env://".
-attributes=<string>
A JSON map value to use as the entirety of the request's attributes
@@ -115,38 …
```
> Merge duplicated attr/secret/kv flag handling into one function

- .github/workflows/enos-run.yml
- enos/modules/test_e2e/main.tf
This PR adds the tparse tool to include a table summary of test results at the end. This is the same tool used by unit tests.
Here's an example log: https://github.com/hashicorp/boundary/actions/runs/3699246273/jobs/6266548822
The standard format didn't look nice...
... so this PR is currently opting to use the plain format
> chore(e2e): Add tparse to summarize test output

- internal/kms/kms_test.go
We observed a flake in `Test_RotateKeys` due to the following reason
```
--- FAIL: Test_RotateKeys/success (0.02s)
kms_test.go:225: 
Error Trace:	/home/circleci/boundary/internal/kms/kms_test.go:225
Error:      	Not equal: 
expected: 21
actual  : 14
Test:       	Test_RotateKeys/success
```
The theory is that there may be some other tests impacting the number of keys, so this PR prevents this test from running in parallel.
> fix(kms/test): Fix flake in Test_RotateKeys

- internal/session/repository_session.go
- internal/session/repository_session_test.go
- internal/session/session.go
- internal/session/session_host_set_host.go
- internal/session/session_target_address.go
- internal/session/session_test.go
- internal/session/testing.go
Summary:
A host_id and host_set_id are no longer required arguments when authorizing a session. The session endpoint is now derived from either a host or a direct network address association to a Target resource. If a network address association is deleted from a Target, then all sessions using the same Target will be canceled. The behavior of canceling a session when a resource is deleted follows the existing pattern for host and host set. A session will not be canceled if the network address value is changed.
> feat: update session domain to support using address directly associated to a target

- .github/workflows/enos-run.yml
- enos/enos-scenario-e2e-database.hcl
- enos/enos-scenario-e2e-static-with-vault.hcl
- enos/enos-variables.hcl
This PR updates the e2e test suite to use the latest version of Vault (version 1.12.2).
> chore(e2e): Update to use Vault 1.12.2

- website/data/docs-nav-data.json
This PR adds a link to the HCP Boundary docs on the Boundary general documentation page.
[View the preview here.](https://boundary-l5siv8hl6-hashicorp.vercel.app/boundary/docs)
> docs: Add HCP link to navigation

- testing/internal/e2e/boundary/boundary.go
- testing/internal/e2e/tests/aws/dynamichostcatalog_host_set_empty_test.go
- testing/internal/e2e/tests/aws/dynamichostcatalog_host_set_test.go
- testing/internal/e2e/tests/aws/dynamichostcatalog_test.go
- testing/internal/e2e/tests/aws/env_test.go
- testing/internal/e2e/tests/database/migration_test.go
- testing/internal/e2e/tests/static/connect_authz_token_test.go
- testing/internal/e2e/tests/static/connect_ssh_test.go
- testing/internal/e2e/tests/static/credential_store_test.go
- testing/internal/e2e/tests/static_with_vault/connect_authz_token_test.go
- testing/internal/e2e/tests/static_with_vault/connect_ssh_test.go
- testing/internal/e2e/tests/static_with_vault/connect_test.go
- testing/internal/e2e/tests/static_with_vault/credential_store_test.go
- testing/internal/e2e/vault/vault.go
This PR adds a test to the Dynamic Host Catalog scenario that verifies the following
- Create an AWS Dynamic Host Catalog
- Create a host set with an invalid tag
- Verify that no hosts appear in the host set
- Attach the empty host set to a target
- Confirm that connecting to the target fails
This PR also contains some fixes where type assertions should have been used.
> test(e2e): Add test for when an incorrect tag is used in a dynamic host catalog

- internal/server/repository_workerauth.go
Initial worker dials were emitting an error when a record was not found, which was not intended.
> Do not emit error on auth not found

- testing/internal/e2e/boundary/authenticate.go
- testing/internal/e2e/boundary/boundary.go
- testing/internal/e2e/boundary/env.go
- testing/internal/e2e/boundary/session.go
- testing/internal/e2e/tests/aws/dynamichostcatalog_host_set_empty_test.go
- testing/internal/e2e/tests/static/bytes_up_down_empty_test.go
- testing/internal/e2e/tests/static/bytes_up_down_test.go
- testing/internal/e2e/tests/static/connect_localhost_test.go
- testing/internal/e2e/tests/static/session_cancel_admin_test.go
- testing/internal/e2e/tests/static/session_cancel_group_test.go
- testing/internal/e2e/tests/static/session_cancel_user_test.go
- testing/internal/e2e/tests/static/session_end_delete_host_set_test.go
- testing/internal/e2e/tests/static/session_end_delete_host_test.go
- testing/internal/e2e/tests/static/session_end_delete_target_test.go
- testing/internal/e2e/tests/static/session_end_delete_user_test.go
- testing/internal/e2e/vault/env.go
- testing/internal/e2e/vault/vault.go
This PR adds some tests around bytes up/down. There are two tests here.
- The first test starts a session and runs a series of commands on the host to send data across the connection. The test verifies that the bytes_down value is increasing as commands are run
- The second test starts and immediately ends a session. The test verifies that the bytes_up and bytes_down values don't change
Additionally, this PR updates a few things
- Refactors some common methods to be more consistent (i.e. moving environment variables to an env.go file)
- Fixes arguments in require.Equal statements to be in the right order
```
❯ go test -v github.com/hashicorp/boundary/testing/internal/e2e/tests/static -count=1 -run TestCliBytesUpDown
=== RUN   TestCliBytesUpDownEmpty
scope.go:57: Created Org Id: …
```
> test(e2e): Add tests for bytes_up/bytes_down

- internal/cmd/base/dev.go
- internal/cmd/base/initial_resources.go
- internal/cmd/base/servers.go
- internal/cmd/commands/database/init.go
- internal/cmd/commands/dev/dev.go
- internal/cmd/commands/server/listener_reload_test.go
- internal/cmd/commands/server/server_test.go
- internal/cmd/commands/server/worker_shutdown_reload_test.go
- internal/daemon/controller/testing.go
Creates a target using an address for boundary dev and when first init-ing boundary (boundary database init).
It also makes this newly created target the default one (ttcp_1234567890). The target using host sources is now a secondary target (ttcp_0987654321).
> feat(cmd): Create target using address on boundary dev / database init

- testing/internal/e2e/boundary/target.go
- testing/internal/e2e/tests/static/target_address_test.go
The following changes adds a new end2end test in enos that validates the latest feature for assigning a network address directly to a Target resource. The test validates the following logic:
- connecting to a target with a host source
- expected error when trying to assign a network address to a Target that has a host source
- assigning a network address to a Target after clearing all host source associations
- connecting to a target with a direct network address association
- expected error when trying to set & add a host source to a Target with a network address assigned to it
- remove the network address from a Target and reassigned a host source to it
> add end2end enos test for target address

- website/content/docs/overview/use-cases.mdx
Via feedback on Slack, the Use Cases topic contains a typo in the Zero Trust section:
> Traditional access solutions do not employ **the** the Zero-Trust philosophy.
This PR deletes the extra word.
> docs: Fix typo in Use Cases topic

- internal/cmd/base/flags.go
- internal/cmd/common/flags.go
- internal/cmd/common/flags_test.go
In #2721, the ability for key-only values was added via using a wrapperspb.StringValue that could be null. This introduced a bug because originally the default case for `-attr` was to get the string value but instead it used the incoming value as-is to allow for nulls; the null check was moved up later but the original behavior was not restored. As a result, non-explicitly-quoted strings carried through the wrapperspb.StringValue, resulting in a map for the value in JSON instead of a string.
This also fixes explicitly quoted string handling.
> Fix string regression in attribute parsing

- internal/daemon/controller/auth/auth.go
- internal/daemon/controller/handlers/accounts/account_service.go
- internal/daemon/controller/handlers/authmethods/authmethod_service.go
- internal/daemon/controller/handlers/authtokens/authtoken_service.go
- internal/daemon/controller/handlers/credentiallibraries/credentiallibrary_service.go
- internal/daemon/controller/handlers/credentials/credential_service.go
- internal/daemon/controller/handlers/credentialstores/credentialstore_service.go
- internal/daemon/controller/handlers/groups/group_service.go
- internal/daemon/controller/handlers/host_catalogs/host_catalog_service.go
- internal/daemon/controller/handlers/host_sets/host_set_service.go
- internal/daemon/controller/handlers/hosts/host_service.go
- internal/daemon/controller/handlers/managed_groups/managed_group_service.go
- internal/daemon/controller/handlers/option_test.go
- internal/daemon/controller/handlers/options.go
- internal/daemon/controller/handlers/roles/role_service.go
- internal/daemon/controller/handlers/scopes/scope_service.go
- internal/daemon/controller/handlers/scopes/scope_service_test.go
- internal/daemon/controller/handlers/sessions/session_service.go
- internal/daemon/controller/handlers/targets/target_service.go
- internal/daemon/controller/handlers/users/user_service.go
- internal/daemon/controller/handlers/workers/worker_service.go
- internal/perms/acl.go
- internal/perms/acl_test.go
- internal/perms/grants.go
- internal/perms/grants_test.go
- internal/perms/output_fields.go
- internal/perms/output_fields_test.go
- internal/perms/testdata/fuzz/FuzzParse/1686a11fab3efeb7d05bf50eb5c61865801c150feb07639363c7123ce92d5d83
- internal/perms/testdata/fuzz/FuzzParse/3c6b045265fd967a6add10031a98efb46f623f95a9b8d3038982bd4cd36298b1
- internal/requests/requests.go
Adds fuzz tests for the grant parser. Running this I found two issues:
* We were not consistently handling invalid unicode. I fixed this by always replacing invalid unicode in inputs with the unicode replacement handler. This is what marshaling to JSON already does.
* We were not handling empty output fields consistently. `output_fields=,` was allowed while `output_fields=` was not. Now the latter is allowed and the former is equal to the latter.
> Add grant parsing fuzz test

- internal/credential/vault/credential.go
- internal/credential/vault/credential_test.go
- internal/credential/vault/private_library.go
- internal/credential/vault/private_library_test.go
- internal/credential/vault/repository_credentials.go
- internal/credential/vault/repository_credentials_test.go
- internal/credential/vault/testing.go
- refactor vault.(issueCredentialLibrary).retrieveCredential to no longer use session id
- remove `dynamicCred`'s `insertQuery` and `updateSessionQuery` functions
- update `TestRepository_IssueCredentials` to perform db lookup for issued credentials
- rename `issueCredentialLibrary` to `genericIssuingCredentialLibrary`
- create new `privateCredentialLibraryAllTypes` struct to handle db operations and decryption
- add `issuingCredentialLibrary` interface to handle credential retrieval in a generic way in preparation for new credential types
> Create issuingCredentialLibrary Interface

- website/content/docs/overview/what-is-boundary.mdx
Fixes a link in `website/content/docs/overview/what-is-boundary.mdx` that had its closing parenthesis (`)`) broken onto a separate line.
Just a quick manual review of the change is needed. 😊
> [docs] Fixing link syntax

- CHANGELOG.md
- internal/db/schema/migrations/oss/postgres/16/03_wh_credential_dimension.up.sql
- internal/db/schema/migrations/oss/postgres/61/01_fix_wh_upsert_credential_group.up.sql
- internal/db/sqltest/tests/wh/credential_dimension/three_credentials_one_change.sql
The wh_upsert_credential_group function was incorrectly attempting to
update the session connection fact table. There are a couple problems
with this:
1. At the time that this runs, there would be no session connection facts
for this session.
2. This function is meant to update the session fact table, there is a
separate function that associates the credential group with the
session connection facts.
This also fixes another bug that was causing expired rows of the
credential dimension to be included in the group membership. And finally
it fixes a typo in the function name.
> fix(wh): Associate session fact with credential dimensions

- website/content/docs/release-notes/v0_10_0.mdx
- website/content/docs/release-notes/v0_11_0.mdx
- website/content/docs/release-notes/v0_1_0.mdx
- website/content/docs/release-notes/v0_2_0.mdx
- website/content/docs/release-notes/v0_3_0.mdx
- website/content/docs/release-notes/v0_4_0.mdx
- website/content/docs/release-notes/v0_5_0.mdx
- website/content/docs/release-notes/v0_6_0.mdx
- website/content/docs/release-notes/v0_7_0.mdx
- website/content/docs/release-notes/v0_8_0.mdx
- website/content/docs/release-notes/v0_9_0.mdx
This PR removes the links from the H1 headings in the release notes.  From the web team:
> docs: Remove links from release note headings - 0.11

- CHANGELOG.md
- internal/daemon/worker/handler.go
- internal/daemon/worker/session/session.go
- internal/session/repository_session.go
Fixes for two race conditions when authorizing sessions.
1. Two calls could reach ActivateSession and execute activateStateCte. The first would succeed and the second would fail with a duplicate key value error
2. Two calls could hit handleProxy; one activates and update the session state to Active; the second would come in before the first call updated the tofu token, resulting in the err `no tofu token but not in correct session state`
Fixes #2741
> bug(sessions): Fix authorizeSession race conditions in handleProxy

- META.d/_summary.yaml
Used by the CORE SRE team Heimdall product to give quick overview of all the HashiCorp repositories.
Initially this just adds some very basic information about this repository. Could be expanded if we
expand the use of Heimdall.
The schema for these files are defined here: https://github.com/hashicorp/cloud-catalog/blob/main/docs/SCHEMA.md
> Add Heimdall summary

- website/content/docs/oss/installing/reference-architectures.mdx
The Reference Architecture topic was missing front matter. This PR adds the front matter to improve search relevancy and SEO.
> docs: Add frontmatter to ref architecture topic

- website/content/docs/release-notes/v0_10_0.mdx
- website/content/docs/release-notes/v0_1_0.mdx
- website/content/docs/release-notes/v0_2_0.mdx
- website/content/docs/release-notes/v0_3_0.mdx
- website/content/docs/release-notes/v0_4_0.mdx
- website/content/docs/release-notes/v0_5_0.mdx
- website/content/docs/release-notes/v0_6_0.mdx
- website/content/docs/release-notes/v0_7_0.mdx
- website/content/docs/release-notes/v0_8_0.mdx
- website/content/docs/release-notes/v0_9_0.mdx
This PR removes the links from the H1 headings in the release notes in branch `0.10.x`. From the web team:
> docs: Remove links from headings -v0.10

- website/content/docs/release-notes/v0_1_0.mdx
- website/content/docs/release-notes/v0_2_0.mdx
- website/content/docs/release-notes/v0_3_0.mdx
- website/content/docs/release-notes/v0_4_0.mdx
- website/content/docs/release-notes/v0_5_0.mdx
- website/content/docs/release-notes/v0_6_0.mdx
- website/content/docs/release-notes/v0_7_0.mdx
- website/content/docs/release-notes/v0_8_0.mdx
This PR removes the links from the H1 headings in the release notes in branch `0.8.x`. From the web team:
> docs: Remove links from headings -v0.8

- website/content/docs/releases/release-notes/v0_1_0.mdx
- website/content/docs/releases/release-notes/v0_2_0.mdx
- website/content/docs/releases/release-notes/v0_3_0.mdx
- website/content/docs/releases/release-notes/v0_4_0.mdx
- website/content/docs/releases/release-notes/v0_5_0.mdx
- website/content/docs/releases/release-notes/v0_6_0.mdx
This PR removes the links from the H1 headings in the release notes in branch `0.7.x`. From the web team:
> docs: Remove links from headings -v0.7

- website/content/docs/releases/release-notes/v0_1_0.mdx
- website/content/docs/releases/release-notes/v0_2_0.mdx
- website/content/docs/releases/release-notes/v0_3_0.mdx
- website/content/docs/releases/release-notes/v0_4_0.mdx
- website/content/docs/releases/release-notes/v0_5_0.mdx
- website/content/docs/releases/release-notes/v0_6_0.mdx
This PR removes the links from the H1 headings in the release notes in branch `0.6.x`. From the web team:
> docs: Remove links from headings -v0.6

- website/content/docs/releases/release-notes/v0_1_0.mdx
- website/content/docs/releases/release-notes/v0_2_0.mdx
- website/content/docs/releases/release-notes/v0_3_0.mdx
- website/content/docs/releases/release-notes/v0_4_0.mdx
This PR removes the links from the H1 headings in the release notes in branch `5.x`. From the web team:
> We're trying to remove instances of links in heading elements, as it can cause difficulties for users who rely on screen readers and voice-based assistive tech, and it can lead to issues when we automatically generation anchor links
> docs: Remove links from headings -v0.5

- .github/workflows/enos-run.yml
- enos/enos-scenario-integration.hcl
- enos/enos-variables.hcl
- enos/modules/test_cli_ui/tests.tf
This PR updates some enos files to remove the `skip_failing_bats_tests` variable. This is additional cleanup from https://github.com/hashicorp/boundary/pull/2468, which removed `SKIP_FAILING_TESTS_IN_CI` from the bats tests.
> chore(enos): Remove unused skip_failing_bats_tests variable

- CHANGELOG.md
- globals/errors.go
- globals/fields.go
- internal/cmd/commands/server/server.go
- internal/cmd/config/config.go
- internal/daemon/controller/handlers/credentialstores/credentialstore_service.go
- internal/daemon/controller/handlers/credentialstores/credentialstore_service_test.go
- internal/daemon/controller/handlers/hosts/host_service.go
- internal/daemon/controller/handlers/hosts/host_service_test.go
- internal/daemon/controller/handlers/targets/target_service.go
- internal/daemon/controller/handlers/targets/tcp/target_service_test.go
- internal/daemon/controller/handlers/workers/worker_service.go
- internal/daemon/worker/controller_connection.go
This fixes two issues that compounded on each other (see the Changelog update for more information):
* The verification logic for hosts was not correct for update operations (in multiple ways) which meant that a host could be updated after creation to have a port. Targets had a previously fixed bug where they did not require a default port, which meant that ports could be used from hosts
* A recent (unreleased) change had prioritized any port coming from the host over the default port, which would mean there was no way if a host had a port specified to use it in multiple targets.
This fixes the update verification logic, and strikes a middle ground between breaking things and not by allowing existing addresses with ports to be used with targets but ignoring that port, instead requiring …
> Fix target port handling

- go.mod
- go.sum
- internal/credential/credential.go
- internal/credential/vault/options.go
- internal/credential/vault/private_library.go
- internal/credential/vault/private_library_test.go
- internal/credential/vault/supported.go
- internal/credential/vault/testing.go
- internal/db/schema/migrations/oss/postgres/56/02_add_data_key_foreign_key_references.up.sql
- internal/db/schema/migrations/oss/postgres/62/02_add_ssh_cert_to_vault_cred_library_view.up.sql
- internal/session/repository_connection.go
- create new `sshCertIssuingCredentialLibrary ` type
- implement `retrieveCredential` function
- interface with vault for ssh sign/issue endpoints
- generate keys locally (for sign)
- modify vault credential library view for new type
- modify `issuingCredentialLibrary` interface and `genericIssuingCredentialLibrary` type and surrounding functions to use interface
> Support Issuing SSH Cert Credentials

- go.mod
- testing/internal/e2e/boundary/account.go
- testing/internal/e2e/boundary/authenticate.go
- testing/internal/e2e/boundary/boundary.go
- testing/internal/e2e/boundary/env.go
- testing/internal/e2e/helpers.go
- testing/internal/e2e/tests/static/authenticate_primary_test.go
Note: This was an experiment to see what was possible. The usefulness of this test is still up for debate.
In https://github.com/hashicorp/boundary/pull/2725, there is a new "short-hand" version of the `authenticate` command that allows users to more quickly log in to boundary. Now, users can just invoke `boundary authenticate`, and boundary will use the user's primary auth method to log in. This PR adds an e2e test to validate this behavior.
Originally, the test tried to use `exec.Cmd.Stdin` to provide the login credentials when `boundary authenticate` prompts for a username and password, but that didn't seem to work. @johanbrandhorst pointed me to try using the `creack/pty` package.
**Test Result**
```
❯ go test github.com/hashicorp/boundary/testing/internal/e2e/tests/static -v -run …
```
> test(e2e): Add test for updated `boundary authenticate` command

- internal/daemon/controller/handlers/targets/target_service.go
This allows the new vault ssh certificate credential library to be used
as an injected application credential source.
> feat(target): Allow vault ssh cert library as credential source

- .github/workflows/enos-run.yml
- enos/modules/test_e2e/main.tf
This PR updates the e2e test suite to upload its `go test` log as a GitHub action artifact. This helps ensure that tests ran successfully (enos does not print out the `go test` output on a success). It also serves to more easily grab all of the output when tests fail. 
The zip file contains a text file for each enos scenario
```
❯ ls -al
total 72
drwx------@  6 mycow  staff    192 Jan 31 11:12 .
drwx------@ 34 mycow  staff   1088 Jan 31 11:53 ..
-rw-rw-r--@  1 mycow  staff   2901 Jan 31  2023 test-e2e-aws.out
-rw-rw-r--@  1 mycow  staff   8041 Jan 31  2023 test-e2e-database.out
-rw-rw-r--@  1 mycow  staff  15858 Jan 31  2023 test-e2e-static.out
-rw-rw-r--@  1 mycow  staff   4522 Jan 31  2023 test-e2e-static_with_vault.out
```
```
❯ more test-e2e-static.out
=== RUN …
```
> chore(enos): Upload e2e test output

- internal/daemon/controller/controller.go
- internal/db/schema/migrations/oss/postgres/62/01_job_run_index.up.sql
- internal/scheduler/cleaner/cleaner.go
- internal/scheduler/cleaner/cleaner_job.go
- internal/scheduler/cleaner/cleaner_test.go
HCP Boundary reports that the job_runs table is filling up with data, and this is something that will be affecting customers too. Create a cleaner job that cleans up old job runs.
> Add job run cleaner

- internal/credential/vault/private_library.go
- internal/credential/vault/repository_credentials.go
- internal/credential/vault/repository_credentials_test.go
When issuing credentials from vault credential libraries, only persist
to the `credential_vault_credential` table if it is revokable. A
credential that is revokable has a valid lease id that can be used to
revoke the lease in vault. If the credential is not revokable it is 
also not renewable since renewing also requires a lease id.
Note that previously we would persist to this table with a sentinel
value for the external id (aka the lease id), and a status of
"unknown". This meant that row was (correctly) ignored by the renewal
and revoke job.
See: https://developer.hashicorp.com/vault/docs/concepts/lease
> fix(vault): Only persist revokable credentials

- internal/credential/vault/private_library.go
- internal/credential/vault/private_library_test.go
fixes issue where an invalid vault path (one not in the format of `.../.../(sign|issue)/username`) would cause a panic rather than handle the error correctly
> Handle Invalid Vault Paths in SSH Signed Certs retrieveCredential

- CHANGELOG.md
- internal/cmd/base/format.go
- internal/tests/cli/boundary/_accounts.bash
- internal/tests/cli/boundary/_credential_libraries.bash
- internal/tests/cli/boundary/_credential_stores.bash
- internal/tests/cli/boundary/_credentials.bash
- internal/tests/cli/boundary/_groups.bash
- internal/tests/cli/boundary/_helpers.bash
- internal/tests/cli/boundary/_host_catalogs.bash
- internal/tests/cli/boundary/_hosts.bash
- internal/tests/cli/boundary/_roles.bash
- internal/tests/cli/boundary/_scopes.bash
- internal/tests/cli/boundary/_targets.bash
- internal/tests/cli/boundary/_users.bash
- internal/tests/cli/boundary/_workers.bash
- internal/tests/cli/boundary/credential_libraries.bats
- version/feature_manager.go
When using the json output of the cli (`-format=json`), a successful call
to the controller API would place the HTTP status code in the JSON as
`status_code`. However, if there was an error from the API the status code
would be placed in the JSON as `status`. In order to be consistent, this
adds a `status_code` field to the error response case. For backwards
compatibility it still populates `status` in the error case.
This inconsistency was missed partially due to a bug in the CLI tests. The
assertion on status code was not valid and would always be successful. Thus
this also fixes the assertions and tests.
> fix(cli): Status code on api error

- internal/daemon/controller/handlers/credentials/credential_service.go
- internal/daemon/controller/handlers/credentials/credential_service_test.go
- internal/daemon/controller/handlers/mask_manager.go
The API was returning a 200 when updating a json credential with an empty object secret. No changes were applied to the credential. The expected behavior is to return an error to the user that the object field cannot be empty. This bug only appears in the API, not the CLI.
1. Launch `boundary dev`
2. Authenticate
```
curl \
--header "Content-Type: application/json" \
--request POST \
--data '{"attributes":{"login_name": "admin","password": "password"},"type": "token"}' \
http://localhost:9200/v1/auth-methods/ampw_1234567890:authenticate | export TOKEN=$(jq -r '.attributes.token')
```
3. Create a Static Credential Store
```
curl \
--header "Content-Type: application/json" \
--header "Authorization: Bearer $TOKEN" \
--request POST \
--data '{"scope_id":"p_1234567890","type": "static"}' \ …
```
> fix(handlers): return error when updating json cred w/ empty obj

- website/content/docs/concepts/domain-model/credentials.mdx
We merged an update to add JSON credentials to the credentials documentation in PR #2871 . In discussions afterwards, we decided it might be nice to add an example of the JSON blob. This pull request adds that example of the JSON blob structure to the JSON credentials documentation.
[View the update in the preview deployment here](https://boundary-bmvgh7hq3-hashicorp.vercel.app/boundary/docs/concepts/domain-model/credentials#json).
> docs: Add JSON credentials blob example

- website/content/docs/concepts/domain-model/credential-libraries.mdx
- website/content/docs/concepts/domain-model/credentials.mdx
The Boundary OSS binaries will be available to the public on Feb 8, but HCP features will not be available until the following week. I documented the HCP-only SSH credential update in the same PR (#2871) with the JSON credential update, and merged the pull request to `main` and `release/0.12.x` branches. The SSH credential injection information needs to be removed from the `release/0.12.x` branch, so that it does not go live on the 8th.
This PR removes the SSH credential injection docs from the `release/0.12.x` branch. We will have to create a new PR or revert this PR to add this content back to the `release/0.12.x` and `stable-website` branches, when the HCP 0.12.0 release goes live.
> docs: Remove SSH creds from 0.12 branch

- internal/daemon/controller/handlers/targets/target_service.go
- version/feature_manager.go
The recent feature of supporting associating a network address directly to a Target has caused a backwards compatibility issue with the older boundary binary cli. When authorizing a boundary session for a target tcp type and utilizing the ssh helper, the hostId value becomes a require value because it is used for `HostKeyAlias`
When authorizing a session, check if the target has a direct network address association and mock the hostId value with the targetId value. Using the targetId value as the mock value for hostId will guarantee a consistent HostKeyAlias value, which will prevent the ssh error: `Warning: Remote host identification has changed`.
> fix(handler): return targetId as hostId for cli edge case support

- enos/enos-scenario-e2e-database.hcl
- enos/modules/test_e2e/main.tf
- testing/internal/e2e/boundary/authenticate.go
- testing/internal/e2e/infra/docker.go
- testing/internal/e2e/tests/database/migration_test.go
- testing/internal/e2e/tests/static/session_cancel_group_test.go
- testing/internal/e2e/tests/static/session_cancel_user_test.go
This PR updates the e2e migration test to use a vault docker container as opposed to an instance of vault created by enos. This helps to reduce the amount of time this test takes to run as well as reduces cost by decreasing the number of items enos needs to create.
Some sample times from the GitHub Action that runs the enos database scenario
```
6m 11
6m 31
6m 37
7m 1
5m 34
5m 51
5m 13
4m 52
```
> test(e2e): Update migration test to use vault docker container

- enos/ci/service-user-iam/github-actions-doormat.tf
Since the `test_ci_cleanup` workflow will be running on a nightly basis via a schedule workflow trigger, the `hc-service-uri` needs to be updated to add the `event_type` `schedule` in order to ensure the service user is permitted to assume the Doormat role for scheduled workflow runs.
> [QT-400] Update ci boundary-enterprise hc-service-uri to include the schedule workflow trigger

- internal/cmd/commands/server/controller_db_swap_test.go
- internal/cmd/commands/server/listener_reload_test.go
- internal/cmd/commands/server/worker_initial_upstreams_reload_test.go
- internal/cmd/commands/server/worker_tags_reload_test.go
- internal/daemon/worker/worker_test.go
This pull request replaces `os.MkdirTemp` with `t.TempDir`. We can use the `t.TempDir` function from the `testing` package to create temporary directory. The directory created by `t.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance, or adds cleanup that we forgot.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := os.MkdirTemp("", "")
require.NoError(t, err)
t.Cleanup(func() { require.NoError(t, os.RemoveAll(td)) })
// now
tmpDir := t.TempDir()
}
```
> test: use `t.TempDir` to create temporary test directory

- website/content/docs/release-notes/v0_12_0.mdx
- website/data/docs-nav-data.json
This pull request creates the release notes for Boundary version 0.12.0. The Boundary team reviewed this content in a Google doc: [Boundary v0.12.0](https://docs.google.com/document/d/12XuX7pdkFEWLCXJiMlnVFJ2KZ5RRhzIm2WOyxD5qbKc/edit?usp=sharing)
[View the preview deployment here](https://boundary-p83facoxn-hashicorp.vercel.app/boundary/docs/release-notes/v0_12_0)
> docs: Create 0.12.0 release notes

- website/content/docs/release-notes/v0_12_0.mdx
This PR adds the CVE link to the 0.12 release notes.
[Deploy preview](https://boundary-qqp53sxzl-hashicorp.vercel.app/boundary/docs/release-notes/v0_12_0)
> adds cve link

- testing/internal/e2e/tests/static/version_test.go
During 0.12.0 testing, there was an issue observed where some additional characters were added to the `boundary version` output. This PR adds an e2e test to validate that output.
Here are some examples where the test would fail.
```
❯ go test -v github.com/hashicorp/boundary/testing/internal/e2e/tests/static -count=1 -run TestCliVersion
=== RUN   TestCliVersion
version_test.go:30: [0a 12 0+oss]
version_test.go:35: 
Error Trace:    /Users/mycow/Developer/boundary/testing/internal/e2e/tests/static/version_test.go:35
Error:          Received unexpected error:
strconv.Atoi: parsing "0a": invalid syntax
Test:           TestCliVersion
Messages:       Invalid value in version (0a.12.0+oss). EXPECTED: Number, ACTUAL: 0a
--- FAIL: TestCliVersion (0.10s)
```
```
❯ go test -v …
```
> test(e2e): Add test for `boundary version`

- enos/ci/service-user-iam/github-actions-doormat.tf
- enos/ci/service-user-iam/outputs.tf
When using the doormat GHA it is required to set a tag named `hc-service-uri` on the role the doormat user is to assume. When the `ci-test-cleanup` scheduled workflow was added, we needed to update the tag to include the new event type. Unfortunately there is a 256 character limit on the size of an AWS tag, therefore we needed to create a new role to support the new workflow. With this PR, I modify the doormat role and policy to extract a second role and policy that is tailored to be used with the scheduled cleanup workflow.
> [QT-400] Fix doormat hc-service-uri for ci bootstrap ci doormat role

- CHANGELOG.md
This PR is just an update to the changelog to reflect a bug that was fixed in our [actions-packaging-linux](https://github.com/hashicorp/actions-packaging-linux) action. We received a report from a user stating that vendor labels were missing when downloading linux packages (for products that were released via CRT) We fixed this in [this PR](https://github.com/hashicorp/actions-packaging-linux/pull/14) and we added a vendor label and set the default to `HashiCorp` This will only affect future releases that go through our linux promotion pipeline -- historical releases will not have this vendor label.
> add changelog update for vendor label for linux packaging

- .github/workflows/build.yml
- .github/workflows/enos-run.yml
- .github/workflows/jira.yml
- .github/workflows/linting.yml
This PR updates some GitHub action workflows because of an upcoming deprecation of the `set-output` command. We were seeing warnings here: https://github.com/hashicorp/boundary/actions/runs/4060061351
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
A number of warnings have been addressed, going from 89 to 9. The remaining warnings will require some updates to `hashicorp/actions-docker-build` ~and `hashicorp/action-setup-enos`~.
> chore: Update deprecated set-output command

- testing/internal/e2e/boundary/account.go
- testing/internal/e2e/boundary/group.go
- testing/internal/e2e/tests/database/migration_test.go
- testing/internal/e2e/tests/static/session_cancel_group_test.go
- testing/internal/e2e/tests/static/session_cancel_user_test.go
- testing/internal/e2e/tests/static/session_end_delete_host_set_test.go
- testing/internal/e2e/tests/static/session_end_delete_host_test.go
- testing/internal/e2e/tests/static/session_end_delete_target_test.go
- testing/internal/e2e/tests/static/session_end_delete_user_test.go
This PR updates the e2e migration test to add some new resources to the database before performing the migration.
- Vault credential (type: username/password)
- User/Role/Group
> test(e2e/migration): Add additional resources to database before migrating

- website/content/docs/concepts/domain-model/credential-libraries.mdx
- website/content/docs/concepts/domain-model/credentials.mdx
Reverts hashicorp/boundary#2908 to add HCP features to the `release/0.12.x` branch and `stable-website` for the 02/14 release of HCP Boundary.
View the updates in the preview deployment on the following pages:
- [Credential Libraries](https://boundary-a78n90ju5-hashicorp.vercel.app/boundary/docs/concepts/domain-model/credential-libraries)
- [Credentials - SSH certificate](https://boundary-a78n90ju5-hashicorp.vercel.app/boundary/docs/concepts/domain-model/credentials#ssh-certificate)
The commit bd2219421efd0d2ff7ce44b542aa4c24b60a63be will have to be cherry picked to `main` because it was not in the original pull request.
> Revert "docs: Remove SSH creds from 0.12 branch"

- website/content/docs/release-notes/v0_12_0.mdx
We published the release notes with last week's OSS Boundary 0.12.0 release. They contained descriptions of the HCP features, although the HCP documentation was not published at that time. On Feb 14, the HCP documentation will be published. This PR adds links to that documentation from the existing release notes.
NOTE: The links in the preview deployment will not work until the updates from pull requests #2952 and #2953 are merged.
> docs: Update 0.12.0 release notes with HCP links

- website/content/docs/concepts/domain-model/credential-libraries.mdx
- website/content/docs/concepts/domain-model/targets.mdx
- website/content/docs/concepts/filtering/worker-tags.mdx
- website/content/docs/configuration/worker/pki-worker.mdx
We had some difficulty merging branches for the 0.12.0 release. Several of the commits from PRs #2952 and #2953 did not make it into the `main` branch, although they were merged to the `stable-website` and `release/0.12.x` branches. This PR cherry picks those commits to the `main` branch, to bring it to parity with `stable-website` and `release/0.12.x`.
> docs: Update main branch with 0.12.0 revisions

- .github/workflows/enos-run.yml
- .github/workflows/test-ci-bootstrap-oss.yml
- .github/workflows/test-ci-cleanup-oss.yml
- enos/README.md
- enos/ci/service-user-iam/main.tf
- enos/modules/iam_setup/main.tf
In order to use the AWS account `boundary_ci` the relevant GitHub workflows have been updated to use the newly created account.
> [QT-444] Use repo isolated AWS account for enos CI tests

- internal/daemon/controller/handlers/targets/target_service.go
This variable is updated in the enterprise repo and needs to stay.
> fix(targets): Readd WorkerFilterDeprecationMessage

- internal/daemon/controller/handlers/targets/target_service.go
This variable is updated in the enterprise repo and needs to stay. This is a backport from `main`.
> fix(targets): Readd WorkerFilterDeprecationMessage (#2982)

- internal/daemon/controller/handlers/targets/tcp/target_service_test.go
In enterprise the error is different, so we need a different test error string to compare against. Create a variable that can be overwritten in the enterprise repo.
> fix(targets): Use correct error string in enterprise

- .github/workflows/test-ci-cleanup-oss.yml
We were previously using the logic/method for doormat-based repos, which doesn't work with the `configure-aws-credentials` action (it masks the accountid...and also just provides it as an output out of the box.)
> Get accountid from configure-aws-credentials action for OSS

- .copywrite.hcl
The previous ignore matched oplog_entry.go accidentally.
> fix(all): make copywrite ignores stricter

- CHANGELOG.md
- internal/cmd/commands/connect/credentials.go
- internal/cmd/commands/connect/credentials_test.go
- internal/cmd/commands/connect/funcs.go
The `boundary connect` subcommands attempt to parse the credentials to
use for brokering. This allows the subcommands to insert the credentials
automatically into the process called by the subcommand, i.e. `ssh` or
`psql`. There is some fallback logic to try a best attempt at parsing
the credential in cases where a credential type has not be set on the
credential source.
The bug was introduced with the recent change to the vault credential
library subtype being renamed from `vault` to `vault-generic`. This
fallback logic would only run if the credential source type was "vault"
or "static", so if the vault credential library was created without
specifying a credential-type, the credential would not be parsed and
automatically passed to the sub-process.
This fix removes the additional check …
> fix(cli): Fallback parsing of un-typed credentials

- .github/workflows/enos-run.yml
This PR updates the enos GitHub action workflow to always run the `Destroy` command. 
Currently, we do the following
- `enos scenario run` (with `continue-on-error`)
- if failure, `enos scenario run` (retry)
- `enos scenario destroy`
If the Retry fails, it marks the workflow as failed (it does not have `continue-on-error`) and skips the destroy step. When testing locally, `enos scenario run` does not cleanup infrastructure if there is a failure. This leads to leaving some infrastructure hanging around.
> chore(enos): Always destroy enos infrastructure

- version/version.go
Now that version metadata is being set to oss, it's appearing in the version string output:
```
Version information:
Git Revision:        d6f04e6e0867932cb1f44ccd94bc584e6a6a842e
Metadata:            oss
Version Number:      0.12.0+oss
```
As a quick fix for the 0.12.x release, I merged in https://github.com/hashicorp/boundary/commit/034f27ec8528251ce23b5afbf3851c48b0c54bec, but I think we'd rather keep these fields set across all build.yml workflows in the boundary-* repos to reduce merge conflicts. This PR is meant to fix the underlying issue in version.go where having the metadata value set to oss was not expected/accounted for. This should be a safe change to merge across the boundary-* repos.
> [main] Update version.go to remove additional oss metadata

- .github/workflows/enos-run.yml
This PR is a follow-up to https://github.com/hashicorp/boundary/pull/3000.
In that PR, we updated the workflow always run `enos destroy` to make sure we clear our infrastructure. However, on the merge to `main`, there was an interesting observation. The workflow failed in an earlier step (before `enos` was even installed). That caused the destroy step to fail because `enos` doesn't exist yet.
This change makes it such that the step only runs if the Retry step fails.
> chore(enos): Modify destroy condition

- enos/enos-scenario-e2e-aws.hcl
- enos/enos-scenario-e2e-static-with-vault.hcl
- enos/enos-scenario-e2e-static.hcl
- enos/modules/test_e2e/main.tf
- testing/internal/e2e/tests/aws/env_test.go
- testing/internal/e2e/tests/database/migration_test.go
- testing/internal/e2e/tests/static/env_test.go
- testing/internal/e2e/tests/static_with_vault/connect_authz_token_test.go
- testing/internal/e2e/tests/static_with_vault/connect_ssh_test.go
- testing/internal/e2e/tests/static_with_vault/connect_test.go
- testing/internal/e2e/tests/static_with_vault/credential_store_test.go
- testing/internal/e2e/tests/static_with_vault/env_test.go
- testing/internal/e2e/vault/env.go
- testing/internal/e2e/vault/vault.go
This PR modifies some of the e2e test suite variables in order to set it up for using docker as an infrastructure platform. These changes also make some things more explicit. Specifically...
- To maintain consistency for how we define ports, we are changing it to be explicitly defined in the enos scenario as opposed to relying on a "default" value. This change is in support of work that attempts to spin up test infrastructure using docker. The openssh-server docker image (that we use as an example host) uses Port 2222, which needs to be passed to the test suite.
- There are some instances where we need to have two different Vault addresses, one used by the Vault CLI and one by the Boundary server instance. In the case when using a Docker container, the Boundary server
needs the Vault …
> refact(e2e): Set up variables to prepare for docker implementation

- .github/scripts/set-test-package-matrix.sh
- .github/workflows/test.yml
- Makefile
- scripts/build.sh
This runs the make targets:
- make test
- make test-api
- make test-sdk
The go tests in the main module are split by package and run in parallel
in a matrix build with GOMAXPROCS=1. This is done primarily to work
around an issue that is only seen on the github runners.  When running
at a higher GOMAXPROCS tests that use vault instances in docker
containers start to intermitently fail with errors from vault, usually
either a 400, 403, or TLS error. It is not clear what the cause of this
is, since the same tests run fine on self hosted runners and on
CircleCI.
Co-authored-by: Sarah Thompson <sthompson@hashicorp.com>
Co-authored-by: Daniel Kimsey <daniel.kimsey@hashicorp.com>
> ci: Run go tests in github action

- Makefile
- scripts/build-ui.sh
- scripts/uiupdate.sh
Updated the UI build scripts to check the edition to know which boundary-ui repo to pull artifacts from. OSS will pull from `boundary-ui` while hcp and ent will pull from `boundary-ui-enterprise`.
I'll followup with a PR in the enterprise repo to actually commit the new `VERSION_ent` file.
> Update ui build scripts to check edition

- .github/workflows/labeler.yml
This PR is a follow-up to https://github.com/hashicorp/boundary/pull/3011.
It addresses an issue where the `labeler` workflow was failing to the following reason.
> ci: Fix permissions in labeler workflow

- enos/modules/iam_setup/main.tf
This PR addresses an issue when running the `e2e_aws` enos scenario locally. It would run into the following error
```
not authorized to perform: iam:CreateUser on resource: 
```
There have been some underlying enos infrastructure changes recently, and this was the recommended approach by the QTI team. The deleted comment was referring to an older way things were handled behind the scenes. Verified with the QTI team that this is all set.
> chore(enos): Fix `iam_setup` when running locally 

- enos/enos-scenario-e2e-aws.hcl
- enos/enos-scenario-e2e-database.hcl
- enos/enos-scenario-e2e-static-with-vault.hcl
- enos/enos-scenario-e2e-static.hcl
This PR explicitly defines all dependencies between steps to ensure that steps run in order. While this doesn't address an immediate issue, it may help to ensure that there's no potential race condition that could occur here.
> chore(enos): Define explicit dependencies between steps

- enos/modules/build_local/main.tf
There was an update to the Boundary build scripts to detect what edition of boundary is being built so that it knows which version of the UI to grab. However, this affected instances when building boundary on an architecture that is not the same as the host (in this case, building a linux/amd64 version on a mac). When the scripts try to use the built CLI to get the edition, it threw an `exec format error`.
This PR updates the enos scripts to default to `oss` so that the build scripts do not have to use the CLI to determine the edition, bypassing the CLI command.
> chore(enos): Default to use OSS edition

- internal/db/sqltest/tests/hcp/billing/monthly_sessions_all.sql
- Create helper function to determine if dates being compared fall in the same month
- Fix expected date for 'yesterday' test
- Check for inequality of current month vs all comparison if yesterday fell in the prior month
Failing pgtap results, for reference: https://app.circleci.com/pipelines/github/hashicorp/boundary-enterprise/3581/workflows/559613bb-7df1-4e5a-82e9-90def37b3f8b/jobs/31020
```
Failed test 27: "hcp_billing_monthly_sessions_all should have 1 row with 48 sessions_pending_count when there are only sessions for yesterday"
have: ("2022-11-01 00:00:00+00","2022-12-01 00:00:00+00",48)
want: ("2022-12-01 00:00:00+00","2022-12-01 14:00:00+00",48)
Failed test 28: "hcp_billing_monthly_sessions_current_month and hcp_billing_monthly_sessions_all should be equal"
Results differ …
```
> Fix sql tests failing on the first of the month

- enos/enos-scenario-e2e-aws.hcl
- enos/enos-scenario-e2e-database.hcl
- enos/enos-scenario-e2e-static-with-vault.hcl
- enos/enos-scenario-e2e-static.hcl
- enos/enos-variables.hcl
- enos/enos.vars.hcl
- enos/modules/test_e2e/main.tf
- enos/scripts/test_e2e_env.sh
- testing/internal/e2e/README.md
If you're running an enos scenario and there's a failure in the test suite for any reason (bug, test issue), enos will throw an error and you would not be able to access the environment variables needed to test/reproduce it locally. Enabling this `e2e_debug` variable will ensure that the enos scenario passes so that you can extract the needed environment variables.
This PR does the following
- adds an enos variable `e2e_debug` to stop scenarios from running the test suite so that you can always get the environment variables of the generated infrastructure
- adds a script `test_e2e_env.sh` to more easily extract the environment variables
> chore(enos): Add debug variable

- .github/workflows/enos-run.yml
- .github/workflows/test-ci-bootstrap-oss.yml
- .github/workflows/test-ci-cleanup-oss.yml
This PR updates the version of the `aws-actions/configure-aws-credentials` GitHub action to use the node16 version. This is to mitigate some deprecation warnings shown below:
Example: https://github.com/hashicorp/boundary/actions/runs/4316959009
The run for this branch reduces the number of warnings: https://github.com/hashicorp/boundary/actions/runs/4317537965
> chore(enos): Use node16 version of action

- .github/scripts/schema-diff-hide-gh-comments.sh
- .github/workflows/schema-diff.yml
- .gitignore
- scripts/schema-diff.sh
The script should be given a base branch to compare against, if not set
it defaults to main. The script will apply the schema migrations for
both the base branch and the current commit and generate dumps that are
then compared to create a diff. The dumps are left in a temporary
directory so that they can be compared using a users preferred diff tool.
For example, generate the dumps and diff against main
./scripts/schema-diff.sh main
Examine the diff to database functions using delta:
delta .schema-diff/funcs_$(git rev-parse main) .schema-diff/funcs_$(git rev-parse HEAD)
This also adds a github action that runs the script on pull-requests
that contain schema changes and reports the diffs as a comment on the
pull-request.
Co-authored-by: Hugo Vieira <hugoamvieira@users.noreply.github.com>
> ci(schema-diff): Add script to generate diff of database schema

- enos/ci/service-user-iam/main.tf
These statements got mixed up in the account migration, this policy should be applied to OSS (non-doormat) projects that need IAM access for testing
> Add extra IAM permissions for demo user creation during e2e tests

- README.md
In https://github.com/hashicorp/boundary/pull/3065, I think we unintentionally removed the boundary logo from the README file. This PR adds the logo back.
> doc: Add boundary logo back to README

- .github/workflows/test.yml
This PR adds the `fail-on-cache-miss: true` setting to more jobs in the test workflow. We have observed some instances where the cache fails to restore due to a timeout (it gets stuck at 99.6%)
```
Received 16777216 of 965520185 (1.7%), 16.0 MBs/sec
Received 180355072 of 965520185 (18.7%), 85.8 MBs/sec
Received 356515840 of 965520185 (36.9%), 113.2 MBs/sec
Received 520093696 of 965520185 (53.9%), 123.8 MBs/sec
Received 679477248 of 965520185 (70.4%), 129.4 MBs/sec
Received 813694976 of 965520185 (84.3%), 129.1 MBs/sec
Received 961325881 of 965520185 (99.6%), 130.7 MBs/sec
Received 961325881 of 965520185 (99.6%), 114.4 MBs/sec
Received 961325881 of 965520185 (99.6%), 101.7 MBs/sec
Received 961325881 of 965520185 (99.6%), 91.5 MBs/sec
Received 961325881 of 965520185 (99.6%), 83.2 MBs/sec …
```
> chore: Add "fail-on-cache-miss" setting to more jobs

- .github/workflows/trigger-test-cron.yml
[Jira Ticket RELENG-483](https://hashicorp.atlassian.net/browse/RELENG-483)
To identify the frequency of boundary OSS failures, we have added a new workflow [trigger-test-cron]  that will trigger on a 2-hour schedule and run the test workflow.
> Releng 483/test failure frequency

- .github/workflows/trigger-test-cron.yml
Lowering the run frequency until GitHub increases our concurrency limit
> [RELENG-483] lower test run frequency per hour

- .github/workflows/enos-run.yml
This PR pins the version of Terraform used in the enos GitHub Action workflows to 1.3.9 in order to mitigate a bug in enos with the introduction of Terraform 1.4.x. This will be reverted once the bug is resolved.
> chore(enos): Pin Terraform to 1.3.9 to mitigate bug

- testing/internal/e2e/infra/docker.go
This PR updates the enos GitHub Action workflow to use our internal docker mirror in order to insulate ourselves from issues with GitHub. We were experiencing test failures when trying to pull the `linuxserver/openssh-server` docker image due to an issue with GitHub Packages.
Note: There is an enos test reporting a failure in the status checks due to a bug in enos with the latest Terraform. That work is ongoing.
> chore(enos): Use docker mirror

- .github/workflows/enos-run.yml
This PR reverts commit 4e697d4dd56b5bfc2e0ef417583c1b6b7f05d449, which pinned the version of Terraform used in enos to `Terraform 1.3.9`. This was due to a bug in `Terraform 1.4.1` resulting in some enos operations to fail. `Terraform 1.4.2` was just released and addresses the bug. 
> Revert "chore(enos): Pin terraform to 1.3.9 to mitigate bug (#3087)"

- website/content/docs/troubleshoot/faq.mdx
From a Slack conversation:
> We get variations of this question a fair bit — can we add an answer to it in the public-facing Boundary FAQ?  https://hashicorp.slack.com/archives/C01CHBHMYJ1/p1670475532772349
> @x980707x
> >[Dynamic Host Catalogs Credential Question [Boundary]](https://discuss.hashicorp.com/t/dynamic-host-catalogs-credential-question/47762/1)
> >Hi!,
> >I am using AWS and I am not using IAM User, I am using IAM Role. Can’t I use an IAM role rather than a credential to use Boundary’s Dynamic Host Catalog?
> >Thanks!
Cannot use IAM role at this time. Work with Joe on the text. Should be added here to the [FAQs](https://developer.hashicorp.com/boundary/docs/troubleshoot/faq) topic.
[View the change in the preview deployment.](https://boundary-diyoapx3l-hashicorp.vercel.app/boun …
> docs: Update FAQs with IAM role answer

- .github/workflows/test.yml
This PR removes an extraneous `fail-on-cache-miss` attribute. This particular job is the setup step, so there should be no expectation that the cache is present.
> chore: Remove extraneous fail-on-cache-miss attribute

- .github/workflows/build.yml
- .github/workflows/enos-run.yml
- Makefile
- enos/enos-modules.hcl
- enos/enos-scenario-e2e-docker.hcl
- enos/enos-variables.hcl
- enos/modules/build_boundary_docker_crt/main.tf
- enos/modules/build_boundary_docker_local/build.sh
- enos/modules/build_boundary_docker_local/main.tf
- enos/modules/docker_openssh_server/main.tf
- enos/modules/docker_postgres/main.tf
- enos/modules/load_docker_image/main.tf
This PR continues to extend on the docker work for e2e tests introduced here: https://github.com/hashicorp/boundary/pull/3073. It adds support for the following...
- when run in CI, it will use the docker image built in the Actions workflow 
- when run locally, it will build a boundary docker image using your local checkout and use that to start a docker container
Next step would be to refactor the existing enos scenarios to make use of the docker containers.
> chore(enos): Use docker image generated from code

- globals/kms.go
- internal/cmd/base/servers.go
- internal/cmd/config/config.go
- internal/daemon/controller/listeners.go
- internal/daemon/controller/testing.go
- internal/daemon/worker/listeners.go
- internal/daemon/worker/testing.go
- internal/daemon/worker/testing_test.go
- internal/daemon/worker/workerdisconnect_test.go
- sdk/wrapper/wrapper.go
This adds an alternate KMS that can be used to handle incoming downstream connections for PKI-KMS registration. This can be specified multiple times; because the upstream only needs to decrypt, we can simply use a PooledWrapper and add each given KMS to the pool.
> Add downstream worker auth KMS

- internal/tests/cli/boundary/_target_host_sources.bash
- internal/tests/cli/boundary/_targets.bash
- internal/tests/cli/boundary/target.bats
- internal/tests/cli/boundary/target_host_sources.bats
- Add bats test coverage for adding a Host Source to a Target
- Create `target_host_sources.bash` file with helper functions for bats test file
1. Add a newly created `host-set` as a `host-source` to a target
i. Verify the newly created `host-source` is present in both JSON & Table format
1. Verify a target can have more than 1 `host-source` by adding an additional `host-source`
1. Verify `host-source` can be disassociated from a target 
Created new resources like a target & host catalog instead of using already created resources because the changes could affect existing tests and it made it easy to change the newly created resources
> Bats Tests: Target Host Sources

- .github/workflows/schema-diff.yml
- scripts/schema-diff.sh
With the change to report changes to constraints instead of all of the 
post-data section, foreign key constraints where no longer captured in the
diff. This now extracts the foreign key constraints and generates a diff of
them between versions.
Also includes some additional documentation about this tool.
> fix(schema-diff): Include foreign key constraints in diff

- website/content/docs/troubleshoot/faq.mdx
Link to the old URL for the dynamic host catalog page removed, added the current valid path.
> Replace broken link

- .github/workflows/build.yml
- .github/workflows/test-cli-ui.yml
The git reference in github.sha is the latest commit on the default
branch (ie `main`). This instead used the commit hash for the workflow
that ran and triggered this workflow.
Blame: e76b3b95114ad696a89fe36f6b1bced4b090b9cf
> fix(cliui): Use correct git sha reference for artifacts

- .github/workflows/build.yml
- .github/workflows/test-cli-ui.yml
This was missed on the previous fix. It now references the correct
artifact name now that this is back to running as part of the build
workflow.
Blame: 181f0f180603a78a54cecdaa64dfd93e5f40cda2
> fix(cliui): Download correct artifact

- internal/daemon/controller/handler_ui.go
- internal/daemon/controller/handler_ui_test.go
- internal/db/sqltest/Makefile
this PR adds a noop function to the UI handler to allow controller metadata to be served for licensed Boundary editions
> feat(ui): serve controller metadata from ui handler

- .github/workflows/enos-run.yml
Recently the enos-provider was updated to add automatic application log file collection for all boundary and remote exec resources. This PR updates the enos run workflow to turn on this feature and to add an upload artifact step to store the logs in the build artifacts. The logs will be zipped up in a file that has the same name as the scenario that failed, with spaces being replaced by underscores.
> [QT-516] Add a step to the enos run workflow to automatically upload application logs when a scenario fails

- CHANGELOG.md
- Makefile
- internal/daemon/controller/handlers/workers/worker_service.go
- internal/daemon/controller/handlers/workers/worker_service_test.go
- internal/daemon/worker/testing.go
- internal/server/public_ids.go
- internal/server/repository_worker.go
- internal/server/repository_worker_test.go
- internal/server/repository_workerauth.go
- internal/tests/cluster/multi_controller_worker_test.go
- internal/tests/cluster/switch_kms_method_test.go
- internal/tests/cluster/unix_listener_test.go
- internal/tests/cluster/worker_replay_test.go
This would cause their public IDs to change, which we do not want.
Note to reviewers: I recommend hiding whitespace.
> Do not allow PKI-KMS workers to have names updated via API

- testing/internal/e2e/infra/docker.go
- testing/internal/e2e/infra/env.go
This PR updates the e2e migration test to use our internal docker mirror to mitigate against potential downtime in other GitHub services (there were failures here due to GitHub packages being down).
> test(migration): Use docker mirror

- internal/tests/cluster/switch_kms_method_test.go
Also extend deadline from 10 seconds to 1 minute, hopefully this should fix any flakiness in this test.
> internal/tests/cluster: switch flaky test to polling

- testing/internal/e2e/tests/static/credential_store_test.go
- testing/internal/e2e/tests/static/testdata/credential.json
[ICU-8561](https://hashicorp.atlassian.net/browse/ICU-8561)
This PR updates the e2e test `TestCliStaticCredentialStore` to do the following:
- Verify JSON-credentials are brokered to target correctly
- Verify private-key credentials are brokered to target correctly
- Use files and constants to store test data instead of hardcoding it
[ICU-8561]: https://hashicorp.atlassian.net/browse/ICU-8561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test(e2e): Verify different credentials are brokered to target

- .github/workflows/build.yml
- .github/workflows/enos-fmt.yml
- .github/workflows/milestone-checker.yml
- .github/workflows/test-ci-cleanup-oss.yml
After installing the GitHub Actions VSCode extension, it reported a few linter errors on some of our workflow files. This PR attempts to address the majority of them. After these changes, the linter still has a couple of warnings about it being unsure if some variable access is correct, but I think those are working correctly.
> chore: Fix issues detected by GitHub Actions linter

- .github/workflows/milestone-checker.yml
This PR updates the `milestone-checker` workflow to fix an error that appears in boundary-enterprise. On the enterprise repo, this job fails due to this error: https://github.com/hashicorp/boundary-enterprise/actions/runs/4639652070/jobs/8210746838. 
Updating the version of node resolved the issue: https://github.com/hashicorp/boundary-enterprise/actions/runs/4640154276/jobs/8211784046?pr=355. 
Not sure if this is the right approach. Using this PR as a discussion starter.
> chore: Update milestone-checker to use newer version of node

- .github/workflows/milestone-checker.yml
This PR adds another permission to the milestone-checker workflow. I noticed that the workflow was passing, but I didn't see the expected "Milestone not set" failure status on a PR. This was in the logs:
```
got check result {
state: 'failure',
sha: '3c340a2cfcc1dcc67b38f2f59756ecef1bbed322',
title: 'Milestone Check',
description: 'Milestone not set',
targetURL: undefined
}
failed to dispatch RequestError [HttpError]: Resource not accessible by integration
at /home/runner/work/boundary/boundary/actions/node_modules/@octokit/request/dist-node/index.js:86:21
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async OctoKitIssue.createStatus (/home/runner/work/boundary/boundary/actions/api/octokit.js:442:9)
at async Dispatcher.dispatch …
```
> chore: Add write permission to milestone checker

- internal/daemon/controller/handlers/credentials/credential_service.go
- internal/daemon/controller/handlers/credentials/credential_service_test.go
When creating a JSON credential with an empty object, the return error is not a human readable message. 
Request:
```
cred, err := credClient.Create(tc.Context(), credential.JsonSubtype.String(), cs.Item.Id, credentials.WithName("foo"), credentials.WithJsonCredentialObject(map[string]any{}))
```
```
{
"kind":"Internal",
"message":"credentials.(Service).createInRepo: unable to create credential: static.(Repository).CreateJsonCredential: missing object: parameter violation: error #100"
}
```
```
{
"kind":"InvalidArgument",
"message":"Error in provided request.",
"details":  {
"request_fields":[{
"name":"attributes.object",
"description":"This is a required field and cannot be set to empty."
}]
}
}
```
> fix(handler): return human readable error for json cred w/ empty object

- enos/enos-scenario-e2e-docker.hcl
- enos/enos-variables.hcl
- enos/modules/docker_boundary/init.sh
- enos/modules/docker_boundary/main.tf
- enos/modules/docker_openssh_server/main.tf
- enos/modules/docker_postgres/main.tf
- enos/modules/docker_vault/main.tf
This PR updates the enos docker scenario to include some additional waits in order to ensure that the docker resources are ready to handle requests. This was done to mitigate flaky behavior where tests would experience some failures because some containers did not finish loading.
> test(e2e): Improve reliability of enos docker scenario

- testing/internal/e2e/tests/static/session_end_delete_user_test.go
When investigating a separate issue, noticed some logs showing that some test data was not cleaned up. Turns out, if the test `TestCliSessionEndWhenUserIsDeleted` fails prior to it deleting the user, then subsequent tests will get impacted.
This PR updates that test to have an additional cleanup step if the test isn't able to get to it.
> test(e2e): Clean up user if test fails

- go.mod
- go.sum
This normalizes behavior around missing map keys. See https://github.com/hashicorp/go-bexpr/pull/38 for more information.
> Bump go-bexpr dep to v0.1.12

- internal/perms/acl.go
- internal/perms/acl_test.go
- internal/perms/grants.go
This makes two changes:
1. ListPermissions assumed every grant string had a type field, which does not match all grant formats. It now infers type from ID for formats which do not specify type.
2. Allow ID-only grant strings to be valid so long as the type specified matches the type of the specified ID.
> Fix ListPermissions when separate id/type grants are used

- internal/perms/acl_test.go
`action.List` is a collection action, that is, it is not part of the set of actions that can be executed against a single instance of any given resource.
As part of the `ListPermissions` call, `idActions` is expected, that is, all the actions that can be executed against a resource instance. `action.List` will never be part of this. This commit updates the tests to reflect this fact.
> fix(perms): Tests use action.List in resource action set

- testing/internal/e2e/tests/aws/worker_test.go
In https://github.com/hashicorp/boundary/pull/3177, we added a new e2e test that uses a worker. We observed one flake in this test due to the following...
```
worker_test.go:63: 
Error Trace:	/home/runner/work/boundary/boundary/testing/internal/e2e/tests/aws/worker_test.go:63
Error:      	Not equal: 
expected: 1
actual  : 255
Test:       	TestCliWorker
```
This PR does the following:
- updates the exit code assertion to correct the `expected` and `actual` values
- modifies the `require` to be an `assert`. I wasn't able to reproduce this locally, so I want to see what the error message if this happens again in CI.
> test(e2e): Fix assertion statement in worker test

- .github/workflows/build.yml
- .github/workflows/enos-run.yml
- enos/enos-modules.hcl
- enos/enos-scenario-e2e-aws.hcl
- enos/enos-scenario-e2e-static-with-vault.hcl
- enos/enos-scenario-e2e-static.hcl
- enos/enos-scenario-e2e-ui.hcl
- enos/enos-variables.hcl
- enos/enos.vars.hcl
- enos/modules/build_local/main.tf
- enos/modules/build_local/templates/build.sh
- enos/modules/read_license/main.tf
- enos/modules/worker/main.tf
This is mostly scenario support for future pipeline work and some housekeeping cleanup. All new attributes have safe defaults won't break current tests. Also, updates the worker module to use new provider attribute for ipv4 public addressing and simplifes variables in the workflow.
> chore(e2e): Update test attributes for new builds

- internal/daemon/controller/handlers/targets/target_service.go
This is just an early error message to avoid running the filtering function if there are no workers to begin with.
> Exit before filtering if no workers are listed

- .github/scripts/set-test-package-matrix.sh
- internal/tests/api/authmethods/authmethod_test.go
The test matrix script was excluding directories that only contained external package tests (i.e. tests packages with _test suffix). The following tests were not being run:
```
./internal/daemon/controller/common/scopeids
./internal/daemon/controller/handlers/authtokens
./internal/daemon/controller/handlers/groups
./internal/daemon/controller/handlers/host_catalogs
./internal/daemon/controller/handlers/host_sets
./internal/daemon/controller/handlers/hosts
./internal/daemon/controller/handlers/roles
./internal/daemon/controller/handlers/scopes
./internal/daemon/controller/handlers/sessions
./internal/daemon/controller/handlers/targets/tcp
./internal/daemon/controller/handlers/users
./internal/db/schema/internal/edition
./internal/db/schema/internal/provider …
```
> .github: fix test matrix script

- internal/daemon/controller/handlers/users/user_service.go
- internal/daemon/controller/handlers/users/user_service_test.go
Add support for setting, adding & deleting LDAP accounts associated with a user.
Change:
- Add LDAP prefix to validation check for `AddUserAccounts`, `SetUserAccounts` & `RemoveUserAccounts`
> chore: user account ldap support

- .github/workflows/test.yml
The original motivation for the matrix was to mitigate an issue some
tests failing that used a vault docker container. When the tests ran in
a single step, these tests would almost always fail. By splitting the
tests per package, the failure rate of these tests was around 20%.
GitHub was able to identify the cause. There was an issue with localhost
resolution that causes requests to the vault containers to sometimes
fail, resulting in the kinds of failures that were seen. Note that the
same issue was not seen when accessing the test postgres database that
was running in a container, since the test code connects via 127.0.0.1,
while the vault container used localhost. This commit includes the
recommended fix so that localhost name resolution works as expected on
the GitHub hosted runners. …
> ci(test): Remove matrix for running tests per package

- testing/internal/e2e/infra/docker.go
This PR updates the migration test to have the vault docker container bound to a different port in order to avoid conflicts with other vault instances.
> test(e2e): Modify port to avoid conflicts

- enos/enos-modules.hcl
- enos/enos-scenario-e2e-aws.hcl
- enos/enos-scenario-e2e-static-with-vault.hcl
- enos/enos-scenario-e2e-static.hcl
- enos/enos-scenario-e2e-ui.hcl
- testing/internal/e2e/tests/static/connect_test.go
This change updates the path to `echo` to work across various workers, as well as providing `binary_name` to the local build & boundary modules
> fix(e2e): Fix path to echo in connect_test & update scenarios for local builds

- CHANGELOG.md
- api/authtokens/option.gen.go
- internal/api/genapi/input.go
- internal/api/genapi/templates.go
This option did not respect whether or not versioning was enabled when writing it out during generation.
This does mean that there is a breaking change for auth tokens, but as it was a no-op anyways it's easy to fix and not something I want to /v2 about.
> Only create WithAutomaticVersioning if versioning is used

- internal/cmd/commands/connect/connect.go
In the helper text function for the connect module there are unneeded quotations.
> Remove quotations when not needed

- website/content/docs/configuration/controller.mdx
- website/content/docs/getting-started/installing/production.mdx
Change references to the deprecated `controllers` field to `initial_upstreams`
> Update references to deprecated controllers field

- enos/enos-modules.hcl
- enos/enos-variables.hcl
- enos/enos.vars.hcl
- enos/modules/test_e2e/main.tf
The default `go test` timeout is 10 minutes, and we're coming awfully close to that limit in some test runs. This adds a tunable for that timeout we can customize per-execution if needed.
> feat(e2e): Add configurable timeout for go test execution within scenarios

- testing/internal/e2e/tests/aws/dynamichostcatalog_host_set_empty_test.go
- testing/internal/e2e/tests/aws/dynamichostcatalog_host_set_test.go
- testing/internal/e2e/tests/aws/env_test.go
- testing/internal/e2e/tests/aws/worker_test.go
- testing/internal/e2e/tests/database/env_test.go
- testing/internal/e2e/tests/database/migration_test.go
- testing/internal/e2e/tests/static/bytes_up_down_empty_test.go
- testing/internal/e2e/tests/static/bytes_up_down_test.go
- testing/internal/e2e/tests/static/connect_authz_token_test.go
- testing/internal/e2e/tests/static/connect_localhost_test.go
- testing/internal/e2e/tests/static/connect_ssh_test.go
- testing/internal/e2e/tests/static/connect_test.go
- testing/internal/e2e/tests/static/credential_store_test.go
- testing/internal/e2e/tests/static/env_test.go
- testing/internal/e2e/tests/static/session_cancel_admin_test.go
- testing/internal/e2e/tests/static/session_cancel_group_test.go
- testing/internal/e2e/tests/static/session_cancel_user_test.go
- testing/internal/e2e/tests/static/session_end_delete_host_set_test.go
- testing/internal/e2e/tests/static/session_end_delete_host_test.go
- testing/internal/e2e/tests/static/session_end_delete_project_test.go
- testing/internal/e2e/tests/static/session_end_delete_target_test.go
- testing/internal/e2e/tests/static/session_end_delete_user_test.go
- testing/internal/e2e/tests/static/target_address_test.go
- testing/internal/e2e/tests/static_with_vault/connect_authz_token_test.go
- testing/internal/e2e/tests/static_with_vault/connect_ssh_test.go
- testing/internal/e2e/tests/static_with_vault/connect_test.go
- testing/internal/e2e/tests/static_with_vault/credential_store_test.go
- testing/internal/e2e/tests/static_with_vault/env_test.go
This PR adds an e2e test that checks that a session is cancelled after deleting the corresponding project it belongs on. This continues the series of tests that test a session ends after other kinds of resources are deleted.
This particular test is slightly different in that it does not read the session id to check that the session status itself is cancelled and solely relying on the goroutine that initiates a user's session to end. This is due to how the data is structured (details here: https://hashicorp.atlassian.net/browse/ICU-7296)
> test(e2e): Add test that checks that session ends after deleting project

- enos/ci/service-user-iam/main.tf
- enos/modules/bucket/locals.tf
- enos/modules/bucket/main.tf
- enos/modules/bucket/outputs.tf
- enos/modules/bucket/variables.tf
- enos/modules/iam_setup/main.tf
This Terraform module can be used with Enos to supply a bucket in S3 along with a policy that allows a given user to write and delete objects in said bucket. I've done some simple testing to confirm that the above behavior is possible. A simple way to test this for yourself is to use a scenario like the one below, grab the outputs from the scenario to know the bucket name and AWS user ID (in order to assume this user's access). You'll need to get the key for this user from the state file itself as it's a sensitive value that can't be shown in Terraform output.
```
module "bucket" {
source = "./modules/bucket"
}
scenario "bucket_test" {
terraform_cli = terraform_cli.default
terraform     = terraform.default
providers     = [provider.aws.default]
step "create_iam_user" {
module = …
```
> Add s3 bucket module for Enos scenarios

- internal/cmd/commands/targetscmd/funcs.go
The current `authorize-session` print function has a case statement which checks whether the session credential type matches "vault" or "static" before accessing and printing the credential's SessionSecret field. The current credential libraries are generated with types "vault-generic" or "vault-ssh-certificate".
In my understanding, this case statement should be updated so we also print read and print credential secrets for all current vault credential source types.
> fix(cli): correctly print secrets in authorize-session for current vault credential source subtypes

- go.mod
- go.sum
This updates the nodee lib with a change that causes 0 cert lifetime to instead use the default, which is what we want.
> Honor default cert lifetime

- internal/cmd/base/servers.go
- internal/daemon/controller/testing.go
- internal/daemon/worker/auth_rotation.go
- internal/daemon/worker/auth_rotation_test.go
- internal/daemon/worker/testing.go
- internal/daemon/worker/worker.go
Most of the changes here are changes or enhancements that are useful for tests. The crux of the issue was that I had pulled up one var to the package level so it could be read from tests, but that var was not being reset between tests. It's not even used in tests anymore, so I put it back to function-local.
> Fix worker auth rotation test

- internal/cmd/ops/server_test.go
- internal/daemon/controller/handlers/scopes/scope_service_test.go
- internal/daemon/worker/auth_rotation_test.go
- internal/daemon/worker/testing_test.go
- internal/daemon/worker/worker_test.go
- internal/daemon/worker/workerdisconnect_test.go
- internal/tests/api/authmethods/authmethod_test.go
- internal/tests/api/credentials/credentials_test.go
- internal/tests/api/scopes/scope_test.go
- internal/tests/api/targets/target_test.go
- internal/tests/cluster/worker_bytesupdown_test.go
- internal/tests/cluster/x509_verification_test.go
A previous commit added a call to t.Cleanup in the NewTestController/NewTestWorker commands; as a result these statements are no longer needed.
> Remove cleanup calls for test controller/worker

- internal/daemon/controller/handlers/targets/target_service.go
For requests to the target authorize session endpoint we support passing
a target name instead of an id. This means that `req.GetId()` might not
be the target's public id. Since the first thing authorize session does
includes retrieving the target as part of the authorization checks, this
subtype check can leverage the public id of the target instead of using
the request.
Fixes: 6178dd516e81e84c732cb700a2c7ecc6ccc167af
> fix(targets): Support authorize session request with target name

- internal/bsr/convert/convert.go
- internal/bsr/convert/internal/asciicast/asciicast.go
- internal/bsr/convert/internal/asciicast/asciicast_test.go
- internal/bsr/convert/options.go
- internal/bsr/convert/options_test.go
- internal/bsr/convert/ssh.go
- internal/bsr/convert/ssh_test.go
This removes the minimum on width and height, instead it will just used
the largest width, height seen as the initial size for the asciicast.
This also provides the ability to still set a minimum via options to
convert.ToAsciicast if the caller has a known minimum size. Also note
that in cases where there is no size information, ie if there was no pty
request, this will still pick a default size of 80x24.
> feat(bsr/convert): Remove asciicast minimum window size

- internal/db/schema/migrations/oss/postgres/60/02_sessions.up.sql
- internal/db/schema/migrations/oss/postgres/64/04_session_list.up.sql
As part of the performance improvements for listing sessions for v0.9.0,
the view used to retrieve sessions for listing was updated to no longer
include a join on session_connection. However, a later migration that
was adding additional columns to this view inadvertently re-added the
join and session_connection columns. This resulted in requests to list
sessions performing this join, and returning additional rows for each
connection in a session. The application would ignore this additional
data, since it is no longer returned via the API. This would be
particularly impactful in cases where there are a large number of
connections per session, as this would greatly increase the amount of
data returned by the database.
This fix removes the session_connection join from this view, which …
> fix(session): List performance with large number of session connections

- website/content/docs/configuration/worker/index.mdx
- website/content/docs/configuration/worker/kms-worker.mdx
- website/content/docs/configuration/worker/pki-worker.mdx
- website/data/docs-nav-data.json
Cleaning up some text and formatting for 0.13, in the future we will restructure the worker docs so that it is easier to understand and use, as well as accommodating for future changes.
> Worker docs cleanup for 0.13

- internal/daemon/common/worker_list.go
- internal/daemon/controller/handlers/workers/worker_service.go
- internal/daemon/controller/handlers/workers/worker_service_test.go
This also slightly changes delete logic and ensures authorized actions match what is allowable.
> Disallow updates on all types of KMS workers

- internal/bsr/internal/fstest/fs_test.go
- internal/bsr/internal/fstest/space.go
This provides a new storage.FS implementation that expands the on
fstest.MemFS by allowing tests to mark the filesystem as out of space.
When this happens any write/create operation will start returning an
error indicating that the filesystem is out of space.
> test(bsr/fstest): Add new FS for testing out of space errors

- website/content/docs/concepts/filtering/worker-tags.mdx
Using worker tags in expressions can be confusing, this adds a note to make it clear how to match values in tags.
> website: add separate note about worker tags

- .release/docker/README.md
- .release/docker/README_docker_io.md
This moves the contents of the readme used for hashicorp/boundary on
docker.io/registry.hub.docker.com to a separate readme file from the one that
documents how to build docker images. It also makes some minor fixups
and updates the docker.io readme, must notably updating the minimum
version of postgres that boundary requires.
> doc(docker): Separate docker.io readme contents from directory readme

- .github/workflows/make-gen-delta.yml
This PR adds another check to the `make-gen-delta` workflow to ensure that `go mod tidy` changes have been committed to the branch. There was a recent case where `go.mod` and `go.sum` were out of sync with the code base. Adding this check would prevent that from happening.
An alternate implementation is to update `make gen` to run `go mod tidy`. Curious to hear if there are any opinions here.
> chore: Add check for `go mod tidy`

- internal/cmd/commands/connect/connect.go
This avoids a situation where teardown results in an error due to the worker not accepting the connection (since the credentials are invalid). Teardown is a best-effort way to avoid sessions that have long lifetimes ending up having to wait for expiration before cleanup, but if we're near expiration it doesn't really matter.
Fixes ICU-9633
> Don't attempt session teardown if the session is expired

- enos/enos-scenario-e2e-aws.hcl
- enos/modules/worker/main.tf
- enos/modules/worker/variables.tf
This PR updates the enos worker module to allow for specifying different worker configs as a variable. This enables the ability for an enos scenario to use a different worker config to test different functionality.
> test(e2e): Set worker config to a variable

- website/content/docs/concepts/security/data-encryption.mdx
- website/content/docs/configuration/session-recording/enable-session-recording.mdx
A bsr KMS key is required to enable session recording, but it currently is not documented. From a [Slack conversation](https://hashicorp.slack.com/archives/C01AQDJF3SA/p1686764521142459).
This PR adds the requirement to the pre-requisites for Enabling session recording. It also adds the `bsr` key to the list of KMS keys in the Data security topic.
View the topics in the preview deployment:
[Enabling session recording on a target](https://boundary-28e411yh8-hashicorp.vercel.app/boundary/docs/configuration/session-recording/enable-session-recording#:~:text=A%20KMS%20key%20with%20the%20purpose%20bsr%20must%20be%20added%20to%20the%20controller%20configuration.%20The%20key%20is%20used%20for%20encrypting%20data%20and%20checking%20the%20integrity%20of%20recordings.%20Refer%20to%20Create%20the%20c …
> docs: Add bsr key to requirements

- website/content/docs/concepts/iam.mdx
- website/content/docs/install-boundary/configure-controllers.mdx
- website/content/docs/install-boundary/configure-workers.mdx
When the text inside a bullet begins with code, our renderer changes the text to a link. The link doesn't go anywhere when you click it, creating a bad user experience:
___________________________________
I discussed it with the DevDot team, and this is a limitation of our system; there is no fix for it at this time.
I thought I figured out a workaround by adding the HTML entity for a space (`&#32;`) before the text for the bullet. The extra space prevented the code from rendering as a link, and Markdown ignored it as a duplicate space. This worked great on my local machine and in Vercel previews:
____________________________________
However, when these updates were published, they did not render the same way in our production environment. The extra space is turning those bullet points …
> docs: Fix display issue with bullets and code

- .github/workflows/build.yml
This PR updates the `build` workflow to ignore running on tags. This was done to prevent extra workflows from triggering that aren't necessary.
> chore: Ignore tags in workflow

- internal/host/plugin/repository_host_catalog.go
- internal/host/plugin/repository_host_catalog_test.go
- internal/host/plugin/repository_host_set.go
- internal/host/plugin/repository_host_set_test.go
onUpdate for host catalog & host set make a plugin call to normalize attributes passed in. This behavior was introduced in [PR-2376](https://github.com/hashicorp/boundary/pull/2376) but was only applied to onUpdate calls. This created different data structures for onCreate calls and onUpdate calls.
> fix: add plugin normalization for onCreate methods

- internal/host/plugin/repository_host_catalog_test.go
- internal/host/plugin/repository_host_set_test.go
- internal/proto/plugin/v1/host_plugin_service.proto
- sdk/pbs/plugin/host_plugin_service_grpc.pb.go
Update comments for `NormalizeSetData` to include when `NormalizeSetData` could be useful and the non-obvious consequences of using it.
Follow-up PR for: #3338
> docs: update NormalizeSetData comments

- api/authtokens/authtokens.gen.go
- internal/api/genapi/input.go
- internal/cmd/commands/authtokenscmd/authtokens.gen.go
- internal/cmd/commands/authtokenscmd/authtokens.go
- internal/cmd/gencli/input.go
The auth-tokens help command included a reference to a non-existent auth-tokens create command. Replace the default help and also add a helpful pointer to the authenticate command.
Before:
```
$ boundary auth-tokens -h
Usage: boundary auth-tokens [sub command] [options] [args]
This command allows operations on Boundary auth token resources. Example:
Create an auth token:
$ boundary auth-tokens create -name prodops -description "For ProdOps usage"
Please see the auth-tokens subcommand help for detailed usage information.
Subcommands:
delete    Delete an auth token
list      List an auth token
read      Read an auth token
```
After:
```
$ boundary auth-tokens -h
Usage: boundary auth-tokens [sub command] [options] [args]
This command allows operations on Boundary auth token resources. …
```
> api: remove create from auth-tokens help

- internal/tests/cluster/recursive_anon_listing_test.go
Recently, we made the initial dev ldap auth-method active-public, so it now shows up in listings.  This simply fixes the tests to reflect that change.
> fix: update recursive auth-method listing test

- .github/workflows/build.yml
- .github/workflows/enos-run.yml
- enos/enos-scenario-e2e-aws-base-with-vault.hcl
- enos/enos-scenario-e2e-aws-base.hcl
- enos/enos-scenario-e2e-docker-base-with-vault.hcl
- enos/enos-scenario-e2e-docker-base.hcl
- enos/enos-scenario-e2e-docker.hcl
- enos/modules/docker_boundary/init.sh
- enos/modules/docker_boundary/main.tf
This PR updates some e2e test scenarios to use docker-based infra as opposed to AWS-based. This drastically improves run-time and reliability for the following scenarios.
Here's an example comparison
```
base: 24m 38s --> 9m 53s
base with vault: 13m 46s --> 2m 52s
```
This leaves the current run times for e2e tests
```
aws: 13m 37s
database: 4m 39s
docker_base: 9m 52s
docker_base_with_vault: 2m 54s
```
> chore: Update some e2e test scenarios to use docker-based infra

- .copywrite.hcl
Updating the `copyright_year` to 2020 after reviewing copywrite [README](https://github.com/hashicorp/copywrite#config-structure) that suggests using the year the project started.
> chore: update copyright_year in copywrite config

- enos/enos-modules.hcl
- enos/enos-variables.hcl
- enos/modules/test_e2e/main.tf
- testing/internal/e2e/boundary/target.go
- testing/internal/e2e/tests/aws/env_test.go
- testing/internal/e2e/tests/aws/worker_test.go
- testing/internal/e2e/tests/base/session_end_delete_project_test.go
- testing/internal/e2e/tests/base/target_address_test.go
Ticket: [ICU-9194](https://hashicorp.atlassian.net/browse/ICU-9194)
This PR prepares OSS for session recording tests:
- Updates environment variables for aws e2e tests
- Refactors the `CreateNewTargetCli` method for targets creation via CLI to support additional options
[ICU-9194]: https://hashicorp.atlassian.net/browse/ICU-9194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test(e2e): Update env variables and target creation

- go.mod
- go.sum
Occasionally, we see an error from the gldap test directory reported
during the shutdown/close of the directories listener.   This update
should fix that issue.
> chore: update gldap dep to fix intermittent shutdown/stop error

- internal/cmd/commands/sessionrecordingscmd/download.go
When using an alias, we automatically add a little blurb to the end of the flag help. When not terminating the flag help with a full stop, this looks a bit odd. Add full stops to all the download flags for consistency.
Old help:
```
Command Options:
-id=<string>
The id of the session recording resource to download
-no-clobber
An option to stop downloads that would overwrite existing files This is
aliased as "-nc". The default is false.
-output=<string>
An optional output file for the download. If not provided the recording
id will be used with a ".cast" extension. Use "-" for stdout This is
aliased as "-o".
```
New help:
```
Command Options:
-id=<string>
The id of the session recording resource to download.
-no-clobber
An option to stop downloads that would overwrite existing files. This …
```
> cmd: fix session recording download flag help

- .github/workflows/enos-run.yml
- enos/enos-scenario-e2e-docker-base-with-vault.hcl
- enos/modules/docker_vault/main.tf
- enos/modules/test_e2e/main.tf
- enos/modules/test_e2e_ui/main.tf
This PR updates the vault docker container used in e2e tests to attach to port 8300 instead of 8200 to prevent conflicts to other Vault instances that may be used in CI workflows.
> chore(e2e): Change port used by vault docker container

- .github/workflows/actionlint.yml
This PR updates the actionlint action to a trusted version. Here are some other examples of its use: https://github.com/search?q=org%3Ahashicorp+3f24bf9d72ca67af6f9f8f3cc63b0e24621b57bf421cecfc452c3312e32b68cc&type=code
> chore: Update actionlint to a trusted version

- website/content/docs/release-notes/v0_13_0.mdx
Remove reference to crash during recovery- we don't have a recovery flow, so the worker can't crash during it
> docs: remove recovery crash scenario from 0.13.0 release notes

- website/content/docs/concepts/domain-model/targets.mdx
This pull request adds the `default_client_port` to the domain model documentation.
[View the update in the preview deployment here.](https://boundary-jjqwfj5op-hashicorp.vercel.app/boundary/docs/concepts/domain-model/targets)
> docs: Add default client port to domain model

- website/content/docs/concepts/credential-management.mdx
- website/content/docs/concepts/domain-model/credential-libraries.mdx
- website/content/docs/concepts/domain-model/credential-stores.mdx
- website/content/docs/concepts/filtering/worker-tags.mdx
The **HCP only** tag should be updated to **HCP/ENT** in places where a feature is supported by both versions. This PR fixes some topics that I missed in the 0.13 release.
> docs: Update HCP only references

- .github/workflows/build.yml
- internal/census/census_job.go
- internal/db/schema/migrations/oss/postgres/73/01_census_logging.up.sql
- internal/db/sqltest/tests/census/last_logged.sql
Census is currently running about once a minute, this will reduce that run-time to once per hour. Also includes a table to track the most recent log time.
> Update census to run less frequently

- CHANGELOG.md
- internal/server/repository_workerauth.go
- internal/server/repository_workerauth_test.go
- internal/server/worker_auth.go
Fixes https://hashicorp.atlassian.net/browse/ICU-9986
> bug(workerAuth): allow duplicate workerAuth inserts if records match

- testing/internal/e2e/boundary/scope.go
- testing/internal/e2e/boundary/target.go
- testing/internal/e2e/tests/base/target_tcp_connect_test.go
This PR adds a test to verify connection to targets via a combination of the `-target-name` and `-target-scope-name` options.
The PR also:
- adds an optional parameter to the `boundary.CreateNewProjectCli` to be able to optionally set custom project name
- adds support of the `target.WithName` option for the `boundary.CreateNewTargetCli`
> test(e2e): Add test to connect to target via its name and scope

- website/data/docs-nav-data.json
In PR #3396 , I updated headings and the TOC to use sentence style capitalization. I missed one of the TOC entries. This pull request updates that entry.
> docs: Fix a capitalization error in the TOC

- website/content/docs/configuration/session-recording/enable-session-recording.mdx
We don't need to inject an application credential source to enable session recording on a target. We only need an injected application credential source before making a target connection.
> docs: Update enable session recording on a target

- .github/workflows/build.yml
- .github/workflows/linting.yml
- .github/workflows/test-sql.yml
- .github/workflows/test.yml
This PR prevents the build and test GitHub Actions workflows from running if the only changes in a PR are in the website/ directory. This allows docs changes to more rapidly make changes without having to wait for the longer workflows, especially since docs changes should have no impact on the application.
> chore: Ignore website directory for build and test workflows

- website/content/docs/configuration/session-recording/create-storage-bucket.mdx
Clarify the requirements for Boundary workers used for session recording
> docs: Session Recording Requirements for Workers

- .github/workflows/security-scan.yml
- scan.hcl
Enabling CodeQL scanning since we can use beefier runners. Also moving to [gosec](https://github.com/securego/gosec) Semgrep rules for a more targeted ruleset.
> chore: prefer gosec for semgrep rule and turn on codeql

- .github/workflows/security-scan.yml
adding `**` per https://github.com/hashicorp/boundary/pull/3418#discussion_r1262902487
> fix paths-ignore on security-scan workflow

- website/content/docs/concepts/domain-model/auth-methods.mdx
The code blocks make it much clearer what is and isn't an example.
> docs: add code blocks to LDAP auth method docs

- website/content/docs/operations/manage-recorded-sessions.mdx
Since we had steps for viewing session recordings and playback related to the UI already, I split the current steps into a `CLI` tab and `Admin Console` tab. The Admin Console tab is fairly sparse and I wonder if this is an exception for a screenshot or gif showing the player in the UI. Let me know your thoughts on that.
I also wanted to ask if we should include a note for channels that cannot be played back. Right now, they are buttons that show as `View` instead of `Play` and have no player shown and just details related to that specific channel recording.
Example with a screenshot of the player:
> docs: update view session recordings in ui steps

- .github/workflows/build.yml
This PR is a follow-up to https://github.com/hashicorp/boundary/pull/3426/files, which attempts to prevent certain workflows from running when there are only changes in the `website/` directory. This PR fixes one of the paths to make sure it's appropriately set.
> chore: Add missing ** in paths-ignore

- internal/bsr/types.go
decoding summary `Errors` field currently fails with type `error`.  Using a string type to handle `Errors` field
**Previous commit approach**
Using a custom `SummaryError` type that implements the `error` interface to fix this issue. This caused the `Errors` field to be nested. eg. `Errors: { Message: "err"}` which failed other tests
> chore: Change summary errors field type

- website/content/docs/api-clients/commands/connect/http.mdx
- website/content/docs/api-clients/commands/connect/kube.mdx
- website/content/docs/api-clients/commands/connect/rdp.mdx
Connect helper documentation for 'http', 'kube', and 'rdp'
> Draft connection option documentation for kube, http, and rdp

- internal/bsr/types.go
- internal/bsr/types_test.go
Add custom error type to to decode and encode `Errors` field
Added some extra checks to handle existing BSR summary types with `Error` fields
> feat: Add custom summary error type

- enos/modules/build_boundary_docker_local/build.sh
- testing/internal/e2e/boundary/session.go
This PR updates the e2e test suite to ensure we re-build the boundary UI when running a docker scenario locally. This ensures we have updated UI changes.
> test(e2e): Build UI when running docker scenarios locally

- testing/internal/e2e/tests/base/session_cancel_group_test.go
- testing/internal/e2e/tests/base/session_cancel_user_test.go
- testing/internal/e2e/tests/base/session_end_delete_host_set_test.go
- testing/internal/e2e/tests/base/session_end_delete_host_test.go
- testing/internal/e2e/tests/base/session_end_delete_project_test.go
- testing/internal/e2e/tests/base/session_end_delete_target_test.go
- testing/internal/e2e/tests/base/session_end_delete_user_test.go
- testing/internal/e2e/tests/database/migration_test.go
Ticket: [ICU-10291](https://hashicorp.atlassian.net/browse/ICU-10291)
This PR updates e2e tests to use the new `ids` field in permission grants, which was introduced in `0.13.1`. 
One thing to note: originally, the migration test was failing with this change (before `0.13.1` was released) because it would try to upgrade from `0.13.0 (latest release) -> latest changes`) and  `0.13.0` did not recognize the `ids` field. Once `0.13.1` was released, that became the latest released version, which does support this field. We may look to address this in future work if we decide to update the migration test to try to update from a variety of different versions (i.e. `0.12.X -> latest`, 0.11.X -> latest`).
[ICU-10291]: https://hashicorp.atlassian.net/browse/ICU-10291?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …
> test(e2e): Update grants to use new ids field

- internal/bsr/convert/convert.go
- internal/bsr/convert/convert_test.go
Check that the conversion to asciicast is done on `exec` or `shell` session program. 
Unsupported session programs will throw an error.
> feat: Perform asciicast conversion sanity checks

- testing/internal/e2e/boundary/host.go
- testing/internal/e2e/tests/aws/dynamichostcatalog_host_set_test.go
Coming from a test plan item in `0.13.1`, there was a check to update a host set from an AWS Dynamic Host Catalog. This PR ports that check over to the e2e test. 
Now, this test will update the filter on one of the host sets and confirm that the right number of hosts show up.
> test(e2e): Add "update host set filter" check

- internal/bsr/errors.go
- internal/bsr/timestamp.go
- internal/bsr/timestamp_test.go
The normal nanosecond range is [0; 999999999]. Any values higher than this represent a second or more, and would cause the timestamp to be adjusted as a result.
This PR adds a check on the upper bound of a decoded nanosecond value.
> fix(bsr): check nanosecond range during decoding

- website/content/docs/configuration/session-recording/create-storage-bucket.mdx
The documentation for [Creating a storage bucket](https://developer.hashicorp.com/boundary/docs/configuration/session-recording/create-storage-bucket) refers to Boundary storage buckets and AWS storage buckets. Both are required for session recording, but at times it is unclear which "bucket" the documentation is referring to. It has caused confusion for users ([via Slack](https://hashicorp.slack.com/archives/C01AQDJF3SA/p1689859211100109)).
This PR attempts to clarify which bucket we are referring to throughout that topic.
[View the updated topic in the preview deployment.](https://boundary-mnir5r385-hashicorp.vercel.app/boundary/docs/configuration/session-recording/create-storage-bucket)
> docs: Clarify storage bucket terminology

- internal/bsr/encode.go
- internal/bsr/encode_bench_test.go
This PR optimizes the Encode function for the ChunkEncoder in the bsr package.
- sec/op: 
- average amount of time each iteration took to complete, expressed in seconds per operation
- we want this number to be as low as possible
- 34.86% faster than the original implementation.
```
28.49µ ±  0%  -35.57% (p=0.000 n=20)
29.22µ ±  0%  -35.66% (p=0.000 n=20)
33.72µ ±  2%  -34.07% (p=0.000 n=20)
44.54µ ±  2%  -35.13% (p=0.000 n=20)
60.50µ ±  3%  -32.86% (p=0.000 n=20)
102.61µ ± 21%  -31.96% (p=0.000 n=20)
175.3µ ±  5%  -33.10% (p=0.000 n=20)
295.3µ ±  2%  -33.12% (p=0.000 n=20)
519.0µ ±  3%  -33.25% (p=0.000 n=20)
796.8µ ±  0%  -43.17% (p=0.000 n=20)
105.2µ        -34.86%
```
- B/s:
- average amount of bytes each iteration processed, expressed in bytes per second
- we want this number to be …
> refactor(bsr): optimize ChunkEncoder.Encode()

- internal/bsr/internal/fstest/fs.go
- internal/bsr/internal/fstest/fs_test.go
This adjusts the behavior of a memFile so that we can open the same file multiple times and re-read the file multiple times.
This issue was resolved, a deep copy was implemented to support concurrent reads:
```
I wasn't sure if I should return a deepCopy of MemFile when calling OpenFile. With the current implementation, calling
OpenFile twice will reset the first reference. This fix assumes that calling OpenFile will not happen concurrently.
```
> fix(bsr): allow reading twice from the same file

- website/content/docs/configuration/worker/index.mdx
The `initial_upstreams` parameter is not used for HCP workers, but this has caused some confusion with users. ([Via Slack](https://hashicorp.slack.com/archives/C01AQDJF3SA/p1690549357466249)) This PR adds clarification that HCP users should configure workers with `hcp_boundary_cluster_id` instead.
[See the update in the preview deployment.](https://boundary-chlj6cxfl-hashicorp.vercel.app/boundary/docs/configuration/worker#initial_upstreams)
> docs: Add note regarding HCP workers

- internal/bsr/container.go
- internal/bsr/container_test.go
This PR adds a new method for the bsr *container called `ValidateChecksums`. This method calculates the checksums of all files that are listed in the SHA256SUM file and compares the expected value. Here is an example output from a session container:
```
ChecksumValidation{
"bsrKey.pub": &FileChecksumValidation{
Filename: "bsrKey.pub",
Passed:   false,
Error:  error("checksum mismatch"),
},
"pubKeyBsrSignature.sign": &FileChecksumValidation{
Filename: "pubKeyBsrSignature.sign",
Passed:   true,
},
"pubKeySelfSignature.sign": &FileChecksumValidation{
Filename: "pubKeySelfSignature.sign",
Passed:   true,
},
"wrappedBsrKey": &FileChecksumValidation{
Filename: "wrappedBsrKey",
Passed:   true,
},
"wrappedPrivKey": &FileChecksumValidation{
Filename: "wrappedPrivKey",
Passed:   true,
}, …
```
> feat(bsr): support container validation

- internal/server/testing.go
The old logic made it impossible for the caller to set the release version with WithReleaseVersion. Only
set the release version when it's not explicitly set already.
> server: allow release version to be set in test
